rdkit/rdkit

CMakeLists.txt, Code/cmake/Modules/CodeCoverage.cmake, Code/cmake/Modules/fixup_coverage.py
To use code coverage:
cmake -DCMAKE_BUILD_TYPE=Debug \
-DRDK_USE_FLEXBISON=ON \
-DRDK_TEST_COVERAGE=ON \
<path to rdkit source tree>
make install
make RDKit_coverage
Note, when making RDKit_coverage, your python paths, (DY)LD_LIBRARY paths must be
set up correctly.  If any of the tests fail, the coverage generator will most
likely fail and certainly will not be complete.
Here is an example from my OSX Box (note, I set the install directory to rdkit_build via)
cmake -DCMAKE_INSTALL_PREFIX=`pwd`/rdkit_build \
...
RDBASE=<path to rdkit source>  DYLD_LIBRARY_PATH=`pwd`/rdkit_build/lib \
PYTHONPATH=`pwd`/rdkit_build/lib/python2.7/site-packages \
make RDKit_coverage
open coverage/index.html in a browser
=> RDKit learns how to compute code coverage for tests

Code/GraphMol/ChemReactions/testReaction.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp
I was running into an issue where round-tripping a rxn block lost the mol file values.
This preserves them if they have not been converted into a smarts query.
n.b. the if statement is missing braces and I might add them back in for clarity.
=> RDKit learns how to round grip MOLFile values.

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py
RWMol becomes a replacement for EditableMol.
It has the EditableMol interface in addition
to the ROMol interface.  In the future this
may or may not grow the RWMol C++ interface.
=> rdkit learns how to wrap a proper RWMol in python

rdkit/Chem/Draw/cairoCanvas.py
has_key() changed to in for python3 compatibility.
patch allowed running of Draw.MolsToGridImage in python3.4
probably relevant to #398
=> cairoCanvas.py python3 compatibility

Code/GraphMol/FindRings.cpp
Story: I have a PDB I want to read into RDKit. It has a disulfide bond
between two cysteines ~400 residues apart. This creates a very large
ring. RDKit throws an error because the number of found rings is less
than the expected number of rings. The ring wasn't found because RDKit
thought all "smallest" rings should be 256 or smaller.
Now, as long as your ring is UINT_MAX aka 4,294,967,295 or smaller, life
is beautiful. I hope no one has a ring bigger than 4 billion atoms.
=> Increase limit for smallest ring size

Code/ChemicalFeatures/Wrap/testFeatures.py, Code/DataStructs/Wrap/testDiscreteValueVect.py, Code/DataStructs/Wrap/testSparseIntVect.py, Code/GraphMol/PartialCharges/Wrap/testPartialCharges.py, Code/GraphMol/Wrap/rough_test.py, Code/ML/InfoTheory/Wrap/testRanker.py, Code/RDBoost/import_array.h, Projects/DbCLI/CreateDb.py, rdkit/Chem/Pharm3D/UnitTestEmbed.py, rdkit/Chem/UnitTestCatalog.py, rdkit/Chem/UnitTestCrippen.py, rdkit/Chem/UnitTestDescriptors.py, rdkit/ML/Composite/UnitTestComposite.py, rdkit/ML/DecTree/UnitTestID3.py, rdkit/ML/DecTree/UnitTestQuantTree.py, rdkit/ML/DecTree/UnitTestXVal.py, rdkit/ML/Descriptors/UnitTestMolDescriptors.py, rdkit/ML/ModelPackage/UnitTestPackage.py, rdkit/ML/UnitTestBuildComposite.py, rdkit/ML/UnitTestScreenComposite.py
- Fixed tests failing on Windows when retrieving sources through the  Windows git client, which converts line terminators to CR+LF
- Added a conditional compilation clause to Code/RDBoost/import_array.h
to avoid a compilation error on Windows with Python3
=> Fixed tests failing on Windows when retrieving sources through the  Windows git client

Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/querytest.cpp
I'm not entirely sure I did this correctly, but the regression tests pass :)  If you think it's a good idea I'll add python wrappers which will probably be a bit harder!
Examples:
QueryAtom qA;
qA.setQuery(makeAtomHasPropQuery("foo"));
QueryAtom qA;
qA.setQuery(makeAtomPropQuery<double>("foo", 2));
QueryAtom qA;
qA.setQuery(makeAtomPropQuery<std::string>("foo", "bar"));
=> RDKit learns how to query properties on Atoms

Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/RDBoost/Wrap.h
Adds basic support for removing the GIL.
Only a few functions were modified that have been tested in a multi-threaded web-service.  
Note: The GIL can only be turned off where code does not call the PYTHON API, in many cases this is the whole function but in a few cases below it isn't.  Fortunately, Python appears to crash when the GIL is not re-acquired before a python api call, so they are fairly easy to find.
=> RDKit learns how to release the GIL in python

Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
Going through ChemicalReaction(rxn.ToBinary()) was lossy when it came to atom properties.
=> RDKit learns how to expose ChemicalReaction copy constructor to python

Code/GraphMol/ChemReactions/ReactionRunner.cpp
This also ensures the atom bookmarks in the reactants
are cleared (allows a product to be a reactant since we
no longer clear the product bookmarks)
n.b. -We might have to think about this a bit, since the bookmarked atoms being returned in the products are from the product itself, this is a safe operation.
However, we could have the same feature by having an alternate atom property along the lines of "reaction-mapped_atom_number" which would satisfy my needs (i.e. getting to the template atoms that were mapped to a product )
=> Save the atom bookmarks so we can deconvolute reaction products.

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/inchi.out, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/inchi.sql, Code/PgSQL/rdkit/sql/rdkit-91.sql
No-Structures are saved to database dumps as blank strings ''.
This patch allows dumps with No-Structures to be read back in.
=> Add code to accept blank SMILES input.

Code/GraphMol/CMakeLists.txt, Code/GraphMol/FileParsers/testMolSupplier.cpp
- modified Code/GraphMol/CMakeLists.txt to make it build under Windows
- modified Code/GraphMol/FileParsers/testMolSupplier.cpp in order
to avoid testSetStreamIndices() failure on Windows due to CR+LF
issues
=> Windows build/test failure fixes

Code/GraphMol/FMCS/CMakeLists.txt
Graph.h is included by FMCS.h, so it should be installed as well.
=> install missing FMCS/Graph.h header file

Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
If the std::vector<shared<ROMol> > are directly exposed in C++ land, they can trivially be wrapped in python.
This also allows C++11 ranges to work which is a nice side-effect.
reactants = rxn.GetReactants()
products = rxn.GetProducts()
agents = rxn.GetAgents()
=> Expose raw MOL_SPTR_VECTORS to C++/Python for Reactions Reactants/Agents/Templates

rdkit/sping/SVG/pidSVG.py
Fix for IPythonNote book using SVG rendering.
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True
This isn't tested anywhere outside the pidtest.py which I assume is tested with nose.
=> Fix StringType access, remove unused imports

Docs/Book/Install.rst, rdkit/Chem/Draw/cairoCanvas.py
* cairocffi aims at being a drop-in replacement for cairo but does not seem to be quite there, yet
* this hack fixes issue #460 by trying to use cairocffi when running on Python3 and cairo when running on Python2
* tested for both Python versions
* I have now completely switched to Python3 with RDKit
=> Fix mol drawing on Python3 (issue #460)

rdkit/Chem/PandasTools.py
*  I used WriteSDF a bit and noticed that it saves floats with E notation which confused some programs. I fixed it so that now it formats the floats "correctly" with decimal notation.  
*  When I tried to fix the code I also noticed that if no properties are given it just pulls the properties from mol objects in "ROMol" and writes those. I modified the code so that embedded properties are removed before molecule is written. 
*  I added few lines to remove embedded properties when loading sdf with LoadSDF. embedProps=False is the default now. I think this reasonable default since all the data is already in columns and as a bonus it will save some memory..
*  And finally I also renamed parameters to be consistent with LoadSDF. Will only break code where "titleColumn" was used.
=> Improvements to LoadSDF and WriteSDF

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/new_canon.cpp
- allows to provide an arbitrary canonical order of the atoms to the SmilesWriter by using an atom property ('_canonicalRankingNumber')
- a performance tuning of the special graph invariant
=> Some enhancements for the new canonicalization

Code/GraphMol/MolDraw2D/MolDraw2D.cpp
Introduce a flag to control the color of the labels of highlighted atoms.
=> MolDraw2D: Fix in highlighting atoms

Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/Wrap/rough_test.py
- modified Code/GraphMol/FileParsers/MolWriters.h to avoid memory corruption
due to double free (close() was being called twice when an exception
occurred in the Python layer, leading to duplicate deletion of dp_ostream)
- modified testGithub498() in Code/GraphMol/Wrap/rough_test.py
to comply with Python 3
- added testGithub497() to test the fix in Code/GraphMol/FileParsers/MolWriters.h
=> Fixed crash upon closing a gzip/bzip2 stream opened in binary mode for use with SDWriter under Python3

Code/GraphMol/SmilesParse/SmilesWrite.cpp
Handle disconnected components correctly when generating the _smilesAtomOutputOrder property. This requires:
(a) the mapping from the fragment molecules back to the original molecule
(b) the fragment maps to be sorted at the same time as the fragment smiles (if canonical)
=> Fix #532 - smilesAtomOutputOrder incorrect

Code/Catalogs/Catalog.h, Code/GraphMol/CMakeLists.txt, Code/GraphMol/FilterCatalog/CMakeLists.txt, Code/GraphMol/FilterCatalog/FilterCatalog.cpp, Code/GraphMol/FilterCatalog/FilterCatalog.h, Code/GraphMol/FilterCatalog/FilterCatalogEntry.cpp, Code/GraphMol/FilterCatalog/FilterCatalogEntry.h, Code/GraphMol/FilterCatalog/FilterMatcherBase.h, Code/GraphMol/FilterCatalog/FilterMatchers.cpp, Code/GraphMol/FilterCatalog/FilterMatchers.h, Code/GraphMol/FilterCatalog/Filters.cpp, Code/GraphMol/FilterCatalog/Filters.h, Code/GraphMol/FilterCatalog/README, Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt, Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp, Code/GraphMol/FilterCatalog/Wrap/rdfiltercatalog.cpp, Code/GraphMol/FilterCatalog/Wrap/rdfiltercatalog.h, Code/GraphMol/FilterCatalog/Wrap/rough_test.py, Code/GraphMol/FilterCatalog/Wrap/test_list.py, Code/GraphMol/FilterCatalog/filtercatalogtest.cpp, Code/GraphMol/FilterCatalog/filtercatlogtest.cpp, Code/GraphMol/test_data/pains.smi, rdkit/Chem/FilterCatalog.py
FilterCatalogs give RDKit the ability to screen out or reject 
undesirable molecules based on various criteria.  Supplied 
with RDKIt are the following filter sets:
* PAINS - Pan assay interference patterns.  
These are separated into three sets PAINS_A, PAINS_B and PAINS_C.
Reference: Baell JB, Holloway GA. New Substructure Filters for 
Removal of Pan Assay Interference Compounds (PAINS) 
from Screening Libraries and for Their Exclusion in 
Bioassays.
J Med Chem 53 (2010) 2719Ð40. doi:10.1021/jm901137j.
* BRENK - filters unwanted functionality due to potential tox reasons 
or unfavorable pharmacokinetics.
Reference: Brenk R et al. Lessons Learnt from Assembling Screening 
Libraries for Drug Discovery for Neglected Diseases.
ChemMedChem 3 (2008) 435-444. doi:10.1002/cmdc.200700139.
* NIH …
=> RDKit learns how to filter PAINS/BRENK/ZINC/NIH via FilterCatalog

Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
Greg, You'll want this to fix the Python3 tests.  Apparently boost text serialization triggers utf-8 encoding errors in python3, safer to use PyBytes instead.
=> Fix Python3 encoding for FilterCatalog/Entry serialization

Code/Catalogs/Catalog.h
Because setCatalogParams is overloaded in the derived classes, it needs to be virtual to have the same effect as before (i.e. resetting the parameters properly)
=> Catalog::setCatalogParams needs to be virtual now

Contrib/SA_Score/sascorer.py
Wow, just discovered the awesome Synthetic Accessibility Scorer.
It seems that one can discover an awesome new feature in RDKit every day.
I changed the file path for fpscores.pkl.gz in sascorer.py so that sascorer can be imported from different locations (assuming that you have Contrib somewhere in your Python import path). Also removed some unused vars.
One question: in sascorer.processMols(mols,outf), the outf parameter is not used in the function.
Should I fix this?
Kind regards,
Axel
=> changed sascorer.py to enable import from different location

Contrib/NP_Score/npscorer.py, rdkit/Chem/TorsionFingerprints.py, rdkit/Chem/UnitTestMol3D.py, rdkit/Chem/test_data/1DWD_ligand_reordered.pdb
If two instances of the same molecule have different atom ordering, the second molecule is reordered to match the atom order of the first one.
The function GetTFDBetweenMolecules() takes now two confIds instead of two lists of confIds and returns a float instead of a list of floats. This has previously led to confusion.
Tests for the changes as well as for the wrapper functions have been added/adapted.
Entry in cookbook has been adapted.
=> Automatic atom reordering in TorsionFingerprints

Docs/Book/Cookbook.md, rdkit/Chem/TorsionFingerprints.py, rdkit/Chem/UnitTestMol3D.py
- Use of Morgan invariants to pick atoms if multiple choices are available
- In case of torsions with symmetric atoms, all possible torsional angles are stored in the TF, thus all possible deviations are determined and the smallest used to calculate the TFD value.
=> Improvements of TFD

CMakeLists.txt, rdkit/Chem/Draw/UnitTestSimilarityMaps.py, rdkit/Chem/PandasTools.py
UnitTestSimilarityMaps was failing on travis because no XWindow display was set.  This forces matplotlib to use the Agg renderer when the DISPLAY variable isn't set which allows the test to pass but perhaps has side-effects.
=> Fix AppVeyor and Travis UnitTests

Code/GraphMol/FileParsers/SequenceWriters.cpp
fixes the following on gcc 4.6.3 Ubuntu 12
Code/GraphMol/FileParsers/SequenceWriters.cpp: In function 'bool RDKit::FindHELMAtom(std::vector<RDKit::AtomPDBResidueInfo*>*, RDKit::AtomPDBResidueInfo*, std::string&, std::string&)':
/home/vagrant/devel/rdkit/Code/GraphMol/FileParsers/SequenceWriters.cpp:362:39: error: 'sprintf' was not declared in this scope
make[2]: *** [Code/GraphMol/FileParsers/CMakeFiles/FileParsers.dir/SequenceWriters.cpp.o] Error 1
make[1]: *** [Code/GraphMol/FileParsers/CMakeFiles/FileParsers.dir/all] Error 2
make: *** [all] Error 2
=> Fixes sprintf not found on some gcc compiles

Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/testMolWriter.cpp, Code/GraphMol/MolOps.cpp
this PR fixes a few errors I observed in running tests after building RDKit with the "Microsoft Visual C++ Compiler for Python 2.7".
the changes make sense to me, but especially those related to the management of wedge bonds (probably a side effect of #611) could require a review.
thanks,
riccardo
=> Fix regressions occurring when building with msvc9

Code/GraphMol/Wrap/Mol.cpp
Never/ever call the Python API when the GIL is released.
Also releases the GIL during GetSubstructMatches.
Any ideas how to add a test case for this?  Do we know when to test threading?
=> Fixes #629 - python GetSubstructureMatch thread safety

rdkit/Chem/Draw/cairoCanvas.py, rdkit/ML/MLUtils/VoteImg.py, rdkit/sping/PDF/pdfgen.py, rdkit/sping/PDF/pdfutils.py, rdkit/sping/PS/pidPS.py, rdkit/sping/WX/pidWxDc.py
In Pillow 3.0.0 some deprecated parts of the API have been removed (http://pillow.readthedocs.org/en/3.0.x/releasenotes/3.0.0.html#deprecated-methods). This pr replaces calls to tostring/fromstring with tobytes/frombytes. 
this changeset might be not backward compatible with the older PIL implementation (I didn't verify) and it's been only verified to the extent of the tests coverage.
=> Image tostring/fromstring methods replaced by tobytes/frombytes

Code/JavaWrappers/MolSupplier.i, Code/JavaWrappers/ROMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BasicMolecule2Tests.java, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
- added SWIG Java wrappers for ResonanceMolSupplier and
getResonanceSubstructMatches()
- added a few tests
=> Minimal SWIG Java wrappers for ResonanceMolSupplier

Code/GraphMol/Resonance.h
Changed unorderd_set to unordered_map (later versions of boost work ok, some versions don't define unordered_map in unordered_set)
=> Fix unordered_map header

Code/GraphMol/MMPA/MMPA.cpp, Code/GraphMol/MMPA/MMPA.h, Code/GraphMol/MMPA/Wrap/rdMMPA.cpp, Code/GraphMol/MMPA/Wrap/testMMPA.py
addResult was leaking the core and side_chains (verified with valgrind)
The raw core and side_chain pointers were converted to RWMOL_SPTR so if they are not pushed onto the result vector, they will be cleaned up regardless of code path.
=> Fixes a memory leak in fragmentMol

rdkit/Chem/PeriodicTable.py
In Python 3.5, there is an annoying FutureWarning about the use of a regular expression in PeriodicTable.py on import of the Chem module:
```
In [1]: from rdkit import Chem
/Users/rich/anaconda/lib/python3.5/site-packages/rdkit/Chem/PeriodicTable.py:131: FutureWarning: split() requires a non-empty pattern match.
splitLine = blankExpr.split(line)
```
This pull request replaces the regular expression with the string method, `split`, that should fulfil the same function.  I don't think this module is used anymore, so could be removed to prevent the warning message, but this fixes the warning message in case we want to keep it.
=> fixed FutureWarning in PeriodicTable.py

CMakeLists.txt
to allow for easier inclusion in other repos
This allows RDKit to be used as a subtree or submodule in other projects.
=> Updates CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

Code/GraphMol/FileParsers/MolFileWriter.cpp
It turns out that boost::format is really slow. This replaces the primary use of it with snprintf and speeds up the generation of Mol blocks by a factor of 4-5.
=> Speed up molblock generation

Code/GraphMol/AddHs.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/molopstest.cpp
This changes the CIPCode and CIPRank atom properties to no longer be computed properties.
Note: under linux I was unable to actually get the bug to manifest (converting the uint property to an int didn't cause problems), but that doesn't mean it shouldn't still be fixed.
=> Fixes #717

Code/RDBoost/PySequenceHolder.h
Caused failures on OSX under some configurations (namely c++11 builds)
=> Fixes return type of operator[] (fails on later clangs)

Contrib/ConformerParser/ConformerParser.cpp
In #627, `readAmberTrajectory` in ConformerParser.h is updated to use `const std::string &`. This updates the corresponding method in ConformerParser.cpp to match. I needed to do this to compile RDKit with contrib and successfully run the tests.
=> Fix ConformerParser to use const std::string &

Code/RDGeneral/Dict.cpp
Small header file addition to Dict.cpp to help build with boost 1.46
=> Fixes Boost 1.46 issues with type traits

Code/GraphMol/Wrap/rdchem.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/Wrap/testThreads.py, Code/RDGeneral/RDLog.h, rdkit/Chem/Draw/IPythonConsole.py
Adds four basic logging functions to Chem that log through the C++
logging mechanism:
Chem.LogWarningMsg(msg)
Chem.LogInfoMsg(msg)
Chem.LogErrorMsg(msg)
Chem.LogDebugMsg(msg)
And a Wrapper to enable logs to be mirrored in Python SysStderr.  One of
the nicer features of this logging system, is that Threaded logging is
synchronized to Python where it is interleaved in raw C++ logging.
Chem.WrapLogs()
This is automatically turned on when using the IPython Console.  Mistyped smiles strings now indicate that something was wrong ;)
=> Adds support for capturing RDLogs in Python StdErr streams

Code/JavaWrappers/gmwrapper/CMakeLists.txt
I wasn't able to compile RDKit (HEAD) in Ubuntu 14.04 with Oracle Java 8 because it added the -Xdoclint:none flag to the `jar cf org.RDKitDoc.jar -d doc` command. Removing it solved the problem.
Hope that it helps! :)
=> Removed -Xdoclint:none flag when packing org.RDKitDoc.jar

Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolHash/Wrap/rdMolHash.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/RDBoost/Wrap.h
@bp-kelley @DoliathGavid 
I'd love your feedback on this attempt to resolve the problem.
It would be easier in C++11, where I could just use a unique_ptr, but this seems like a reasonable workaround until we reach that point.
=> Stop possible core leaks in pythonObjectToVect()

Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/test1.cpp
Captures the standard operations to get ready for doing a molecular rendering:
- kekulization
- generation of coordinates
- wedging bonds
- adding Hs to chiral atoms
Also fixes #772 (so that `wedgeMolBonds()` prefers wedging bonds to Hs)
=> Add prepareMolForDrawing() function to C++

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
This is a small one to modify `prepareMolForDrawing()` to generate the 2D coordinates in a standard orientation.
=> standardize the orientation when generating coords

Contrib/NP_Score/npscorer.py
* made Python3 compatible
* modified load path for the publicnp.model file to enable import of the module from other locations
* my editor removed some trailing whitespace
=> npscorer.py: Py3 compat and importable from other locations

Code/GraphMol/Chirality.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/molopstest.cpp, Code/GraphMol/test_data/pubchem_87396055.sdf
Modifies the fix for #805 to continue to allow stereochemistry on the `P=C` double bond. Instead it modifies `cleanUp()` to modify the bonding pattern in this rarely encountered substructure.
Based on the mailing list thread and some searches I did, I'm no longer 100% comfortable just removing the stereochemistry of these double bonds. This approach modifies the `cleanUp()` function to convert the `P=O` bond to the zwitterionic form `[P+][O-]` when substructures like `C=P(=O)R` or `N=P(=O)R' are found.
=> An alternate approach to fixing #805

Code/GraphMol/ChemReactions/testReaction.cpp
Fixes #825 
Fixes three silly issues.
1) adds rxn->initReactantMatchers()
2) move TEST_ASSERT(prod.size()>0) until after the reaction is run
3) turn on isomeric smiles for the expected smiles check.
=> Fixes #825 test60RunSingleReactant() not being run

rdkit/Chem/Draw/IPythonConsole.py, rdkit/Chem/Draw/UnitTestDraw.py, rdkit/Chem/Draw/__init__.py
This assembles the final svg using regexp operations instead of parsing the xml and working directly with the tree.
I think it's ok to do things this way, and suspect that it ends up being faster, but it's probably possible to do things differently if someone else thinks this is horrible.
=> add Draw.MolsToSVGGrid()

Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, Code/GraphMol/MolAlign/testMolAlign.cpp
This is a quick fix so that the substructure matcher in the align tools takes into account of QueryAtoms and QueryBonds.
This may introduce backwards incompatibility issues if there's alignment code that for some reason depended on the lack of query matching (which albeit, is a bit weird).
=> Fix alignMols so that it takes into account of QueryAtoms and QueryBonds

Code/GraphMol/MolOps.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/molopstest.cpp, Docs/Book/RDKit_Book.rst
The `cleanUp` function previously just handled perchloric acid. This generalizes it to handle chloric and chlorous acids as well, along with the corresponding Br and I equivalents.
The idea is to be able to handle these species, which have perfectly reasonable octet-satisfied Lewis dot structures, without requiring the addition of new valence states to the halogens.
=> Additional "hypervalent" halogen cleanups

Code/GraphMol/FileParsers/MolWriters.h
I could reproduce the crash on my system when I invoked flush() on the SDWriter(); the crash happened when I quit the Python interpreter because ~SDWriter() was invoked and the boost_adaptbx::python::streambuf destructor throws an exception upon flushing the stream itself.
Wrapping the destruction of the streambuf in a try...catch block should fix the issue for you too, hopefully.
=> Attempt to fix crash while running testGithub497() on Windows with Python 3.x

CMakeLists.txt
This was buried in the extended travis-builds patch.  It automatically configures libc++ on APPLE when boost has been linked to it.
=> Autodetect boost c++ library and compile with matching one

CMakeLists.txt
minor correction to #845 
this wasn't explicitly specifying `libstdc++` when it was required.
=> make the use of libstdc++ explicit

Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp, Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp, Code/GraphMol/ForceFieldHelpers/Wrap/testHelpers.py
There was a bug in getUFFAngleBendParams(), where the theta0 value (in radians) was multiplied by the RAD2DEG conversion factor before being returned to the user (which is correct, since theta0 values in the UFF parameters are given in radians), but then, instead of the original theta0 value in radians, the value in degrees was passed to Utils::calcAngleForceConstant(), which is obviously wrong.
I also fixed the relevant tests.
=> Fixed a bug in getUFFAngleBendParams()

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/testReaction.cpp
The atom-map info is there and is sufficient, adding the redundant isotope info is just confusing
=> stop including isotope labels in reduceProductToSideChains()

External/INCHI-API/CMakeLists.txt
Recent changes to the InChI cmake process moved these lines so it attempts to add an inchi target even if compiling using the system InChI. This resulted in the following error:
CMake Error at External/INCHI-API/CMakeLists.txt:64 (install):
install TARGETS given target "Inchi" which does not exist in this directory.
This commit simply moves the lines back such that the inchi target is only added when downloading and compiling local inchi.
=> Fix building with system InChI

Code/PgSQL/rdkit/CMakeLists.txt, Code/PgSQL/rdkit/README
- added some instructions to help finding PostgreSQL under RHEL/CentOS
using the PostgreSQL RPMs provided by the PostgreSQL RPM Building Project
=> Added some instructions to help finding PostgreSQL under RHEL/CentOS

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
I was getting horrible segfaults where qbi was being set to 2359832 (or some large number), and BondTable.at(qbi, tbi) was subsequently crapping out.
I'm actually baffled by how this ever worked. Maybe it was because we were always growing contiguously (but it seems that even then, you'd have the number of seed bonds possibly be number of seed atoms - 1 for totally aliphatic chains).
=> Fix out of range dereference in MCS code.

External/AvalonTools/CMakeLists.txt
@ptosco : it would be helpful if you could take a look at this and see if it looks right to you.
The goal is to prevent the build system from downloading the AvalonToolkit source distrib if AVALONTOOLS_DIR is set.
=> do not download the avalon distribution if we don't need it

Code/JavaWrappers/gmwrapper/CMakeLists.txt
The -Xdoclint:none breaks the build on CentOS 7, which has Java 8, but whose javadoc does not seem to support the -Xdoclint:none flag. The documentation builds fine in its absence, so I thought to introduce an additional check to allow building on CentOS 7 (and possibly on other platforms which have the same problem).
=> - fixed a build failure on CentOS 7

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py
This tiny modification allows us to do `LoadSDF(..., molColName=None)`, which will produce DataFrame only with molecular properties. It's useful when you deal with large SDFs.
=> Allow reading just the properties from SDF file

rdkit/Chem/ChemUtils/TemplateExpand.py
The building_block_%d needed to be parsed to find the actual index, this just saves the the raw index.
This is used in some external regression tests that may be folded into at a later date.
=> Adds the default index to the building block templates

Code/GraphMol/Wrap/rdchem.cpp, Code/GraphMol/molopstest.cpp, Code/RDGeneral/RDLog.h
- rename RDLog::AddTee()->RDLog::SetTee()
- remove a leak when RDLog::SetTee() (formerly AddTee()) is called twice
- add RDLog::ClearTee() method to allow RDLog::SetTee() to be safely used with a stream that goes out of scope.
=> cleanups of RDLog's tee behavior

Code/GraphMol/RWMol.cpp
It's very possible, that I don't understand something (apologies) but shouldn't the second loop iterate over vertices adjacent to the second end of the bond being removed?
=> Bug when removing stereo info?

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/molopstest.cpp
aromatizeIfPossible - checks kekulized queries for aromatic compatibility
adds IGNORE_MAPPED and IGNORE_ATTACHEDRGROUPS options to adjustDegree
Adds the appropriate options to AdjustQueries that will work for the proposed prepareQueries and sanitizeReactions.
This is basically a review for whether this is a suitable API or whether we want to move these into a prepareQueries function.
=> Adds aromatization and reaction options to AdjustQuery

Code/GraphMol/Wrap/testTrajectory.py
We are comparing floats, so assertAlmostEqual should be used.
=> Minor fix to Code/GraphMol/Wrap/testTrajectory.py

Code/PgSQL/rdkit/mol_op.c
In Fedora land, format-security GCC warnings are treated as errors
so the build would fail like this:
```
In file included from /usr/include/pgsql/server/postgres.h:48:0,
from rdkit.h:40,
from mol_op.c:33:
mol_op.c:339:19: error: format not a string literal and no format arguments [-Werror=format-security]
elog(WARNING, t);
^
```
=> Fix format-security GCC warning

Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp, Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp, Code/GraphMol/ForceFieldHelpers/Wrap/testHelpers.py
- calcImplicitValence() and setNumExplicitHs() are now called after all aromaticity flags have been set
- ChemicalForceFields.MMFFHasAllMoleculeParams() now operates on a copy of the molecule such that atom and bond aromaticity are not altered by the check
- test11 was added to GraphMol/ForceFieldHelpers/Wrap/testHelpers.py to check for the two bugs fixed by this PR
=> Fixes MMFF94 aromaticity perception and ChemicalForceFields.MMFFHasAllMoleculeParams()

Code/GraphMol/Atom.cpp, Code/GraphMol/Atom.h, Code/GraphMol/FileParsers/SDWriter.cpp, Code/GraphMol/FileParsers/TDTWriter.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/ROMol.cpp, Code/GraphMol/RWMol.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/test1.cpp, Code/RDGeneral/RDProps.h, Code/RDGeneral/testDict.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
Adds atom map and Rlabel apis to the Atom.  Atom maps probably should be on the Atom, rlabels could be free functions and not on the Atom.  We could do the same for molfile values and aliases.
C++
```
atom->setAtomMapNum(mapno);
atom->setRlabel(rlabel);
atom->getAtomMapNum();
atom->getRlabel();
```
python
```
atom.SetAtomMapNum(mapno)
atom.SetRlabel(rlabel)
atom.GetAtomMapNum()
atom.GetRlabel()
```
Values of 0 unset atom maps and rlabels.
=> Adds Atom atom map and rlabel apis

External/INCHI-API/CMakeLists.txt
- removed comment which does not apply any more
- put the final if(RDK_BUILD_PYTHON_WRAPPERS) clause outside the initial
if(RDK_BUILD_INCHI_SUPPORT) clause, as otherwise the if(RDK_BUILD_INCHI_SUPPORT)
which is inside the if(RDK_BUILD_PYTHON_WRAPPERS) clause would always evaluate to
true and noinchi.py wouldn't get a chance to be copied. This simply restores the behaviour
before commit 5d3bb1148848169aa6df342aaac1f1d97a0c3496
=> Fixes #1018

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/MolDraw2DCairo.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/test1.cpp
Used for attachment points and unknown stereochem
This is not a perfect implementation, but is a decent place to start
Currently only supports SVG and Cairo canvases.
Example images:
=> Add an initial version of wavy bonds

rdkit/__init__.py
Without this, it's very easy to get a SegFault when importing RDKit
binaries into a python interpreter with a UCS2 vs UCS4 symbol
mismatch. For example:
$ python -c "import rdkit.rdBase"
Segmentation fault
A UCS2 vs UCS4 mismatch should throw the more intelligible stack trace:
$ python -c "import rdkit.rdBase"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "rdkit/__init__.py", line 2, in <module>
from .rdBase import rdkitVersion as __version__
ImportError: /path/to/lib/libboost_python.so.1.59.0: undefined symbol: PyUnicodeUCS2_FromEncodedObject
Was there a good reason to not propagate ImportError? This doesn't seem to detract from the goal of #380 that originally put the code in there.
=> Cause ImportError from failed dlopen of the rdBase.so shared library to propagate.

Code/GraphMol/Chirality.cpp, Code/GraphMol/molopstest.cpp
This changes the way ring stereochemistry is identified and renders it insensitive to the details of the ring-finding algorithm.
The new implementation is about the same speed as the old one (maybe a bit quicker). It could almost certainly be optimized, but I want to get the fix in first and deal with that later when time arises.
It's been through valgrind and is clean.
=> Fixes issue #1021

Code/GraphMol/Atom.h, Code/GraphMol/Bond.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/test1.cpp
The "side effect" of this is that calling `{Atom,Bond}::getOwningMol()` now has a PRECONDITION that the owning molecule is actually set.
Given that those methods both dereference the pointer before returning it, I am *amazed* that this hasn't been a problem previously. Still, good to fix it now.
=> Fixes #1041

rdkit/Chem/Descriptors.py, rdkit/Chem/Descriptors3D.py, rdkit/Chem/UnitTestDescriptors.py
@bp-kelley It's not for this particular pull request, but we should think about how to get these into your properties interface and what the appropriate behavior should be for molecules that don't have conformers (at the moment it's a failing PRECONDITION, which is probably not long-term right)
=> make the 3D descriptors available in the Descriptors module

Code/GraphMol/Wrap/Conformer.cpp, Code/GraphMol/Wrap/rdchem.h, Code/GraphMol/Wrap/testConformer.py
hi Greg, 
The conformer GetPositions now  returns a numpy array rather than a tuple of tuples - I think this will be nice to most users, since probably people convert it into numpy manually anyway. 
But it's very minor and was mainly an exercise so feel free to drop it
=> Conformer GetPos returns a numpy array rather than a tuple of tuples

Code/GraphMol/Wrap/Mol.cpp, rdkit/Chem/Draw/IPythonConsole.py
A small one that builds on top of @bp-kelley's work to make the output of the rdkit logs visible in the jupyter notebook
=> Allow the output of ROMol::debugMol() to show up in jupyter

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/test1.cpp, Code/PgSQL/rdkit/CMakeLists.txt, Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/props.out, Code/PgSQL/rdkit/mol_op.c, Code/PgSQL/rdkit/rdkit.h, Code/PgSQL/rdkit/rdkit.sql.in, Code/PgSQL/rdkit/sql/props.sql, Docs/Book/Cartridge.md
This also adds JSON configuration options for the `MolDraw2D` class.
Here are a couple examples of how you invoke this from SQL:
```
glandrum=# select mol_to_svg('CO[2H]'::mol);
glandrum=# select mol_to_svg('CO[2H]'::mol,'legend');
glandrum=# select mol_to_svg('CO[2H]'::mol,'legend',250,200,'{"atomLabelDeuteriumTritium":true}');
```
It might be worth thinking about having a version where the full configuration is pulled from JSON instead of allowing the legend, width, and height to be provided without using JSON.
=> Provide SVG output from the cartridge

Code/GraphMol/Wrap/props.hpp, Code/GraphMol/Wrap/rough_test.py
Fixes #1113 
Reverse the order of property lookups, doubles should come last.
=> Check for doubles after other integer types when reporting properties

rdkit/TestRunner.py
shows the name and additional arguments of the failing subtest
=> add more detailed error reporting when python tests fail in TestRunner.py

Code/GraphMol/FindRings.cpp, Regress/Scripts/new_timings.py
This has the following two performance improvements to findSSSR that leads to speeding up Chem.SanitizeMol substantially on large systems  (thousands of atoms):
- When the fragment does not contain any rings as determined by Euler's formula (E-V+1 = #rings) such as a water box, skip the SSSR detection entirely. ~1800x faster on 9,000 waters with explicit hydrogens. 
- Avoid an O(N^2) loop to determine the number of bonds in the fragment. Use a cheaper method of summing the atom degrees and dividing by two. (There was already a loop over atom degrees, so easy to highjack that loop to do this operation). ~10x on 60,000 carbon atom chain with a cyclic-propane attached. 
The result is no real measurable effect on the new_timings.py smiles parsing unfortunately, but didn't make it worse :-) …
=> SSSR performance improvements to support larger systems

Contrib/M_Kossner/Frames.py, External/pymol/modules/pymol/rpc.py, Scripts/AddIssue.py, rdkit/Chem/DSViewer.py, rdkit/Chem/Pharm2D/LazyGenerator.py, rdkit/DataStructs/HierarchyVis.py, rdkit/Dbase/DbReport.py, rdkit/sping/PDF/pdfdoc.py, rdkit/sping/PDF/pidPDF.py, rdkit/sping/Pyart/Fontmapping.py, rdkit/sping/ReportLab/pidReportLab.py, rdkit/sping/SVG/pidSVG.py, rdkit/sping/TK/pidTK.py, rdkit/sping/tests/pidtest.py
This replaces all remaining has_key uses in the Python code.
Tests run fine, however I don't think there is a test for the SVG generation and I couldn't get cairo working on my laptop. Still, the changes are syntactic only, so modifications should be fine.
=> Replace has_key use in Python (#issue1042)

Code/GraphMol/Descriptors/test_data/pmi.py, Code/GraphMol/MolDraw2D/test_dir/test_rdkit_draw.py, Code/GraphMol/StructChecker/Wrap/rough_test.py, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/Wrap/testConformer.py, Code/cmake/Modules/fixup_coverage.py, Scripts/PythonFormat.py, rdkit/Chem/Descriptors3D.py, rdkit/Chem/Draw/IPythonConsole.py, rdkit/Chem/Draw/UnitTestIPython.py, rdkit/Chem/Draw/cairoCanvas.py, rdkit/TestRunner.py
Script PythonFormat.py will test the RDkit python code for conformance with the agreed format using yapf.
For each Python file that is found in $RDBASE (excluding the build and External directories), yapf is used with the style configuration in $RDBASE/setup.cfg. If a change is required, the difference is printed. At the end of the process, all non-conformant files are listed and the required yapf command(s) printed.
If changes are found, the script will exit with error code 1, otherwise 0.
Here is an example of running the Script. The script ends with error code 1.
```
peter$ python Scripts/PythonFormat.py 
--- /Users/peter/git/rdkit-gedeck/Code/GraphMol/Descriptors/test_data/pmi.py	(original)
+++ /Users/peter/git/rdkit-gedeck/Code/GraphMol/Descriptors/test_data/pmi.py	(reformatted)
@@ …
```
=> Script PythonFormat.py will test the RDkit python code for conformance with the agreed format using yapf

rdkit/Chem/Draw/UnitTestDraw.py, rdkit/Chem/Draw/UnitTestIPython.py
Importing IPythonConsole automatically executes `InstallIPythonRenderer()`. This causes problems with the UnitTestDraw.TestGridSVG test if automatic detection of unit tests is used. The test runner in RDkit avoids this problem by running individual processes for each unit test file. This PR implements setUp and tearDown methods that isolate the iPython tests within the same process.
=> Remove iPythonConsole configuration for normal Draw tests

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/AlignTests.java
Adding this method to the Java wrappers will allow RMSD calculations without the need to actually align the probe conformation to the reference
=> Added getAlignmentTransform to ROMol.i to expose in Java SWIG wrapper

Code/GraphMol/ChemReactions/Enumerate/Enumerate.cpp, Code/GraphMol/ChemReactions/Enumerate/EnumerationStrategyBase.h
With this change the code can now be built on systems with older versions of boost (multiprecision first showed up in 1.53).
=> only use boost::multiprecision when it is installed

Code/GraphMol/ROMol.cpp, Code/GraphMol/ROMol.h, Code/GraphMol/RWMol.cpp
As it turns out, boost::graph's use of a list has a non-constant behavior for getting the number of bonds (edges).  This is a patch to prevent this behavior for large systems.
It is somewhat informational, @coleb - please check to see if this helps your run-times.
=> Removes exponetial numBonds behavior

Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp
One more occurrence of `uint64_t` that requires `<boost/cstdint.hpp>` due to the lack of `<stdint.h>` in Visual Studio 2008.
=> Include <boost/cstdint.hpp> for uint64_t

Code/GraphMol/StructChecker/AtomSymbolMatch.cpp
The 'at' method of std::map is a C++11 feature not supported by Visual Studio 2008.
=> replace std::map::at with std::map::find

Code/GraphMol/Trajectory/Trajectory.cpp, Code/GraphMol/Trajectory/trajectoryTest.cpp, Code/GraphMol/Wrap/testTrajectory.py, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/TrajectoryTests.java
This fixes an issue with the `URANGE_CHECK` in the `getSnapshot` and `removeSnapshot` methods on `Trajectory`.
I came across the issue due to trajectory test failures when compiling with VS2008: any `GetSnapshot(n)` call on a `Trajectory` after calling `Clear()` results in a crash, rather than the expected Range Error Runtime error. For other compilers, the underlying vector elements may happen to still be accessible after calling clear on the vector, so the tests pass, but a similar crash can occur if an index larger than the original size of the vector is passed to `GetSnapshot(n)`.
The problem occurs specifically when the snapshot vector is empty - the size is zero as an unsigned int, which I think rolls over to INT_MAX when 1 is subtracted. As a result, `URANGE_CHECK` fails to catch …
=> Fix Trajectory GetSnapshot behaviour after Clear

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py
This will be more useful in a later pull request I'm working on that
exposes QueryBonds to Python. Though it is usable without QueryBonds
as well, so submitting this for now.
=> Expose RWMol.ReplaceBond to Python

Code/GraphMol/Resonance.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/resMolSupplierTest.cpp
This PR fixes #1162. At a closer look, the resMolSupplier test were fine. It was the underlying code not coping correctly with degenerate structures. Indeed, the two degenerate Kekule structures should be in the first two places when enumerating as they are degenerate. Boost 1.62 was just the trigger of two underlying bugs:
- fixed issue with weighted formal charges being stored as unsigned rather than as signed int
- the sum of formal charge and multiple bond indices is now used as last resort sort criterion to achieve stable sorting of degenerate resonance structures
=> Fixes #1162 (resMolSupplierTest failing with boost 1.62)

rdkit/CMakeLists.txt
Ensure `RDContribDir` is still available if `RDConfig` falls back to `RDPaths.py`
#1024 originally added `RDContribDir`, but not if neither `RDBASE` or `CONDA_DEFAULT_ENV` are set.
=> Add Contrib dir to RDPaths

Docs/Book/Install.md
Specific information for setting up the environment, building and testing. 
Ideally, we should fix the CMakeCache.txt file somewhere else.
=> Add information on building RDkit on macOS using conda

Code/GraphMol/Chirality.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/JavaWrappers/RDKFuncs_doc.i
This is a change in behavior of findPotentialStereoBonds to make it match _some_ of its doc strings. This makes findPotentialStereoBonds mark double bonds as Bond::STEREOANY if it could potentially be cis/trans. Previously, it would be marked Bond::STEREONONE, which isn't very helpful for locating the bond for further enumeration processing. 
Also wrapped findPotentialStereoBonds into Python and cleaned up and consolidated the doc strings for it into the header file. Test cases in Python to make sure it finds double bond stereo when it should, and doesn't when it shouldn't.  
The next pull request I want to submit after this is to submit a bond stereo enumerator. However, this comment in the code about how Bond::setStereo should not be wrapped has given me pause: …
=> Find potential stereo bonds should return any

Code/GraphMol/Chirality.cpp, Code/GraphMol/molopstest.cpp
This not only makes things correct, it also makes them faster.
The problem arose because `assignAtomCIPRanks()` does not do the recursion to deal with dependent stereochemistry that `assignStereochemistry()` does. This patch just uses whatever information on CIP ranks is there already, which usually comes from assignStereochemistry().
=> Fixes #1230

Code/GraphMol/ChemReactions/CMakeLists.txt
Second time's the charm.  This has been tested to compile, but I haven't had a compile failure so I don't know if it fixes those.
=> Turns on -fpermissive for gcc >= 6 and boost < 1.62

rdkit/Chem/PandasTools.py
This fixes a problem with versions of pandas that have "odd" version numbers like this (which is what's currently deployed via conda):
```
In [2]: pd.__version__
Out[2]: '0.19.2+0.g825876c.dirty'
```
This is what's causing the current travis failures.
Since this is minor and gets the tests working again, I'm going to go ahead and merge it soonish, but feedback from @gedeck and @bp-kelley would still be very welcome. :-)
=> make the Pandas version checking more robust

Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/test1.cpp
This is a simple patch to change the behavior so that `[Fe]->[Cu]` no longer matches `[Fe]<-[Cu]`.
=> Usethe directionality of dative bonds in substructure matching

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
This is a C++-based alternative to #1157 
Also provides some additional control over the MCS parameters from Python by exposing the MCSParameters objects to the Python wrapper.
=> Add the option to match formal charges to FMCS

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes #1322
Uses the `atomLabel` property
=> Add support for custom atom labels to C++ drawing code

Code/GraphMol/RWMol.cpp
A small change with huge performance impact:
stop looping over bond indices when renumbering bonds and use the BGL-provided edge interator interface instead.
=> Fixes #1359

Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
@bp-kelley : the change is trivial, but it has not yet been tested by actually building the C# wrappers
It would be great if you could try it out with your C# builds.
=> Fixes #664

Code/cmake/Modules/RDKitUtils.cmake
This is connected with #1036, there's a bunch of discussion there.
The change is simple and a good one to make, thought it will break other people's build scripts.
I've confirmed that builds and tests work on linux, the mac, and windows, but having others try would be good.
=> add "RDKit" to the beginning of all library names

Code/GraphMol/MolPickler.h
just a little one, but without it the code doesn't build with the old version of visual studio that conda uses for python 2.7
=> Fixes #1388

Code/GraphMol/Fingerprints/PatternFingerprints.cpp, Code/PgSQL/rdkit/expected/reaction.out
This tweak moves the new pattern added as part of #1354 to the end of the list of patterns so that the bit ids generated by the other patterns remains constant.
It also updates the expected results for the cartridge tests to reflect the new bits.
=> modify pattern fp order; update expected psql results

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Parsing SMILES with short (<9 character) chemaxon extensions is failing for me when compiling with VS2008.
I think this is because incrementing an iterator beyond its end leads to undefined behaviour, so `(first + 9) < last` is not actually guaranteed to return false for strings with less than 9 characters. Seems not to be an issue with most compilers but caused a crash in VS2008.
Changing to `std::distance(first, last) > 9` seems to fix the problem for me.
=> Fix cxsmiles parse on VS2008

Code/SimDivPickers/CMakeLists.txt, Code/SimDivPickers/MaxMinPicker.h, Code/SimDivPickers/testPickers.cpp
I also did a quick tour through the code to make sure this problem isn't present elsewhere. 
All other uses of `boost::uniform_int` were clean
=> fixes #1421

Code/GraphMol/Chirality.cpp, Code/GraphMol/hanoitest.cpp, Code/GraphMol/testChirality.cpp
When conflicting stereo directions are found on an atom:
- A warning is raised
- the double bond stereochemistry is set to STEREONONE
- the directionalities on the offending stereobonds are set to NONE:
```
In [2]: m = Chem.MolFromSmiles(r'C/C(\F)=C/C')
[05:10:05] Conflicting single bond directions around double bond 2.
[05:10:05]   BondStereo set to STEREONONE and single bond directions set to NONE.
In [3]: m.Debug()
Atoms:
0 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
1 6 C chg: 0  deg: 3 exp: 4 imp: 0 hyb: 3 arom?: 0 chi: 0
2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
3 6 C chg: 0  deg: 2 exp: 3 imp: 1 hyb: 3 arom?: 0 chi: 0
4 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
Bonds:
0 0->1 order: 1 conj?: 0 aromatic?: 0
1 1->2 order: 1 conj?: 0 aromatic?: …
```
=> Fixes #1423

rdkit/Chem/QED.py
Explicitly calls the Strict Rotor calculation in QED since the default can change based on the CMAKE file.
=> Directly specify rotor model used in QED.

Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/Descriptors/Wrap/test3D.py
If we disable 3D descriptors, RDKit fails to build.
Is there any reason *not* to always build 3D?  This would make the logic simpler.
=> Don't build AUTOCORR2D if 3D is turned off

Code/GraphMol/Descriptors/CMakeLists.txt, Code/GraphMol/Descriptors/GETAWAY.cpp, Code/GraphMol/Descriptors/MolData3Ddescriptors.cpp, Code/GraphMol/Descriptors/WHIM.cpp, Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt, Code/GraphMol/Wrap/CMakeLists.txt
- linked a few missing libraries that caused undefined references with MSVC
- changed a few `and` (that MSVC does not understand) into `&&`
- allocated a `double[]` as a `double *` on heap as MSVC does not accept non-const static arrays, and a couple others as `std::vector<double>`
- adjusted some indentation (purely cosmetic)
=> - assorted fixes to get the current master branch to build on Windows

Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
=> Removes trailing spaces after \ to fix windows compilation errors

Code/GraphMol/MMPA/MMPA.cpp, Code/GraphMol/MMPA/Wrap/testMMPA.py
Fixes #1407
Properly maps atom maps to the side chains.
Current output
```
Contrib/mmpa/rfrag.py <cs_c.smi | grep ':3'
Nc1cc(O)cc(Cl)c1,a,c1c([*:1])cc([*:3])cc1[*:2],Cl[*:1].N[*:2].O[*:3]
Nc1occ(Cl)c1O,b,c1oc([*:2])c([*:3])c1[*:1],Cl[*:1].N[*:2].O[*:3]
```
This seems like a bit of overkill, perhaps there is a better way.
=> Adds canonicalization of atom maps

Code/DataStructs/Wrap/DataStructs.cpp, Code/DataStructs/Wrap/testBV.py
adds `ConvertToNumPyArray()` versions for the various `SparseIntVect` types
=> fixes #1447

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/test1.cpp, Code/JavaWrappers/MolDraw2D.i
Fixes #1510, among other things.
Instead of just supporting B&W rendering, I also added support for more general palettes (in the sense that code can now provide an `atomic_num->DrawColour` map).
=> Provide support for color palettes in MolDraw2D

Code/GraphMol/FindRings.cpp, Code/GraphMol/molopstest.cpp
This just causes the molecule processing to fail in a reasonable amount of time; it is not an actual fix to the underlying ring-finding problem
The real solution here would be to finish integrating the new ring-finding code from Florian (which I will eventually do). However, since that has turned out to be harder than expected, I'm adding this workaround so that the ring-finding algorithm throws an exception when things get too hairy instead of consuming all system memory.
I verified that this fix did not lead to any additional molecule parsing failures when processing the 1.7 million structures in ChEMBL 23
=> A sort of fix for #1281 

Code/GraphMol/QueryAtom.h, Code/GraphMol/QueryBond.h, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/test1.cpp, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Bond.cpp
This also moves the C++ versions of the `describeQuery()` functions for atoms and bonds from the code for the Python wrapper into the main C++ API. The functions are generally useful.
=> Fixes #1489

Code/GraphMol/CMakeLists.txt, Code/GraphMol/MolBundle.h, Code/GraphMol/ROMol.h, Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/testMolBundle.cpp
This adds a `MolBundle`: a class to hold groups of molecules that have the topology (currently enforced as the same number of atoms and bonds).
It also adds integration of that class with the substructure searching code.
At the moment this isn't particular interesting, but it lays the groundwork for support of things like enhanced stereochemistry in the not-too-distant future.
The current implementation is certainly not the most memory efficient way of solving the problem, but the API should allow us to move to something better if that becomes important. The once concern there is the `getMols()` method, which we may want to consider removing from the API.
=> Add a MolBundle class

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/MolPickler.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/testPickler.cpp, Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/rdkit-91.sql
The R-group decomposition PR changed `AdjustQueryParameters::adjustDegree` from bool to int and used the value of the int to determine which type of degree query was added - normal or heavy-atom degree. This was awkward and not backwards compatible.
This PR switches `AdjustQueryParameters::adjustDegree` back to being a bool and adds the new parameter `AdjustQueryParameters::adjustHeavyDegree` to allow heavy-atom degree queries to be added.
=> handle the heavy-atom degree queries differently

External/INCHI-API/inchi.cpp, External/INCHI-API/test.cpp, rdkit/Chem/UnitTestInchi.py
The InChI parser has a number of special cases to try and get the molecule more "RDKit like". This makes some small modifications to one of them in order to fix the handling of the substructure `CN(=O)=N(=O)C`. (this is something that the InChI code produces)
=> Fixes github #1572

Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp, Code/GraphMol/MolAlign/Wrap/testMolAlign.py, Code/GraphMol/MolAlign/testMolAlign.cpp, rdkit/Chem/AllChem.py
getBestRMS() was previously a Python-only function. This
adds a C++ version of the function.
=> Added C++ version of getBestRMS()

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/hanoitest.cpp, Code/GraphMol/new_canon.cpp, Code/GraphMol/new_canon.h
This fixes a bug in the way atom degree was treated when canonicalizing fragments of molecules. It only affects `MolFragmentToSmiles()` and `canonicalizeFragment()`.
The key point is to not lose all information about the degree of the atom in the full molecule
@NadineSchneider has looked at it and "signed off". :-)
=> Fixes github1567

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
There's a workaround to get roughly the same effect from client code, but it's a pain. This is an easier (and more intuitive) solution to the problem: if `continuousHighlighting` is on and you call `drawMolecules()` and just provide the atoms to be highlighted, then the behavior is the same as `drawMolecule()` in the same situation - bonds connecting the highlighted atoms will also be highlighted.
Also adds a `fillHighlights` option to `DrawOptions`
=> Support continuous highlighting in drawMolecules().

Code/SimDivPickers/MaxMinPicker.h, Code/SimDivPickers/Wrap/MaxMinPicker.cpp, Code/SimDivPickers/Wrap/testPickers.py
This is used to either set or return a threshold for the picks.
It allows retrieval of the distance of the last item picked from its nearest neighbor as well as specification of a minimum value this should be.
@bp-kelley : I'm struggling a bit with how to expose this extra arg that's used to return a value on the Python side without breaking the existing python API. Any thoughts?
=> [WIP] add threshold argument to maxmin picker

rdkit/Chem/UnitTestMol3D.py
My fingers are used to having py.test run my test cases!
@bp-kelley, no reason to make you fix this.
=> Use self.assertEqual for better failing test case error messages.

Code/GraphMol/Descriptors/AUTOCORR3D.cpp
The `std` version doesn't exist in older compilers (like MSVC2010)
=> switch to using boost::isnan instead of std::isnan

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/QueryAtom.h, Code/GraphMol/QueryBond.h, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/Wrap/MolOps.cpp
This is what `QueryBond::setQuery()` does and makes more sense than requiring the caller to remember to do the delete in order to avoid a leak
This could theoretically cause problems if there is any client C++ code that is using `QueryAtom::setQuery()` and being careful about deleting the existing query. This doesn't seem overly likely.
=> QueryAtom::setQuery() should delete the old query first

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py
This was "inadvertently omitted" from the original PR for the MolBundle.
=> add substructure searches of Mols using MolBundles from Python

Code/JavaWrappers/gmwrapper/GraphMolJava.i
I was getting the following error while trying to build Java wrappers on Windows with VS2017 and Boost 1.64:
`C:/boost/boost_1_64_0/boost/smart_ptr/shared_array.hpp:57: Error: Syntax error in input(3).`
The reason is that the `BOOST_SP_NOEXCEPT` macro is not defined when `shared_array.hpp` is included by SWIG. The fix is to add a definition for `BOOST_SP_NOEXCEPT` in `GraphMolJava.i` to those already present.
=> Fixes Java wrapper build error with Boost 1.64

Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake, Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake, Code/GraphMol/SmilesParse/smiles.yy, Code/GraphMol/SmilesParse/test.cpp
Fixes #1623 
This implements an extension to the OpenSMILES standard to handle ring closure numbers greater than 99, and up to five digits. The extension supports %(N) to %(NNNNN), where N is a digit. 
Test cases are included.
I didn't force the requirement of a non-zero leading digit, but that may be something you wish to consider.
=> Add support for %(NNN) notation for ring closures

Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt
This links in additional libraries to make things work
With the code at this state I can do a conda build that includes cairo support, which is a big win on the Windows side.
=> Enable windows build that uses cairo

rdkit/Chem/Draw/IPythonConsole.py
SVG rendering in IPythonConsole is broken. 
Quick hot fix to get it working again.
Not sure the best way to unit test this internal API.
=> Fixing bug in IPythonConsole SVG rendering introduced in 1027d4469545653180fff9a38dc8224bd50e8b0d

Code/DataManip/MetricMatrixCalc/Wrap/rdMetricMatrixCalc.cpp, Code/DataStructs/Wrap/DataStructs.cpp, Code/Demos/boost/numpy/linalg.cpp, Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp, Code/GraphMol/ReducedGraphs/Wrap/rdReducedGraphs.cpp, Code/Numerics/Alignment/Wrap/rdAlignment.cpp, Code/RDBoost/CMakeLists.txt, Code/RDBoost/boost_numpy.h, Code/SimDivPickers/Wrap/HierarchicalClusterPicker.cpp, Code/SimDivPickers/Wrap/MaxMinPicker.cpp
boost python numeric no longer exists in boost 1.65, so check boost version and conditionally use boost python numpy.
Fixes #1581
Fixes https://github.com/rdkit/homebrew-rdkit/issues/43
=> Use numpy not numeric for boost 1.65+ - fixes #1581

Code/GraphMol/MolTransforms/MolTransforms.cpp, Code/GraphMol/MolTransforms/Wrap/testMolTransforms.py, Code/GraphMol/MolTransforms/test1.cpp
There is no need to enforce that (i, j) and (k, l) be bonded when setting a i, j, k, l dihedral.
For example, in OCC#CCN one might want to rotate clockwise by 60 degrees the hydroxymethyl and aminomethyl groups around the C#C axis by doing a perfectly legitimate
`MolTransforms::setDihedral(conf, 0, 2, 3, 5, MolTransforms::getDihedral(conf, 0, 2, 3, 5) + 60.0)`
but the current code does not allow this as (i, j) and (k, l) are not bonded. However, the only requirement here is that (j, k) be bonded.
So I am removing the checks for (i, j) and (k, l) to be bonded that I originally put in, as they are not required.
=> There is no need to enforce that (i, j) and (k, l) be bonded when setting a i, j, k, l dihedral

Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
Apologies for the amount of code reformatting that got mixed in here.
The actual changes are the two uses of this code snippet to register the `MOL_SPTR_VECT` class:
```
// logic from https://stackoverflow.com/a/13017303
boost::python::type_info info =
boost::python::type_id<RDKit::MOL_SPTR_VECT>();
const boost::python::converter::registration *reg =
boost::python::converter::registry::query(info);
if (reg == NULL || (*reg).m_to_python == NULL) {
python::class_<RDKit::MOL_SPTR_VECT>("MOL_SPTR_VECT")
.def(python::vector_indexing_suite<RDKit::MOL_SPTR_VECT, true>());
}
```
No specific test is included for this since the fix just prevents a warning from Boost. If the rest of the tests pass then we haven't broken anything.
=> Fixes #1695

Code/GraphMol/MolTransforms/Wrap/rdMolTransforms.cpp, Code/GraphMol/MolTransforms/Wrap/testMolTransforms.py
Request from Pavel Polischuk:
https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg07600.html
Implements Python wrappers for computePrincipalAxesAndMoments() and computePrincipalAxesAndMomentsFromGyrationMatrix()
=> - implemented Python wrappers for computing PMI axes and moments

Code/GraphMol/Descriptors/AUTOCORR2D.h, Code/GraphMol/Descriptors/CMakeLists.txt, Code/GraphMol/Descriptors/test.cpp
Nothing particularly complicated here: make sure that the Autocorr2d descriptor is always enabled.
=> Fixes github #1702

Code/GraphMol/ROMol.h, Code/GraphMol/test1.cpp
This updates the `ROMol` documentation to recommend an alternative approach to looping over an atom's neighbors or bonds.
I added a couple of tests to demonstrate that it actually works.
I think that this:
```
for (const auto &nbri :
boost::make_iterator_range(m.getAtomNeighbors(atomPtr))) {
const auto &nbr = (*m)[nbri];
// nbr is an atom pointer
}
```
is pleasingly simpler than this:
```
ROMol::ADJ_ITER nbrIdx,endNbrs;
boost::tie(nbrIdx,endNbrs) = molPtr.getAtomNeighbors(atomPtr);
while(nbrIdx!=endNbrs){
const ATOM_SPTR at=molPtr[*nbrIdx];
...
++nbrIdx;
}
```
If this looks reasonable, I'll start working through the code to make this the standard way of calling those functions.
=> [WIP] additional range-based for examples

Code/GraphMol/MolPickler.cpp, Code/GraphMol/SmilesParse/smatest.cpp
Fixes a problem pickling/unpickling range queries.
Fixes the unpickling of the new cactvs extensions added in #1704
=> Get queries from the new cactvs SMARTS extensions to pickle correctly

Code/RDBoost/boost_numpy.h
report from Roger S. easy fix.
=> fix illegal use of typename in the new python_numpy code

Code/GraphMol/MolPickler.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.h, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/testPickler.cpp, Code/cmake/Modules/FindCairo.cmake
The current SMARTS parser uses about charges, number of Hs, and isotopes exclusively to construct query information, but the corresponding properties of the atoms themselves aren't set. This leads to this behavior:
```
In [28]: p = Chem.MolFromSmarts('F([N@H+](Cl)Br)')
In [29]: Chem.MolToSmiles(p,isomericSmiles=True)
Out[29]: 'FN(Cl)Br'
In [30]: print(Chem.MolToMolBlock(p))
RDKit          
4  3  0  0  0  0  0  0  0  0999 V2000
0.0000    0.0000    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
0.0000    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
0.0000    0.0000    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
0.0000    0.0000    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
3  2  6  0
2  4  6  0
2  1  6  0
V    2 [N&*&H1&+]
M  END
```
This PR changes that, with it applied you …
=> Set atomic properties from SMARTS

Code/GraphMol/Depictor/EmbeddedFrag.cpp, Code/GraphMol/Depictor/testDepictor.cpp
The change made to fix #910 caused the problem. The fix here (to include all explicit atoms when looking at degree) resolves it without breaking anything else. Thought `getDepictDegree()` is super simple, I think it's worth keeping around in case we find some other case in the future where some refinement needs to be done.
I'll backport to master after it's merged.
=> Fixes #1691

Code/GraphMol/AddHs.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp
This PR fixes behavior of AddHs for molecules read from PDB file. Current behavior is to ignore residue information. What's more, the Hs written to PDB file are always HETATM and of UNL residue.
Proposed changes add AtomPDBResidueInfo based on the information collected from the root atom.
I decided against adding a flag, since it doesn't break default behavior and is kind of expected when working with proteins.
=> Improve AddHs for molecules read from PDB

Projects/DbCLI/TestDbCLI.py, rdkit/RDConfig.py
Sometimes python is installed as "python3" not "python".  This updates the TestRunner to work in these cases.
=> Updates python test runner to always use sys.executable

CMakeLists.txt, Scripts/run_python_tests.py, rdkit/TestRunner.py
This provides a new cmake option `RDK_INSTALL_PYTHON_TESTS`, which defaults to off.
When this is set, the cmake-based installation will include the tests and test data that are found in the `rdkit` directory (the current behavior is to not include these in the installation). 
Another change is to start installing the `Scripts` directory in `${RDKit_ShareDir}`. This makes the helper scripts like `FeatFinderCLI.py` part of the installation. When test installation is enabled this directory will also include the script `run_python_tests.py`d, which launches the test framework to run all tests in the `rdkit` module.
=> Allow installation of Python tests to facilitate testing installations

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/test1.cpp
Allows blank lines in place of old-style atoms lists when `strictParsing` is false
=> Fixes #1689

Code/GraphMol/FileParsers/PDBParser.cpp, Code/GraphMol/Wrap/rough_test.py
This is small addition to #1629, which treats the bonds in PDB file as explicit. If they are made between blacklisted pair of atoms (waters, anions, noble gases, metaloids or metals) they are made zero-order. This is very in line with the [original publication by Alex Clark](http://pubs.acs.org/doi/abs/10.1021/ci200488k), which introduced the zero-order bonds. If someone wanted these bonds removed, then appropriate `flavor` flag will ignore PDB CONECT records and will get the bonding from atoms proximity, which will not add those. 
This will also make recent changes to PDB reader less intrusive and more backward compatible, as all bonds from file will be in place, as one could suspect.
=> Treat bonds in PDB CONECT records explicitly, but make blacklisted ones zero-order.

rdkit/Chem/Features/FeatDirUtilsRD.py, rdkit/Chem/Features/UnitTestFeatDirUtilsRD.py, rdkit/Chem/Features/test_list.py
Dear Greg,
First of all, as is the first time I write you, I want to present me. I am starting my PhD of bioinformatics in Barcelona, and I am using the RDKit library in some aspects of my work.
ConcreteIy, I am using the FeatDirUtilsRD to calculate the feature vectors of a feature and I have found some apparent mistakes in the function GetDonor2FeatVects.
I think that there is a confusion with the "nbrs" list. The first thing that the function does is to create a "hydrogens" list to use it after. But after the while loop, the list "nbrs" doesn't contain anymore the all neighbours (including hydrogens) of the donor, but only the heavy neighbour atoms. The "nbrs" list is used after the while with two meanings: as if it contained all the neighbours or only the heavy ones (I think here is …
=> Fix: GetDonor2FeatVects heavy atoms confusion

CMakeLists.txt, Code/GraphMol/SLNParse/CMakeLists.txt, Code/GraphMol/SLNParse/SLNParse.cpp, Code/GraphMol/SLNParse/Wrap/CMakeLists.txt
This is another "take advantage of built-in C++11 features" ticket and removes the boost regex dependency.
Since regex is only used in the SLN parser, this isn't a big change.
I've tested on linux, the Mac, and Windows (VS2015).
=> switch to using std::regex in the SLN parser

Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
The second commit also clears up some deprecation warnings in `testMolDescriptors.py`
=> Fixes #1749

Code/GraphMol/CMakeLists.txt, Code/GraphMol/ROMol.h, Code/GraphMol/test-valgrind.cpp, Code/GraphMol/test1.cpp
The new code for doing range-based loops over atoms and bonds illegally dereferences the `end()` vertex/edge iterators when `CXX{Atom,Bond}Iterator::end()` is called. This fixes that.
There's also a memory leak fix for one of the recently added tests.
=> Stop dereferencing end() iterators

Code/GraphMol/ChemReactions/testReaction.cpp, Code/GraphMol/ChemTransforms/testChemTransforms.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/ReducedGraphs/Wrap/testReducedGraphs.py, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/molopstest.cpp, Code/GraphMol/testChirality.cpp, rdkit/Chem/Fraggle/FraggleSim.py, rdkit/Chem/Fraggle/UnitTestFraggle.py, rdkit/Chem/Recap.py, rdkit/Chem/UnitTestEnumerateHeterocycles.py, rdkit/Chem/UnitTestSmiles.py
outputting dummy atoms as `[*]` instead of `*` is unnecessary and ugly, so stop doing it.
=> Stop putting brackets around * atoms in SMILES

Docs/Book/Cookbook.md
Under the **Neutralizing Charged Molecules** heading, there was a reference to the mailing list archive, however, this link pointed to an unrelated topic which related to the **Parallel conformation generation** heading. I have replaced it with the only thread from the mailing list archive which I could find which relates to the appropriate topic. Unfortunately, there does not appear to be the original code available from this thread as it point to a dead Google Code Wiki link. 
I apologize if I have included the incorrect thread, but I just wanted to try and fix this issue.
=> Replace link to incorrect thread

Code/GraphMol/Aromaticity.cpp, Code/GraphMol/Resonance.cpp, Code/GraphMol/molopstest.cpp
setAromaticity() now works even if there are aromatic atoms present and the relevant test case is added
Fixes #1730
Removed the existing aromaticity info check from aromaticityHelper() used by setAromaticity() that made it not touch the molecule if there are any atoms set as aromatic already.
=> Fix for issue #1730

Code/DataStructs/BitOps.cpp, Code/RDGeneral/StreamOps.h, Code/SimDivPickers/MaxMinPicker.h
This is a somewhat cleaned up version of an idea from Roger to make the Tanimoto similarity calculation faster. It is a bit hacky, but saves some memory allocation.
At some point in the not too distant future we should switch away from the use of `boost::dynamic_bitset` for the `ExplicitBitVect` data structure and this can be removed. I've got a branch in progress for that switch, but it's unlikely to be done for the next release, so I think it's worth using this for a while.
=> speedup the NumBitsInCommon operation

Code/JavaWrappers/DistGeom.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/DistanceGeometryTests.java
- They should not be writeable (this was a problem everywhere)
- On the Mac there were seg faults caused by globals being deleted (at least I think that was what was going on).
- The EmbedParameters struct also did not have a copy ctor in Java.
This fix manually creates functions to expose copies of the relevant objects to Java and adds the copy ctor.
=> change how the EmbedParameter objects are exposed to Java

CMakeLists.txt, Code/cmake/Modules/RDKitUtils.cmake
the changes to the cmake system were resulting in huge conda installs on windows.
This fixes that by allowing the "dev" pieces to be skipped when doing a "make install"
=> allow libs to not be installed

Code/GraphMol/FMCS/FMCS.cpp, Code/RDGeneral/types.h
I had compilation issues on Windows because I set /D_USE_MATH_DEFINES globally. This caused a compilation failure when including types.h.
Maybe the `_DEFINED_USE_MATH_DEFINES` setting is excessive.
=> Allow types.h to be included in applications that use /D_USE_MATH_DEFINES

Code/GraphMol/Wrap/RingInfo.cpp
This PR exposes in Python the smallest ring size for bonds and atoms from `RingInfo` and directly from `Bond` and `Atom` objects. There are no efficient ways to do it now from Python other than iterating over a range of sizes with `IsInRingSize`...
`RingInfo` has those methods already exposed in Java. Is there an automatic way we could make sure that the exposed API match?
=> Expose minAtomRingSize() and minBondRingSize() to Python wrappers

Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/test1.cpp, Code/GraphMol/MolDraw2D/test1.cpp.hold, Code/GraphMol/MolDrawing/DrawingToSVG.h, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java, Code/PgSQL/rdkit/expected/props.out, rdkit/Chem/Draw/__init__.py, rdkit/Chem/PandasTools.py
As I understand it, there are two ways to handle the svg namespace in svg output: Either use `xmlns:svg='http://www.w3.org/2000/svg'` and prefix every svg element with `svg:`, or use `xmlns='http://www.w3.org/2000/svg'` to indicate a default namespace so no prefixes are needed.
I think they are equally valid. RDKit uses the former, however there are a whole bunch of places in the python wrappers where the `svg:` prefix is manually stripped off every element before the output is returned. The `xmlns` definition is not modified, so I think the output is invalid.
I presume there may be some issue with using the prefixed version that caused the stripping code to be added in the first place. So instead, this PR makes svg the default namepace, so no prefixes or stripping are needed.
=> Make svg xmlns prefix use more consistent

Code/GraphMol/QueryOps.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/SLNParse/SLNAttribs.cpp
Fixes QueryOps.h to not consider dummy atoms as "heavy" as they can be either.  This allows the RGroupDecomp to allow rgroups to match both heavy and H atoms.
=> R-group Decomposition: allow H replacements when matchOnlyAtRgroups is set

rdkit/RDConfig.py
These manually set paths are incorrect on Windows. In fact, they don't need to be manually set anyway. Instead, just fall back to using RDPaths, which hardcodes a (placeholder) path at build time. When installing a conda package, conda dynamically replaces all occurrences of hardcoded absolute paths with the correct path to the environment.
This should mean that the [rdconfig.patch](https://github.com/rdkit/conda-rdkit/blob/dev/anaconda5_moderncxx/rdkit/rdconfig.patch) used in the conda recipe is no longer needed.
=> Don't manually set RDConfig paths in conda env

Code/GraphMol/FileParsers/CMakeLists.txt
Fixes a link error of `fileParsersTest1` when building with `maeparser`
=> Fixes a link error on Windows

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py
The Pandas doctest was failing as on Windows you may get a spurious warning about missing fonts, e.g.:
```
Warning: unable to load font metrics from dir c:\build\rdkit\rdkit\sping\PIL\pilfonts
```
This can be solved using `doctest.ELLIPSIS`, however I redefined the `ELLIPSIS` marker to be `*...*` rather than the default `...` as the latter can be confused by `doctest` with the Python continuation prompt and therefore not work as expected when used at the beginning of a lline, as required to match a line which may have any content (as well as no content at all). See https://stackoverflow.com/questions/1024411/can-python-doctest-ignore-some-output-lines for a discussion.
=> Fixes pandas doctest on Windows

Scripts/create_deb_packages.sh
related to https://github.com/rdkit/rdkit/issues/911 and https://github.com/rdkit/rdkit/pull/1580
A ready to use script so that people can easily generate binary deb packages
from the source tree.
This will ease the Ubuntu PPA maintainance and make sure that people can easily
check the working condition and relevance of the cpack rules related to deb packages.
=> added Scripts/create_deb_packages.sh

rdkit/Chem/PandasTools.py
One of the defaults for how printing of data frames is done changed with the move to pandas 0.23.
Here's some more detail on the underlying change:
https://github.com/pandas-dev/pandas/issues/21337
=> get the pandas tests working with pandas 0.23

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
This method was overlooked when I created the wrappers.
=> expose MolDraw2DSVG.tagAtoms() to python

Code/GraphMol/FileParsers/test1.cpp, Code/RDGeneral/LocaleSwitcher.cpp
Locale handling was broken under Windows.
- avoids that the recursion counter becomes negative
- resets the switched boolean
- restores the pre-existing locale rather than the user-defined one as it may have changed compared to the user's default locale (I implemented the same behaviour as on other platforms)
=> Fixes locale handling on Windows

External/CoordGen/CMakeLists.txt
This updates the cmake configuration so that it uses named releases (instead of particular commits) of the coordgenlibs and maeparser from Schrodinger
=> Fixes #1887

Code/cmake/Modules/RDKitUtils.cmake, External/CoordGen/CMakeLists.txt
The code in the `coordgen` and `maeparser` now incorporates explicit `dllimport`/`dllexport` decorators, however it does not seem to support building static libraries on Windows anymore, as `dllimport`/`dllexport` decorators are always added.
As the RDKit needs to build static libraries too, I added a `patchCoordGenMaeExportHeaders()` function to `RDKitUtils.cmake` which adds a few pre-processor directives to `coordgen` and `maeparser` headers to allow that. Additionally, I removed the `CMAKE WINDOWS EXPORT_ALL_SYMBOLS` bit from the `coordgen` `CMakeLists.txt` as it is not needed anymore, since now explict decorators are present in the headers. I also added the `-DIN_COORDGEN` and `-DIN_MAEPARSER` definitions to the `coordgen` `CMakeLists.txt` as required by the new `coordgen`/`maeparser` …
=> Allow coordgen and maeparser to be built as static libraries

Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
CSharp wrappers fail to build on Windows against DLLs.
Same fix as for the Java wrappers - I just had not thought of the CSharp wrappers in the first place as I never used them.
=> Fix the build of CSharp wrappers just as for Java wrappers

Code/cmake/Modules/RDKitUtils.cmake
The `RDKit` prefix is not added to dynamic libraries on Linux/macOS.
Also, symbolic links are not created for Linux and macOS dynamic libraries.
Adds the `RDKit` prefix to dynamic libraries on Linux/macOS.
Creates symbolic links for Linux and macOS dynamic libraries.
=> Fixes the absence of the RDKit prefix in .so/.dylib libraries

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py, ReleaseNotes.md
There was no straightforward way to have `GetAtomSmarts()` (which returns SMILES if the atom has no query) return isomeric SMILES for atoms. This clears that up by adding an optional argument to `RDKit::SmilesWrite::GetAtomSmiles()` that causes it to return isomeric SMILES. In the spirit of #1679, this defaults to `true`. This is different than the current behavior (thus the `changes results` tag), but is certainly more correct.
=> Allow Atom.GetAtomSmarts() to return isomeric SMILES

Contrib/IFG/ifg.py
@thegodone @Richard-Hall : The IFG contribution to the RDKit didn't include anything explicit about the license. This fixes that.
Are you ok with the changes?
=> Make IFG contrib license clearer

Code/GraphMol/AddHs.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/FilterCatalog/FunctionalGroupHierarchy.cpp, Code/GraphMol/FilterCatalog/update_pains.py, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/StructChecker/ReCharge.cpp, Code/GraphMol/StructChecker/Tautomer.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/testPicklerGlobalSettings.cpp, Code/SimDivPickers/testPickers.cpp
**What does this implement/fix? Explain your changes.**
I compiled using clang and Python3. It's possible that neither are the default for other users, so I saw a couple of warning messages that looked easy to fix.
This includes two commits:
- Close open file handles during build set-up (a6e8fa9), which addresses several "ResourceWarning:
unclosed file" when building under Python3
- Address minor compiler warnings (af9a4fd), which addresses several trivial warning messages under clang.
=> Addresses several minor warning messages during the build

External/CoordGen/CoordGen.h, External/CoordGen/test.cpp, rdkit/RDConfig.py
This does two things:
1) Remove the cause of the segfault
2) start setting `$RDBASE` on the Python side when `RDPaths` is being used.
=> Fixes #1929

Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
not just after searching
This was noted by Andrew Dalke.  It can be a large optimization or a minor one depending on the number of false positives in the bit vector.
=> Fix embarassing bug, check the counter each iteration 

Docs/Book/Install.md
To build RDKit under anaconda environment in linux, a couple of fixes are required, since the GLIBC version with which 'boost' requires is higher than the one in the default compiler. Also, numpy headers must be linked into the main include directory for RDKit to be able to find them.
It adds detailed instructions on how to build from source in Linux/andaconda3 environment.
Thanks!
=> Update Install.md for linux build in anaconda environment

Docs/Book/Install.md
Also fixes a couple other lines that didn't get parsed as code blocks.
Not sure whether or not you're OK pointing users to the unofficial conda-forge feedstock -- the installation is probably easier via the conda-forge package if you already are using other package supplied via conda-forge. But those users might already know about the rdkit package?
=> Add conda-forge tip to Install.md

Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/test.cpp
adds another special case for these.
At some point it would be worthwhile to refactor the way that ring closures are handled by the SMILES/SMARTS parsers, but that's a larger undertaking.
=> Fixes #1972

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/smatest.cpp
The trick here is to call `updatePropertyCache()` before generating SMARTS.
=> Fixes #1985

Code/DataStructs/testDatastructs.cpp, Code/GraphMol/Fingerprints/AtomPairs.cpp, Code/GraphMol/Fingerprints/MorganFingerprints.cpp, Code/GraphMol/Fingerprints/test1.cpp
This is a "do the right thing by default" fix: the code will now call `assignStereochemistry()` if you ask for a fingerprint where chirality is used on a molecule where stereochemistry has not been assigned.
=> Part of a fix for #1993

Code/GraphMol/SmilesParse/CMakeLists.txt, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParse.h, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/SmilesParse/smiles.ll, Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake, Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake, Code/GraphMol/SmilesParse/smiles.yy, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/SmilesParse/test2.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
It ended up being reasonably straightforward (though somewhat under-documented) to add mulitiple entry points to the parsers.
`SmilesWrite.cpp` is a good target for a future refactoring exercise: there's more duplicated code there than I would like.
Fixes #1919
=> Add support for constructing atoms/bonds from SMILES/SMARTS

Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/molopstest.cpp
makes sure we don't destroy a double bond's StereoAtoms just because a bond connected to one of its atoms is removed
=> Fixes #1990

Code/GraphMol/Substruct/SubstructMatch.cpp
Based on this SE post: https://stackoverflow.com/questions/44534516/error-make-array-is-not-a-member-of-boostserialization
Fixes #2015
=> Add missing boost header for v1.64

Code/GraphMol/MolOps.cpp, Code/GraphMol/molopstest.cpp
Fix for #2020 
During halogen cleanup, only add a positive formal charge when there is a double bond and a negative charge is also set on the oxygen atom.
Closes #2020
=> correct mistake in halogen cleanup and add test cases, fix for #2020

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp, ReleaseNotes.md
Adds atom ring membership to be taken into account when determining whether a ring-ring match is present.
We should also add something equivalent for completeRingsOnly, but that can be a separate issue.
=> Fixes #2034

Code/GraphMol/test-valgrind.cpp, Code/RDGeneral/Dict.h
Simple fix for Dict.h
Operator= was leaking non-pod properties from the underlying Dictionary.
=> Fix memory leak in Dict operator=

Code/GraphMol/AddHs.cpp, Code/GraphMol/catch_tests.cpp
Simple fix: copy properties from reactant atoms over to product atoms.
I don't think this should break anything, but you may want to have a look at it @bp-kelley
=> Fixes #2062

Code/GraphMol/SmilesParse/SmilesParse.h, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp
This allows these constructs to be used:
```
auto m = "c1ccccc1"_smiles;
auto p = "c1ccc[c,n]c1"_smarts;
```
The types of both `m` and `p` above are `std::unique_ptr<RWMol>`, so the above is roughly a replacement for:
```
std::unique_ptr<RWMol> m(SmilesToMol("c1ccccc1"));
std::unique_ptr<RWMol> p(SmartsToMol("c1ccc[c,n]c1"));
```
This is a small bit of syntactic sugar, but I think it will make writing tests easier and less error prone (by "enforcing" the use of smart pointers).
=> Add user-defined literals for parsing SMILES and SMARTS

CMakeLists.txt, External/catch/CMakeLists.txt
This is the only changes we make to the RDKit in order to be able to build it internally for our infrastructure. Hopefully they are generally useful enough features that they could be included in the mainline RDKit. 
- Adding a RDK_BUILD_RPATH_SUPPORT CMake option to build the RDKit shared libraries with -rpath pointing to the location that the C++ shared will be installed into.
- Allow catch to be manually downloaded into the proper location (similar to the rest of the Extrernal dependencies). We have the requirement that our software deployments need to be self-contained (i.e. make no external internet connections), this gives us a guarantee that we have all the proper sources in place to re-create any binary package. 
Including these in the mainline would make it easier for us to keep …
=> Expose a CMake flag to build RDKit with -rpath

.gitignore
Building & running tests on RDKit places some files outside of the build directory. These will always show up on git as "untracked".
This PR is to have git ignore these files.
=> Updated .gitignore with files generated outside of build directory.

Code/PgSQL/rdkit/CMakeLists.txt
https://gitlab.kitware.com/cmake/cmake/issues/17223
https://bugzilla.redhat.com/show_bug.cgi?id=1618698
It is adding `cmake -D PostgreSQL_CONFIG=<whatever>` support, for systems where `pg_config` lives in `/bin/pg_server_config`.
=> PgSQL: add support for PostgreSQL_CONFIG cmake var

Code/GraphMol/Canon.cpp, Code/GraphMol/Canon.h, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp
Fix #2042 the code was developped during Cambridge RDKit UGM 2018 by Guillaume GODIN and Takayuki Serizawa.
We implement a new option to generate pure random smiles from a given rootAtoms number. This parameters doRandom is set by default to false to have rule based rdkit smiles generator. Setting it to True allows user to generate more smiles.
basically this is the command to run to produce more random smiles:
t= Chem.MolToSmiles(m, rootedAtAtom=n, canonical=False, doRandom=True)
complete example to show that the number of generated smiles increase:
from __future__ import print_function
import random
from rdkit import rdBase
def allsmiles(smil, doRandom):
m = Chem.MolFromSmiles(smil) # Construct a molecule from a
if m is None:
return smil
N = m.GetNumAtoms()
if …
=> Fix #2042 allowing python/c++ randomizer smiles generator

External/CoordGen/CoordGen.h
This should not have been in the release in the first place
=> Coordgen: stop printing Templates location

Code/cmake/Modules/RDKitUtils.cmake
This addresses the problem pointed out by @balducci in #2125
=> add explicit catch dependency for tests that use it

Code/PgSQL/rdkit/bfp_gin.c, Code/PgSQL/rdkit/bfp_gist.c, Code/PgSQL/rdkit/low_gist.c, Code/PgSQL/rdkit/rdkit_gist.c
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=6337865f36da34e9c89aaa292f976bde6df0b065
Upper-cased spelling for boolean definitions has been removed in Postgresql 11 in favour of using just lower-cased spelling. As mentioned in the postgresql commit, existing code can be changed to
the lower-cased spelling in a backward compatible way.
=> PgSQL: fix boolean definitions for Postgresql 11

rdkit/Chem/Recap.py
Recap.py line 141
Recap.py
In RecapHierarchyNode class, __init__ defines 'parents' but __del__ defines 'parent'. It seems bug.
Taka
=> Fix typo in RecapHierarchyNode destructor

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Adds a bondLineWidth parameter to `MolDrawOptions` and exposes it to Python.
also adds the symbolColour to the wrapper
=> Fixes #2151

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/smatest.cpp
The logic for detecting a situation that's not translatable into SMARTS was "overly simple"
This clears that up.
=> Fixes #2142

Code/GraphMol/MMPA/MMPA.cpp
Building in Debug configuration with MSVC 2017 currently fails with the latest release. This PR fixes this.
mmpa.cpp contains some code that uses the old RDKit API but is protected by a #define _DEBUG which is commented out at the top of the file. This code writes to stdout some debugging information. Fixing this code should be trivial but that is not the subject of this PR.
The problem is that _DEBUG is defined by MSVC 2017 when building in Debug configuration. So I've renamed the #define in this file from _DEBUG to MMPA_DEBUG.
=> Rename the #define _DEBUG to MMPA_DEBUG in mmpa.cpp

rdkit/Chem/PandasTools.py
If something is wrong with one of the structures in an sdf, smiles cannot be generated and Chem.PandasToolsLoadSDF will throw an error and stops processing the file. Here I propose skipping the compound and continue processing the sdf.
=> Skip compound if smiles conversion fails

Docs/Book/Install.md
If boost is installed with conda, cmake will not find it. For that reason,
we have to specify BOOST_ROOT.
=> Update installation instructions for Linux

Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.h
Fixes a serious bug (operator= doesn't return a value) and suppresses another warning.
=> Fix TautomerTransform in operator=

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
Two fixes to the RGropuDecomposition code.
1. Using the adjustQuery method of fixing degrees wasn't working as expected, this hand-rolls a solution to reject matches not at rgroups
2. Keep the user supplied rlabels (i.e. don't relabel)
=> RGroupDecomposition fixes, keep userLabels more robust onlyMatchAtRGroups

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py
When PandasTools is used, setting global pandas variables like
'display.max_rows' or 'display.max_columns' have no effect. For example,
executing the following code results in printing ten rows although
'display.max_rows' is set to 5:
```python
import pandas as pd
from rdkit.Chem import PandasTools
PandasTools.RenderImagesInAllDataFrames()
pd.set_option('display.max_rows', 5)
pd.DataFrame(['some text'] * 10)
```
Solve this problem by using pandas' default HTML rendering method instead
of the DataFrameFormatter. Additionally, remove all unnecessary
'pd.set_option' calls.
=> Do not allow PandasTools to overwrite pandas settings

Code/PgSQL/rdkit/expected/inchi.out, Code/PgSQL/rdkit/mol_op.c, Code/PgSQL/rdkit/sql/inchi.sql
Fixes #2176
Adds check of returned string from MolInchi() and MolInchiKey() and converts blank results into NULL. Valid InChI strings or InChI keys will never be blank strings.
=> Fix #2176: InChI functions should return NULL on un-InChI-able input molecules.

Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #2220 
Adds a free function on both the C++ and Python side that takes a `Drawer` and `const ROMol` and calls `prepareMolForDrawing()` before drawing it.
=> Fixes #2220

rdkit/Chem/EnumerateStereoisomers.py
rdkit/Chem/EnumerateStereoisomers.py:215: DeprecationWarning: invalid escape sequence \B
Just escaping some doc tests so they don't throw warning when our downstream libraries import this module.
=> Silencing some Python 3 warning messages

Code/GraphMol/ChemReactions/Enumerate/EvenSamplePairs.cpp, Code/GraphMol/ChemReactions/Enumerate/EvenSamplePairs.h
Fixes #2209 
The EvenPairsSampling code was internally using a system sized decoding scheme, it now properly uses 64 bit integers on all systems.
_**Not yet tested on a 32 bit build.**_
=> Fixes #2209 - testEnumeration on 32bit systems

Code/GraphMol/ROMol.h, Code/GraphMol/Sgroup.h
My commit of the SGroups apparently breaks compilation with DLLs under Windows due to linking problems in the FileParsers caused by missing exports for the SGroup functions.
This fixes the issue by adding the required "RDKIT_GRAPHMOL_EXPORT" to the functions used in FileParsers library.
My bad, sorry!
=> Added exports for SGroup functions

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/catch_tests.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
There's always some processing applied to molecules read from CTABs which has the side effect of removing info from bonds.
This adds the stereo and bond-type information from the CTAB as bond properties so that we can access them later if we care to.
=> keep extra information about bonds from Mol files

Code/GraphMol/FileParsers/MolFileParser.cpp
This produces a warning when a mol file is parsed if a 2D conformation (something with all zero Z coordinates) is tagged as 3D.
=> add warning for 2D conformations flagged as 3D

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/catch_tests.cpp, Code/GraphMol/testChirality.cpp
Bridgehead atoms shouldn't be excluded from ring chirality.
I suppose one can argue about this, but this is at least consistent with how InChI handles it and that is, after all, IUPAC. ;-)
=> Fixes #2266

Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Allows atoms to be selected by adding a transparent circle on top of them with `tagAtoms()` is called. These can have JS events associated with them.
Here's an example, part of the output from `d.TagAtoms(dm,events={'onclick':'alert'})`:
```
<circle  cx='45.869' cy='261.564' r='14.8752' class='atom-selector atom-0' style='fill:#fff;stroke:#fff;stroke-width:1px;fill-opacity:0;stroke-opacity:0'  onclick='alert(0);'/>
<circle  cx='45.869' cy='150' r='14.8752' class='atom-selector atom-1' style='fill:#fff;stroke:#fff;stroke-width:1px;fill-opacity:0;stroke-opacity:0'  onclick='alert(1);'/>
```
Also adds a class to lines from each bond with bond IDs:
Example for a bond:
```
<path class='bond-4' d='M 268.997,261.564 157.433,261.564' style='fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:2 …
```
=> Improve interactivity of output SVG

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/catch_tests.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake, Code/GraphMol/SmilesParse/smiles.ll, Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake, Code/GraphMol/SmilesParse/smiles.yy, Code/GraphMol/catch_tests.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/testChirality.cpp
`/` and `\` now count as unspecified bond types.
=> Fix #2148 and #2244

Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp, Code/GraphMol/Wrap/rough_test.py
This is a very quick patch to store extra CXSMILES information as a property, so that this information can be consulted or reused.
By storing the extra CXSMILES information, it is available to be examined, so that even parts that are not currently being understood by RDKit are available to the user..
=> Store extra CXSMILES data as a property

External/AvalonTools/AvalonTools.cpp, External/AvalonTools/Wrap/testAvalonTools.py, External/AvalonTools/test1.cpp
Fixes #1062 
Works around an AvalonTools issue in the computation of 2D coordinates, that could ignore/discard the double bond stereochemistry when an intermediate ctab representation is used for an input molecule, and possibly assign inconsistent 2D layout data.
These changes should resolve the problem in the assignment of a 2D layout. The general correctness of using a mol block in function molToReaccs is still unclear.
=> don't use a ctab as input for the computation of 2D coordinates

rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
Since #2022, RDkit mols have had information about groups of atom
with defined relative stereochemistry (StereoGroup). This commit
allows EnumerateStereoisomers to generate stereoisomers defined
in a mol's stereo groups.
By default, this includes the stereo groups in the generated
stereoisomers. Also adds an option to constrain stereo expansion
to _only_ expand sites specified at a stereogroup. This allows
the resulting set of molecules to (optionally) retain any
ambiguity in assignment in the original mol.
=> Issue #2109: Enumerate all stereoisomers associated with StereoGroups

Code/SimDivPickers/Wrap/testPickers.py
We were occasionally getting random failures in the tests due to the pick space being too limited.
This increases the pick space.
There will still be the occasional failure, but it should be a lot less frequent now.
=> fix a problem with the random pickers test

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/Wrap/MaeMolSupplier.cpp, External/CoordGen/CMakeLists.txt, External/CoordGen/test.cpp
Update maeparser to release v1.1 and coordgen to v1.2.1.
- The update to the latest maeparser comes with a change in the interface: the constructors for MaeParser and Reader that previously took a reference to a stream now take a shared_ptr to a stream. I have updated the MaeMolSupplier with the simplest change I can think of: adding an extra property to hold the shared_ptr to guarantee it is available as long as the object exists. But having the shared_ptr means that, as soon as the object is destroyed, the pointer to the stream will also be deleted. So, now, the MaeMolSupplier(std::istream *inStream, ...) interface always has to take ownership of the stream, so I added a precondition to check that. I'm open to any alternate suggestions on hwo to implement the update, though.
- The …
=> Update maeparser & coordgen libraries

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Here's the issue:
```
In [8]: scaff = Chem.MolFromSmiles('Cc1ccccc1')
In [16]: ms = [Chem.MolFromSmiles(x) for x in ('c1ccccc1C','Fc1ccccc1C','c1cccc(F)c1C','Fc1cccc(F)c1C')]
In [17]: rdRGroupDecomposition.RGroupDecompose([scaff],ms,asSmiles=True)[0]
Out[17]:
[{'Core': 'Cc1c([*:1])cccc1[*:2]', 'R1': '[H][*:1]', 'R2': '[H][*:2]'},
{'Core': 'Cc1c([*:1])cccc1[*:2]', 'R1': '[H][*:1]', 'R2': 'F[*:2]'},
{'Core': 'Cc1c([*:1])cccc1[*:2]', 'R1': 'F[*:1]', 'R2': '[H][*:2]'},
{'Core': 'Cc1c([*:1])cccc1[*:2]', 'R1': 'F[*:1]', 'R2': 'F[*:2]'}]
```
=> fixes an r-group symmetrization problem

Code/GraphMol/AddHs.cpp, Code/GraphMol/catch_tests.cpp
Adds some special cases to ensure that we don't end up setting z coords for 2D conformations.
This code is a mess and really should be refactored, but I'd like to get the fix in first so that we know it'll make the next release.
=> fixes #908

Code/JavaWrappers/CMakeLists.txt
made necessary by the new iostreams dependency of coordgen
=> change to make the SWIG builds work on windows

Scripts/create_deb_packages.sh
the build script for deb packages was still using python2
=> update debian build script to python3

Code/GraphMol/MolStandardize/CMakeLists.txt, Code/GraphMol/MolStandardize/Fragment.cpp, Code/GraphMol/MolStandardize/Fragment.h, Code/GraphMol/MolStandardize/Wrap/Fragment.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/catch_tests.cpp, Code/GraphMol/MolStandardize/testFragment.cpp
The idea of the option is to not remove anything from molecules where every fragment matches a salt.
An example:
```
In [3]: fm = rdMolStandardize.FragmentRemover(skip_if_all_match=True)                                                                          
In [4]: Chem.MolToSmiles(fm.remove(Chem.MolFromSmiles('C.[Na+].[Cl-]')))                                                                       
[15:39:02] Running FragmentRemover
[15:39:02] Removed fragment: chlorine
[15:39:02] Removed fragment: sodium
Out[4]: 'C'
In [5]: Chem.MolToSmiles(fm.remove(Chem.MolFromSmiles('[Na+].[Cl-]')))                                                                         
[15:39:07] Running FragmentRemover
[15:39:07] Removed fragment: chlorine
[15:39:07] Removed fragment: sodium
[15:39:07] All …
```
=> Add a skip_all_if_match option to the FragmentRemover

External/CoordGen/CMakeLists.txt
Coordgen has received another bug fix update, which addresses incorrect stereochemistry labels. This is a PR to update to the last version.
Also, I have changed the "zlib" dependence, as apparently it needs to be uppercase (https://cmake.org/cmake/help/v3.6/module/FindZLIB.html)
=> Update coordgenlibs to v1.2.2

rdkit/Chem/MolStandardize/charge.py
AcidBasePair Name was Incorrect.  
It was using an em dash instead of a double minus.  
This likely happened due to autocorrect in a text editor when placing it in.
Replace \u2013 with --.
It might only be one minus?  I don't know enough chemistry to know what it *should* be.
=> Remove Unicode From AcidBasePair Name

Code/RDGeneral/types.h
_MolFileRLabel are unsigned int, not int. if a user accidentally sets them to int, confusing problems occur (e.g. exception while writing an SD file).
=> Update the type hint in types.h for _MolFileRLabel

Code/DataStructs/CMakeLists.txt, Code/DataStructs/DatastructsStreamOps.h, Code/DataStructs/testDatastructs.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/MolPickler.h, Code/GraphMol/testPickler.cpp, Code/RDGeneral/RDValue-doublemagic.h, Code/RDGeneral/RDValue-taggedunion.h, Code/RDGeneral/StreamOps.h, Code/RDGeneral/testDict.cpp
Adds custom handlers to pickle arbitrary properties.
An example implementation of an ExplicitBitVector serializer is given.
I'm not super thrilled about using the bad_any_cast exception as flow control, I'll look for another solution.
=> Allow custom type-handlers in the RDProps interface

Code/RDBoost/Wrap/RDBase.cpp
Most backend functions that use an RNG take a seed argument, but there's at least one place (the SMILES generator) where it doesn't make sense to have the extra argument, but reproducibility would still be nice.
This enables that.
=> Allow C RNG to be initialized from Python

Code/GraphMol/QueryOps.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Queries.cpp, Code/GraphMol/Wrap/rough_test.py
Adds queries for bit explicit bit vector prop.
Example:
```
m = Chem.MolFromSmiles("CC")
for atom in m.GetAtoms():
bv = DataStructs.ExplicitBitVect(4)
bv.SetBit(atom.GetIdx())
atom.SetExplicitBitVectProp("prop", bv)
sma = Chem.MolFromSmarts("C")
for atom in sma.GetAtoms():
bv = DataStructs.ExplicitBitVect(4)
bv.SetBit(1)
qa = rdqueries.HasBitVectPropWithValueQueryAtom("prop", bv, tolerance=0.0)
res = m.GetSubstructMatches(sma)
assertEqual(res, ((1,),))
```
This returns true if the tanimoto distance between bv and the atom bit vector prop "prop" is less than or equal to the supplied value.
=> Add ExplicitBitVect prop and query

Code/GraphMol/MolOps.h, Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.cpp, Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.h, Code/GraphMol/MolStandardize/Charge.cpp, Code/GraphMol/MolStandardize/Charge.h, Code/GraphMol/MolStandardize/Fragment.cpp, Code/GraphMol/MolStandardize/Fragment.h, Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.cpp, Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.h, Code/GraphMol/MolStandardize/MolStandardize.cpp, Code/GraphMol/MolStandardize/Normalize.cpp, Code/GraphMol/MolStandardize/Normalize.h, Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.cpp, Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.h, Code/GraphMol/MolStandardize/Wrap/Charge.cpp, Code/GraphMol/MolStandardize/Wrap/Fragment.cpp, Code/GraphMol/MolStandardize/Wrap/Normalize.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/testNormalize.cpp, Data/MolStandardize/acid_base_pairs.txt, Data/MolStandardize/normalizations.txt
The idea is to allow the user to provide a string (from Python) or stream (from C++) with initialization parameters for most of the MolStandardize components.
It's not there for the Tautomer code yet, but that's not finished anyway. To be added in the next release cycle as that code is finished.
=> Allow components of the MolStandardize code to be initialized from streams

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Parsing a CXSMILES string that contains HTML char codes in the format "&#nnnn;" (which are something legal, apparently) makes the parser choke on the initial ampersand, as it triggers parsing of an enhanced stereo group.
This patch mitigates the issue by triggering the enhanced stereo parsing only if the ampersand is not followed by a hashtag (HTML char codes are still not supported). I also included a simple test for this issue.
=> CXSMILES parsing chokes on HTML char codes

Code/GraphMol/FragCatalog/FragCatalogUtils.cpp, Code/GraphMol/FragCatalog/test1.cpp, Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogUtils.cpp, Code/GraphMol/MolStandardize/testFragment.cpp
Test `testMolStandardize.py::TestCase::test11FragmentParams` was failing on my home computer. Upon investigation, the problem was the whitespace in the last line in the test data, right before the triple quotes. The input to function `getSmarts()` is only checked to be empty or a comment, and a whitespace-only string gets past both checks and may be parsed as a "name" without an actual SMARTS string.
I don't really know why this wasn't failing anywhere else.
I added trimming of whitespace before the checks, and also an additional check to make sure we actually have a SMARTS string to parse before actually trying to parse it.
The code seems to be duplicated in FragCatalogUtils.cpp and FragmentCatalogUtils.cpp (the only difference I see is the return of `readFuncGroups()` which uses a …
=> Trim whitespace from mol fragment SMARTS and check SMARTS presence

Code/GraphMol/FindRings.cpp, Code/GraphMol/molopstest.cpp
Fixes #2403
For my horrible example molecule (a highly symmetric
nanotube with 2400 atoms and > 1000 rings), this speeds up
`symmetrizeSSSR()` from 5s to about 0.001s. `findSSSR()` takes
another .4s or so.
I've got some ideas about speeding up SSSR a bit more, but I
don't know if that is the bottleneck in sanitization for real
molecules, so I probably won't pursue it yet.
Is the symmetric SSSR supposed to be the "relevant cycles"? (relevant cycles are the union of all SSSR). SSSSR looks pretty close.
=> Issue #2403: Speed up SSSR symmetrization

Code/GraphMol/Chirality.cpp, Code/GraphMol/testChirality.cpp
`assignStereochemistry()` now clears direction on single bonds around double bonds that don't have stereochemistry
=> Fixes #2422

rdkit/Chem/MolStandardize/standardize.py, rdkit/Chem/MolStandardize/test_standardizer.py
Currently rdkit.Chem.MolStandardize.standardize.Standardizer sometimes maintains molecular properties and sometimes does not.  Specifically this sometimes happens in the normalize step for certain molecules.
I chose to fix the problem at the Standardizer level instead of the Normalize layer because I'm not sure if normalize is intended to maintain molecule level properties or not.
is UnitTestMolVS run?  It requires a MolVs dependency.
=> Chem.MolStandardize.standardize.Standardizer drops molecular properties

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, rdkit/Chem/Draw/__init__.py
Adds an option so that the call to `prepareMolForDrawing()` in `MolDraw2D::drawMols()` can be disabled
=> add prepareMolsBeforeDrawing option for drawMols 

Code/GraphMol/Atom.h, Code/GraphMol/Bond.h, Code/GraphMol/Conformer.h, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SubstanceGroup.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Bond.cpp, Code/GraphMol/Wrap/Conformer.cpp
Adds `hasOwningMol()` to a few objects.
Note that `SmilesWrite::GetAtomSmiles()` still doesn't work (and won't) since it relies upon information about valence that's only available for atoms associated with molecules. We could think about changing that, but that's a bigger project.
=> Fixes #2450

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SmilesTests.java
This enhancement adds the `rankMolAtoms()` from `new_canon.h` to the Java wrapper of the ROMol object. Currently, the canonical ranks are only available via a call to `ROMol#MolToSmiles()` followed by parsing atom or molecule properties
=> Added rankAtoms to ROMol wrapper and added Java test case

Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/SmilesMolSupplier.cpp, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp, Code/GraphMol/Wrap/MolSupplier.h, Code/GraphMol/Wrap/rough_test.py, Code/RDGeneral/FileParseException.h
The problem was that "standard" MolSuppliers would detect EOF and return the final molecule at the same time, but `ForwardSDMolSupplier` wouldn't detect EOF until the subsequent call to `next()`.
The workaround for this in `MolSupplNext()`, which is used in the Python wrapper, ended up causing the reported bug in the `SmilesMolSupplier`.
The changes here should make all of this more robust
=> Fixes #2479

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h
Fixes issue 2486
calculateScale takes account of the  highlight radius of any highlighted atoms so the circles aren't clipped at the edges of the picture.
I have done basic testing in C++ on MacOS.  Sadly, I seem to have lost my RDKit mojo completely, and have been unable to build the python wrappers on MacOS and totally failed to build it on Ubuntu, C++ and python.  I can try harder if necessary, but I hope this is a small enough change that it won't be.
=> Fix 2d depict

rdkit/Chem/BRICS.py
Fixes minor bug in the BRICSBuild() function: the `scrambleReagents` argument wasn't being passed to child calls.
=> BRICSBuild now passes scrambleReagents to children

Code/GraphMol/Wrap/SDWriter.cpp
The previous SDWriter docs for writing to a gzipped object throws an error in python3. From the mailing this, 'wt+' seems to work fine.
https://sourceforge.net/p/rdkit/mailman/message/36406080/
=> fix to SDWriter docs

Code/GraphMol/FileParsers/CMakeLists.txt, Code/GraphMol/FileParsers/FileParsers.h, Code/GraphMol/FileParsers/XYZFileWriter.cpp, Code/GraphMol/FileParsers/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py, Code/JavaWrappers/ROMol.i
XYZ file format is very simple and easily usable as input geometries for such quantum chemistry packages as Gaussian.
This PR adds support of XYZ format for output. Usage is as follows:
```python
>>> from rdkit.Chem import AllChem
>>> m = AllChem.AddHs(AllChem.MolFromSmiles('O'))
>>> AllChem.EmbedMolecule(m)
0
>>> print(AllChem.MolToXYZBlock(m))
3
O    -0.005703    0.385159   -0.000000
H    -0.796078   -0.194675   -0.000000
H     0.801781   -0.190484    0.000000
```
First line: number of atoms
Second line: title (optional)
Remaining lines: element symbol and x, y and z coordinates in Å.
=> Support XYZ format for output

External/CoordGen/CMakeLists.txt
Updating maeparser and coordgen to the latest versions: v1.2 and v1.3 respectively.
=> Update maeparser and coordgen versions

rdkit/CMakeLists.txt, rdkit/Chem/Pharm2D/UnitTestMatcher.py, rdkit/Chem/UnitTestFragmentDescriptors.py, rdkit/Chem/UnitTestMCS.py, rdkit/TestRunner.py
This has been bugging me for some time: as debug builds are (way) slower than release ones, the timeout test failed every time. This led me to ignore failures from UnitTestMCS, which I know is not a good idea, because eventually something else will fail.
I have now implemented something that will skip the timeout test on debug builds, but still run the other ones.
I also corrected some warning messages about 'invalid escape sequences' which should actually be ENDDOWNRIGHT bond directions.
=> Do not run UnitTestMCS.py::TestTimeout in debug builds

Code/GraphMol/FileParsers/FileParserUtils.h
This addresses a linking error when using dynamic libraries on Windows:
MDLParser.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl RDKit::FileParserUtils::finishMolProcessing(class RDKit::RWMol *,bool,bool,bool)" (?finishMolProcessing@FileParserUtils@RDKit@@YAXPEAVRWMol@2@_N11@Z) referenced in function "void __cdecl RDKit::`anonymous namespace'::ParseV3000RxnBlock(class std::basic_istream<char,struct std::char_traits<char> > &,unsigned int &,class RDKit::ChemicalReaction * &)" (?ParseV3000RxnBlock@?A0xcb91cdb2@RDKit@@YAXAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@AEAIAEAPEAVChemicalReaction@2@@Z)
..\..\..\bin\RDKitChemReactions.dll : fatal error LNK1120: 1 unresolved externals
We may want to set default visibility on Linux to hidden, too, so that we can catch linking …
=> Add RDKIT_FILEPARSERS_EXPORT to finishMolProcessing

Code/Geometry/CMakeLists.txt, Code/Geometry/Wrap/Point.cpp, Code/Geometry/Wrap/testGeometry.py, Code/Geometry/catch_tests.cpp, Code/Geometry/point.h
Adds a `Point2D(const Point3D &other)` ctor.
This is a convenience thing.
=> Allow Point2D to be constructed from Point3D

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
This allows you to provide a specific distance bounds matrix to the molecule embedding functions.
This allows you to take advantage of all the features of the molecule embedding code (like random coordinates, ETKDG, etc.) but seed the initial geometries with the bounds matrix.
=> Allow providing a bounds matrix to EmbedMol

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
This pull request removes a lower bound on the number of steps used in the rdFMCS algorithm, which would result in the timeout option being ignored and extremely slow matching when the search space is large.
See [issue 2581](#2581) for further details.
=> Remove arbitrary lower bound on the number of steps. [closes #2581]

rdkit-config.cmake.in
Fixes #2584
The inclusion statement for rdkit-targets.cmake was using a path that depended explicitly on the install location under $PREFIX. This was unnecessary (because both files are installed into the same directory), and prone to issues when this install location is modified.
=> fix the inclusion path for the targets file (#2584)

Code/GraphMol/Substruct/SubstructUtils.cpp
I think this completely inocuous, but won't hurt to fix it anyway.
=> Fix inocuous typo/bug in Dative bond matching

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmartsWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
We have MolFragmentToSmiles already. But I think that when talking
about a fragment or part of a molecule, maybe SMARTS makes more
sense. If I see a SMILES string, I'll definitely think that
it should be a valid molecule, but I have no such
presumption about SMARTS.
Additionally, Schrodinger software sometimes generates SMARTS
for selection using a set of atoms picked in a GUI. It would
be useful to generate these SMARTS using RDKit.
Oh, these functions should probably take ROMol by value, instead of by reference. They make an internal copy anyway, so if they took the ROMol by value, we might eliminate a couple of ROMol copies when a move is possible. Doubt this would have a noticeable effect anywhere, though.
=> Adds MolFragmentToSmarts to generate smarts for a subset of a Molecule

Code/GraphMol/Canon.cpp, Code/GraphMol/Canon.h, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Wrap/rough_test.py
Explanation of the problem is in the comments of Issue #1028 . But it summarizes into that SMILES parsing and writing were using different criteria to decide if the chiral tag of an atom had to be flipped or not.
This PR moves the code to decide whether to flip a chiral atom into Canon.cpp, and uses the same function to check chiral atoms at writing and parsing of SMILES strings.
I have not checked the change in the python test, but both strings seem to be "stable" and not flip on roundtripping the SMILES -- if the fix of the reference is wrong, then maybe the algorithm to decide the flipping is not quite correct.
=> Use the same criteria to flip chiral atoms in SMILES parsing/writing (Fixes #1028)

Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp, Code/GraphMol/Wrap/PDBWriter.cpp, Code/GraphMol/Wrap/SDWriter.cpp, Code/GraphMol/Wrap/SmilesWriter.cpp, Code/GraphMol/Wrap/TDTWriter.cpp, Code/GraphMol/Wrap/rough_test.py, Code/RDBoost/python_streambuf.h
This behavior from the current code is irritating:
```
In [22]: bio = BytesIO()                                                                                               
In [23]: w = Chem.SDWriter(bio)                                                                                        
In [24]: w.write(Chem.MolFromSmiles('CC'))                                                                             
In [25]: w.close()                                                                                                     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: a bytes-like object is required, not 'str'
The above exception was the direct cause of the following …
```
=> raise ValueErrors when constructing streambuffs with the incorrect type.

Code/GraphMol/Fingerprints/PatternFingerprints.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp
The problem was caused by the very large number of matches for some of the patterns in these big molecules.
The solution is brute force and can be out maneuvered by running a really huge molecule through the pattern fingerprinter, but there's not really a solution to that with the current implementation.
=> Fixes #2614

Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/test1.cpp
Example:
```python
mol = Chem.MolFromSmiles(r'C/C=C/C')
query = Chem.MolFromSmiles(r'C/C=C/C')
bond = query.GetBondWithIdx(1)
bond.SetStereoAtoms(0, 3)
bond.SetStereo(Chem.BondStereo.STEREOTRANS)
assert mol.HasSubstructMatch(query, useChirality=True)
-----
<ipython-input-2-63fb196a0558> in <module>()
9 bond.SetStereo(Chem.BondStereo.STEREOTRANS)
10 
---> 11 assert mol.HasSubstructMatch(query, useChirality=True)
AssertionError: 
```
This happens because of stereo labels are matched like this:
https://github.com/rdkit/rdkit/blob/cb64898b3d0725624138f4fcf99c9a277e89010a/Code/GraphMol/Substruct/SubstructMatch.cpp#L190-L194
=> E/Z and CIS/TRANS stereo bonds are incorrectly matched

Code/Catalogs/Catalog.h, Code/GraphMol/MolStandardize/Charge.cpp, Code/GraphMol/MolStandardize/Metal.cpp, Code/GraphMol/MolStandardize/MolStandardize.cpp, Code/GraphMol/MolStandardize/Normalize.cpp, Code/GraphMol/MolStandardize/Normalize.h
This is mostly mechanical "stop copying things that don't need to be copied" work.
There's definitely still some more fat in here to be pruned, but I think this takes out most of the big chunks.
For what it's worth, this reduces the C++ run time on the set of examples provided in #2615 from 20.8 sec to 7.4 sec.
=> optimization of the MolStandardize code

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
zero order bonds were being drawn the same as single bonds.
=> draw zero-order bonds

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/catch_tests.cpp, Code/GraphMol/catch_tests.cpp
Atoms from the "organic subset" that have ununusual non-standard valences were not having those valences written to mol blocks.
This clears that up.
It only affects atoms in the organic subset that have the `noImplicit` flag set and that have a non-standard valence.
This also fixes #2649. That's not really related except that it also is related to reading/writing mol blocks.
=> Fixes: Atoms in non-standard valences not being properly written to mol blocks

Code/GraphMol/Subgraphs/SubgraphUtils.cpp, Code/GraphMol/Subgraphs/test2.cpp
Fixes #2647 
PathToSubmol copied the bonds over in the order of the indices.  This played higglety pigglety on the stereo order.
=> Fixes #2647

Docs/Book/Install.md
So far, the installation instructions for Linux rely on a specific 
python version in order to include numpy. Replace the hard-coded path 
with a call to numpy.get_include().
=> Get numpy include dir programmatically

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
This PR fixes #2663 by adding a ring/non-ring bond query as in the original MCS code by Andrew Dalke.
It also updates a few test cases to cope with the new bond notation and adds a specific C++ test case.
=> Fixes #2662 and #2663

Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/catch_tests.cpp
Modifies `tagAtoms()` to add bond selector class info as well as atom selector info.
Also includes a bit more documentation
=> add bond-selector info to SVGs

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
Example: Fixes #2666
Before this commit, if enhanced stereochemistry information was
added to a CXSMILES string as well as other information, the
separator would be missing. This made CXSMILES written by
RDKit unreadable if enhanced stereo information was present.
Also adds a test and a simple function for reducing the probability
that this mistake will be made with other new CXSMILES sections.
=> Issue #2666: Missing separator in CXSMILES with enhanced stereo

Code/GraphMol/MolStandardize/Normalize.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
The Normalizer would generate an exception for molecules with fragments if the transforms had ring queries.
The simple fix is to just always call `fastFindRings()` in `normalizeFragment()`.
=> fix a problem with normalize, ringinfo, and fragments

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py, Code/JavaWrappers/RGroupDecomposition.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/RGroupDecompositionTests.java
Adds RGroupDecomposigion::getRGroupLabels.
Adds keys() method to wrapped std::maps.
```
ROMol core = RWMol.MolFromSmiles("c1ccccc1");
RGroupDecomposition decomp = new RGroupDecomposition(core);
m = RWMol.MolFromSmiles("c1(Cl)ccccc1");
assertEquals(0,decomp.add(m));
m = RWMol.MolFromSmiles("c1c(Cl)cccc1");
assertEquals(1,decomp.add(m));
assertTrue(decomp.process());
Str_Vect keys = decomp.getRGroupsAsColumns().keys();
assertTrue(keys.size() == 2);
assertTrue(keys.get(0).equals("Core"));
assertTrue(keys.get(1).equals("R1"));
```
=> Allow Java to see RGroup labels in the std::map wrapper.

External/CoordGen/CMakeLists.txt
This new version is a bugfix for the previous one, v1.2.2, in which a couple templated functions were not properly dll exported.
There exports are required for #2620 to compile on windows (but there is still another problem with that PR).
=> Update maeparser to v1.2.2.

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FMCSTests.java
This pull request adds an alternative AtomComparator option for the FMCS code.
The option, `AtomCompareAnyHeavyAtom` allows MCS generation on structures with explicit hydrogen atoms, where a match is wanted between different heavy atoms, or between hydrogens, but not Hydrogen <--> Heavy atom.
For example, consider the following pair of structures:
`Oc1c([H])c([H])c([H])c([H])c1O`
`[H]c1c([H])c([H])c([H])c([H])c1[Cl]`
A standard 'AnyAtom' MCS will allow the first atom of each to match each other, e.g. 'O' matches '[H]', in addition to the last pair of atoms matching each other (i.e. 'O' matches '[Cl]'). In some applications, it may be preferrable to allow the latter match, but not the former.  This pull request adds that functionality and test cases in C++, Java and Python wrappers
=> Added AtomComparator.AtomCompareAnyHeavyAtom and test cases to FMCS code

Code/MinimalLib/demo/demo.html, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h
what's in this PR:
- `get_substruct_match()` now returns matching atoms and bonds
- `get_substruct_matches()`
- a set of functions that should (I hope) allow the JS code to be used by ketcher as an alternative to a server.
=> Adds additional capabilities to the minimal JS wrapper

Code/JavaWrappers/CMakeLists.txt, Code/JavaWrappers/MolHash.i, Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i, Code/JavaWrappers/gmwrapper/CMakeLists.txt, Code/JavaWrappers/gmwrapper/GraphMolJava.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolHashTest.java
exposes MolHash to the SWIG wrappers
Includes a test for the java wrappers, but not C#
=> Fixes #2677

External/CoordGen/CMakeLists.txt
Sorry, I didn't expect coordgen to get a new release too, or I would have included it into the last update to maeparser.
This release includes some performance improvements, and should be a drop in replacement for v1.3.1.
=> Update coordgen to v1.3.2

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py
In #2206 someone noted that cells in pandas data frames are not truncated if rdkit.Chem.PandasTools is used. Even data frames without molecules are affected.
Instead of setting the global pandas variable display.max_colwidth to -1 (infinite), a different mechanism is used to render molecule images in data frames. 
Before (note: any HTML is rendered, text is not truncated):
After changes:
=> Fix long columns pandas

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, rdkit/Chem/Draw/IPythonConsole.py, rdkit/Chem/Draw/__init__.py
This, plus the change in the Python API to support it, makes it possible to control the drawing options that are used in jupyter.
It also makes it easy on the Python side to have a "global" set of drawing options that can be used with any MolDraw2D object. This has been possible on the C++ side all along.
=> Add a drawOptions object to IPythonConsole

Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/StereoGroup.cpp, Code/GraphMol/Wrap/rough_test.py
The key here is to use an `Atom` as the held type of the wrapper class, not an `Atom *`.
Required some changes to the StereoGroups wrapper code too since returning an `std::vector<Atom *>` directly to Python no longer works. Returning a tuple isn't such a bad thing. :-)
=> Fixes #2639

Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
Close #2680
Write `viewBox` attribute in `RDKit::MolDraw2DSVG::initDrawing`.
=> Add viewBox to SVG (close #2680)

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp
One enhancement and some bug fixes to the tautomer/protomer algorithm:
The enhancement: Skip making non-conjugated CC multiple bonds single. 
The current code generates the same HetAtomTautomer hashes for `C/C=C/C` and `C/C=C\C`. This PR changes that.
Note that this is an extremely conservative change: it will still change conjugated double bonds, even if there are no hetero atoms connected to any of them:
```
In [4]: rdMolHash.MolHash(Chem.MolFromSmiles('C/C=C/C=C/C'),rdMolHash.HashFunction.HetAtomTautomer)                                                                                              
Out[4]: 'C[CH][CH][CH][CH]C_0_0'
```
It probably makes sense to come back to this at some point and fix that too.
The fixes:
1. ensures that the aromatic flag is removed from bonds that are …
=> A few MolHash fixes

Code/GraphMol/FilterCatalog/FilterCatalogEntry.h
Removes the deprecation warning when creating a FilterCatalogEntry object.  This should have been fixed a long time ago ...
=> Eat our own dogfood, Clone is deprecated so use copy

Code/GraphMol/Chirality.cpp, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_tests.cpp
It took several weeks, but I finally found something to complain about in PR #2623:
There is a small detail I did not consider: bonds can be written in reverse, so that their direction needs to be reversed to be correctly considered.
I just hit this:
```python
mol = Chem.MolFromMolBlock(
"""C/C=C/O
RDKit          3D
4  3  0  0  0  0  0  0  0  0999 V2000
0.0175    0.0570   -0.2095 C   0  0  0  0  0  0  0  0  0  0  0  0
-0.7490    1.1168    0.0782 C   0  0  0  0  0  0  0  0  0  0  0  0
-2.0935    1.1693   -0.1018 O   0  0  0  0  0  0  0  0  0  0  0  0
1.5185   -0.0072   -0.0078 C   0  0  0  0  0  0  0  0  0  0  0  0
4  1  1  0
1  2  2  0
3  2  1  0
M  END
""")
print(mol.GetBondWithIdx(1).GetStereo())
sma = Chem.MolToSmarts(mol)
print(sma)
q = Chem.MolFromSmarts(sma) …
```
=> Fix set stereo bond labels to SMARTS mol

Code/GraphMol/SubstanceGroup.h, Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py
This adds code to allow StructureGroups to be created and edited from Python.
This may be ready to go as-is, but I'd like to see if there are any comments before merging
This addresses #2489
=> [WIP] Make StructureGroups editable from Python

Code/GraphMol/FilterCatalog/CMakeLists.txt, Code/GraphMol/FilterCatalog/FilterCatalog.h, Code/GraphMol/FilterCatalog/FilterCatalogRunner.cpp, Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp, Code/GraphMol/FilterCatalog/Wrap/rough_test.py, Code/GraphMol/FilterCatalog/filtercatalogtest.cpp, Code/JavaWrappers/FilterCatalog.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FilterCatalogTests.java
This adds a simple threaded runner to the filter catalog.
```
smiles = [...]
results = FilterCatalog.RunFilterCatalog(fc, smiles, numThreads=-1)
assert len(results) == len(smiles)
for result in results:
if len(result): # filters have been hit
filters = [x.GetDescription() for x in result]
```
The one thing I don't like is that we don't have a "bad smiles" filter, so smiles strings that can't be parsed return an empty filter list.
=> Add threaded runner for the filter catalog

Code/JavaWrappers/gmwrapper/src-test/org/RDKit/DistanceGeometryTests.java
The default seed for the RNG used by the distance geometry code is 42u, same as the explicit seed in this test. The order in which tests are run is apparently not deterministic.
When `test9ETKDGParams2()` runs before any of the other tests that don't seed the RNG it ends up using the RNG which has just been seeded with 42u, so it generates the same results as the tests where the seed is explicitly set to 42.
Fix this by calling the conformation generator once without a seed before making the call that we check the results of.
way more words to explain than fix. :-)
=> fixes #2727

Code/GraphMol/Bond.cpp, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/testReaction.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_tests.cpp, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemReactionTests.java
The fix to allow bond stereochem to be handled correctly in reactions introduced in #2553 works by setting `BondStereo` flags (which are generally pretty straightforward to translate into products) and removing `BondDir` flags (which are considerably more problematic). Unfortunately there's (still) plenty of downstream code that expects those bond dirs to be there and this change breaks all of that. Frighteningly, it didn't break it in a way that showed up in the tests. 
This PR fixes that problem (by reassigning bond dirs in the products if there were any in the reactants). It also adds some new tests to increase the size of our safety net. Finally it exposes `MolOps::setDoubleBondNeighborDirections()` to python, which should have been done a while ago.
=> Cleanup some unintended consequences of #2553

rdkit/Chem/Draw/__init__.py
It fix the problem when using `useSVG=True` in `MolsToGridImage` with an `SDMolSupplier` object as `mols`. Fixed as of #1592.
=> Apply fix for #1592 to _MolsToGridSVG

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/MaximumCommonSubgraph.h, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
This PR implements what I presented in my lightning talk at the RDKit UGM 2019.
Following discussions with Greg, I decided to implement three different levels of consideration of ring fusion:
- `RingCompare=IgnoreRingFusion` (corresponding to `BondCompareParameters.MatchFusedRings=False`): this is the default, and keeps the current MCS behaviour, where ring fusion is not taken into account, and the MCS between &alpha;-methylnaphthalene and &beta;-methylnaphthalene will return 11 atoms and 11 bonds, corresponding to methylcyclodecapentaene
- `RingCompare=Permissive` (corresponding to `BondCompareParameters.MatchFusedRings=True, BondCompareParameters.MatchFusedRingsStrict=False`): ring fusion is taken into account, but if one of the molecules does not feature any ring fusion in the MCS, …
=> Add consideration of ring fusion to the MCS algorithm

Code/SimDivPickers/LeaderPicker.h
Removed `RDKIT_SIMDIVPICKERS_EXPORT` directive which should not be there (`LeaderPicker.cpp` is part of `rdSimDivPickers` so it should not be imported nor exported) and prevents DLLs from building on Windows.
=> Removed RDKIT_SIMDIVPICKERS_EXPORT

Contrib/SA_Score/sascorer.py
When using SA_Score in a parallel setting, I sometimes get random failures due to `calculateScore` reading from an intermediate value of `_fscores`. This PR avoids updating the global variable until the loaded features are ready for use.
=> Fix data race in sascorer.py

Code/GraphMol/ChemReactions/CMakeLists.txt, Code/GraphMol/FMCS/CMakeLists.txt, Code/GraphMol/MolStandardize/CMakeLists.txt, Code/RDGeneral/CMakeLists.txt
Installing RDKit breaks the directory structure for headers: directories under Graphmol/ChemReactions/ and Graphmol/MolStandardize/ get flattened.
So if you include, e.g. Graphmol/ChemReactions/Enumerate.h, it includes EnumerateBase.h, which in turn includes "../Reaction.h", which in the source is in the parent directory but in the installation is in the same directory as Enumerate.h and EnumerateBase.h, instead of in the parent directory as specified, thus breaking the build.
I patched the CMakeFiles to reproduce the same directory structure as in the sources.
Also, some header files that get included from other header files are not included in the installation, e.g. EnumerateTypes.h or Target.h. I added those to the installation.
Finally, path "hash" under RDGeneral gets duplicated in …
=> Fix installed header directory structure

Code/GraphMol/MolStandardize/Fragment.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
Fragments were being incorrectly removed from molecules because the salt stripper was only considering that the number of atoms in the fragment has to match the number of atoms in the molecule, 
The specific example that brought this up was this salt definition (benethamine):
which was matching:
The simple fix is to just consider bond counts as well as atom counts when considering whether or not a fragment matches.
=> Salt stripper should consider bond matches as well as atom matches

Code/PgSQL/rdkit/expected/avalon.out, Code/PgSQL/rdkit/expected/bfpgist-91.out, Code/PgSQL/rdkit/expected/fps.out, Code/PgSQL/rdkit/expected/props.out, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/expected/reaction.out, Code/PgSQL/rdkit/expected/sfpgist.out, Code/PgSQL/rdkit/expected/slfpgist.out, Code/PgSQL/rdkit/sql/avalon.sql, Code/PgSQL/rdkit/sql/bfpgist-91.sql, Code/PgSQL/rdkit/sql/fps.sql, Code/PgSQL/rdkit/sql/props.sql, Code/PgSQL/rdkit/sql/rdkit-91.sql, Code/PgSQL/rdkit/sql/reaction.sql, Code/PgSQL/rdkit/sql/sfpgist.sql, Code/PgSQL/rdkit/sql/slfpgist.sql
The problem was test output that didn't match what was expected due to the "Improve performance by using a new algorithm for output of real and double precision values" change in PostgreSQL 12:
https://www.postgresql.org/docs/12/release-12.html
We change the output `extra_float_digits` setting to get postgresql 12 to behave like previous versions.
This came up in the discussion of #2700
=> Make the cartridge tests work with PostgreSQL 12

Docs/Book/Overview.md
None
Adds the Open Force Field toolkit to the list of open-source packages that use RDKit
A truly open-source OFF toolkit wouldn't be possible without RDKit. Thanks to @greglandrum and all of the other maintainers for their hard work!
=> Add OFFTK to open-source users

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
- fixes #2801
- corrects a couple of typos
Certain bond queries translate to an empty SMARTS string (e.g., `makeBondOrderEqualsQuery(Bond::UNSPECIFIED)`. In those cases, no `&`, `;` or `,` symbol should be added to connect the queries.
=> Fixes #2801

CMakeLists.txt
When serialization library is not found CMakeLists.txt would clear out
${Boost_LIBRARIES} var, breaking linkage of Python bindings (at least).
----
We've hit this while building RDKit locally with minimum of Boost libraries installed.
I can't resist linking this great wiki page: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies#What_are_automagic_dependencies.3F (this section and the next one).
=> Fix build without boost serialization library

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/FileParsers/test_data/bad_ppty.mae, Code/GraphMol/FileParsers/test_data/props_test.mae, Code/GraphMol/FileParsers/test_data/stereochem.mae, Code/GraphMol/Wrap/MaeMolSupplier.cpp, Code/GraphMol/Wrap/MolSupplier.h, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
This started as a fix for #2617, but I added some more changes. That issue is caused by #2579, but after finding the problem, the `MaeMolSupplier` does not stop iteration despite it does not get any more structures, and continues returning "None" forever.
Also, this depends on schrodinger/maeparser#46 and schrodinger/maeparser#49, and should not be merged until these changes are accessible to RDKit.
Changes in the PR:
- Check the state of the stream after the creation of the Supplier: on construction, the `Reader` populates the internal buffer, so that, if there aren't any problems, the stream may be left either in a `good` state, if there was more data available than fits in the internal buffer, or with the `failed` and `eof` bits activated if there was less data than the buffer tried to …
=> Rework MaeMolSupplier, fix #2617

Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/MolHash/nmmolhash.h
Just realised we missed this for v2019.09.2.
Fixes #2752
Changes as recommended by Greg in #2752.
Patch currently in conda-forge recipe: https://github.com/conda-forge/rdkit-feedstock/pull/38/commits/a495c5ac3b6685c317c6199fdb78059386560601
=> Fix MolHash compile with VS2015 - fixes #2752

Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
Removed `confId` parameters from `UFFOptimizeMoleculeConfs` and `MMFFOptimizeMoleculeConfs` as that parameter is not actually used (see #2805).
=> Fixes #2805

Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h, Code/GraphMol/ForceFieldHelpers/Wrap/testHelpers.py
The problem was that `MMFF::MMFFOptimizeMoleculeConfs()` whenever MMFF failed to assign atom parameters to a molecule (i.e., `MMFF::MMFFMolProperties::isValid()` returns `false`), it would attempt to access `std::vector` members before allocating them, hence, the segfault.
=> Fixes GitHub #2820

Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp
Small documentation fix
The library enumeration had some example code available here https://www.rdkit.org/docs/source/rdkit.Chem.rdChemReactions.html which is wrong for this part : 
`for result in library:
for results_for_product_template in products:
for mol in results_for_product_template:
Chem.MolToSmiles(mol) # finally have a molecule!`
result should be products
=> small documentation fix in enumeration examples

Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/Substruct/vf2.hpp
Something I didn't catch in the review of #2500 
There's a situation where an iterator was being incremented past the end of the vector and this was leading to a crash under some circumstances under Windows (possibly only a problem when doing debug builds).
It's an easy enough fix.
=> Fix windows substructure crash

External/YAeHMOP/CMakeLists.txt, External/YAeHMOP/EHTTools.cpp, External/YAeHMOP/EHTTools.h
Today I tried for the first time to build RDKit support for YAeHMOP and I failed.
This PR fixes a few issues and allows building YAeHMOP under both Linux and Windows.
=> Fix YAeHMOP build

Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp, Code/GraphMol/SubstructLibrary/SubstructLibrary.h, Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp, Code/GraphMol/SubstructLibrary/Wrap/rough_test.py, Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
The fix checks the query for ring based queries, and performs a full sanitization if necessary.
Also, when using the external API, all molecules are returned in their fully sanitized form.
=> Fixes #2830

Code/GraphMol/ROMol.cpp
Small tweak to fix the O(N) behavior or getNumBonds
=> Remove O(N) behavior of getNumBonds

CMakeLists.txt, Code/GraphMol/ChemReactions/CMakeLists.txt, Code/GraphMol/FilterCatalog/CMakeLists.txt, Code/GraphMol/SubstructLibrary/CMakeLists.txt
Since we never add a define for `RDK_USE_BOOST_SERIALIZATION` it doesn't end up getting used most of the time, even if it's requested.
=> add define for RDK_USE_BOOST_SERIALIZATION

External/YAeHMOP/EHTTools.cpp, External/YAeHMOP/EHTTools.h, External/YAeHMOP/Wrap/rdEHTTools.cpp, External/YAeHMOP/Wrap/testEHTTools.py, External/YAeHMOP/test1.cpp
The matrix that was being returned was `numAtoms x numAtoms`. It should be `numAtoms x numOrbitals`. This fixes that.
The reference values in the tests are from a calculation run using the `bind` command line tool.
=> Fixes the size of the reduced charge matrix from eHT calculations

rdkit/Chem/PandasTools.py
The root cause of the problem was this PR that was included in pandas v0.25.1: https://github.com/pandas-dev/pandas/pull/27991/files
In earlier versions `DataFrame._repr_html()` called `DataFrame.to_html()`, so we could get by with just monkey patching `to_html()`. Now the two functions are independent of each other, so we have to modify both.
If we were willing to give up the ability to control whether or not molecules are rendered as images on a per DataFrame basis (the logic here: https://github.com/rdkit/rdkit/blob/master/rdkit/Chem/PandasTools.py#L382) we could re-simplify this by just patching `DataFrameFormatter.to_html()`, but that would involve removing functionality that may be useful to some people.
As a future ToDo: in a future release we should agree on some reasonably …
=> Fixes #2673

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/rdkit-91.sql, ReleaseNotes.md
This is a straightforward fix, but it does change the default behavior of molecular equality queries in the cartridge, so it gets a mention in the release notes.
=> Fixes #2790

rdkit/Chem/FragmentMatcher.py
hopefully ipython examples are rendered properly now
Docs here aren't being rendered, I think this is because of missing blank lines
https://www.rdkit.org/docs/source/rdkit.Chem.FragmentMatcher.html
I think this should work, I couldn't find the instructions for how to build the docs locally to check though
=> Fixing docs for Chem/FragmentMatcher.py

Code/GraphMol/AddHs.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_tests.cpp
Introduces a new parameters object that gives better control
We also add a `removeAllHs()` function to make it easy to really get rid of everything.
=> Fix #2848: add options to control removeHs

Code/GraphMol/MolStandardize/MolStandardize.cpp, Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/Tautomer.h, Code/GraphMol/MolStandardize/Wrap/CMakeLists.txt, Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp, Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/testTautomer.cpp
During the 2018 GSoC project to do a C++ implementation of MolVS, doing the tautomer enumeration and canonicalization were stretch goals. @susanhleung actually managed to complete the tautomer enumeration, but since canonicalization wasn't complete, we didn't publicize this particularly widely.
This PR does the last bit of work and adds tautomer canonicalization.
Notes to reviewers: 
- the goal of this first merge is to implement the tautomer scoring and canonicalization schemes that are used in MolVS. Once we have that in place the arguments can start (if really necessary) about whether or not we want a different/modified default scoring scheme.
- I will be probably be adding some additional tests over the next couple of days, those won't the design or (hopefully) …
=> Add MolVS tautomer canonicalization

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/testMolSupplier.cpp
We should also consider changing the behavior of `MaeMolSupplier` for the next release and make it throw an easily recognizable exception (maybe `FileParseException`) when it hits bad stuff in the input instead of using invariants for everything. But that's an enhancement for the next release.
=> Fixes #2881

.azure-pipelines/linux_build_cartridge.yml, azure-pipelines.yml
Adds a new configuration and does a basic build against the system (ubuntu 18.04) postgresql install.
I just did a linux version of this because (I believe) we don't really need to do cross-platform testing of the cartridge. A possible exception to this could be windows... if we could get a reproducible windows cartridge build working in azure devops
=> Add a cartridge test to the azure devops config

Code/JavaWrappers/MolDraw2D.i, Code/JavaWrappers/csharp_wrapper/CMakeLists.txt
This pull request does two things- 
1. Simple change to the MolDraw.i swig interface so that I can create a ROMol_Ptr_Vect in Java or C# and draw those molecules using  MolDraw2DSVG
2. A change the the csharp_wrapper CMakeLists.txt to use mcs as the mono compiler rather than gmcs (which isn't shipped any more).  Without this change it is not possible to create a makefile for building the wrapper.
The current code base does not compile the c sharp assembly as `PropertyPickleOptions.cs` will not compile.  As I don't need that code I can delete that file and compile manually.
I'm using dotnet core to build a Linux library.  If it's of interest and I could look at replacing mcs with dotnet in CMakeLists.txt.
I've published a [Nuget](https://www.nuget.org/packages/RDKit2DotNetCoreLinux/2019.9.0 …
=> Fix to allow multistructure images in Java/C# and use MCS for c# wrapper

Code/GraphMol/Aromaticity.cpp, Code/GraphMol/catch_tests.cpp, rdkit/Chem/UnitTestInchi.py
The solution here is to make sure that atoms in the fused rings are not considered to be part of the aromatic system unless they are in one or two rings. The problem with acepentalene was caused by the central atom (which is shared by all three rings) being included.
=> Fixes #2895

rdkit/Chem/PandasTools.py
Pandas 1.0 (which just came out and which is now used by the CI systems) changes the output of the `.info()` method.
Rather than continuing to chase that, this adds a couple of simpler tests and skips testing the `.info()` output in the doc string.
=> fix doctest problem with Pandas v1.0

rdkit/Chem/PandasTools.py
the module `pandas.io.formats.html` didn't show up until a more recent version, so we need to catch the `ImportError` when it's missing.
Hopefully nobody's actually using this ancient version, but it is what you get from apt in Ubuntu 18.04
=> patch to make PandasTools tests pass with pandas v0.22

rdkit/Chem/MolStandardize/standardize.py
mol.SetProp(k, v) fails for non-string values.
=> Fix regression introduced by e245349c

Code/MinimalLib/minilib.cpp, Code/MinimalLib/tests/tests.js
A couple small fixes to the JS wrappers:
- return potential stereocenters as well as specified ones (was #2936)
- fix the logic for handling the JSON for highlighting substructures (it was failing unless all optional values were provided)
=> Fixes #2936

Code/GraphMol/SmilesParse/SmilesParse.cpp
This PR avoids a data race identified by TSan in SmilesParse.cpp. I'm not sure it's the best solution---the race could still exist if multiple callers of `{Smarts,Smiles}ToMol` use different settings for `debugParse`---but it avoids the issue in the usual case of repeated calls to `{Smarts,Smiles}ToMol` with the same params.
=> Avoid data race warning in SmilesParse.cpp

Code/GraphMol/Descriptors/MolSurf.cpp, Code/GraphMol/Descriptors/test.cpp
An easy fix to this problem.
After looking at the rest of the code and going back to the original paper: I'm somewhat suspicious about what this is actually calculating relative to what's in the paper. There's no doubt that the descriptor, as calculated, is useful, but I don't think it corresponds particularly well to what's in the Labute paper. We may want to consider revisiting this at some point in the future.
=> Fixes #2948

Code/GraphMol/ScaffoldNetwork/Wrap/CMakeLists.txt, Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/testPickleScaffoldNetwork.py, Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
The python wrapping of ScaffoldNetworks fails to build when Boost serialization is not available. The reason is that, when serialization is not available, the string constructor for `ScaffoldNetwork` isn't available either, but it is still specified in the python wrapper.
This patch removes the pickling capability from `ScaffoldNetwork` when boost serialization is disabled. I also split off the pickling test to a separate test file that does not get run when serialization is turned off (else, it will fail with a message saying serialization is not available for that class). I also (accidentally) yapf-formatted the original test file.
=> Fix build without boost serialization.

Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
Based on a couple of good suggestions from @frakruger:
- Remove attachment points from fragments and then make the result generic instead of removing attachment points directly from generics
- Attach the GenericBond nodes (when created) to the corresponding Generic nodes. This makes it clear that the GenericBond scaffold is derived from the Generic scaffold.
Here's an example network showing the new connectivity:
=> ScaffoldNetwork rearrangements

Code/GraphMol/QueryOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Docs/Book/RDKit_Book.rst
Although these are probably nonsense, I've seen some pretty
big [r#] expressions in SMARTS expressions. In particular, for
SMARTS generated for toolkits that don't have the range
extension, people do this to mean "in rings bigger than 6" or
whatever:
[r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,...]
stopping at some point. Usually 17 or 18 (a heme is 16), but I've seen 24. Bumping to 40, but I don't see a strong reason not to eliminate the upper bound. Unless we want it to match the maximum size in `makeAtomInRingOfSizeQuery()`?
One funny note is that even before this, the SMARTS expression `[r{17-400}]` was allowed.
=> Enable larger ring matches in SMARTS expressions

rdkit/Chem/Draw/__init__.py
Also allows bond highlighting in notebook SVGs
The code to allow `_moltoimg()` to display bond highlights was misbehaving when no bond highlights were provided. The default to an empty bond highlight list leads to a different C++ function being called which disables continuous highlights.
This fix uses different overloads for the cases where bond highlights are/are not provided.
I also added the same logic to `_moltoSVG()`
Unfortunately the testing of this cannot reasonably be automated - comparing PNGs to each other doesn't make much sense.
=> Fix atom highlighting in notebook PNGs

Code/GraphMol/FileParsers/FileParsers.h, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
All the previously missing properties can now be read and written.
The bond properties were all already parsed, this completes writing them.
This also adds convenience functions to make it easier to write V3000 mol blocks or mol files, which we should be using more often
=> Add support for the rest of the v3000 atom properties

rdkit/__init__.py
Moves the Jupyter extension notification to the python logger.  This enables us to turn it on or off.
Fixes #3006
=> Move jupyter extension logging to the python logger

.gitignore, Code/cmake/Modules/Findcoordgen.cmake, External/CoordGen/CMakeLists.txt
This updates maeparser to v1.2.3 and coordgen v.1.4.0:
- Changes in maeparser are all build-related.
- Changes to coordgen also include build improvements, but also a bug fix to prevent propagation of bad chirality (schrodinger/coordgenlibs#54), some performance improvements, and hardcoding of the templates into the code. This means that templates.mae no longer needs to be in the installation (so I removed any references from RDKit). Also, it makes maeparser an optional dependency of coordgen (it is enabled by default; now it is only used in case the user provides a custom templates file).
The build improvements in maeparser and coordgen allow for building static libraries out of the box. At present, this is not of great relevance to RDKit, as we don't use maeparsers or coordgens cmake …
=> Update Maeparser & Coordgen Dependencies

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_graphmol.cpp
- Add tests for phosphine and arsine chirality
- Add support to isAtomPotentialChiralCenter()
Accept both 2 (implicit H), 3 and 4 coordinate P and As atoms as potential
chiral centers
Fixes #2949 
Adds support for phosphine and arsine chirality in isAtomPotentialChiralCenter()
Support for phosphine and arsine chirality in assignChiralTypesFromBondDirs() will be added in a separate, future PR.
=> phosphine&arsine chirality support isAtomPotentialChiralCenter()

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_graphmol.cpp, rdkit/Chem/UnitTestMol3D.py
I have patched `FindPotentialStereoBonds()` to check that bonds marked as STEREOANY have stereo bonds. If they have, the bond is skipped, but if not, then the bond is rechecked in order to have stereo atoms assigned, or be relabeled as STEREONONE.
This fixes #2890: `EnumerateStereoisomers()` was failing because the input STEREOANY bond did not have stereoatoms assigned. Once it gets them, the enumeration succeeds.
=> Address issue #2890

Docs/Book/GettingStartedInPython.rst
The doctests were occasionally failing because I had forgotten the random seed.
=> add random seed to docs to get reproducible conformations

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/RingMatchTableSet.h, Code/GraphMol/FMCS/Test/testFMCS.cpp, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Code/GraphMol/Wrap/rdchem.cpp, Code/JavaWrappers/FMCS.i, Code/RDBoost/Wrap.h
This PR adds support for user-defined Python FMCS functors and progress callbacks.
The pre-defined C++ compare functions can be called from Python too, so users do not have to reimplement Python versions of the already available C++ functionality (e.g., `CheckAtomRingMatch`, `CheckAtomCharge`, `CheckAtomChirality`, `CheckBondStereo`, `CheckBondRingMatch`), and can focus only on the custom behavior which is not available OOTB in the C++ layer.
I struggled to maintain backwards compatibility with the previous FMCS C++ implementation, so users who have written custom C++ `compare` functions won't need to change anything.
I had to add a `bool MatchIsotope` variable to `MCSAtomCompareParameters` or isotopic SMARTS could not have been written from Python unless the built-in …
=> Added support for Python FMCS functors

Code/SimDivPickers/DistPicker.h
That function is in the anonymous namespace so it is not reachable anyway, hence no point in exporting it. The `dllexport` raises a build error when building DLLs on Windows, though only in `Debug` mode for some reason.
=> Removed dllexport from a function that lives in the anonymous namespace

Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h, rdkit/Chem/Draw/__init__.py
Several things here:
1) move "atomNote" and "bondNote" to common_properties
2) move addStereoAnnotation to the MolDraw2DUtils namespace
3) add addAtomIndices and addBondIndices
4) initialize MolDrawOptions members directly instead of via the ctor
5) add tests for all that
6) the usual reformatting
It's worth showing off how the atom index annotations work. 
This bit of C++:
```
{
MolDraw2DSVG drawer(250, 200);
m1->getAtomWithIdx(2)->setProp(common_properties::atomNote, "foo");
drawer.drawOptions().addAtomIndices = true;
drawer.drawOptions().addStereoAnnotation = true;
drawer.drawMolecule(*m1);
drawer.finishDrawing();
std::string text = drawer.getDrawingText();
std::ofstream outs("testAtomBondIndices_5.svg");
outs << text;
outs.flush();
}
```
Produces this image:
=> Tweaks and refinements to new drawing code.

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Tweak to atom annotation to fix problem shown by:
rdDepictor.SetPreferCoordGen(False)
mol = Chem.MolFromSmiles('C[C@H](F)N')
d = rdMolDraw2D.MolDraw2DCairo(250, 200)
d.drawOptions().addAtomIndices = True
d.DrawMolecule(mol)
d.FinishDrawing()
with open('atom_annotation_3.png', 'wb') as f:
f.write(d.GetDrawingText())
where the zero appeared at the end of the C-C bond so looked like an oxygen, espcecially in B/W.
Tested on Mac only.
=> Fixed bug with annotation on degree-1 atoms.

Code/GraphMol/ChemReactions/DaylightParser.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp
Fixes #2954 
Implemented an approach which does not use std::string::find to find ">" occurrences. The new implementation checks the chracters around ">" and seperates the reactants and products accordingly. Corresponding tests have also been implemented.
=> Fixes #2954:Rxn Smarts with Dative Bonds not parsed

Code/GraphMol/Depictor/RDDepictor.cpp, Code/GraphMol/MolTransforms/test1.cpp
When using coordGen for 2D coords, always moves the coords to be centred on (0,0).  Fixes an issues laying out some molecules in grids.
Tested on Mac only.
=> Coordinates from coordgen are not centered around the origin

Code/GraphMol/ScaffoldNetwork/CMakeLists.txt
would be good to put those header files in a sensible place
=> fix a typo in ScaffoldNetwork/CMakeLists.txt

Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/testPropertyLists.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/catch_graphmol.cpp
I think some Catch2 test cases are wrongly tagged—`[foo,bar]` should be `[foo][bar]`.
See https://github.com/catchorg/Catch2/blob/v2.1.2/docs/test-cases-and-sections.md#tags
<details>
<summary>build</summary>
```shellsession
$ cmake -Bbuild -GNinja ..
$ cmake --build build Code/GraphMol/ChemReactions/all
```
</details>
For example,  [Code/GraphMol/ChemReactions/catch_tests.cpp](https://github.com/rdkit/rdkit/blob/9ce1955e8d88b8113900b152f228a2ab49a747ea/Code/GraphMol/ChemReactions/catch_tests.cpp) has the following tests:
```shellsession
$ cd build
$ ./Code/GraphMol/ChemReactions/rxnTestCatch -l
All available test cases:
Github #1632
[Reaction,PDB,bug]
Github #2366 Enhanced Stereo
[Reaction,StereoGroup,bug]
Github #2427 cannot set maxProducts>1000 in runReactants
[Reaction,bug]
negative …
```
=> Correct TEST_CASE tags for Catch2

Code/GraphMol/Resonance.cpp, Code/GraphMol/resMolSupplierTest.cpp
Accessing a non existing `std::map` key caused a default value to be returned, i.e. a `nullptr`, which once dereferenced caused a segfault. This PR fixes the problem with appropriate checks.
=> - fixes GitHub #3048

CMakeLists.txt, CTestConfig.cmake, Code/DataStructs/testDatastructs.cpp, Code/GraphMol/ChemReactions/DaylightParser.cpp, Code/GraphMol/ChemReactions/Enumerate/testEnumerate.cpp, Code/GraphMol/ChemReactions/testReaction.cpp, Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/PDBParser.cpp, Code/GraphMol/MolDraw2D/test1.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Substruct/test1.cpp, Code/RDGeneral/testDict.cpp, Code/boost/serialization/singleton.hpp, Code/cmake/rdkit_valgrind.suppressions
I ran a memtest and found some problems. Most of them were mols left over in tests, but there was also some more serious stuff:
- The valgrind command was missing the `--error-exitcode` argument. Without it, valgrind returns "0" even if it found some leaks. Somehow, I failed to include it when I set up the mem testing config.
- Updated the suppressions. These are less specific now, and the suppressions should now match in more environments.
- CX Smiles leaked a mol if the parser was not able to parse the CX extensions.
- PDB and Maestro suppliers leaked mols when the parsing failed.
- Reactions parsing was reading out of bounds (it tried to read one char before the start of the string).
Also, testEnumerate is quite hard for valgrind: it fails after ~10 minutes, and the log only contains …
=> Mem checkup

Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/rdkit-91.sql
This commit adds testing for support of CXSmiles in the cartridge by testing the mol_out function which is called in pg_dump.
Fixes #2795
=> Fixes #2795

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/testReaction.cpp
Fixes #3097 by disabling strict flag on `calcImlicitValence` in reactions
=> Reactions should not use strict implicit valence calculations

Docs/Book/Cookbook.rst
This pull request adds a new section on generating conformers with ETKDG into the Cookbook. In particular, it illustrates the various improvements to the initial ETKDG that we made in this new paper: J. Chem. Inf. Model., doi: 10.1021/acs.jcim.0c00025
Sorry for the delay, I was waiting for the article number for our paper to come out from the JCIM website.
=> Cookbook entry for ETKDG with rings

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/MaximumCommonSubgraph.h, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Docs/Book/GettingStartedInPython.rst, ReleaseNotes.md
See #3095 
If the MCS is constituted by a single atom, it is not reported. While this is most likely not a major problem, I think it is reasonable to expect that even a single atom, with no bonds, should be considered as an acceptable MCS.
This PR implements recognition of single atoms as the MCS. As there can be multiple single-atom MCSs between two structures that do not share anything larger, a criterion is adopted to ensure consistency (see the `std::max` lambda in `MaximumCommonSubgraph::makeInitialSeeds()`.
If you think this is completely unreasonable, feel free to bin it.
=> Fixes #3095 (single-atom MCSs are not captured)

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
This will now center molecules if `centreMoleculesBeforeDrawing` is true
it also changes the default value of `centreMoleculesBeforeDrawing` to false so that the default behavior of current code is not affected
=> Fixes #3126

Code/GraphMol/Wrap/Bond.cpp, Code/GraphMol/Wrap/rough_test.py
Basically copied over these two wrappers from Atom.cpp to Bond.cpp.
Added the wrappers for completeness / consistency between QueryAtom and QueryBond, and because they'd actually be useful in a program in which I want to modify SMARTS patterns programmatically. (My workaround until now had been to convert to an EditableMol, delete the bond, and add a new bond to replace it. And still isn't as flexible.)
=> Python wrapper: SetQuery and ExpandQuery for bonds

Code/GraphMol/AddHs.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp
Fixes #3150 
Fixes removeHs removing Hydrides by adding a removeHydrides flag to RemoveHsParameters.
If removeHydrides is false, Hydrogen atoms with formal charge -1 and degree less than or equal to 1 are kept
removeHydrides is kept true by default
=> Fixes #3150

Code/cmake/Modules/FindInchi.cmake
with cmake 3.17.2 the original code produced the following warning:
"The package name passed to `find_package_handle_standard_args` (INCHI) does
not match the name of the calling package (Inchi).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern."
=> fix a small inconsistency in the name of the inchi package

Code/GraphMol/hanoitest.cpp, Code/GraphMol/molopstest.cpp
`random_shuffle()` is deprecated in c++14 and removed in c++17, so we remove it here.
=> Remove usage of the deprecated random_shuffle() function

Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
Just a matter of checking that we aren't passing a null molecule in and raising a `ValueError` if we do.
=> Fixes #3177

Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp, Code/JavaWrappers/ROMol.i
https://github.com/rdkit/rdkit/issues/1820
Two common tasks in molecular docking results analysis are comparing predicted poses of a molecule with the reference one, and clustering the predicted poses. An extension of the current RDKit's function for symmetry-adapted RMSD computation would be helpful in such cases, where two molecules are compared with respect to their positions in a binding pocket, and alignment is excessive.
Nope
=> GetBestRMS with turned off alignment for molecular docking purposes

Code/GraphMol/MolPickler.cpp
#3211 
Fixes the problem that the code ignores failures when reading from a stream.
It would also have been possible to explicitly check the status of the stream after each read, but using exceptions seemed easier.
There are probably other areas that have similar problems.
I only looked at this area, because it currently blocks https://github.com/google/oss-fuzz/pull/3856.
Note, I don't know whether I should have moved the new struct to a different position/file.
Feel free to move it.
=> Throw exception when reading from stream fails.

Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
This PR fixes the iterator interface of `CompressedSDMolSupplier`, which is not compliant with the python3 requirements.
=> fix the CompressedSDMolSupplier python iterator interface

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
There are times when the RGroupDecomposition code is extremely slow (more than minutes).
Since I suspect these situations will always exist and because it takes a while to fix problems as we find them, it seems logical to add an optional timeout.
The approach I took here is very simpleminded: if either an individual call to `process()` or the entire call to `Decomp()` take longer than the timeout then we throw a runtime_error.
I don't think there's a reasonable way to return partial results (like the MCS code does) given that we could time out before all the molecules have been added.
This also:
- adds code to release the GIL when doing RGD from Python
- resolves #3224 by adding an option to run without any symmetrization for those cases where it's just too slow
=> Add optional timeout to RGroupDecomposition

Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
This also makes the documentation for assignStereochemistry() clearer.
The changes made to clear the R/S labels in EnumerateStereiosomers() should also be applied to E/Z labels on bonds: all labels should be converted to CIS/TRANS on first call. But this is a bigger change and wouldn't be one for a bug fix release.
=> Fixes #3231

.azure-pipelines/linux_build.yml
the linux CI builds are now failing because we aren't doing this
the reason it's necessary:
The conda cairo package is built against X11, so you need to have X installed on the backend in order to use it. The rdkit cairo_nox build gets around this problem
=> lock CI cairo version to (hopefully) force an install from the rdkit repo

Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py
If this isn't present then the `DATAFIELDS` property of SubstanceGroups cannot be accessed from Python
As an aside: we should come up with a more systematic (and automated) way of adding the `GetXXXProp()` methods to classes in Python
=> add GetStringVectProp() to SubstanceGroup class

Code/GraphMol/FindRings.cpp
When finding rings - If we've exhaustively searched
an atom and found no rings, we should mark the bonds to
that atom as "not in a ring". We can also mark any
neighboring low degree atoms in the same way.
This speeds up searches in large molecules, because
a ring search that _doesn't_ find any rings is very
expensive, and it's a bummer to pay for that search
on two neighboring atoms, for instance.
Ring finding is a bottleneck in sanitization,
especially for larger molecules.
Here are some SSSR timings on protiens from the RCSB PDB:
Before this commit:
- 3EOH: 3.5s
- 2J3N: 1.2s
- 1NKS: 0.05s
After this commit:
-  3EOH: 0.8s
-  2J3N: 0.3s
-  1NKS: 0.02s
=> Speed up ring finding by skipping nodes not in rings

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/catch_tests.cpp
There's no reason that we should have `add{Atom,Bond}Indices()` modifying a molecule more than once. This disables that.
The property that's used here won't ever be seen by calling code since these two functions are always called on the copies that MolDraw2D works with. The test verifies that.
=> Fixes #3258

External/CoordGen/CMakeLists.txt
This updates to build against the latest Coordgen release, v1.4.1. 
This new release only includes some performance improvements.
=> Update to Coordgen v1.4.1

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes #3262
This turns off minFontSize when drawing annotation in 2D drawings, to stop the annotation clashing with other bits on the drawing.  It applies only to the new DrawText classes so not the current version (2020.03.3).
Tested in C++ on macOs.
=> Annotation clashes with symbols on small drawings. #3262

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/MolPickler.h, Code/GraphMol/QueryOps.cpp, Code/Query/AndQuery.h, Code/Query/EqualityQuery.h, Code/Query/GreaterEqualQuery.h, Code/Query/GreaterQuery.h, Code/Query/LessEqualQuery.h, Code/Query/LessQuery.h, Code/Query/NullQueryAlgebra.h, Code/Query/OrQuery.h, Code/Query/Query.h, Code/Query/RangeQuery.h, Code/Query/SetQuery.h, Code/Query/XOrQuery.h, Code/Query/test.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h, Docs/Book/RDKit_Book.rst
Support the atom queries that are also supported in CXSMILES: `Q, A, M, X, QH, AH, MH, XH`
This adds a new data field, `d_queryType`, to the `Query` class to make this easier and to allow us a bit more control over handling "named" queries in the future.
There's cleanup in here too.
=> Add cxsmiles query atoms to CTAB parsers and writers

Code/GraphMol/CMakeLists.txt, Code/GraphMol/ChemReactions/Reaction.cpp, Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.h, Code/GraphMol/MolBundle.h, Code/GraphMol/MolEnumerator/CMakeLists.txt, Code/GraphMol/MolEnumerator/LinkNode.cpp, Code/GraphMol/MolEnumerator/MolEnumerator.cpp, Code/GraphMol/MolEnumerator/MolEnumerator.h, Code/GraphMol/MolEnumerator/PositionVariation.cpp, Code/GraphMol/MolEnumerator/Wrap/CMakeLists.txt, Code/GraphMol/MolEnumerator/Wrap/rdMolEnumerator.cpp, Code/GraphMol/MolEnumerator/Wrap/rough_test.py, Code/GraphMol/MolEnumerator/catch_main.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp, Code/GraphMol/Wrap/MolBundle.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/testMolBundle.cpp, Code/JavaWrappers/CMakeLists.txt, Code/JavaWrappers/MolBundle.i, Code/JavaWrappers/MolEnumerator.i, Code/JavaWrappers/gmwrapper/CMakeLists.txt, Code/JavaWrappers/gmwrapper/GraphMolJava.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolEnumeratorTests.java, rdkit/Chem/AllChem.py
Though what is here is already useful, I'm doing the PR to collection comments on the basic design before I do more work.
The primary goal is to be able to enumerate molecules from some of the interesting features that show up in Mol files. Three specific examples of the type of enumeration I'm thinking about.
**Position variation bonds**
This molecule with position variation bonds:
Should enumerate to these four molecules:
This enumeration is implemented in the current PR.
**Link atoms**
This molecule with a link node:
Should expand to these four molecules:
**SRUs**
This molecule with an SRU that has associated counts:
should expand to these three molecules:
The last one is not yet implemented.
Link atoms and SRUs require a change to the MolBundle class to remove the restriction that all …
=> Support enumerating some mol file features into `MolBundles`

Code/MinimalLib/docker/Dockerfile, Code/MinimalLib/tests/tests.js, Code/RDStreams/CMakeLists.txt
Two main (small) changes here:
- get `RDStreams` to build properly when `RDK_USE_BOOST_IOSTREAMS` is off
- update to use the new versions of the emscripten tools properly
This should not be merged until after the `Dockerfile` has been changed to point at master again.
=> Fixes #3267

Code/cmake/Modules/RDKitUtils.cmake
Each `conda` incremental build on Windows was starting from scratch driving me _slightly_ nervous.
This change avoids that if `CMAKE_BINARY_DIR==CMAKE_SOURCE_DIR` (as in `conda` builds)
`export.h` is overwritten at each incremental build causing the whole RDKit to be rebuilt every time.
=> Avoid really slow Windows conda builds

Code/JavaWrappers/ScaffoldNetwork.i, Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
Exposes ScaffoldNetwork, TautomerQuery and RGroupDecomposition to SWIG C# wrappers. 
I can't get ScaffoldNetwork.counts to wrap properly in C#, so I added an helper extension method.
On Linux building the C# wrappers does not wrap std::vector&lt;unsigned&gt;.  Adding a SWIG template for std::vector&lt;unsigned&gt; breaks the build because of conflicts with the template for std::vector&lt;boost::uint32_t&gt;.  Other than the extension method I was unable to find a workaround.  Interestingly, the Java wrappers do not have this problem with the std::vector&lt;boost::uint32_t&gt; template applied to std::vector&lt;unsigned&gt;.
=> ScaffoldNetwork not in C# wrappers

Code/GraphMol/MolInterchange/Parser.cpp, Code/GraphMol/MolInterchange/test1.cpp
This was a logic error when handling bond stereo and stereoAtoms
=> bonds with "either' stereo cannot be read from JSON

Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h, Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
This is a more intuitive measure of how often a scaffold "appears" in a dataset than the current `counts` metric, which is almost an implementation detail.
Since you can never be sure, I benchmarked this on a set of ~20K molecules and the new feature doesn't make the code take measurably longer to run
=> ScaffoldNetwork: add feature to count the number of molecules a scaffold originates from

Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py
We have discussed this as part of #2597 with @greglandrum and we decided to use consistently `operator()` (C++) and `__call__()` (Python) for user-overridable methods (e.g., custom FMCS compare functions, callbacks).
I have made the old function names deprecated such that they can be removed in release 2021.01.
I have added relevant tests to make sure both the new and deprecated functions still work.
Additionally, the new code will throw a Python exception if the virtual C++ method is not overridden by the Python derived class as soon an attempt to set the compare/callback is made, whereas previously the exception was thrown only when the virtual C++ function was actually called in the absence of the Python override, which was a bit annoying.
=> Use operator() and __call__() consistently across RDKit

Code/GraphMol/ConjugHybrid.cpp, Code/GraphMol/catch_graphmol.cpp
There's no sense trying to assign reasonable hybridization states to the actinides. They don't really make sense and end up with silly molecule renderings. This changes the behavior so that anything past Ac just gets assigned "S" as its hybridization state.
There's also some cleanup in this PR
=> Stop trying to assign hybridization to actinides

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/ChemReactions/MDLParser.cpp, Code/GraphMol/FileParsers/FileParserUtils.h, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smatest.cpp, Docs/Book/RDKit_Book.rst, ReleaseNotes.md
Adds support for parsing:
- `rb`  : ring-bond count  - converts to query
- `u` : unsaturation - converts to query
- `s` : non-hydrogen substitution count - converts to query
- `m`: variable attachment points  - adds bond property corresponding to what you get from a Mol file
- `LN`: linknodes - adds mol property corresponding to what you get from a Mol file.
It also adds a new SMARTS primitive, `d`, which queries for the non-hydrogen degree of an atom, because that seems useful. There's an argument that this should go in its own PR, and I'm happy to do that if others prefer.
Other things in this PR:
- extended the documentation of which pieces of CXSMILES are supported
- moves a couple useful functions from `FileParserUtils.h` to `QueryOps.h` and deprecates the old versions
- remove an …
=> Expanded support for CXSMILES features

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/Fingerprints/PatternFingerprints.cpp, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/TautomerQuery/catch_tests.cpp, Code/JavaWrappers/ChemTransforms.i
TautomerQuery catch test was broken when adding aromatic bond fuzzy matching to pattern fingerprinting.
The error was caused by using a test molecule which was similar to a tautomer template but without tautomer bonds.  By including singleOrAromatic in the tautomer pattern fingerprint, all the query bonds in the test molecule were identified as tautomer bonds.
Also includes a wrapping of fragmentOnBonds for Java/C#.  I can remove and submit in another request if this is inappropriate.
=> Fixes for aromatic bond fuzzy queries

.azure-pipelines/linux_build.yml, .azure-pipelines/linux_build_py37.yml, .azure-pipelines/mac_build.yml, .azure-pipelines/vs_build.yml, Docs/Book/RDKit_Book.rst
the problem was fixed here: https://github.com/sphinx-doc/sphinx/issues/8084
but that is not yet released
=> lock sphinx version in CI due to problem with v3.2.0

Code/GraphMol/FindRings.cpp
Before this commit:
3EOH: 0.72s
2J3N: 0.26s
1NKS: 0.018s
After this commit:
3EOH: 0.35s
2J3N: 0.07s
1NKS: 0.007s
This change speeds up ring performance by not storing every path back to the root. Instead, it keeps track of parents and rebuilds paths from the parents once a cycle is found. It also stops the BFS once the depth of the BFS is larger than the smallest ring (i.e., we found a path that is longer than the smallest ring).
=> Sped up SSSR by not storing every path back to root

README.md
None
None. Just added a link to Alpine APK packages
The linked GitHub repository has a release page, which contains following APK packages:
* rdkit-*version*-r0.apk (dynamic libraries)
* rdkit-static-*version*-r0.apk (static libraries)
* rdkit-dev-*version*-r0.apk (header files)
* rdkit-doc-*version*-r0.apk (documentation)
* py3-rdkit-*version*-r0.apk (Python3 files)
* rdkit-java-*version*-r0.apk (Java wrapper files)
* rdkit-java-doc-*version*-r0.apk (Java wrapper documentation)
* rdkit-pgsql-*version*-r0.apk (PostgreSQL cartridge)
where *version* is between Release_2020_03_1 and Release_2020_03_5 (latest).
For each APK file, three Alpine versions available: v3.10, v3.11, and v3.12 (latest).
=> Add APK package link for Alpine Linux distribution

Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Tiny improvement in SVG output.
The SVG generated by MolDraw2DSVG sometimes contains "fill-opacity=" as opposed to "fill-opacity:" as sub-attributes of a style attribute. This can break downstream parsing, for example, in my use case, svglib/reportlab in python.
Thanks for the fantastic toolkit!
=> Replace fill-opacity= with fill-opacity: in MolDraw2DSVG and tests

Code/GraphMol/AddHs.cpp, Code/GraphMol/molopstest.cpp
Hs are not put in the same plane as the `sp2` system the atom belongs to. This affects ethylene (2 heavies only) and conjugated systems of any size.
This gist demonstrates the bug:
https://gist.github.com/ptosco/620edc8a3fd411928499204003eefb59
This gist shows the results obtained after merging this PR:
https://gist.github.com/ptosco/93f85d18794ed46da4122fa35bdb7b6e
=> Fixes a bug in AddHs() involving sp2 centers with degree 1

Code/GraphMol/Resonance.cpp, Code/GraphMol/Resonance.h, Code/GraphMol/Wrap/ResonanceMolSupplier.cpp, Code/GraphMol/resMolSupplierTest.cpp
- Fixed #3349
- fixed a few typos
- removed `const` from `ResonanceMolSupplierCallback::operator()`, which should be allowed to modify the owning object
- added missing `const` to some getters
=> Fixes #3349

Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py
This specifically does:
- `GetCStates()`
- `GetBrackets()`
- `GetAttachPoints()`
=> expose additional SubstanceGroup data members to Python

Code/GraphMol/QueryAtom.h, Code/GraphMol/catch_adjustquery.cpp
Modifies the `QueryAtom(const Atom &)` ctor to ensure that the following atom properties are translated into queries if they have non-zero values:
- isotope
- formal charge
- num radical electrons
=> Fixes #3388

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
=> Recursive smarts cannot be used in the core for rgroup decomposition

Code/GraphMol/ChemReactions/MDLParser.cpp, Code/GraphMol/ChemReactions/ReactionParser.h, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/testReaction.cpp
Similarly to the MDL molblock parser I think it would be good to enable passing explicit flags to the MDL rxnblock parser.
Particularly from Python, that does not allow write to reactant and product templates, it makes life easier in situations like the one exemplified in the test case compared to `SanitizeRxn()`.
=> Allow passing explicit removeHs, sanitize and strict flags to the MDL rxn parser

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/ReactionUtils.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp, Docs/Book/RDKit_Book.rst
This fixes #2891 and generally improves the handling of atomic chirality in reactions.
It expands the number of non-obvious cases where chirality is handled correctly and adds some documentation to set expectations about what does and does not work.
=> Improvements to reaction chirality handling

Code/GraphMol/MolEnumerator/MolEnumerator.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp
For efficiency reasons we don't want to do a full sanitization, but It doesn't make any sense to require client code to do this.
=> MolEnumerator::enumerate() should call updatePropertyCache()

Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/testTautomer.cpp
Turns out this was a very simple fix. There was already a rule to penalize exocyclic nitrogen bonds from aromatics to nitrogen, which however was conflicting with another rule addressing guanidines, so the net effect of the rules was zero and the exocyclic double bonded ended up with exactly the same score as the exocyclic one.
Changing the guanidine pattern to only apply to aliphatic C fixes the issue.
I had to change a single unit test where before my fix tautomers had the same score and the exocyclic tautomer was chosen as the canonical one based on lexical order:
After my fix the endocyclic tautomer scores higher, as expected.:
This is also the tautomer predicted to be the most stable by both UNICON (https://doi.org/10.1021/acs.jcim.6b00069) and MoKa …
=> Fixes #3430

Code/GraphMol/MolStandardize/testTautomer.cpp
Added `#pragma`s for GCC/clang and MSVC to silence deprecation warnings as that line is test is actually meant to test the deprecated form.
=> Silence deprecation warning

rdkit/Chem/__init__.py
The tag is used in places like `EnumerateStereoisomers()`, which won't be updated to use the new code by default until the next release.
=> set the ChiralityPossible tag when using the new code with FindMolChiralCenters

Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
This allows metadata to be added to/read from PNG files and strings.
Allows us to use PNG files like SDFs :-)
=> expose PNG metadata functions to python

External/INCHI-API/Wrap/pyInchi.cpp
The InChI Trust website has changed the locations of the documentation and FAQ for the InChI software APIs.
No Issue
I have updated the link for the FAQ, but unfortunately the User Guide is no longer directly linkable, but is available for download as part of a zip file of documentation from the main downloads page.
=> Fix dead links to inchi-trust

Code/GraphMol/MolStandardize/MolStandardize.cpp
This PR contains two very simple MolStandardizer code cleanups:
- `MolStandardize::chargeParent()` does not need to call `cleanup()` because it calls `fragmentParent()` which already does
- `MolStandardize::reionize()` should pass `params.acidbaseFile` to the `Reionizer` constructor (it looks like this was forgotten)
=> Two simple MolStandardizer code cleanups

Code/GraphMol/MolStandardize/Normalize.cpp, Code/GraphMol/MolStandardize/Normalize.h, Code/GraphMol/MolStandardize/Wrap/Normalize.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/testNormalize.cpp
This PR contains a few improvements to `MolStandardize::Normalizer`:
- use `ROMOL_SPTR` consistently (cosmetic change)
- allow using multiple alternative normalization patterns that match the same functional groups. I have added a test case where multiple custom patterns all match malformed azides. With the current RDKit master the `Normalizer` keeps adding the custom pattern again and again until it reaches the maximum number of normalization restarts (200 by default), and then applies no other normalization SMARTS. With the fix included in this PR this does not happen anymore.
- add missing parameter to `NormalizerFromData` factory method (Python wrappers): apparently one of the parameters had been forgotten in the Python signature
- add `NormalizerFromParams` factory method (Python …
=> A few improvements to MolStandardize::Normalizer

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/test1.cpp
Fixes Github3391.
drawMolecules() was drawing 2 methane molecules badly - the text for the first one was poorly spaced.  This was because the scale was being calculated to take account of the fixed font size after the first molecule was drawn.
I had a complete nightmare merging master into the previous PR attempting to fix this bug.  The code is otherwise the same, I think.  Sorry.
=> Fixed bad draw scale in drawMolecules. Github3391.  Take 2.

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp
includes:
- increasing the minimum font size to 6
- further tweaking to the dash counts for wedged bonds
- making the arrows on dative bonds more prominent
- allowing the drawing of radicals to be disabled
=> A few small tweaks to the drawing code

Code/RDGeneral/RDLog.cpp
Simple fix to BlockLogs, it was turning on all logs when it went out of scope, this just turns on the logs that were turned off.
=> BlockLogs was reenabling all logs, not just the ones that were disabled

External/INCHI-API/test.cpp
I forgot to re-enable these in #3366
=> enable accidentally disabled inchi tests

Code/GraphMol/FileParsers/CMakeLists.txt
OK, there was actually a problem, but it was just a typo.
=> Fixes typo that causes the build to fail

Code/GraphMol/ROMol.h
This change improves the throughput of many common rdkit operations on my setup (x86_64 debian buster / clang 7 / 8-core cpu):
The number of `RDKit::MolToSmiles` calls/s is about 2.8% higher
The number of `RDKit::SmilesToMol` calls/s is about 5.8% higher
The number of `RDKit::MolToInchiKey` calls/s is about 2.0% higher
=> ROMol: add inline impl for common getNumAtoms call

Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
Some of the rdMolStandardize functions were not checking that they were being passed valid pointers, so it was pretty easy to make them crash the kernel.
=> Fix a crashing bug with None in rdMolStandardize

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
It was an oversight that this wasn't originally included.
=> allow fillColour to be changed from python

Contrib/ConformerParser/Wrap/testConformerParser.py, Contrib/ConformerParser/test.cpp
These two tests are failing because they look for their input files in paths that do not exist.
The tests are currently not exercised in the CI builds, so I didn't notice until I enabled some extra options in my build.
=> fix paths in ConformerParser tests

rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
Passing `flagPossibleStereoCenters=True` to `AssignStereochemistry()` in `EnumerateStereoisomers` allows the stereo atoms in the enumerated mols to get the `_ChiralityPossible` property, and be counted by `rdMolDescriptors.CalcNumAtomStereoCenters()`.
I also added a test to check that the property is set on outputs of `EnumerateStereoisomers()`
=> Fixes #3505

Code/GraphMol/Wrap/test_data/do_smiles.bomb.py, Code/GraphMol/Wrap/test_data/do_smiles.py, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/MolKey/InchiInfo.py, rdkit/Chem/Pharm3D/Pharmacophore.py, rdkit/Chem/fmcs/fmcs.py, rdkit/ML/Data/DataUtils.py, rdkit/ML/Descriptors/MoleculeDescriptors.py, rdkit/ML/Scoring/Scoring.py, rdkit/sping/PDF/pdfgen.py, rdkit/sping/PDF/pdfutils.py, rdkit/sping/PDF/pidPDF.py, rdkit/sping/PS/pidPS.py, rdkit/sping/stringformat.py
Sometimes, when working with python some Deprecation Warnings about invalid escape sequences show up:
```
rdkit\Chem\EnumerateStereoisomers.py:165: DeprecationWarning: invalid escape sequence \[
""" returns a generator that yields possible stereoisomers for a molecule
```
```
rdkit\ML\Descriptors\MoleculeDescriptors.py:109: DeprecationWarning: invalid escape sequence \ 
doc = re.sub('\ *\n\ *', ' ', doc)
```
Those aren't a problem (though someone mentioned that in a future python release these warnings might turn into errors), although they are sometimes an annoyance.
I thought I might get them fixed so that the warnings stop showing up. Also, along the way, I noticed my editor trimmed whitespace at the end of the lines of the files I edited.
=> Fix python invalid escape sequences

Code/GraphMol/Atom.cpp, Code/GraphMol/catch_graphmol.cpp
Unintended (and untested for) consequences of changing Hs to be "early" atoms.
The fix here is to explicitly handle the special cases of implicit valence of H atoms:
- `H+`: no implicit Hs
- `H`: one implicit H
- `H-`: no implicit Hs
For the sake of (very minor) efficiency, I also added a special case for atomic number=0 (i.e. dummy atoms).
=> fix problem with H+ caused by #3473

Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, rdkit/ML/Descriptors/UnitTestMolDescriptors.py
This resolves #3511.
A quick wrapping of the return type of the BCUT2D descriptors into a Python list.
I'd prefer a tuple, but AUTOCORR2D is also returning a list, so I guess it makes sense to follow the same pattern.
=> Fixes #3511

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Since `legend_height_` is being zeroed out at the end of `drawMolecules()` subsequent calls to drawing commands end up producing incorrect results (vertically offset by `legend_size_`).
Here's an example:
The hexagons there are drawn using atom coordinates.
=> legend_height_ should be preserved after drawing the molecule

rdkit/Chem/ChemUtils/DescriptorUtilities.py, rdkit/Chem/Descriptors.py, rdkit/Chem/UnitTestDescriptors.py
Yesterday, looking at #3511, I became curious about the AUTOCORR2D descriptors: I noticed that while BCUT2D ones left over a cache (with a non-Python type), there wasn't one for the AUTOCORR2D descriptors.
Looking a bit further, I noticed these had to be explicitly set up... using a function that was missing an underscore (`setupDescriptors()`). From there, it was an interesting trip to find that the setup mechanism wasn't working... and neither was the test that was supposed to catch it, since it was over indented so that it was an inner function of the previous test, and therefore, never ran.
This is my attempt to fix it
=> Fix AUTOCORR2D descriptors

Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
I have noticed that this test fails on `Debug` builds, which are sloooow. This gives it a bit more time.
=> Give a bit more time to RGD test in debug builds

Code/GraphMol/Wrap/Conformer.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rdchem.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/Wrap/seqs.hpp, Code/GraphMol/Wrap/testConformer.py
This PR fixes #3492 as well as other issues connected to C++ objects being destroyed too early.
For example, the current RDKit master branch segfaults when doing:
```
In [1]: from rdkit import Chem
In [2]: Chem.MolFromSmiles("CC").GetBonds()[0].GetOwningMol()
Segmentation fault
```
or
```
In [1]: from rdkit import Chem
In [2]: Chem.MolFromSmiles("CC").GetAtoms()[0].GetOwningMol()
Segmentation fault
```
while after this PR this does not happen anymore.
=> Fixes #3492

Code/PgSQL/rdkit/bfp_gist.c, Code/PgSQL/rdkit/low_gist.c, Code/PgSQL/rdkit/rdkit_gist.c
Fixes #3521
This PR implements a small cleanup of the postgres cartridge code, removing the inclusion directive for a header file that apparently wasn't actually used. In particular, this change also fixes a build issue with the recent PostgreSQL 13 release, that removed the same header file.
As far as I can tell, this header was already unnecessary when building the cartridge with PostgreSQL 9.5. I tested this change on linux only, I suppose the general organization of the postgres header files directly imported by the cartridge code could be sufficiently uniform across the supported OSs, but please consider testing on other platforms if you have the required build environments.
=> remove the include directive for unused <access/tuptoaster.h> header

CMakeLists.txt, Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
Gets builds working when RDK_USE_BOOST_SERIALIZATION is disabled
Minor build system changes associated with this too.
=> Fixes #3529

Code/GraphMol/SubstanceGroup.h, Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py, Code/GraphMol/catch_sgroups.cpp
The following attributes of SubstanceGroups could be added, but not modified/removed:
- Brackets
- CStates
- AttachPoints
Rather than adding an interface to modify or remove individual groups, this just adds simple methods to remove them entirely. New/modified values can then be added back to the SubstanceGroup being modified.
=> Add missing methods to remove SubstanceGroup attributes

Code/GraphMol/Wrap/MolSupplier.h, Code/GraphMol/Wrap/ResonanceMolSupplier.cpp, Code/GraphMol/Wrap/SDMolSupplier.cpp
While working on #3523 I noticed that `MolSupplNextAcceptNullLastMolecule` is an exact duplicate of `MolSupplNext`. I guess probably originally it wasn't, but now it is, so it does not make sense to keep both.
=> Removes function which is an exact duplicate of another function

Code/GraphMol/RGroupDecomposition/RGroupCore.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
It took me a bit to figure this out, even though the fix is actually simple.
See a description of the issue below.
```
import rdkit
rdkit.__version__
'2021.03.1dev1'
from rdkit.Chem.Draw import MolsToGridImage
from rdkit.Chem import rdDepictor, rdRGroupDecomposition
core_molblock = """
RDKit          2D
10 10  0  0  0  0  0  0  0  0999 V2000
-3.6689   -0.8582    0.0000 R#  0  0  0  0  0  1  0  0  0  0  0  0
-2.2421   -1.3211    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
-1.1279   -0.3169    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.4403    1.1502    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-0.3261    2.1543    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
1.1007    1.6914    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
1.4132    0.2243    0.0000 C …
```
=> Fixes an RGD issue with cores having dummies adjacent to R-group labels

Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
* Fix a bug in Python `CountMatches` which would run on 1000 threads
The `CountMatches` Python function definition in the `boost::python` class featured a `maxResults` parameter which is not actually present in its C++ counterpart (as it does not apply to match counting). As a consequence, the previous `numThreads` parameter default (`-1`) was being overwritten with the `maxResults` default (`1000`), causing `CountMatches` to run on 1000 threads when invoked from Python
=> Fixes bug in SubstructLibrary Python wrappers (see #3557)

Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp, Code/GraphMol/MolDraw2D/MolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
The `clearDrawing()` methods were not taking the `offset` into account when clearing the background prior to drawing the molecule. This PR fixes that.
=> Fixes #3540

Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
This PR is a patch to the previous [PR I submitted for macrocycle conformer generation](https://github.com/rdkit/rdkit/pull/2999) in order to get the trans preference behaviour when sampling amides in macrocycles. 
In the previous PR, I only forced trans configuration of amides when the three consecutive bonds are all ring bonds (in the function `_setMacrocycleAllInSameRing14Bounds`).
However, another enforcing is needed when faced with two consecutive ring bonds(in the function `_setMacrocycleTwoInSameRing14Bounds`), which was included during my [code development](https://github.com/rinikerlab/RDKit_mETKDG/blob/master/modified_rdkit/Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp#L884) and I (carelessly) neglected to add in that PR. 
This PR adds two more variants of the …
=> correct handling of amide distances for macrocycles

CMakeLists.txt, Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, rdkit/Chem/Draw/__init__.py
Since we can specify our own fonts, it was inevitable that molecules would be rendered with Comic Sans. This takes that game one step further and fakes hand-drawn lines for bonds.
This was originally just going to be a joke, but I unexpectedly find myself actually liking this way of drawing molecules.
A few examples:
=> add a "comic mode" to MolDraw2D

Code/GraphMol/MolDraw2D/DrawText.h, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolTransforms/MolTransforms.cpp, Code/GraphMol/MolTransforms/MolTransforms.h, Code/GraphMol/SubstanceGroup.h
There's also a bit of refactoring of how annotations are handed in general.
Example output:
Some additional example files for more testing would certainly also be useful, but I think something is better than nothing and these aren't terrible.
=> Add rendering of SGroup brackets to MolDraw2D

Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
This is a super simple fix to make sure that atomic coordinates are not written using scientific notation.
It's worth noting that the code now always outputs six digits of precision because we've switched to fixed and the default precision for C++ is 6 digits: https://en.cppreference.com/w/cpp/io/ios_base/precision
=> Fixes #3597

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake, Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake, Code/GraphMol/SmilesParse/smiles.yy
To resolve this we needed to track the order of bonds from the SMILES.
This does this via a temporary bond property which is removed before the molecule is returned to the user.
It's worth pointing out that this fixes the problem with parsing CXSMILES. We'll still be writing them incorrectly. That's for a separate issue/PR.
=> Fixes #3320

Code/GraphMol/FileParsers/PNGParser.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Disables kekulization when generating the mol blocks for PNG metadata
This should also fix #3572
=> Fixes #3543

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
One line change to make sure that the chiral flag is captured when parsing V3K mol blocks.
=> Fixes #3620

Code/DataStructs/Wrap/testBV.py, Code/DataStructs/Wrap/wrap_BitOps.cpp
This makes a minor tweak to speed up calls to `BulkXSimilarity()` by about 10% and introduces new wrapper functions to find the nearest neighbors of a particular fingerprint in a list of other fingerprints.
Here's the performance impact:
| Action | master | this PR |
|----------|-----------|-----------|
| 10K calls to `BulkTanimotoSimilarity()` across ~36K fingerprints | 35.7s | 32.4s |
| find nearest neighbor in the 36K fingerprints for 3K fingerprints using `BulkTanimotoSimilarity()` and a Python sort | 20.0s | 18.7s |
| find nearest neighbor in the 36K fingerprints for 3K fingerprints using `TanimotoSimilarityNeighbors()` | N/A | 7.4s |
There's also a bit of refactoring to simplify `wrap_BitOps.cpp`
=> A couple changes to speedup bulk similarity calculations from Python

Code/GraphMol/Bond.cpp, Code/GraphMol/Bond.h, Code/GraphMol/Chirality.cpp, Code/RDGeneral/Ranking.h
The changes in this patch increase throughput of `iterateCIPRanks` by about 62%.  This patch consists of many changes that all combine to contribute to the performance gains, and these are the major changes:
* Introduce `Bond.getTwiceBondType` to avoid floating point operations in `floor(2*bond->getBondTypeAsDouble() + .1)`
* In RDGeneral/Ranking.h/rankVect, just store the last index (instead of the last vector) and avoid creating a copy at the current index.
* In GraphMol/Chirality.cpp/iterateCIPRanks, reserve more capacity ahead of time.
* In GraphMol/Chirality.cpp/iterateCIPRanks, avoid materializing `localEntry` and then copying into `cipEntries`; instead, track the data to be added in a `counts` vector and a `updatedNbrIdxs` vector and directly insert into `cipEntries`.
In …
=> Speed up GraphMol/Chirality.cpp/iterateCIPRanks

Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
hooray for fixes which just involve moving a line of code
no test here since we don't have tests for moldraw2djs
=> moldraw2djs should not close all polygonal paths

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Examples of what these look like:
Note that the coordinate generation still won't do anything sensible with these (the examples are all read in from mol blocks), that's one for another day (and another PR)
=> Support rendering variable attachment points

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
This is a simple one to allow structures to be rendered without atomic symbols (yet still with colors, so you get renderings like this):
It's been possible to do this all along by setting the `_displayLabel` property to `""`. This just makes that easier
=> add configuration option to disable atom symbols in the rendering

Code/GraphMol/RGroupDecomposition/RGroupData.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp, Code/GraphMol/RGroupDecomposition/RGroupScore.cpp, Code/GraphMol/RGroupDecomposition/RGroupScore.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Sorry Brian, another one for the exclusive RGD club. If you get to the end of the PR review you'll get the "RGD Master" qualification and a life-long unlimited Advil liquid capsule supply.
- replaced `set` with `vector` for SMILES-based R-group equivalence
As anticipated in one of Brian's comment (that I have removed). the `set` should rather be a `vector` to properly address `bis` geminal susbtitution
- the first `GreedyChunk` is constituted by `chunkSize+1` mols
An outdated copy of `matches.size()` was being used, with the consequence that the first `GreedyChunk` was constituted by `chunkSize+1` mols rather than `chunkSize`
- labeled R-groups may not be extracted when `onlyMatchAtRGroups==false`
This bug was originally reported by @rvianello (see <i>Bug description</i> below) and it …
=> Fixes a few residual issues with the RGD code

External/catch/CMakeLists.txt
This updates catch2 version which caused the build on Apple's M1 to fail
Generally, builds run fine, I've both built against the official Python 3.9 with universal binaries which was just released, miniforge's python3.9 and a miniforge's 3.8 environments. 
For people trying to build this on the M1 I would recommend getting all binary dependencies with miniforge.
Code signing caused issues as well - unfortunately the fix suggested in the rdkit docs didn't work so I had to sign all `.dylibs` using an actual apple developer account (`codesign -f -s "<yourid>"  $HOME/miniconda3/lib/*/*.so`)
=> Bump catch2 version to allow builds on Apple M1

Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py
The existing tests did not cover the case where a custom Python `AtomTyper` is used in the absence of a custom Python `BondTyper` and `MCSAtomCompareParameters.RingMatchesRingOnly`, `MCSBondCompareParameters.RingMatchesRingOnly` or `MCSBondCompareParameters.CompleteRingsOnly` are requested. In that case `MCSBondCompareAny`, `MCSBondCompareOrder` and `MCSBondCompareOrderExact` expect that `userData` is a `FMCS::RingMatchTableSet*`, and this was not happening, as Python functors use `userData` for another purpose, thus causing a crash.
This PR fixes the problem and adds tests to avoid that this happens again in the future.
=> Fixes #3635

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp
Unlike chirality, fragment on bonds wasn't preserving the internal bond-stereo.
This only became an issue when using the fragmented mol directly, round-tripping through smiles fixed the issue.
This PR properly updates the bond stereo atoms that were being removed when the bonds were cut.
=> BondStereo info lost in FragmentOnBonds()

Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/QTDemo/CMakeLists.txt, Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt
This fixes #3658 the way I suggested in the issue: by adding the Qt libraries as "private" link target to MolDraw2D and rdMolDraw2D, so that they are not propagated to other libraries linking against these two.
=> Fixes #3658

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
This implements #3667 by adding a callback function pointer to the EmbedParameters struct.  In my application the callback function queries the calling process (a Mathematica kernel) to see if a user has aborted, and if so it throws an exception and returns to top level.  This is convenient if the user asked for a 3D plot of a huge protein without realizing how long it takes to generate coordinates.
I don't know if there is an equivalent abort functionality in an interactive python session, this PR does not address the python wrappers.
If the callback function is provided, it will be called prior to calling `generateInitialCoords` in each embedding attempt, with the iteration number passed as an argument.
One could imagine extending this callback function to be called *after* …
=> Embedder callback

Code/GraphMol/MolDraw2D/Wrap/testMolDraw2DQt.py
I was looking at some internal examples, and I think that a
context manager is the idiomatic way to control lifetimes
of the QPainter and QImage.
I ran the tests and can reproduce some terrible lifetime
crashes if I don't use the context manager (and don't
use Greg's attribute trick).
=> Make the scope control for Qt more idiomatic

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/FMCS.h, Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
@driesvr has reported that lone atoms belonging to incomplete rings can still be included in MCS results also when `CompleteRingsOnly` is set to `true` (#3693).
This is a consequence of `CompleteRingsOnly` being a `BondCompareParameters` flag only.
This PR adds `CompleteRingsOnly` also to `AtomCompareParameters` (similarly to what already happens for `RingMatchesRingOnly`), thus covering the use case reported in #3693.
Note that at the moment the `AtomCompareParameters.CompleteRingsOnly` can only be set using the `findMcs(mols, params)` overload.
Calling the `findMcs` overload with `completeRingsOnly` set to `true` still only sets `BondCompareParameters.CompleteRingsOnly` to `true`. This mirrors what happened in the past for the `ringMatchesRingOnly` parameter, that originally only set …
=> Addresses #3693

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/FileParsers/SmilesMolSupplier.cpp, Code/GraphMol/FileParsers/TDTMolSupplier.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp, Code/GraphMol/Wrap/ContextManagers.h, Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp, Code/GraphMol/Wrap/MaeMolSupplier.cpp, Code/GraphMol/Wrap/PDBWriter.cpp, Code/GraphMol/Wrap/SDMolSupplier.cpp, Code/GraphMol/Wrap/SDWriter.cpp, Code/GraphMol/Wrap/SmilesMolSupplier.cpp, Code/GraphMol/Wrap/SmilesWriter.cpp, Code/GraphMol/Wrap/TDTMolSupplier.cpp, Code/GraphMol/Wrap/TDTWriter.cpp, Code/GraphMol/Wrap/rough_test.py
This fixes #3703 and #2217: MolWriters and MolSuppliers can now be used in Python `with` statements
Other changes to make this work:
- Added a `close()` method to `MolSupplier()`
- Make sure `MolWriter::close()` only calls `flush()` if the stream is still valid
=> Support context managers for mol Suppliers and Writers

Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
I was building master on Mac, and the build failed with:
```
rdkit/Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp:110:28: error: use of undeclared identifier 'MolIOEnter'
```
Apparently, this include was missing in the PR. I wonder how the CI build passed.
=> Missing include in PR #3704

Code/GraphMol/FileParsers/FileParsers.h, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.h, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/ROMol.cpp, Code/GraphMol/SubstanceGroup.h
<b>PR scope</b>
- eliminate some documentation ambiguity about the role of the `strictParsing` flag
- fix some inconsistencies between SGroup parsing function prototype declarations and implementations
- add a workaround for accepting malformed V2000 'M  SAP' entries affecting older version of MarvinJS (only if `strictParsing` is set to `false`)
- if `strictParsing` is set to `false`, malformed V2000/V3000 SGroups are ignored rather than causing the parsing to fail
- fix a couple typos in warnings
<b>PR motivation</b>
The motivation for this PR is that older versions of MarvinJS (`MJ2009`-`MJ2011`, and possibly later ones; `MJ2021` is not affected) are affected by a bug in the way the `M  SAP` entry is output.
For example, the MDL molblock generated for this molecule:
is:
```
MJ201100 …
```
=> Make better use of strictParsing for SGroups

rdkit/Chem/Draw/cairoCanvas.py
The current code checks whether the methods tostring and fromstring
exist in a PIL image object like this:
getattr(image, 'tobytes', image.tostring)
This code raises an exception when image doesn't have the tostring
method. That seems to be the case in recent pillow versions!
Check if the tostring or tobytes method exists (in this order).
This is related to #644.
=> Check PIL support for tostring and fromstring

Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py, Code/GraphMol/Fingerprints/MorganFingerprints.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp
Fixes #1761
- Changed the types of arguments radius and nBits from function MorganFingerprintHelper from int to unsigned int. 
- The C++ MorganFingerprint code now throws a ValueErrorException
- Implemented new test for control
I also checked fingeprint functions `GetAtomPairFingerprint, GetHashedAtomPairFingerprint, GetHashedAtomPairFingerprintAsBitVect, GetTopologicalTorsionFingerprint, GetHashedTopologicalTorsionFingerprint, GetHashedTopologicalTorsionFingerprintAsBitVect` and `GetMorganFingerprintBV` and changed int to unsigned int when found.
However, I have a question: 
In `rdkit/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp` in line 469 function `MorganFingerprintHelper` is called with `nBits = -1`. This variable is then used in line 382 to call either function …
=> Fixes issue 1761

Code/MinimalLib/minilib.cpp, Code/MinimalLib/tests/tests.js
As one of the goals of `MinimalLib` is enabling visualization of molecules in the browser, `strictParsing` should be set to `false` in order to avoid that malformed S groups prevent molecules from being rendered (see #3705).
=> Set strictParsing to false in MinimalLib

Code/GraphMol/Abbreviations/Wrap/testAbbreviations.py, Code/GraphMol/Wrap/Mol.cpp
Does this by adding support for std::shared_ptr<ROMol> return values in the Python wrappers.
Now that we know this is possible (and easy), it's worth considering a large-scale cleanup action to ensure that all RDKit-wrapped objects support std::shared_ptr and to come up with a plan for switching to using it instead of boost::shared_ptr in the API
=> Fixes #3692

Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp
Fixes #3702
The EnumerateLibrary destructors were not being called.
Validated with valgrind
=> Fixes Memory leak in enumerate library python wrapper

Code/GraphMol/MolOps.h
This caused me a bit of confusion looking at the comment in the header.  Looks like [this comment](https://github.com/rdkit/rdkit/pull/2872#discussion_r365465170) was missed in the pull request.
=> Fix comment to match the code in RemoveHsParameters

Code/GraphMol/FMCS/DebugTrace.h, Code/GraphMol/FMCS/Test/testFMCS.cpp, Code/GraphMol/FMCS/testFMCS_Unit.cpp
Including `Winsock2.h` has a number of advantages:
* It is much smaller than `Windows.h`, improving build time.
* It allows rdkit to be used in environments where `WIN32_LEAN_AND_MEAN` is set.
* It is [the recommended way to get `timeval`](https://docs.microsoft.com/en-us/windows/win32/api/winsock/ns-winsock-timeval) (rdkit doesn't actually use `timeGetTime`).
=> Include Winsock2.h instead of Windows.h in DebugTrace.h

Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/MolDraw2D/test1.cpp
The scoring scheme which was being used to pick which bonds to wedge had the wrong relative contributions to weights, so low-degree connections to heavy atoms were not being favored as they should have been.
=> Fixes #3216

External/CoordGen/CMakeLists.txt, External/CoordGen/CoordGen.h, External/CoordGen/Wrap/rdCoordGen.cpp, External/CoordGen/test.cpp
Coordgen's default behavior is to treat all bonds to metal atoms as zero order. In v1.4.2 an option was added to allow this behavior to be disabled.
This bumps the version of coordgen we expect from v1.4.1 to v1.4.2, allows that zero-order bond parameter to be changed, and modifies the default behavior so that bonds to metals are no longer set to zero order by default.
=> Support new coordgen option to not always make bonds to metals zero-order

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/testReaction.cpp
Fixes #3078 
This patches the Reactions code to do the right thing, as we discussed in the issue, and set stereo bonds in the reaction for which we have no stereo information to `STEREONONE`, instead of `STEREOANY`, as it was being done.
This fixes the issue with using `findPotentialStereoBonds()` on reaction products, since these won't have `STEREOANY` bonds without bond directions anymore.
=> Addresses #3078 (second try)

rdkit/Chem/Draw/IPythonConsole.py
Follow-up to #3690.
After importing IPythonConsole, regular PIL image rendering fails with:
```
FormatterWarning: Exception in image/png formatter: 'Image' object has no attribute 'text'
```
The current pillow [documentation](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.info) suggests that `text` should be replaced with `info`.
I've tested this with Google-internal colab; will run additional tests with Jupyter soon...
=> Fix pillow error in IPythonConsole.py

.azure-pipelines/mac_build_java.yml
SWIG 4.0 seems to be showing up in the MacOS CI builds, and the RDKit doesn't currently work there.
This locks SWIG at v3
=> lock swig version in MacOS CI builds

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/FileParsers/test_data/stereochem.mae
This adds a case to consider "undefined" chirality when parsing chiral labels (it just skips the label translation, as it is unknown), as well as attempts to skip to the next CT block in case parsing fails.
This also adds two new cases to the tests: one with a malformed chiral label (to trigger a parsing failure), and another one that exercises the "undefined" chiral labels.
=> Addresses issue #3815

rdkit/Chem/PandasTools.py
When loading SDF to a Pandas dataframe and discarding of molecules and retaining SMILES, the SDMolSupplier was not sanitizing the molecules before producing of SMILES. This tiny PR addresses this issue.
Additional change to improve the performance by getting property dict in one call instead of a loop over all properties.
=> Sanitize molecules when SMILES needs to be produced in PandasTools

Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h
It would be worth doing some refactoring of this code at some point and coming up with some kind of "get human readable form of a query" function, but that's a much larger task.
Here are two sample images.
Atom list:
and NOT atom list:
=> MolDraw2D: first pass at rendering atom lists

Code/GraphMol/AddHs.cpp, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp, Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp, Code/GraphMol/ForceFieldHelpers/MMFF/testMultiThread.cpp, Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp, Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/catch_graphmol.cpp
A not-infrequent source of confusion/bug reports is generating 3D conformations for molecules which don't have H atoms added.
This adds a simple test to detect if a molecule has all the explicit Hs it could have, calls that as part of the embedding code, and issues a warning when appropriate.
@ptosco : think it would be sensible to do the same thing when building the MMFF and UFF force fields? If so, I will go ahead and add it to this PR
=> Issue a warning when embedding a molecule with no Hs

Code/GraphMol/Descriptors/AUTOCORR2D.cpp, Code/GraphMol/Descriptors/testAUTOCORR2D.cpp
This was just a missing check for zero in a divisor.
Because clang-format also ran on AUTOCORR2D.cpp it looks like the changes are more extensive. The only non-formatting related change in that file is line 110
=> Fixes #3806

rdkit/Chem/Draw/UnitTestDraw.py, rdkit/Chem/Draw/__init__.py
This just disables the creation of metadata when generating the images of fingerprint bits. It doesn't make sense to be generating that partial data anyway.
=> Fixes #3796

Code/GraphMol/SmilesParse/CMakeLists.txt, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
also speeds up compiles of the SMILES catch tests by using the catch_main.cpp in GraphMol
This is a simple fix since we had the logic for writing dative bonds to SMARTS exactly backwards.
=> Fixes #3774

Code/GraphMol/MolEnumerator/LinkNode.cpp, Code/GraphMol/MolEnumerator/LinkNode.h, Code/GraphMol/MolEnumerator/MolEnumerator.cpp, Code/GraphMol/MolEnumerator/MolEnumerator.h, Code/GraphMol/MolEnumerator/PositionVariation.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp
Since earlier enumeration steps may change atom indices we need to keep a map between original atom IDs and the atoms themselves.
This is theoretically necessary for bonds as well, but we don't currently have any enumeration steps which work with bond indices.
=> Fixes #3844: MolEnumerator and link nodes

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp
The output of MolDraw2D (especially svg) can be manipulated on-the-fly to produce hilights and many other effects without the need to do full re-draw. This is especially useful for web services which can interactively update the svg within browser and save the round trip to server enabling much more responsive user experience. 
However, in order to allow atoms to be recolored bonds need to be split into per-atom fragments and tagged with atom information. This PR implements code both to split bonds and add parent atom information to svg drawing.
Bond splitting is enabled via new drawing option "splitBonds" which forces the bond rendering to be split into per atom fragments. Bond fragments are tagged with then parent atom idx. If bonds are not split the bond elements are tagged with both …
=> Facilities for interactive modification of molecule drawing

Code/GraphMol/Depictor/RDDepictor.h
A trivial one just to fix an inconsistency between header prototype and implementation prototypes.
=> Renames optional parameter that I forgot to rename previously

Code/GraphMol/AddHs.cpp, Code/GraphMol/molopstest.cpp
Closes #3854.
Having two neighbors at exactly opposite ends of a line means the dot product of their normalized vectors will be -1 (or very close). If that's the case, just take the opposite of the position vector of the 3rd neighbor.
After the change, the code in the issue prints this mol file:
```
RDKit          2D
9 10  0  0  1  0  0  0  0  0999 V2000
5.0014    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
4.1764    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
3.3514    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
2.9389    1.1271    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
3.3514    1.8412    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
4.1764    1.8412    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
4.5889    1.1271    0.0000 C   0  0  0  0  0 …
```
=> Addresses #3854

Code/GraphMol/MolDraw2D/DrawTextJS.cpp, Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/test1.cpp
This PR addresses and fixes #3852:
- `width` should not be implicitly cast to `unsigned int` (I have also fixed the same issue in a few places in the `svg` and `cairo` drawers)
- coordinates should not be rounded ahead of using them in context, as the context will do that with interpolation/antialiasing when generating the bitmap
The differences are particularly evident for the first molecule; look in particular at the carbonyl double bond and at the benzene double bonds. The connections between lines used to have a small "angle" where there was a color change, and now they don't anymore, and all bonds are now nicely parallel, as we rely on antialiasing to do the interpolation and the smoothing rather than rounding pixels to integer upfront.
Before | After
--- | ---
Before | After
--- | …
=> Fixes #3852

Code/GraphMol/FileParsers/CMakeLists.txt
=> Fix build error with static boost libraries (missing zlib)

Code/GraphMol/AddHs.cpp, Code/GraphMol/ReducedGraphs/ReducedGraphs.cpp, Code/GraphMol/ReducedGraphs/Wrap/testReducedGraphs.py, Code/GraphMol/ReducedGraphs/test1.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/molopstest.cpp, Code/RDBoost/Wrap/RDBase.cpp
Currently running the following from Python yields:
```
In [1]: from rdkit.Chem import rdReducedGraphs
...: from rdkit import Chem
...:
...: m = Chem.MolFromSmiles('OCCc1ccccc1')
...: mrg = rdReducedGraphs.GenerateMolExtendedReducedGraph(m)
...: mrg.GetAtomWithIdx(0).GetProp('_ErGAtomTypes')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-4da04832ad1a> in <module>
4 m = Chem.MolFromSmiles('OCCc1ccccc1')
5 mrg = rdReducedGraphs.GenerateMolExtendedReducedGraph(m)
----> 6 mrg.GetAtomWithIdx(0).GetProp('_ErGAtomTypes')
ValueError: key `_ErGAtomTypes` exists but does not result in unregistered C++ type
```
In fact, `_ErGAtomTypes` is a `std::list<int>` that cannot be …
=> Allow retrieving the _ErGAtomTypes property from Python

Code/GraphMol/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp
Changes the way the number of radicals is calculated for atoms where we have no preferred valence information:
Now numRadicals is just equal to the number of valence electrons %2.
=> Fixes #3330

rdkit/Chem/Draw/SimilarityMaps.py, rdkit/Chem/Draw/UnitTestSimilarityMaps.py
Allows colormaps to be provided to the similarity map code when using the C++ renderer.
Colormaps can be provided either as a list/tuple with three (r,g,b,a) (or just (r,g,b)) tuples or as a matplotlib colormap
=> Fixes #2904

Code/GraphMol/Bond.cpp, Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
The goal of this basic implementation is to start to allow work with hydrogen bonds in the RDKit.
Things which are supported:
1. Reading/writing H bonds from V3000 mol files
2. Reading H bonds from CXSmiles
3. Drawing H bonds
4. Generating 2D coordinates for molecules with H bonds (no code changes needed here)
5. Generating 3D coordinate for molecules with H bonds (see below)
Clearly we should add more functionality going forward, but I figure this is better than nothing (and it's not that much code anyway)
About the integration of H bonds into the conformer generator: the bounds matrix builder has always had the ability to deal with unknown bond types - it just picks a very wide window of possible bond lengths - the change here is just to make sure that those wide bounds are used for …
=> Add basic support for hydrogen bonds

Code/GraphMol/DistGeomHelpers/CMakeLists.txt, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
@hjuinj noticed that the ETKDGv3 macrocycle terms were not be applied when working with [6VY8](https://www.rcsb.org/structure/6VY8).
The underlying problem is that the logic we added to exclude fused rings from consideration when using small-rings terms was being incorrectly applied to macrocycles.
Here's the new logic:
- two small rings share 2 or more bonds: all bonds in both rings excluded
- small ring shares 2 or more bonds with a macrocycle: all bonds in the small ring (this includes the overlapping bonds) are excluded
- two macrocycles share 2 or more bonds: no bonds are excluded by the fused-ring logic
=> ConfGen: Macrocycle torsion terms not being used with fused macrocycles

Code/GraphMol/AddHs.cpp, Code/GraphMol/catch_graphmol.cpp
Tweaks the way that the position of the H is determined when the molecule already has coordinates
and simplifies things a bit.
Following the IUPAC guidelines, this places the H so that it bisects the largest angle:
=> Fixes 3879: bad placement of Hs with fused rings

Code/GraphMol/Abbreviations/Abbreviations.cpp, Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp, Code/GraphMol/AddHs.cpp, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/MolEnumerator/PositionVariation.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/MolStandardize/Fragment.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/ROMol.cpp, Code/GraphMol/ROMol.h, Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h, Code/GraphMol/ReducedGraphs/ReducedGraphs.cpp, Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp, Code/GraphMol/Wrap/EditableMol.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/molopstest.cpp
The idea here is to make it simpler and less error prone to remove atoms/bonds from a molecule.
In the current code if you want to remove more than one atom you need to be sure to do the removals ordered by decreasing atom index. Code needs to use a pattern like this:
```
aidsToRemove=[]
for atom in rwmol.GetAtoms():
if we_want_to_remove(atom):
aidsToRemove.append(atom.GetIdx())
for aid in sorted(aidsToRemove,reverse=True):
rwmol.RemoveAtom(aid)
```
with the new API this can be simplified to:
```
rwmol.BeginBatchEdit()
for atom in rwmol.GetAtoms():
if we_want_to_remove(atom):
rwmol.RemoveAtom(atom)
rwmol.CommitBatchEdit()
```
or, using a context manager:
```
with Chem.RWMol(mol) as rwmol:
for atom in rwmol.GetAtoms():
if we_want_to_remove(atom):
rwmol.RemoveAtom(atom)
```
Both are simpler …
=> Allow batch editing of molecules: removal only

Code/GraphMol/MolDraw2D/Qt/Wrap/CMakeLists.txt, Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt
PR #3832 caused a partial regression on #3659: despite splitting Qt-dependent code into separate instances of the drawing libraries, it reverted the MolDraw2D Python wrappers to be linked against Qt GUI libraries, which is not desired.
Also, Code/GraphMol/MolDraw2D/Qt/Wrap/CMakeLists.txt is only used if Qt support is enabled, so no need for the extra check.
=> Fix #3659 regression introduced in #3832

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
This PR fixes #3886 by ignoring the `InitialSeed` when it does not consist of a valid MCS, and issuing a warning.
Added relevant C++ test and modified existing Python tests to cope with the new behavior.
=> Fixes #3886

Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
Fixes a small warning here
```
Code/GraphMol/RGroupDecomposition/RGroupMatch.h:19:1: warning: 'RGroupMatch' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
Code/GraphMol/RGroupDecomposition/RGroupDecomp.h:72:1: note: did you mean struct here?
```
=> Change class to struct for forward declaration

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py
Example
```
m = Chem.MolFromSmiles("CNO")
m2 = Chem.MolFromSmiles("c1ccccc1")
m3 = Chem.MolFromSmiles("C1CC1")
rwmol = Chem.RWMol(m)
rwmol.InsertMol(m2)
rwmol.InsertMol(m3)
assert Chem.MolToSmiles(rwmol) == Chem.CanonSMiles("CNO.c1ccccc1.C1CC1")
```
=> Exposes InsertMol to python RWMol

Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/catch_graphmol.cpp
The problem was caused by the fact that `[N,O]` in SMARTS produces an OR query where the children are `AtomType` queries and not `AtomAtomicNum` queries.
The fix is to correctly handle `AtomType` queries in `getAtomListQueryVals()`
=> Fixes #3912

Code/cmake/Modules/FindInchi.cmake, External/AvalonTools/CMakeLists.txt
Those URLs are available as https so no reason to stick to legacy http URLs.
=> Use https for Avalon and Inchi downloads

Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
The CTAB documentation is a bit ambigious as to whether SDT lines are allowed to include empty fieldnames, but files definitely appear "in the wild" where fieldnames are empty. We can support them without problems, so it seems logical to do so.
=> support empty/missing SDT lines for SGroup data

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
In general I do like the practice of coloring bond lines to match the atoms at either end, but I find it rather distracting on wedged bonds.  For example I prefer the version on the right,
- The new option simply uses the `symbolColour` to draw the wedges, alternatively the new option could be a color itself.
- If it is kept as a boolean, perhaps the name `blackWedgeBonds` is inappropriate?  I am always keepint `symbolColour` as the default black so it works for me.
- I'm not sure I added the hook into python correctly, as I don't build the python extensions  myself (or if I do then I don't know how to use them)
- I haven't added a test.  I think a test would create an SVG on a simple molecule and test for the presence of a single triangle or three, but I have no experience with the SVG …
=> add a new mol draw option to draw wedge bonds with a single color 

Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/RGroupGa.cpp, Code/GraphMol/RGroupDecomposition/testRGroupInternals.cpp
Fixes #3746 
Fixes RGD GA hanging when running on simple systems.
The GA hangs when in cannot construct a population of different decompositions.  This PR fixes the code that determines the number of RGD permutations.  If the number of permutations is too small to create a GA population exhaustive search will be used instead.  The example in issue #3746 now runs fine:
=> RGD: fix GA delegating to exhaustive search for simple systems

Code/JavaWrappers/Bond.i, Code/JavaWrappers/GenericRDKitException.h, Code/JavaWrappers/MolEnumerator.i
This fixes building the Java wrappers on windows when `RDK_SWIG_STATIC = OFF`:
- The export for `GenericRDKitException` isn't required on windows, and does actually cause problems. We might still need it for Linux/Mac (I remember I had trouble with this when doing the visibility patch), so define it only for those platforms.
- The things I added ignores for are mentioned in Bond.h and MolEnumerator.h, but are not DLL exported, so these can't be linked to the wrapper library. Since these look like internal details, I just ignored them in the interface files, so that they don't get wrapped.
=> Fix building JavaWrappers on Windows, dynamic linking

Code/GraphMol/MolDraw2D/DrawText.h, Code/GraphMol/MolDraw2D/DrawTextFT.h, Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h
Enabling Qt support breaks the windows build: since we split off support to a separate library, some of the components of MolDraw2D now need to be exported, so that they can be used from MolDraw2DQt. Also, the export macro for `MolDraw2DQt` is wrong (in the CMakeLists file relevant to the Qt directory we define `RDKIT_MOLDRAW2DQT_BUILD`, but not `RDKIT_MOLDRAW2D_BUILD`)
=> Fix MolDraw2DQt exports

Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/RGroupScore.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
- remove temp labels from RGD results
- remove a debug printout in non-debug builds
=> Remove temporary labels from RGD results

Code/GraphMol/RGroupDecomposition/RGroupScore.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupInternals.cpp
The scoring function was not taking into account empty rgroups which biased certain arrangements of rgroups that didn't have an rgroup at every position.
@ptosco @jones-gareth  @greglandrum This resolves #3924 and mercifully doesn't fail any of the existing regression tests!
=> Fixes #3924

Code/GraphMol/Fingerprints/MHFP.cpp, Code/GraphMol/Fingerprints/MHFP.h, Code/GraphMol/Fingerprints/Wrap/MHFPWrapper.cpp, Code/GraphMol/Fingerprints/Wrap/testMHFP.py, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, ReleaseNotes.md
There's more detail in the discussion of #2788, but the short form is that we now explicitly kekulize molecules in the SMILES writing code if asked to generate Kekule SMILES.
Fixing this also exposed #3942, so I fix that in this PR as well.
=> Fixes #2788: kekuleSmiles=true not producing kekule SMILES

Code/GraphMol/MolInterchange/Writer.cpp
If the property fails to stringify then just don't write the property to json rather than throwing an exception.
=> fixes #3956

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_chirality.cpp, Docs/Book/RDKit_Book.rst
This is a followup from #3632
This deviates from the idea of directly following the InChI recommendations, but I think it makes sense to allow these structures to be chiral:
FWIW: this is what the RDKit did up until #3632 was merged
=> Allow three-coordinate bridgehead N to be chiral.

Code/GraphMol/Chirality.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/catch_graphmol.cpp
The simple definition of bridgehead stereo used in #3958 is a bit too simple.
We required three bonds which are each in at least two rings, but this doesn't work for things like this:
where only two rings are found.
This PR adds a new query operation with (I think) a more reasonable definition of what a bridgehead atom is:
```
// at least three ring bonds, at least one ring bond in a ring which shares at
// least two bonds with another ring involving this atom
```
=> Fix definition of bridgehead stereo

Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h
Simple fix to use `reset()` instead of `release()`
Thanks to @rvianello for pointing this out.
=> RWMol should reset(), not release(), dp_delAtoms and dp_delBonds

Code/GraphMol/RGroupDecomposition/RGroupCore.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/RGroupScore.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, ReleaseNotes.md
- use a `boost::dynamic_bitset` rather than a `std::set` for lookups
I replaced a `std::set` which was being used for lookups with a `dynamic_bitset` as it is more efficient. We consistently use `dynamic_bitset` for this purpose all over the RGD code, but apparently we missed this one.
- do not add unnecessary R-labels
While testing the RGD code on some internal datasets I ran into two cases that I believe were yielding suboptimal results when `onlyMatchAtRGroups=false`, because unnecessary R labels were being dynamically added.
Both are addressed by the new `testDoNotAddUnnecessaryRLabels()` and I will illustrate them below.
1. There is a single core
while the molecules are
Before this PR, the code would not make a difference between assigning a H substituent vs a heavy atom substituent …
=> Do not add unnecessary R-labels (and an optimization)

External/CoordGen/CMakeLists.txt
This is pretty urgent, because it includes a fix for a 10X
performance regression in coordgen that happened
in the 2.0.0 release
(https://github.com/schrodinger/coordgenlibs/pull/90).
It also fixes coordinate generation for 2.2.2 bicyclic systems
(https://github.com/schrodinger/coordgenlibs/pull/87)
I think that this should be included in any patch for the 
2021.03 release.
=> Update coordgen to 2.0.3

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/catch_graphmol.cpp
`RWMol::replaceAtom()` and `RWMol::replaceBond()` can both leave dangling pointers in the bookmarks vectors.
This clears that up.
This fix also should clear at least the following OSSFuzz issues:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27315
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25906
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24406
Additionally some leaks in the tests in catch_graphmol.cpp have been fixed.
I also added a couple of other small fixes connected with issues discovered by OSSFuzz:
- bogus input character referenced in error reporting in the MolFileParser
- additional defensive programming around possible malicious input to the deserialization code
- correctly fail when parsing maliciously constructed SMARTS input
=> A set of fixes for problems caused by bad input

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp, Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp, Code/GraphMol/molopstest.cpp
Fix some problems found when building with `-fsanitize-address` on linux
This is one where it's worth reviewing at the indivdual commits:
- The first two are memory leaks when exceptions are thrown (not a big deal, but still...)
- The third is a legit multi-threading bug in the SubstructLibrary
- The last one is just fixing leaks in the tests.
=> Cleanup some problems found during an ASAN build

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/Wrap/testFMCS.py, Code/GraphMol/FMCS/testFMCS_Unit.cpp
While looking at some of the test cases in #4019 I have noticed that currently the MCS does not do what is expected in this case:
```
mol1 = Chem.MolFromSmiles("C1CCCC1C")
mol2 = Chem.MolFromSmiles("C1CCCC1C1CCCCC1")
MolsToGridImage((mol1, mol2))
```
```
ps = rdFMCS.MCSParameters()
ps.AtomCompareParameters.CompleteRingsOnly = True
ps.timeout = 300
res = rdFMCS.FindMCS((mol1, mol2), ps)
res.queryMol
```
As `AtomCompareParameters.CompleteRingsOnly` was set to `True`, atom 5 should not be part of the MCS, as we have requested that only atoms which are part of a complete ring are included, and this is not the case.
The reason why this happens is that in #3695, when I implemented the `AtomCompareParameters.CompleteRingsOnly` parameter (in addition to the already existing …
=> Avoid that lone atoms which are part of a ring in one of the molecules become part of the MCS

Code/GraphMol/FileParsers/CMLWriter.cpp, Code/GraphMol/FileParsers/CMakeLists.txt, Code/GraphMol/FileParsers/FileParsers.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py, Code/JavaWrappers/ROMol.i
Support Chemical Markup Language, CML, for writing
http://www.xml-cml.org/
CML is an XML variant and thus machine-friendly.
Example:
```python
mol = """acrylonitrile
7  6  0  0  0  0  0  0  0  0999 V2000
-0.6992   -1.1405    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
1.5210    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
2.7820    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
-1.7845   -1.1255    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
-0.2103   -2.1109    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
-0.4773    0.9730    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
1  2  2  3
1  5  1  0
1  6  1  0
2  3  1  0
2  7  1  0
3  4  3  0
M  ISO  1   7   2
M  END
"""
m = …
```
=> Support Chemical Markup Language, CML, for writing

Code/MinimalLib/docker/Dockerfile
The boost libraries are no longer available from bintray, so grab them from the new location.
=> Update boost download location in Dockerfile

Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp
switch to using `std::unique_ptr` in `get_mol()` and `get_qmol()`
also clears up some leaked memory in the C test so that it can be run in valgrind
=> Fixes #4102

rdkit/Chem/Draw/UnitTestDraw.py, rdkit/Chem/Draw/qtCanvas.py
Fixes #4105
This pull request adds `PySide2` to the list of Qt/Python backend supported by `MolToQPixmap`. As `PyQt5` is already supported, support for `PySide2` can be easily extended. `PySide2` is added at the end so that the existing precedence is unchanged. Furthermore, it seems more logical to try Qt4 -> Qt5 backends instead of trying PySideN packages -> PyQtN packages and crisscrossing Qt versions in doing that.
Comments:
I could not work out how the `testQtImage` test is exercised on continuous integration. Should there be changes to how CI dependencies are set up, e.g. to add PySide2 as an installed package?
This does change the ImportError message. Previously if nothing can be found, the error message complains about PyQt5 (without mentioning having tried PySide). Now the error …
=> Allow MolToQPixmap to support PySide2

Code/MinimalLib/cffi_test.c, Code/MinimalLib/common.h
The change here is simple: catch all exceptions when processing user-provided input so that we always just return nullptr in those cases.
=> handle bad input more gracefully in the minimallib

Contrib/FreeWilson/README.md, Contrib/FreeWilson/freewilson.py, Contrib/FreeWilson/test/test_freewilson.py
This fixes an issue when using multiple scaffolds and predictions_to_csv.
The issue was later compounds adding rgroups were not setting the header correctly and throwing an exception because there was no csv column assigned.
The solution is to sent in the full decomposition which has all the column data.
(Also I added the missing chembl tests)
=> FreeWilson: change predictions_to_csv API to cover multi scaffolds

azure-pipelines.yml
These are failing and I'm not convinced that there's value in continuing to do them here anyway.
Autofuzz is still running against the code base, so we still have fuzzer coverage
=> disable the fuzzer CI builds

Code/GraphMol/Substruct/CMakeLists.txt, Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/Wrap/rough_test.py
adds a short-circuit test to the substructure matching so that it immediately returns an empty result set if either the molecule or the query is empty
=> Fixes #4138

Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/ReactionPickler.cpp, Code/GraphMol/ChemReactions/Wrap/testSanitize.py, Code/GraphMol/ChemReactions/testReaction.cpp
The `ChemicalReaction` copy constructor and the `ReactionPickler` `_depickler ` create `ROMol`s, while `constructMolFromString` creates `RWMol`s which are then cast to `ROMol`s. This is why the `dynamic_cast` performed by `RxnOps::sanitizeRxn` failed with the copy constructor and the depickler, while it succeeded on the reaction created directly from SMARTS.
This PR sets the copy constructor and the depickler to create `RWMol`s and adds relevant C++ and Python tests.
=> Fixes #4162

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestChem.py
Fixing this sensibly requires exposing the "new" `includeRings` argument to `clearComputedProps()` to Python, but we should have done that already anyway.
=> Fixes #4144

Code/GraphMol/Conformer.h, Code/GraphMol/catch_graphmol.cpp
adds a check for the possible overflow in `Conformer::setAtomPos()` and throws a ValueError on overflow.
Maybe it should be a PRECONDITION instead to be consistent? Seems like a ValueError though.
=> fixes #4128

Code/GraphMol/MolDraw2D/Qt/Wrap/rdMolDraw2DQt.cpp
On 64-bit windows, I noticed that the value of `ptr`/`pointer_to_QPainter` can exceed the maximum `unsigned long int` value. In some cases, this caused an OverflowError when using `MolDraw2DFromQPainter` to make a PNG. I think that changing the `ptr` type to `size_t` should prevent this issue on all platforms, but there might be a better approach.
Here is the traceback I was getting:
```
drawer = MolDraw2DFromQPainter(cpp_qp, options.width, options.height)
...\rdkit\Chem\Draw\__init__.py:177: in MolDraw2DFromQPainter
d2d = rdMolDraw2DQt.MolDraw2DFromQPainter_(width, height, ptr, panelWidth, panelWidth)
E   OverflowError: Python int too large to convert to C unsigned long
--------------------- Captured stdout call -----------------------------
QPainter address: <PyQt5.QtGui.QPainter object …
```
=> Fix python to C++ pointer conversion issue in moldrawFromQPainter

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes #4156
The scaling was being incorrectly calculated when drawing radical molecules in a grid.  Fixed with test case.
The radical positioning depends on the text drawer fontScale, and that wasn't being reset at the start of each molecule's scale calculation.
=> Fix incorrect scaling in grid drawing with radicals.

Code/GraphMol/MolDraw2D/test1.cpp
The tests added in #4163 assumed freetype is installed and required coordinate matching to multiple decimal places.
This fixes the first of those and makes the matching laxer
=> make a test more permissive

Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h
- remove d_partialBonds private data member - never used in any code
- remove RWMol::destroy()  - redundant with ROMol::destroy()
There was a bit of discussion of this connected with #4171, and it turned out that the required changes were easy
=> RWMol cleanup

.gitignore, Code/GraphMol/Canon.cpp, Code/GraphMol/SmilesParse/test.cpp
Reference Issue
fixes #3967
What does this implement/fix? Explain your changes.
Seems like the two reported smiles issues are caused by two different bugs.
For "C=c1s/c2n(c1=O)CCCCCCC\\N=2" the bug seems like it's cause by the ring closure happening on the double bond. This condition is checked on line 384 in Canon.cpp
I struggled quite a bit figuring out exactly why "C1=C\\C/C=C2C3=C/C/C=C\\C=C/C\\3C\\2\\C=C/1" isn't working. It seems like it's a similar issue to the first one, but only because "secondFromAtom1" is not aromatic and is closing the ring. The condition for checking this is on lines 385-387 in Canon.cpp
I wanted to refactor this line into an inline function since it is use many times, but I didn't want to make this PR too big.
atom2Dir = (atom2Dir == Bond::ENDUPRIGHT) ? …
=> fixes #3967

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/testReaction.cpp
This closes #4114 
Besides the bond properties, also EITHERDOUBLE Bond Dir was not being copied over to reaction products.
This enables copying bond properties and EITHERDOUBLE for reactant bonds that are not specified in the product template, or are specified in the product template as "Null Bond".
=> Fixes #4114

Code/GraphMol/SubstanceGroup.h, Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/RDBoost/Wrap.h
Currently, we only have infrastructure in place to update Substance Group atoms and bonds in a one-by-one basis. This adds some low level functions to allow bulk updates to them.
These functions are not safe, and should be used carefully, since passing the wrong data to Substance Groups might invalidate them as well as the owning mol. Also, these don't update any other Substance Group features, like attachment points or c-states. Still, they are the base to implement further code to update Substance Groups to accommodate operations like splitting fragments or running reactions on molecules.
=> Add low level functions to bulk-update Substance Group atoms & bonds

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Allows a couple of additional problems with v3000 mol files to be ignored when strictParsing=false:
- missing SGroup section
- mssing END SGROUP
- missing BEGIN/END OBJ3D (no tests for this, but we don't have any tests for OBJ3D anyway)
Additionally: if there aren't enough SGroups we'll now generate an error unless strictParsing is false
=> allow more recoverable V3000 parsing errors when strictParsing=false

Code/GraphMol/RGroupDecomposition/RGroupCore.cpp
=> Fix memory leak with deleting array

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp
This fixes #4222. Just as suspected, a call to `updatePropertyCache()` requiring strict valences.
=> Fixes #4222

Code/Geometry/point.h, Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Previously the code was incorrectly actually assigning stereo in these cases
This also adds a small speedup for `Point3D::angleTo()`
Thanks to Roger Sayle for the patch
=> double bonds now have EITHER stereo if no coordinates are present

Code/GraphMol/Wrap/Trajectory.cpp
Description: Shift `Trajectory` and `Snapshot` class constructors to methods on the classes themselves to prevent shadowing of class names in the Python wrapper module
Discussion https://github.com/rdkit/rdkit/discussions/4053
- The `rdkit.Chem.rdtrajectory.Trajectory` and `rdkit.Chem.rdtrajectory.Snapshot` classes were originally shadowed by identically-named functions acting as constructors in the Python wrapper module `rdkit.Chem.rdtrajectory`
- This PR shifts the class constructors to methods on the classes themselves, removing the identically-named functions acting as constructors
- It is also expected that, after the un-shadowing, the documentation at https://www.rdkit.org/docs/source/rdkit.Chem.rdtrajectory.html will be populated with the classes …
=> Shift `Trajectory` and `Snapshot` constructors to methods on classes

Code/GraphMol/Chirality.cpp, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
Fixes #3759
See also: #2890 #3015
This fixes an issue where `EnumerateStereoisomers` raises a Pre-condition Violation due to missing stereo atoms for a double bond with `EITHERDOUBLE` direction set. This typically happens with input from a MOLfile with an explicit "either" cis/trans double bond.
Here's a simple example. (Note the bond stereo value `3` in first bond line.)
```python
from rdkit.Chem import AllChem
mb = """
Marvin  08270811582D          
4  3  0  0  0  0            999 V2000
-2.5929    1.4143    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.7679    1.4143    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.3554    2.1288    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-3.0054    0.6998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
1  2  2  3  0 …
```
=> Fix EnumerateStereoisomers for EITHERDOUBLE cis/trans bonds

Code/RDGeneral/RDValue-taggedunion.h, Code/RDGeneral/testRDValue.cpp
Two issues were found in rdvalue_cast functions:
- casting to uint16_t was actually casting to uint8_t
- casting to uint8_t was casting from the unsigned value of the union, if the value was typed as signed
There was two issues in the tests as well, which is why the above issues were not caught. In addition, conversions of all min/max numeric limits of the smaller types i.e. (u)int8/16 are now explicitly tested.
This cleans up changes made in #4194
=> Fixes to integer conversions and their tests

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Passes the `strictParsing` argument further down the parsing stack and catches this case.
Fixing this makes me realize that there's a "nice opportunity" to be better about identifying/working around bad input bits in the V3000 atom parsing. But that's for an enhancement PR
=> Fixes #4256

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h, Code/GraphMol/Wrap/Mol.cpp
The MDL v2000 format does not have native support for coordinate bonds, so these are typically encoded as "query" bonds (type "8") and adding a data Substance Group with the field name "MRV_COORDINATE_BOND_TYPE" and the coordinate atom as data.
When RDKit finds one of those, it takes it literally and adds a `QueryBond` and a Substance Group to the mol. This patch fixes this behavior, turning the `QueryBond` into a regular dative `Bond` and dropping the Substance Group.
I think we could remove the call to `removeSubstanceGroupsReferencingBond()` from `replaceBond()` (the bond gets replaced, not removed, and we can always remove the Substance Group manually), but I chose the conservative approach, and made it optional by adding an extra argument to the function.
=> Turn MRV_COORDINATE_BOND_TYPE data Substance Groups into coordinate bonds

Code/GraphMol/Atom.cpp, Code/GraphMol/Bond.cpp, Code/GraphMol/Bond.h, Code/GraphMol/QueryBond.cpp, Code/GraphMol/QueryBond.h, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/querytest.cpp
- adds getValenceContrib() to QueryBond
- adds hasBondTypeQuery() and hasComplexBondTypeQuery() to QueryOps namespace
- atoms with complex bond type queries now have explict and implicit valences of 0
- adds tests for the above
- some duplicated code removal in Bond.cpp
=> Fixes github #4311

Code/GraphMol/RGroupDecomposition/RGroupCore.cpp, Code/GraphMol/RGroupDecomposition/RGroupCore.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
Since the RGD code uses substructure matching to do most of its work, it makes sense to allow some control over how that matching is done. This PR adds an additional `SubstructMatchParameters` member to `RGroupDecompositionParameters`.
I still need to add the code to expose this to Python and a few tests for that, so I'm going to mark this as a draft until I've added that.
=> Support using SubstructMatchParameters in RGD

Code/GraphMol/Atom.cpp, Code/GraphMol/Bond.cpp, Code/GraphMol/Bond.h, Code/GraphMol/QueryBond.cpp, Code/GraphMol/QueryBond.h, Code/GraphMol/QueryOps.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/RGroupDecomposition/RGroupCore.cpp, Code/GraphMol/RGroupDecomposition/RGroupCore.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp, Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/querytest.cpp
Today I have built the RDKit with GCC 9.3.0 on a machine with 40 CPU cores and I had a failure in `testCrambin` (`Code/GraphMol/Wrap/rough_test.py`). Upon investigation this turned out to be caused by the algorithm that only keeps unique substructure matches not being deterministic, and hence liable to returning different matches depending on the substructure match concurrency.
This PR implements a robust solution, which I believe is also more elegant and computationally efficient compared to the one that was in place before.
Now match uniquification always returns the match vector with indices in the minimum sorted order across all the possible permutations. I have adjusted `testCrambin` results accordingly.
I am surprised that the test has not failed before.
=> Make sure that ResonanceMolSupplier substructure matches are uniquified consistently

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Small PR to expose and test `atomColourPalette` as one of the `drawOptions` that can be set from JSON.
=> Expose atomColourPalette as JSON drawOption

Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
This PR addressed #4329 by implementing `get_morgan_fp_as_uint8array()`, which returns the Morgan bit vector to JS as a more useful `Uint8Array`.
=> Addresses #4329

External/AvalonTools/AvalonTools.cpp, External/AvalonTools/CMakeLists.txt, External/AvalonTools/test1.cpp
The problem was caused by the avalon toolkit's (potential) addition of hydrogens and atom renumbering.
The fix for #4075 introduced in #4079 wasn't particularly robust.
When the number of atoms returned by the avalon code is larger than what we started with, or in cases where the input molecule already has Hs, this does an explicit substructure match between the mol returned from the avalon code and the input molecule rather than using heuristics.
=> Fixes #4330

CMakeLists.txt, Code/GraphMol/FMCS/Test/testFMCS.cpp, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Code/GraphMol/FileParsers/GeneralFileReader.h, Code/GraphMol/FileParsers/MolSGroupParsing.h, Code/RDGeneral/RDExportMacros.h, Code/cmake/Modules/RDKitUtils.cmake
- fixes MinGW build. Some pre-processor directives were (relatively) recently
changed and caused the MinGW build to break. This PR fixes the problem
- make sure that supplier `istream` is opened in binary mode or `istream::tellg()` will
report wrong offsets on MinGW builds (MSVC will make no difference) and cause
`SmilesMolSupplier` read faillures
- avoid that in MSVC conda DLL builds the `libboost_*.lib` static
libraries are picked by `cmake` instead of the `boost_*.lib` import libraries
as they live in the same directory by defining `BOOST_ALL_DYN_LINK`
I have noticed this in a Python 3.9 build against the latest Boost 1.73
available in conda.
You may ignore the huge diff in the two FMCS tests; they are due to having applied `clang-format`. The only relevant change in each of the files …
=> Two MinGW build fixes and one MSVC build fix

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmartsWrite.h, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParse.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py, Docs/Book/RDKit_Book.rst
Parse/write CXSMILES extensions as part of dealing with SMARTS.
As far as I can tell from the CXSMILES/CXSMARTS documentation the extensions (the CX part) are the same for both SMILES and SMARTS.
=> Fixes #4319: allow CXSMILES extensions for SMARTS

Code/GraphMol/FileParsers/MolSGroupWriting.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
The current SGroup writer is correct and efficient in terms of the number of output lines that it uses, but the output can be fairly ugly since it unnecessarily breaks elements across multiple lines.
Here's an example output from the current master:
```
query
RDKit          2D
0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 2 1 1 0 0
M  V30 BEGIN ATOM
M  V30 1 C 3.541700 -5.875000 0.000000 0
M  V30 2 C 4.875300 -5.105000 0.000000 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 1 1 2
M  V30 END BOND
M  V30 BEGIN SGROUP
M  V30 1 DAT 0 ATOMS=(1 2) FIELDDISP="    4.8753   -5.1050    DA    ALL  0     -
M  V30   0" QUERYTYPE=SMARTSQ QUERYOP== FIELDDATA="[#6;R]"
M  V30 END SGROUP
M  V30 END CTAB
M  END
```
And with this PR:
```
query
RDKit          2D
0  0  0  0  0  0  0  0  0 …
```
=> Improved sgroup output

Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
We didn't have code which handled the possibility that there'd be a trans bond in a ring. :-(
=> Fixes #4346 : trans bonds are now properly honored in macrocycles

Code/GraphMol/ChemTransforms/MolFragmenter.h, Code/GraphMol/MolHash/nmmolhash.h, Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.h
This is not necessary and raises annoying warnings during compilation.
=> Removed spurious dllexport on enums

Code/GraphMol/MolEnumerator/PositionVariation.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp
Add code to allow either end of the attachment bond to be the atom which gets replicated.
Here's the logic:
```
// marvin sketch seems to place the position-variation dummy at the
// beginning of the bond, so we're going to favor taking the end atom.
// In case other tools construct this differently, we have an
// exception to that if the end atom is an AtomNull query and the
// beginning atom is not one.
```
Add code to fix H count on aromatic heteroatoms which are being modified as part of the enumeration
=> Fixes #4382 and #4381: two Enumeration related bugs

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
It ended up making more sense to just add a parser/writer for the data blocks than to add code to skip them on parsing.
This is intentionally ignoring coordinates associated with the data blocks, but I haven't actually seen any of those in the wild yet and we are unlikely to do anything sensible with them anyway.
=> Fixes: #4233  Handling of SGroup data blocks in CXSMILES

Code/JavaWrappers/GenericRDKitException.h, Code/JavaWrappers/gmwrapper/CMakeLists.txt
I have recently submitted a PR to enable building C# wrappers with MinGW compilers.
This PR enables building Java wrappers with MinGW compilers.
=> Enable building Java wrappers with MinGW compilers

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h, Docs/Book/RDKit_Book.rst
This is a another collection of improvements to reading/writing of CXSMILES, along with a couple of other small connected changes. Since the "CXSMARTS" support uses the same code as CXSMILES this affects that as well.
Changes here:
- generating SMILES or SMARTS for a molecule will now add a property `_smilesBondOutputOrder` which includes the order in which the molecule's bonds were written to the SMILES or SMARTS. This is directly analagous to the `_smilesAtomOutputOrder` property, which has been around forever.
- Polymer SGroups can now be read from/written to CXSMILES. (This also fixes a bug where they caused the CXSMILES parser to fail)
- SGroup hierarchy can now be read from/written to CXSMILES. (This also fixes a bug where this caused the CXSMILES parser to fail)
- Link nodes can …
=> CXSMILES improvements

Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogUtils.cpp, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.cpp, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.h
This fixes a few memory leaks identified by running the C++ tests in an ASAN build
=> clean up some leaks identified by an ASAN build

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/testReaction.cpp
Fixes #4410
A simple fix for a silly mistake: in the reaction code, the part that calculates stereochemistry from product bond directions did not consider the possibility of reversed bonds, which effectively "flips" the direction.
This had been hidden from some time, until the stereo refactoring in 19bdd21de1c90f01f630b28ff72b3af9176d886f started recalculating bond directions even for bonds that already had them.
=> Fixes #4410

Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/Wrap/rdmolfiles.cpp
Fixes a test failure on Windows due to a `CXSmilesFields` `enum` value overflowing the max `int32` limit.
The problem does not show up on other platforms as the `enum` casting done by the compiler is implementation-dependent.
According to the standard, unscoped enums are implicitly converted to `int` (https://docs.microsoft.com/en-us/cpp/cpp/enumerations-cpp?view=msvc-160), so a value exceeding the maximum `int32` integer will be converted to a negative value, which is exactly what happens with the `CX_ALL` `enum` value which is converted to `-1` causing one of the Python tests to fail:
```
2021-08-19T14:53:05.5899376Z ERROR: testCXSmilesOptions (__main__.TestCase)
2021-08-19T14:53:05.5900940Z ---------------------------------------------------------------------- …
```
=> Fixes a test failure on Windows

Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp, Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/Deprotect/Wrap/DeprotectWrap.cpp, Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp, Code/GraphMol/MolChemicalFeatures/Wrap/rdMolChemicalFeatures.cpp, Code/GraphMol/MolDraw2D/Qt/Wrap/rdMolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp, Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp, Code/GraphMol/TautomerQuery/Wrap/rdTautomerQuery.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/RDBoost/Wrap.h, External/FreeSASA/Wrap/rdFreeSASA.cpp
Closes #4425 
It took me a while to find the converters responsible of triggering the warnings. And while looking for them, I made some refactoring:
- added a templated function to Wrap.h that makes the check to see if a converter for a specific type has already been set up.
- added a check based on this function to `RegisterVectorConverter()`
- also added checks to other converter registrations for types that look like generic enough as to be potentially used somewhere else.
- Replaced several definitions of converters for vectors of different types with `RegisterVectorConverter()`, to benefit for the check and reduce redundant code.
- remove some unused boost::python headers.
And I think that's all I did. The rest is clang-format getting over excited about code that apparently hasn't …
=> Addresses #4425

Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/Wrap/testSGroups.py, Code/GraphMol/catch_sgroups.cpp
Closes #4434.
A simple fix (add the property when we find the group definition), and a simple test to check that the "index" property is present (both in v2000 and v3000) and has a value matching the expected index of the group.
=> Addresses #4434

Code/GraphMol/Abbreviations/Abbreviations.cpp, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/Descriptors/GETAWAY.cpp, Code/GraphMol/MolStandardize/Metal.cpp, Code/GraphMol/StereoGroup.cpp, Code/GraphMol/SubstanceGroup.cpp
Relatively small set of changes to try and ensure lambdas are being used cleanly and efficiently.
1. For lambdas being used locally: capture things which are cheap to copy and which the lambda doesn't need to change by value, Capture others by reference
2. Get rid of default captures which aren't needed
=> cleanup the use of lambdas in the code

Code/cmake/Modules/RDKitUtils.cmake
Fixes #4449 
Currently, we use a list of hardcoded patterns to distinguish which link dependencies shouldn't get the "_static" suffix added. This list doesn't contain any patterns matching maeparser or coordgen. The simplest solution would be to add them, but I think we can do better than this.
In my changes, I replace this mechanism with a different check: if a link dependency is an explicit file path or a target imported from a CMake package (`find_package()` sets the `IMPORTED` property to `TRUE`), then we use it as is. In any other case, we add the "_static" suffix.
The more intuitive approach, which is checking whether RDKit created the target is not possible: we do not create the targets in sequence, so that when we specify link dependencies we might not yet have defined the targets …
=> Addresses #4449

Code/GraphMol/FileParsers/MolSGroupWriting.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #4471
Just make sure continuation lines start with a space. We know the first line will start with a space because we always add one before each tag.
=> Fixes #4471

Code/GraphMol/FileParsers/MolSGroupWriting.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #4477.
The problem happens when we add a line to out buffer that is exactly 71 characters long, and then some others that are empty (as happens for properties that the SGroup doesn't have).
The 71-char line causes anything in the buffer to be flushed (the flushing threshold is at 78 chars, and the prefix is already 7 chars long). Then, the 71 char line is not long enough to be split into 2 lines, so the buffer becomes exactly 78 chars long (prefix + 71-char line), which is enough to be flushed the next time we add something.
But the next thing we add is an empty string: this flushes the buffer, but since `start == length == 0`, `currentLine` doesn't get updated, so the next time we add another line, the same buffer will be flushed again.
The easiest way to fix this is not doing …
=> Fixes #4477

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #4473 
Allow MRV_COORDINATE_BOND_TYPE Sgroups to reference bond indexes. This is not the ideal situation, since we don't have an explicit indication of which atom is the coordinate one, and we have to assume it is the one at the end of the bond.
=> Fixes #4473

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/FileParsers/catch_main.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/testSGroups.py, Code/GraphMol/testSGroup.cpp, ReleaseNotes.md
Changes here:
- #4468: support reading SMARTS queries on atoms from SGroups in V2000 and V3000 mol blocks. These are indicated using   `QUERYTYPE=SMARTSQ` or `QUERYTYPE=SQ`.
- #4476: read Data SGroup (i.e. SDT) properties from V2000 mol blocks even if the FIELDNAME is empty
- Changes the behavior of `RWMol.replaceAtom()` to not remove SubstanceGroups involving the changed atom. This isn't necessary and doesn't really make sense.
=> Fixes #4468 and #4476

Code/DataStructs/Wrap/SparseIntVect.cpp, Code/DataStructs/Wrap/testBV.py, Code/DataStructs/Wrap/testSparseIntVect.py, Code/DataStructs/Wrap/wrap_ExplicitBV.cpp, Code/DataStructs/Wrap/wrap_SparseBV.cpp
Adds ToList methods to SparseIntVector and ExplicitBitVector
```
bv.ToList()
```
Is about 30x faster than
```
list(bv)
```
=> Add ToList method to Sparse/ExplicitBitVector

Code/GraphMol/Chirality.cpp, Code/GraphMol/testChirality.cpp
Fixes #4494
This change allows us to keep the STEREOANY/EITHERDOUBLE until we force a stereo calculation from scratch.
We need to check both double and aromatic bonds since after sanitization rings may be aromatized.
=> Fixes #4494

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/MaximumCommonSubgraph.h, Code/GraphMol/FMCS/testFMCS_Unit.cpp
Fixes #4498
Addresses the issue by remembering which ones of the input mols were initialized with bogus ring info, and resets them at cleanup.
=> Fixes #4498

Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py
Fixes #4514
This just exposes the `ClearProp` method in Python.
=> Fixes #4514

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/catch_main.cpp
This modifies the SGroup data drawing code to recognize the situation where the coordinates are zero and the position is specified relative to the atom. In these cases the usual "pick the best spot you can find" code is now used.
=> Fixes #4508

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParse.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Wrap/rough_test.py, Docs/Book/RDKit_Book.rst, ReleaseNotes.md
The major change here is to change the default parameters for the SMILES and SMARTS parsers to parse molecule names by default.
This shouldn't break any existing code unless someone has written code which depends on SMILES including whitespace being parsed without having a `_Name` property set, but that seems unlikely.
Regardless, this is flagged as a backwards-incompatible change.
There's also a bit of refactoring in there.
=> Fixes #4503

Code/GraphMol/Kekulize.cpp, Code/GraphMol/catch_graphmol.cpp
Modifies the sanitization code so that `O=n1ccccc1` can be kekulized. This will only happen if the other sanitization options are set up so that neither the cleanup nor the valence-check steps happen.
It seems reasonable that the kekulization code doesn't need to continue to enforce valence constraints; those should be (and are) done elsewhere.
The idea and patch are from Roger Sayle
=> be more tolerant when kekulizing

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
simple fix: we were trying to avoid having to copy the input molecule in `setupDrawMolecule()`, but there's really no way around that if the method is returning an `std::unique_ptr`.
=> Fixes #4538

Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
This small PR exposes `get_smarts()` functionality to JS. This is very hand, for example, to convert MDL queries to SMARTS strings.
=> Expose get_smarts to JS

rdkit/Chem/Draw/IPythonConsole.py, rdkit/Chem/Draw/UnitTestIPython.py
The changes here:
1. The molecules in a `MolBundle` are now rendered as a molecule grid
2. If molecules have non-private, non-computed properties, they will be displayed with the molecule in the notebook. To do this the molecule+properties are rendered in a small HTML table
Example MolBundle rendering:
Example molecule + property rendering:
=> Additions to the jupyter integration

Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/Substruct/vf2.hpp
Closes #4558
I was debugging the issue when I noticed the value of `NULL_NODE` was weird: being a `uint32_t`, setting a value of 32767 felt weird, especially since `NULL_NODE` is involved in some checks as in `IsFeasiblePair()` and the value 32767 is not too high and can easily be reached in cases as the one in the description.
Updating the value to its maximum capacity (`0xFFFFFFFF`) did actually solve the issue, and the script presented in the case now prints the following:
```
num atoms: 84525
56350
indexes: [0]
deltas : []
all equal: True
indexes: [1]
deltas : []
all equal: True
indexes: [2]
deltas : []
all equal: True
indexes: [3]
deltas : []
all equal: True
indexes: [4]
deltas : []
all equal: True
indexes: [5]
deltas : []
all equal: True
indexes: [6]
deltas : []
all equal: True …
```
=> Fixes #4558

Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/TautomerQuery/TautomerQuery.cpp
~This leverages `std::lower_bound()` and sorting to reduce the number of searches to determine duplicates, and `std::list` and `std::list::insert()`  to reduce the number of vector reallocations to improve performance. It also use `std::move()` to avoid copies, although this seems to have a smaller effect.~
The result of these changes is that the my test script for issue #4558 (56350 matches in total, half of them, 28175, are unique) went from taking ~4 minutes to uniquify results, all  the way down to 15 seconds.
I haven't tested the Tautomer one, I just copied over the changes from the one for Substructure matching.
=> Improve performance of removing substruct/tautomer duplicates

Code/GraphMol/QueryOps.h
This fixes these annoying warnings I've been seeing for some time when using clang 12 to build a project that uses rdkit:
```
In file included from ../../../rdkit/include/rdkit/GraphMol/QueryAtom.h:16:
../../../rdkit/include/rdkit/GraphMol/QueryOps.h:87:20: warning: loop variable 'nbri' is always a copy because the range of type 
'iterator_range<typename range_iterator<const pair<adjacency_iterator<adjacency_list<vecS, vecS, undirectedS, Atom *, Bond *, 
no_property, listS>, unsigned long, out_edge_iter<__wrap_iter<stored_edge_iter<unsigned long, __list_iterator<list_edge<unsigned 
long, Bond *>, void *>, Bond *> *>, unsigned long, edge_desc_impl<undirected_tag, unsigned long>, long>, long>, adjacency_iterator<
adjacency_list<vecS, vecS, undirectedS, Atom *, Bond *, no_property, listS>, …
```
=> Fixes a couple build warnings in QueryOps.h

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, Code/DataStructs/Wrap/testBV.py, Code/DataStructs/Wrap/wrap_BitOps.cpp, Code/Geometry/catch_tests.cpp, Code/GraphMol/Abbreviations/catch_tests.cpp, Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/Bond.cpp, Code/GraphMol/Canon.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/Deprotect/Deprotect.h, Code/GraphMol/Deprotect/deprotectTest.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/Matrices.cpp, Code/GraphMol/MolCatalog/test1.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/catch_adjustquery.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/molopstest.cpp, Code/GraphMol/testMolBundle.cpp, Code/GraphMol/testPickler.cpp, ReleaseNotes.md
This mainly adds tests to improve test coverage.
This is, of course, a story which could go on for a long time. Some improvement is better than none. :-)
Bug fixes made along the way:
- copy-pasta in `parseAdjustQueryParametersFromJSON()`
- copy-pasta in `adjustQueryProperties()`
- `Bond::getValenceContrib()` would return non-zero results for atoms not involved in the bond
- `StereoType` missing `operator!=`
- `DeprotectData` missing `operator!=`
- overly aggressive caching in `getDistanceMat()` and `get3DDistanceMat()`
This also deprecates the definition of `BalabanJ` which is in `MolDiscriminators.cpp`. If we want to keep this we should move it to the Descriptors directory.
=> Improve test coverage and some bug fixes

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
according to the specification the LINKNODES should come before the SGRoups and the COLLECTIONS should come before the 3D objects. 
Unfortunately I haven't been able to find any public data with OBJ3Ds in it, so I can't really do a test for that last one.
=> Fixes #4561

rdkit/Chem/Descriptors.py, rdkit/Chem/UnitTestDescriptors.py
Closes #4567
As suggested, we just return 0 if there aren't any heavy atoms in the mol.
=> Fixes #4567

Code/GraphMol/catch_chirality.cpp, Code/GraphMol/molopstest.cpp
I noticed some warnings during the build. This addresses them:
- In catch_chirality.cpp, clang compiled about unused comparison results. I think these were meant to be assignments. I added an extra check to make sure we don't set tetrahedral stereo by default. I think this was introduced in #4536.
- In molopstest.cpp, `std::random_shuffle` is deprecated since C++. I replaced it with `std::shuffle`. This seems to have been introduced earlier, but I hadn't noticed it until now.
=> Fix (new?) warnings

Code/ForceField/UFF/Params.cpp, Code/ForceField/UFF/Params.h, Code/ForceField/UFF/testUFFForceField.cpp, Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp, Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp, ReleaseNotes.md
The way we were using the singleton here was, I think, not particularly threadsafe. This might have been leading to a Heisenbug in the KNIME nodes.
The changes here outsource worrying about thread-safe initialization to boost::flyweight (yay!).
I didn't add any new tests because we're already doing current multi-threaded UFF and conformer generation (this also uses UFF parameters) tests. Those weren't showing any problem and I didn't manage to come up with anything that would reproducibly show the problem.
=> fix a thread-safety bug in the UFF parameter loading

Code/GraphMol/Abbreviations/Abbreviations.cpp, Code/GraphMol/Atom.cpp, Code/GraphMol/CMakeLists.txt, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/ReactionUtils.cpp, Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/Depictor/DepictUtils.cpp, Code/GraphMol/Depictor/EmbeddedFrag.cpp, Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp, Code/GraphMol/FindRings.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/ROMol.h, Code/GraphMol/Resonance.cpp, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/catch_moliterators.cpp, Code/GraphMol/new_canon.cpp, Code/JavaWrappers/ROMol.i
The idea is to make looping over atom neighbors or bonds even simpler:
```
for(const auto nbr : mol.atomNeighbors(atom)){
// do something with nbr, which is a const Atom *
}
for(const auto bnd : mol.atomBonds(atom)){
// do something with bnd, which is a const Bond *
}
```
I should have done these a long time ago!
There are still times when the older style `mol.getAtomNeighbors()` and `mol.getBondNeighbors()` are useful, so those have not been removed or deprecated and will continue to show up in code.
*NOTES FOR REVIEWERS*: 
In addition to adding this new code and tests for it, I also started to translate some of the existing RDKit code to use this pattern. I wanted to do some in order to get a feeling for what using this pattern is like, but I didn't want to make the review impossible. …
=> add ROMol::atomNeighbors() and ROMol::atomBonds()

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/fmcs.out, Code/PgSQL/rdkit/low_gist.c, Code/PgSQL/rdkit/mol_op.c, Code/PgSQL/rdkit/sql/fmcs.sql
This pull request is intended to address a few warnings in the cartridge code, due to some unused variables, one missing inclusion directive and a few integer-to/from-pointer conversions in the fmcs code.
In the process I added a test case exercising the overloaded fmcs aggregator for mol values.
=> Fix some compile-time warnings in the postgres cartridge code

rdkit/Chem/MolDb/Loader_sa.py
The MolDb sqlalchemy adapter doesn't work with v1.4 or later of sqlalchemy because it uses a symbol which was deprecated in 2010. This fixes that.
more info here: https://github.com/sqlalchemy/sqlalchemy/issues/6263
=> handle sqlalchemy deprecation

Docs/Book/GettingStartedInPython.rst, rdkit/Chem/Draw/UnitTestSimilarityMaps.py
Some configuration change is causing the windows CI builds to fail on the similarity map tests.
This PR is to try and track that down and fix it.
Try cleaning up the similarity map tests a bit before disabling them completely on windows (temporarily)
We should track the configuration problem down eventually, but I think it make sense to wait until we've moved to the new windows CI platform (with VS2019 instead of VS2017) before doing that. Here's the issue for that:
https://github.com/rdkit/rdkit/issues/4677
=> [Operational] get windows CI builds working again

Code/GraphMol/ChemReactions/ReactionFingerprints.cpp, Code/PgSQL/rdkit/expected/reaction.out
Fixes #4631
The call to `getHashedTopologicalTorsionFingerprintAsBitVect` in `generateFingerprintAsBitVect` is modified to pass the `fpSize` argument, that was previously omitted and resulting in a fixed fingerprint size of 2048 bits.
I assumed the missing argument was simply due to an oversight, just let me know if it was for some reason intended.
The implemented change in general affects the computation of reaction fingerprints of type TopologicalTorsion, and it's not limited in scope to the postgres cartridge.
=> fix TopologicalTorsion fingerprint in ReactionFingerprints' generateFingerprintAsBitVect

Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/Substruct/SubstructMatch.cpp
Fixes #4651 
This is a simple fix to a nasty issue.   If an exception is thrown in the recursive bowels of a substructure search, the mutexes are not cleared.  This creates a deadlock on the second call.
=> Recursive Substructure Search Deadlock

Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp
This adds three new atom color palettes:
- avalon
- CDK
- dark mode
and two new drawing modes:
- dark mode
- monochrome (= provide just foreground and background colors)
The modes set all colors (except highlighting... I didn't figure out a reasonable way to automate that), not just the atom palette.
Here are some examples:
Dark mode:
Avalon mode:
CDK mode:
And monochrome, with an "arbitrary" choice of fg/bg colors:
=> Add some new color palettes to MolDraw2D

rdkit/Chem/AllChem.py
This PR fixes useless docstring of ConstrainedEmbed.
`AllChem.ConstrainedEmbed` returns the same object with `mol`, ie, the code below always prints `True`.
```python
newmol=AllChem.ConstrainedEmbed(mol, template)
print(newmol is mol)
```
Therefore, the following explanations are useless. I believe that points should be compared with `template`'s ones.
=> Fix docstring of ConstrainedEmbed

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
I believe that that SDD/FIELDDISPLAY coordinate parsing in `MolDraw2D.cpp` is incorrect.
The format for these lines is:
```
M  SDD sss xxxxx.xxxxyyyyy.yyyy eeefgh i jjjkkk ll m noo
```
For V3000 FIELDDISPLAY is identical except for the index (sss).
I've changed the parsing and added a unit test.
Cheers,
Gareth
=> Molfile SDD records not properly displayed

Code/GraphMol/RGroupDecomposition/RGroupCore.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
If  you have a core that contains atom list records (`M ALS` in the MOL block) those query atoms do not get assigned to the matching structure atoms during decomposition.  The ALS record is retained in the matching core and the atom type in the core atom is always the first atom type in the list- so if you output to smiles you may get the wrong atom type.
For example:
Anyway, the fix is trivial and I've included a test.
=> RGD:  fix for cores with MOL  block atom lists

rdkit/Chem/TorsionFingerprints.py, rdkit/Chem/UnitTestMol3D.py
This is a simple one: we just need to add a fall-through case which picks one of the atoms around the highly coordinated atom.
=> Fixes #4720

Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/Tautomer.h, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.cpp, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h, Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.cpp, Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.in, Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.v1.in, Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/testTautomer.cpp
The rules the tautomer enumeration code was using are derived from the ones in https://doi.org/10.1007/s10822-010-9346-4 but didn't use some of the cactvs SMARTS extensions that the rules in the paper use. Since the RDKit now supports most of those extensions (the one which is unsupported is `e`, but that only shows up in one rule), this updates the definitions.
For people who want to continue to use the old definitions: I added a new parameter object with those. This is easily accessible from C++ and Python.
=> Fixes #4700: changes default tautomer enumeration rules

Code/GraphMol/TautomerQuery/TautomerQuery.cpp
I was wondering how could the tests pass given `Data/MolStandardize/tautomerTransforms.in` does not exist anymore, and then I realized that's because `tautomerFile` was defined but actually never used. So I thought we might as well get rid of it :-)
=> Remove dead code

Code/PgSQL/rdkit/cache.c, Code/PgSQL/rdkit/cache.h
The proposed changes mainly replace the existing mechanism for deallocating the cache resources with a similar functionality based on the memory context callback api (available in postgres 9.5 and later). Also, the allocation of the cache holder instances, previously using direct calls to malloc/free, is now delegated to the associated memory context.
So far, I only tested this with postgres 14.1, and verified that the regression tests were unaffected in my development environment. Running some queries under valgrind didn't report any leaks (some memory is reported to be in use at exit, but I think this might be in general expected).
=> Refactor the memory management of the postgres cartridge cache module

Code/GraphMol/GenericGroups/CMakeLists.txt, Code/GraphMol/Substruct/CMakeLists.txt
This fixes a couple of typos found by @ptosco in the CMakeLists.txt files associated with GenericGroups that were added in #4673.
=> Fix GenericGroups installation typos

Code/PgSQL/rdkit/CMakeLists.txt
I noticed that the upgrade sql scripts are created and installed from inside the source tree. This PR just moves them into the corresponding build directory.
@ptosco  I only tested these changes on linux, but I'm hopeful they are small enough to work on windows too.
=> generate the sql update files in the binary (build) directory

Code/GraphMol/GenericGroups/generic_tests.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/Wrap/substructmethods.h
`mol.GetSubstructMatch()` and `mol.HasSubstructMatch()` were running in NOGIL mode when `extraFinalCheck` (which requires a callback into Python) was set. This led to crashes.
This PR fixes that and does a minor bit of refactoring so that the three substructmatch helper functions all use another helper to actually do the substruct search. This way any future tweaks only have to happen in one place.
This also adds an additional test to the GenericGroups code, just to be sure that they are compatible with extraFinalChecks.
=> Fixes crashing bug with finalSubstructChecks

rdkit/Chem/Draw/__init__.py
Fix `_moltoSVG` like the fix to `_moltoimg` by d2422dac6d7e79b0a12253fac0a44c02e03bd64c in #3034.
Fixes #4792
=> Fix `_moltoSVG` to avoid kekulization failure

Code/GraphMol/Atom.cpp, Code/GraphMol/Atom.h, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Kekulize.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/catch_graphmol.cpp, Code/PgSQL/rdkit/expected/reaction.out
This also adds a new function: `RDKit::isAromaticAtom()`, which returns true for atoms which either have their aromatic flag set or which have an aromatic bond to them.
=> Fixes #4785: aromatic bonds no longer set aromatic flags on atoms

Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/Qt/catch_qt.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Simple change to use `getDrawLineWidth()` instead of `lineWidth()`, like all the other drawers do.
I checked the output PNGs from the new Qt tests and they look fine.
=> Fixes #4764

Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp, Code/GraphMol/MMPA/Wrap/rdMMPA.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolInterchange/Wrap/rdMolInterchange.cpp, Code/GraphMol/MolStandardize/Wrap/Validate.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp, Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp, Code/GraphMol/SubstructLibrary/Wrap/rough_test.py, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/RDBoost/Wrap.h
The function `pythonObjectToVect()` returns, by design, a `nullptr` when it's called with either `None` or an empty sequence.
However, there are a bunch of spots in the code where the results of `pythonObjectToVect()` are de-referenced without being checked.
This fixes all of those.
=> Fix a number of crashing bugs in the python wrappers

Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/smatest.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out
These weren't being correctly assigned the SingleOrAromatic shorthand
This has no impact on correctness, just the verbosity of the output SMARTS.
Here's a demonstration of the problem.
Before this PR:
```
In [3]: Chem.MolToSmarts(Chem.MolFromSmarts('C(C)C'))
Out[3]: 'C(-,:C)C'
```
After this PR:
```
In [2]: Chem.MolToSmarts(Chem.MolFromSmarts('C(C)C'))
Out[2]: 'C(C)C'
```
=> correctly tag unspecified branch-begin bonds in SMARTS

Code/GraphMol/ChemTransforms/CMakeLists.txt, Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
When `replaceCore` breaks a small ring containing double bonds, this sets double bonds to CIS so that we don't end up with crossed bonds in mol blocks.
=> Fixes #4809: double bond stereo can now be set after calling replaceCore()

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/SmilesParse/smiles.ll, Code/GraphMol/SmilesParse/test.cpp, Docs/Book/RDKit_Book.rst
adds support for `$` to the SMILES/SMARTS parsers and writers.
=> Fixes #4842: support $ for quadruple bonds in SMILES and SMARTS

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
The drawing code had some broken logic to try and fix wedged bonds drawn from non-chiral atoms. This was resulting in wedged bonds being drawn backwards if the central atom didn't have marked tetrahedral stereo.
Aside from the fact that the logic was broken, by the time we get to the drawing code we shouldn't be doing this kind of chemistry "cleanup" anymore anyway, so this just removes that logic.
=> Fix bug with wedges being drawn backwards

Code/GraphMol/RGroupDecomposition/RGroupData.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupUtils.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Currently RGD does not decompose correctly if an input structure contains a dummy atom.  For example, if a second RGD is performed on the groups from an earlier RGD.  Just to be clear- by submitting a fix I'm not endorsing the practice!
Before
After
Note: the difference in the core depiction is due to the improvements in master since the 21.09 release. The PR fixes the R2 and R4 groups.
=> RGD: dummy atom in input structure is mishandled

Code/GraphMol/FilterCatalog/FilterCatalogRunner.cpp
I ended up diving into `RunFilterCatalog()` while debugging #4846, and noticed a couple bugs:
- The Python docs say "Use numThreads=0 to use all available processors." but that currently doesn't work (this is implemented in `getNumThreadsToUse()` so we can use the result without any extra logic).
- The function actually starts `numThreads + 1` threads, which may cause duplicate results / race conditions.
This fixes both problems.
=> Fix RunFilterCatalog() thread counts.

Code/GraphMol/MolDraw2D/CMakeLists.txt
The MD5 hash for the comic neue font bundle from google fonts has changed, not sure why.
This updates the expected value in the cmake files
=> update MD5 for the comicneue font

Docs/Book/source/rdkit.Chem.rdCIPLabeler.rst, Docs/Book/source/rdkit.Chem.rdMolEnumerator.rst, Docs/Book/source/rdkit.Chem.rdTautomerQuery.rst, Docs/Book/source/rdkit.Chem.rst
I noticed that three modules that I have seen in the code are not actually present in the Sphinx docs:
* `rdkit.Chem.rdMolEnumerator`
* `rdkit.Chem.rdCIPLabeler`
* `rdkit.Chem.rdTautomerQuery`
If this was unintentional, this PR fixes it.
=> Build documentation for 3 missing modules

.azure-pipelines/vs_build.yml, .azure-pipelines/vs_build_dll.yml, azure-pipelines.yml
The windows-2016 VMS are deprecated and there's no reason to be using ubuntu-18.04 any more.
=> update CI VMs to latest versions

Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake, Code/GraphMol/SmilesParse/smarts.yy
this one slipped through the cracks when adding support for coordinate bonds to the SMILES parser
=> Fixes #4878: cannot parse coordinate bonds from CXSMARTS

Code/JavaWrappers/MolOps.i
This is another basic one to clear up some easy-to-fix leaks due to forgotten `%newobject` calls.
=> fix some leaks in the SWIG wrappers

Code/GraphMol/Atom.h, Code/GraphMol/QueryAtom.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py
Addresses #4880
This is exposes the `getQueryType()` query atom function to python so that atom query types/symbols (Q, QH, X, XH, etc) can be accessed. This is mostly helpful because the query symbols can now be used as a dummy label so that it will render in image generation. Here is an example of what the images will looks before and after setting dummy labels using query atom symbols:
This might be something we want to automatically render
=> Added GetQueryType() to python query atom API

rdkit/Chem/FeatMaps/FeatMapParser.py, rdkit/Chem/FeatMaps/FeatMapUtils.py, rdkit/Chem/FeatMaps/FeatMaps.py
--------------------
Updated Changes
- [New]: Cleanup `class FeatMapParser`,
- [Recall]: Function `ScoreFeats()` changed the default variables for data/memory safety. Check in PR 4815. This may cause backward incompatible
- [Recall]: Function `GetFeatFeatDistMatrix()` is optimized.
=> Clean-up Python #4815 - P1.5: Chem\FeatMaps
