rdkit/rdkit

- Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
- Fixed two trivial bugs that went unnoticed so far because that
part of code is never executed running the validation suite
(and probably hardly executed at all), but still worth fixing!
> Fixed two trivial bugs

- Code/GraphMol/Canon.cpp
- Code/GraphMol/Canon.h
- Code/GraphMol/ChemReactions/testReaction.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/test.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/hanoitest.cpp
- Code/GraphMol/molopstest.cpp
- Code/GraphMol/new_canon.cpp
- Code/GraphMol/new_canon.h
- Code/GraphMol/testChirality.cpp
Updates to the new canon branch
> New canonicalization 24 july2014

- Code/GraphMol/FMCS/FMCS.cpp
- Code/GraphMol/FMCS/FMCS.h
- Code/GraphMol/FMCS/Wrap/rdFMCS.cpp
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FMCSTests.java
* restore java and python wrappers. 
* new parameter (matchChiralTag) 
* new function findMCS_P(mols, string p) accepts JSON parameters
> restore java and python wrappers. New parameter (matchChiralTag) 

- Code/GraphMol/AtomIterators.cpp
- Code/GraphMol/AtomIterators.h
- Code/GraphMol/BondIterators.cpp
- Code/GraphMol/BondIterators.h
I was running some tests and noticed some methods of the Atom/Bond iterator interfaces that I think could be const.
> added const qualifiers to some methods of Atom/Bond iterator classes

- Code/GraphMol/ChemReactions/testReaction.cpp
- Code/GraphMol/FragCatalog/FragCatalogEntry.cpp
- Code/GraphMol/FragCatalog/Wrap/rough_test.py
- Code/GraphMol/MolOps.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/hanoitest.cpp
- Code/GraphMol/new_canon.cpp
- Code/GraphMol/new_canon.h
- rdkit/Chem/UnitTestCatalog.py
- handling molecules/proteins with multiple fragments
- add criteria for using special symmetry invariant
> Some performance fixes for the new canonicalization

- Code/GraphMol/new_canon.cpp
- Code/GraphMol/new_canon.h
- remove redundant call of updateAtomNeighborIndex()
- revise comparison in SpecialSymmetryAtomCompareFunctor due to inconsistency
> New canonicalization: two small fixes

- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- added a relevant test to Code/GraphMol/Wrap/rough_test.py
> Added a Python wrapper for getShortestPath()

- Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h
- Code/GraphMol/Wrap/rough_test.py
- Made the single-threaded code in MMFF::MMFFOptimizeMoleculeConfs() as efficient
as the multi-threaded one, avoiding re-generation of MMFFMolProperties and
force-field for each conformation
> Optimized MMFF::MMFFOptimizeMoleculeConfs()

- Code/GraphMol/MMPA/MMPA.cpp
- Code/GraphMol/MMPA/MMPA_UnitTest.cpp
- Code/GraphMol/MolOps.cpp
- Code/GraphMol/new_canon.h
> fix MMPA bugs for some tests

- rdkit/Chem/SimpleEnum/Enumerator.py
> Fix issue with invalid reactions throwing NameError

- rdkit/Chem/PandasTools.py
The dataframe index can not be called by name directly, so an additional conditional was inserted to enable the above mentioned functionality.
> changed FrameToGridImage() so that the dataframe index can be used as legend

- rdkit/Chem/PandasTools.py
- rdkit/Chem/UnitTestPandasTools.py
The Pandas writer is now 15% faster, because it use the RDKit API more efficiently.
The Pandas writer can now save to an gzip file.
AddMoleculeColumnToFrame() is 10% faster because it uses the pandas API more efficiently.
> pandas performance and functionality improvements

- rdkit/Chem/PandasTools.py
Users can now set *PandasTools.molRepresentation = 'svg'* to enable svg rendering in pandas data frames
I tried using svg code generated by RDKit directly but it is not rendered properly (newlines at beginning and end and it does not set table width). So now it relies on IPython.display.SVG to fix svg code generated by RDKit.
Demo here: http://nbviewer.ipython.org/github/samoturk/cheminf-notebooks/blob/master/IPython/PandasTools.py%20SVG.ipynb
> Added option to use SVG rendering in pandas data frames

- Code/GraphMol/DistGeomHelpers/Embedder.cpp
- Code/GraphMol/DistGeomHelpers/Embedder.h
- Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
chirality test added and flag for them introduced
> Chirality tests

- Code/GraphMol/MMPA/MMPA.cpp
> fixes #655

- Code/GraphMol/FMCS/Seed.cpp
This is a very minor clean up. There was really no need to use newAtomsMap - a set suffices. In fact we weren't even checking for aIdx anyways.
> Use sets instead of and map. Minor comments cleanup.

- CMakeLists.txt
- Code/GraphMol/FilterCatalog/CMakeLists.txt
- Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt
- Code/JavaWrappers/CMakeLists.txt
I don't think we need to have this duplicated across multiple files.
> move the boost serialization configuration to the global cmakelists.txt

- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
- Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
> Improvements to bounds-matrix construction for highly constrained systems.

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/molopstest.cpp
Checks for degenerate coordinates when trying to figure out where Hs should be placed.
> Fixes #678

- Code/RDGeneral/Dict.cpp
this time relative to the correct commit
> Fixes #703

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/ReactionRunner.h
This PR exposes generateOneProductSet
This would be called from the client side via RDKit::ReactionRunnerUtils::generateOneProductSet
> Expose generateOneProductSet

- Code/GraphMol/Wrap/rdchem.cpp
- Code/GraphMol/Wrap/rough_test.py
Cleans up the crash for #750 as well as another problem with the tests on Windows.
> Fix issue750

- rdkit/Chem/Draw/IPythonConsole.py
Fixes issues with newer jupyter ipython installations.
Note: Needs to be checked on windows
> Fixes notebook problems with newer jupyter installs

- Code/PgSQL/rdkit/adapter.cpp
- Code/PgSQL/rdkit/expected/inchi.out
- Code/PgSQL/rdkit/mol_op.c
- Code/PgSQL/rdkit/rdkit.h
- Code/PgSQL/rdkit/rdkit.sql91.in
- Code/PgSQL/rdkit/sql/inchi.sql
> support providing InChI (or InChI key) generation options in cartridge

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
The idea is to make it easy to, for example, only add Hs on chiral atoms (to help cleanup depictions).
> Add argument to addHs allowing only certain Hs to be considered

- rdkit/Chem/Draw/__init__.py
This should probably be merged before #775
> Fixes #776

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
The fix is small, but this is a crashing bug in the current release that is affecting people, particularly KNIME users.
I'd like to get it in reasonably quickly so that I can do a patch binary release of the java wrappers for KNIME.
> Fixes #781

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/molopstest.cpp
This is a version of #778 without the extra commit
> Fix for Issue #754

- rdkit/Chem/Draw/cairoCanvas.py
This is a bug, surface is not defined, should be self.surface but probably this branch is not executed too frequently.
> surface -> self.surface

- Docs/Book/Install.md
https://github.com/rdkit/rdkit/issues/762
> add some boost packages about thread

- Code/GraphMol/Descriptors/MolDescriptors.cpp
- Code/GraphMol/Descriptors/test.cpp
- Code/GraphMol/atomic_data.cpp
- Code/GraphMol/atomic_data.h
- Code/GraphMol/molopstest.cpp
Accounting for the mass of the electron when calculating exact mol wt.
> Fixes Issue 694

- Code/JavaWrappers/ChemReactions.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemReactionTests.java
> Exposes reduceProductToSideChains to Java

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/__init__.py
Includes:
- progress on #773
- including legends
- wider wedges
- better dashes
- fixes to `getAtomCoords()`
> A number of small additions and features to the drawing code

- rdkit/sping/PDF/pdfgen.py
- rdkit/sping/PDF/pdfutils.py
- rdkit/sping/PS/__init__.py
- rdkit/sping/PS/pidPS.py
- rdkit/sping/PS/psmetrics.py
- rdkit/sping/SVG/__init__.py
- rdkit/sping/SVG/pidSVG.py
Some changes to the legacy sping code to gain python3 compatibility.
> Fixes #398

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
This is a simple drawing quality one.
> make Hs black instead of gray

- Code/GraphMol/Aromaticity.cpp
- Code/GraphMol/molopstest.cpp
- rdkit/Chem/Fraggle/FraggleSim.py
- rdkit/Chem/Fraggle/UnitTestFraggle.py
Stop marking rings composed exclusively of dummy atoms as aromatic.
Fixes #518
> Fix issue #518

- Code/GraphMol/Atom.h
- Code/GraphMol/SmilesParse/SmilesParseOps.cpp
- Code/GraphMol/SmilesParse/SmilesParseOps.h
- Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.yy
- Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smiles.yy
- Code/GraphMol/SmilesParse/test.cpp
- Code/RDGeneral/types.cpp
- Code/RDGeneral/types.h
This time we accept the ring closures after a branch, but we still get atom chirality right.
> Fixes #786

- Code/GraphMol/ChemTransforms/MolFragmenter.cpp
- Code/GraphMol/ChemTransforms/testChemTransforms.cpp
Just a matter of checking the bond ordering to see if the atom stereochemistry needs to be swapped.
> Fixes #511

- Code/ForceField/MMFF/testMMFFForceField.cpp
- Code/ForceField/UFF/testUFFForceField.cpp
- Code/GraphMol/DistGeomHelpers/Embedder.cpp
- Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionAngleM6.cpp
- Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
- Code/GraphMol/ForceFieldHelpers/CrystalFF/testCrystalFF.cpp
- Code/GraphMol/MMPA/MMPA.cpp
- Code/GraphMol/MMPA/MMPA_UnitTest.cpp
- Code/GraphMol/MolAlign/O3AAlignMolecules.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
- Code/GraphMol/MolOps.cpp
- Code/GraphMol/SLNParse/SLNAttribs.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/new_canon.h
- Code/RDGeneral/types.cpp
- Code/RDGeneral/types.h
- External/AvalonTools/AvalonTools.h
- External/AvalonTools/Wrap/pyAvalonTools.cpp
- External/AvalonTools/test1.cpp
- External/INCHI-API/inchi.cpp
- ReleaseNotes.md
g++ v5.2 and v4.8 now compile most everything without warnings.
> Fix a bunch of compiler warnings

- Code/GraphMol/FileParsers/MolWriters.h
- Code/GraphMol/FileParsers/SDWriter.cpp
- Code/GraphMol/FileParsers/testMolWriter.cpp
- Code/GraphMol/Wrap/SDWriter.cpp
- Code/GraphMol/Wrap/rough_test.py
- ReleaseNotes.md
> feat/github831: Add getSDText() static method.

- Code/GraphMol/Fingerprints/Fingerprints.cpp
- Code/GraphMol/Fingerprints/Fingerprints.h
- Code/GraphMol/Fingerprints/test1.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- add an unfolded count-based version of this FP
- add a bitinfo map to allow mapping bits back to atoms like the one used in MorganFPs
- refactor some code to largely avoid code duplicates
> Add an unfolded count-based version of the RDKFingerprint

- Code/GraphMol/ChemReactions/DaylightParser.cpp
- Code/GraphMol/ChemReactions/Reaction.cpp
- Code/GraphMol/ChemReactions/Reaction.h
- Code/GraphMol/ChemReactions/ReactionUtils.cpp
- Code/GraphMol/ChemReactions/ReactionUtils.h
- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- provide a function to re/move agents
- add utils function to remove atom-mapping numbers
> Add some utils functions to ChemReactions

- Code/GraphMol/QueryOps.h
Fixes regression tests on RHEL5 (gcc 4.1)
> Fixes exception when using gcc 4.1 or earlier (RHEL5 default compiler)

- Code/PgSQL/rdkit/README
- Docs/Book/Install.md
- External/AvalonTools/README
- External/INCHI-API/README
- Updated Install.md and README files related to the new CMake build
procedures involving the Avalon Toolkit, InChI and PostgreSQL cartridge
> Updated Install.md and README files

- ReleaseNotes.md
- rdkit/Chem/Descriptors.py
The fix is the one proposed in the issue
> Fix/github846 : Return value of NumRadicalElectrons and NumValenceElectrons should be int

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
The test added is the usual thing for the drawing code: produce some files for visual inspection.
> Fixes #852

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
As is usual with the whack-a-mole game that is working on depictions, looking at the test cases for this highlight the next problem to fix, but this fix is still a step forward.
> Fixes #860

- Code/DataStructs/SparseIntVect.h
- Code/GraphMol/FilterCatalog/FilterCatalog.cpp
- Code/GraphMol/FilterCatalog/FilterCatalog.h
- Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
- Code/RDGeneral/BoostEndInclude.h
- Code/RDGeneral/BoostStartInclude.h
Builds upon @bp-kelley's changes from #861 and a patch to remove warnings from @giallu
> Get things building with gcc4.4 on centos6

- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
Re-adds CalcNumRotatableBonds(True) to python API
> Fixes regression in python api CalcNumRotatableBonds

- Code/GraphMol/Fingerprints/MorganFingerprints.cpp
- Code/GraphMol/Fingerprints/test1.cpp
> Fix for github874

- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/Draw/__init__.py
this was a simple (and dumb) one
> Fixes #876

- Code/PgSQL/rdkit/expected/btree.out
- Code/PgSQL/rdkit/expected/reaction.out
didn't update the expected results for the cartridge tests.
> adjust cartridge tests after the fix for #874

- Code/GraphMol/Depictor/RDDepictor.cpp
@rvianello caught that this one was causing intermittent problems on windows.
> Fixes depictor problem with empty fragments

- Code/JavaWrappers/BitOps.i
- Code/JavaWrappers/gmwrapper/CMakeLists.txt
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BitOpsTests.java
minor enhancement to expose the FPS reading and writing functions to the SWIG wrappers.
> expose FPS functions to SWIG

- rdkit/Chem/PyMol.py
> Add SaveFile method to the PyMol wrapper

- Code/GraphMol/FilterCatalog/CMakeLists.txt
Very simple fix to this issue.
> Fixes #904: PAINS filters update fails when old Python is installed

- Code/GraphMol/Kekulize.cpp
- Code/GraphMol/molopstest.cpp
> improve error reporting for kekulization failures

- Code/RDGeneral/Dict.h
Simple fix caused by an error when removing redundant code
> Removes incorrect setting of hasNonPodData

- Code/GraphMol/PeriodicTable.cpp
- Code/GraphMol/PeriodicTable.h
- Code/GraphMol/test1.cpp
Adds thread safety to PeriodicTable initialization.
> Fixes #381

- Code/GraphMol/molopstest.cpp
Fixes a small regression caused by two pull requests
> AddTee is now SetTee

- rdkit/Chem/PandasTools.py
@nhfechner @samoturk : it would be cool if you could quickly look at this to make sure you think it makes sense.
> Fixes #933

- Code/GraphMol/Aromaticity.cpp
- Code/GraphMol/Descriptors/test.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
- rdkit/Chem/UnitTestDescriptors.py
This is a basic model that only includes five- and six-rings and ignores fused ring envelopes.
> Add support for a simplified aromaticity model.

- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
> Fixes #932

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
Another simple one.
The only question is what the default drawing color should be. I think black is probably ok.
> Fixes #953

- Code/RDGeneral/RDValue-taggedunion.h
- Code/RDGeneral/testRDValue.cpp
Adds missing headers files for older gcc/boost combinations
> Fixes includes for older boost/gcc

- Code/PgSQL/rdkit/rdkit_gist.c
The PgSQL cartridge failed to build under Windows after commit 4997acdda853f74d7043d0882b8f01cc760f8a02.
> Fixes built-in popcount in PgSQL cartridge on Windows

- Code/GraphMol/FileParsers/MolFileStereochem.cpp
- Code/GraphMol/FileParsers/testMolWriter.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
- Code/GraphMol/MolDraw2D/test1.cpp
> A variety of drawing-related changes

- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
- Add tests for that
- Improve the C++ tests for aromatizeIfPossible
> Expose the aromatizeIfPossible parameter to python

- Code/PgSQL/rdkit/README
- fixed a few slashes in a Linux path
- added some information how to run PgSQL ctest
> PgSQL README typos

- Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
> Fixes rounding errors in test

- Contrib/AtomAtomSimilarity/AtomAtomPathSimilarity.py
This is a reference implementation of the Atom-Atom-Path (AAP) similarity metric from Gobbi et al, J. Cheminf. (2015) 7:11.  It is slow - a 40*40 similarity matrix takes around 10s.  But it does reproduce the similarities in the paper, the supplementary and the java test code.  I hope people find it useful!
> added an implementation of the Gobbi Atom-Atom-Path (AAP) similarity

- Code/GraphMol/Atom.h
there's some auto-reformatting in there too
> remove a compiler warning

- External/INCHI-API/CMakeLists.txt
@ptosco : It would be cool if you could quickly look at this since it's related to your recent InChI changes.
> fix non-inchi build

- Code/GraphMol/QueryOps.cpp
- Code/GraphMol/QueryOps.h
- Code/GraphMol/Wrap/Queries.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/querytest.cpp
The list:
- queryAtomNumRadicalElectrons
- queryAtomHasChiralTag
- queryBondHasStereo
> Adds some additional canned atom and bond query definitions

- Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
- Code/GraphMol/FilterCatalog/Wrap/rough_test.py
> add pickle support to FilterCatalog

- Code/GraphMol/MolDraw2D/CMakeLists.txt
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/MolDraw2DCairo.h
- Code/GraphMol/MolDraw2D/MolDraw2DQt.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DQt.h
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
- Code/GraphMol/MolDraw2D/MolDraw2Dwx.h
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
It's likely that we will want to add a convenience function or two to simplify the API, but the functionality seems to work and it's not *that* bad to use now.
> Add multiple molecule drawing to the C++ interface

- Code/GraphMol/MolDraw2D/CMakeLists.txt
- Code/GraphMol/MolDraw2D/Wrap/CMakeLists.txt
- Code/GraphMol/Wrap/CMakeLists.txt
The recent multi-mol drawing changes broke the windows build. this fixes it.
> get the new multi-mol drawing code building properly on windows

- Code/GraphMol/Depictor/RDDepictor.cpp
- Code/GraphMol/Depictor/testDepictor.cpp
This was just a matter of re-ordering the calls to assignStereochemistry() and symmetrizeSSSR()
> Fixes github #1073

- Code/GraphMol/MMPA/MMPA.cpp
> Fixes #1044

- Code/Catalogs/Catalog.h
- Code/DataStructs/BitOps.cpp
- Code/DataStructs/ExplicitBitVect.h
- Code/DataStructs/SparseBitVect.h
- Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FilterCatalog/FilterCatalog.h
- Code/GraphMol/Fingerprints/AtomPairs.cpp
- Code/GraphMol/Fingerprints/Fingerprints.cpp
- Code/GraphMol/FragCatalog/FragCatParams.h
Nothing particularly interesting here, I had some time and was building on windows, so I got rid of a bunch of warnings.
Don't worry though, the fun isn't over, there are plenty more.
> clear up a bunch of windows warnings

- Docs/Book/Cartridge.md
- Docs/Book/Cookbook.md
- Docs/Book/GettingStartedInPython.rst
- Docs/Book/Install.md
- Docs/Book/Makefile
- Docs/Book/Overview.md
- Docs/Book/RDKit_Book.rst
- Docs/Book/conf.py
- Fixes #1079 
- A number of other cleanup tasks
- Switch to using recommonmark instead of converting rst -> md
> Documentation update.

- rdkit/Chem/Draw/cairoCanvas.py
I have noticed that Pango/PangoCairo text handling (superscript/subscript) does not work with `cairocffi`. This PR gets it to work again, while keeping compatibility with the old pycairo/pango/pangocairo Python 2 modules. Tested under all platforms with both Python 2 and 3.
I am aware that the Python 2D depiction will become soon obsolete once the C++ depiction module becomes feature-complete, but I think this can be useful for the time being.
> - Get pango 2D depiction to work with cairocffi

- Code/GraphMol/Descriptors/test_data/pmi.py
- Code/GraphMol/StructChecker/Wrap/rough_test.py
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/Wrap/testConformer.py
- rdkit/Chem/Descriptors3D.py
- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/UnitTestIPython.py
- rdkit/Chem/Draw/cairoCanvas.py
No manual changes to the code.
> yapf formatting of recent changes to Python code in rdkit and Code

- Code/GraphMol/FileParsers/PDBParser.cpp
- Code/GraphMol/FileParsers/SequenceParsers.cpp
- Code/GraphMol/FileParsers/SequenceParsers.h
- Code/GraphMol/FileParsers/SequenceWriters.cpp
- Code/GraphMol/FileParsers/test1.cpp
- Code/GraphMol/FileParsers/test_data/4BNA.pdb
- Code/GraphMol/FileParsers/test_data/4TNA.pdb
This is the contribution Roger Sayle mentioned at the 2016 RDKit UGM to add support for nucleotide sequences to the RDKit.
> Expanded sequence support

- Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
- Code/GraphMol/FilterCatalog/Wrap/rough_test.py
> Exposes normalize option to GetFlattenedFunctionalGroupHierarchy

- Code/PgSQL/rdkit/Makefile
links some additional RDKit libraries that are required to support SVG output
> add missing $RDKLIBS

- Contrib/RxnRoleAssignment/README.txt
- Contrib/RxnRoleAssignment/identifyReactants.py
- Contrib/RxnRoleAssignment/utils.py
This code allows automatically assigning reaction roles (educt or reagent) to the molecules of a reaction. The algorithm is described in:  
Schneider, N.; Stiefl, N.; Landrum G.A. 
What's what: The (Nearly) Definitive Guide to Reaction Role Assignment. 
Journal of Chemical Information and Modeling, 2016, DOI: 10.1021/acs.jcim.6b00564.
> Rxn role assignment code

- Code/PgSQL/rdkit/CMakeLists.txt
- Code/PgSQL/rdkit/Makefile
- Code/PgSQL/rdkit/bfp_gin.c
- Code/PgSQL/rdkit/rdkit.sql.in
@giallu @rvianello : this should supercede #1183 
I've included all of @giallu's changes and also got the standard build files working.
I believe this should work on versions of PostgreSQL from 9.2 to 9.6
> fix compatibility with PostgreSQL 9.2

- rdkit/Chem/Fraggle/FraggleSim.py
- rdkit/Chem/Fraggle/UnitTestFraggle.py
- rdkit/Chem/Fraggle/test_list.py
Improved test coverage to 100%
Use more pythonic idioms
> Review of rdkit.Chem.Fraggle code

- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- Code/GraphMol/Wrap/MolOps.cpp
just a small change to a typedef
> Gets the reaction sanitization code working correctly on 32bit systems

- README.md
- rdkit/VLib/Filter.py
- rdkit/VLib/Node.py
- rdkit/VLib/NodeLib/SDSupply.py
- rdkit/VLib/NodeLib/SmartsMolFilter.py
- rdkit/VLib/NodeLib/SmartsRemover.py
- rdkit/VLib/NodeLib/SmilesDupeFilter.py
- rdkit/VLib/NodeLib/SmilesOutput.py
- rdkit/VLib/NodeLib/SmilesSupply.py
- rdkit/VLib/NodeLib/UnitTestNodeLib.py
- rdkit/VLib/NodeLib/test_list.py
- rdkit/VLib/Output.py
- rdkit/VLib/Supply.py
- rdkit/VLib/Transform.py
- rdkit/VLib/UnitTestVLib.py
- rdkit/VLib/test_list.py
Most modules are at 100%, only the Database modules are untested.
> Reviewed unit tests of rdkit.VLib - coverage now 67.1%

- Code/GraphMol/Wrap/Table.cpp
- Code/GraphMol/Wrap/rough_test.py
I added PeriodicTable GetMostCommonIsotope python wrap as it didn't existed and I needed it. I'll try to check other non python wrapped functions and wrap them in my free time.
> Add python wraps

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/testReaction.cpp
> Fixes #1266

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/testChirality.cpp
There was no reason to require only two ring bonds.
> Fixes #1294

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
- Code/RDBoost/Wrap.h
Adds support for atom/bond highlighting to the MolDraw2D.DrawMolecules() method in Python.
> Resolve #1323

- .gitignore
Added another test artifact to gitignore.
> Add test artifact to gitignore

- rdkit/Chem/Draw/IPythonConsole.py
This provides better rendering and an easier install than the older approach.
> Start using py3Dmol in the notebook

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
There's a bit of additional refactoring of the cxsmiles parsing code too.
> Support parsing atom properties and atom values from cxsmiles

- Code/GraphMol/MolPickler.h
> Fixes overflow error in boost when compiler chooses int for enum type

- Code/GraphMol/Wrap/Atom.cpp
- Code/GraphMol/Wrap/rough_test.py
One line fix... if only they were all this easy. :-)
> Fixes #1352

- Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smarts.yy
- Code/GraphMol/SmilesParse/smatest.cpp
The change is relatively small, but I find the "documentation" about what should happen here somewhat ambiguous. Please take a look at the tests I added to see if you agree that the right thing is now happening.
Fixes #1338
> Fix handling of Hs in SMARTS queries

- Code/GraphMol/MolDraw2D/test1.cpp
Connected with #565.
The functionality was already there, this just shows how to use it
> Add sample of how to draw with a fixed bond length

- Code/GraphMol/AtomIterators.cpp
- Code/GraphMol/AtomIterators.h
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/itertest.cpp
I'm going to revert this since I came up with a better solution
> Revert "Fix/github1366"

- ReleaseNotes.md
- rdkit/Chem/MCS.py
- rdkit/Chem/UnitTestMCS.py
switch those tests over to using rdFMCS
Fixes #1335
this has turned up some bugs in the FMCS code that need to be filed
> deprecate rdkit.Chem.MCS;

- Code/GraphMol/Descriptors/Lipinski.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
> Add feature for #1375

- Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
> Fixes #1385

- Code/GraphMol/Atom.cpp
- Code/GraphMol/ChemReactions/Reaction.cpp
- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/testReaction.cpp
This ended up being a bit more complicated than I had thought it would be, but the conditions under which the new bond are added are specific enough that it really shouldn't have any effects elsewhere.
> Fixes #1387

- rdkit/Chem/PandasTools.py
At least the regression tests pass :)
> Fixes PandasTools to also work with pandas 0.20

- Code/GraphMol/Descriptors/CMakeLists.txt
- Code/GraphMol/Descriptors/USRDescriptor.cpp
- Code/GraphMol/Descriptors/USRDescriptor.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
- Code/GraphMol/Descriptors/test.cpp
We originally pulled this out because of the patent, which has since lapsed:
https://patents.google.com/patent/US8244483B2
So there doesn't seem to be any reason to not include @sriniker's code again.
> Bring back USR and USRCAT descriptors

- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
expose a missing function to the python wrapper
> expose and test GetDrawCoords()

- Code/GraphMol/FilterCatalog/CMakeLists.txt
really simple change to allow cmake to work when python isn't installed
> fixes #1435

- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/UnitTestSuppliers.py
> fix a couple failing windows tests related to temp file removal

- rdkit/Chem/AllChem.py
> GetConformerRMS() documentation is misleading

- Code/GraphMol/FileParsers/SequenceParsers.cpp
Simple fix for looking up Helm Monomer 'D'
> Fixes lookup for HELM Monomer 'D'

- Code/cmake/Modules/FindCairo.cmake
FindCairo was failing for my Linux conda environment with Python 3.6 (the latest). So I googled for a newer version, and this one seems to work fine.
> - updated FindCairo.cmake

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/smatest.cpp
Fixes #1472 
Ensures that atom map and isotope info is added for atoms that don't have queries
It's a simple one
> Fixes #1472

- Code/GraphMol/Kekulize.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
Fixes #1478
Simple one: detect rings made up solely of dummy atoms and do not kekulize them.
> Fix for #1478

- Code/RDGeneral/LocaleSwitcher.cpp
A small tweak to #1494 to fix the travis build.
> Remove xlocale header

- Code/GraphMol/RWMol.h
Fixes #1462
Adjusts the addAtom documentation to indicate that the index (not number of atoms) is returned.
> Fixes atom documentation

- .travis.yml
- rdkit/Chem/PandasTools.py
> Fixes #1507

- Code/JavaWrappers/MolDraw2D.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
Not a complex fix... just need to expose an additional header file.
> Fixes #1522

- Code/JavaWrappers/Bond.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemTests.java
I have added the IsInRing() and IsInRingSize(int) methods and corresponding test cases to the Java wrapper
> Added IsInRing methods to Bond in Java wrapper(addresses #1535)

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/molopstest.cpp
stop removing Hs, even implicit ones, that are attached to dummies
> Fixes #1439

- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
Adds the ability to set and get background and highlight colors from python.
This isn't the nicest solution imaginable since I was not able to expose the `boost::tuple` based `DrawColour` directly, but it does work.
There is sample code out there that purports to handle `boost::tuple` correctly in python wrappers (http://pyplusplus.readthedocs.io/en/latest/troubleshooting_guide/automatic_conversion/tuples.hpp.html) but I was unable to get that working in both directions. Python->C++ was fine, but the other direction consistently failed.
> Fixes #1519

- rdkit/Chem/Draw/__init__.py
> fixes #1481: use the new drawing code in the notebook

- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/__init__.py
All are on the Python side.
These are small ones.
> A few reaction drawing tweaks

- Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
- Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
- Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
- Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
- Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
- Fixes #1550 
- Add option to remove Hs from sidechains output by R Group decomposition code
- exposes a few additional parameters to python
> R group improvements

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/testReaction.cpp
> Fixes github #1544

- Code/JavaWrappers/MolDraw2D.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
no new functionality here, just a bit of cleanup and a new test.
> Fix problems in the SWIG wrappers caused by #1546

- Code/GraphMol/RGroupDecomposition/RGroupDecomp.h
- Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
- Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py
They were inconsistent with other parameter objects.
> remove setters and getters for RGroupDecompositionParameters

- rdkit/Chem/AllChem.py
- rdkit/Chem/__init__.py
Adds the ability to do stereochemistry expansion on molecules, including a heuristic to check whether or not the resulting structures are physically reasonable.
Once we have some experience with the basics, moving this from Python to C++ is pretty straightforward.
@bp-kelley : since I know you've thought about this, your feedback on the approach would be really useful.
Relevant to #626
> Implement stereoisomer enumeration

- rdkit/Chem/PandasTools.py
> fix a dumb interbranch clash

- Code/GraphMol/Descriptors/GETAWAY.cpp
- Code/GraphMol/Descriptors/MolData3Ddescriptors.cpp
- Code/GraphMol/Descriptors/WHIM.cpp
- Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
At this point everything seems to build with MSVC10 (needed for python2 builds with conda)
> get the new code building with the old compiler

- Contrib/NP_Score/npscorer.py
added a scoring variant with an additional confidence value between 0..1
that describes how many fragments of the tested compound were found in the model data set.
> NP Likeness with confidence value

- rdkit/Chem/EnumerateStereoisomers.py
> Fixes #1637 - Removes external six dependency

- rdkit/Chem/AllChem.py
Fixes #1650 
Conformers are iterated using their internal ids now.
> Fix issue 1650: GetConformerRMSMatrix not working with some conformers removed

- README.md
> Add 2017 UGM into README.md

- Code/GraphMol/ChemReactions/Enumerate/EnumerateBase.h
- Code/GraphMol/ChemReactions/Enumerate/testEnumerate.cpp
See #1657 for a bit more explanation.
> Fix github1657

- Code/GraphMol/Aromaticity.cpp
- Code/GraphMol/MolOps.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
- Docs/Book/RDKit_Book.rst
See the comments in #1622 for some more discussion.
> Add an MDL aromaticity model (Fixes #1622)

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/ROMol.cpp
- Code/GraphMol/ROMol.h
- Code/GraphMol/test1.cpp
Adds range based for over atoms.
I think I can do the same for bonds as well if we like this approach.
> Enable range-based for loops for molecules

- Code/GraphMol/Aromaticity.cpp
- Code/GraphMol/Kekulize.cpp
- Code/GraphMol/molopstest.cpp
> Fixes #1703

- Code/cmake/Modules/FindCairo.cmake
fix an error that shows up with cmake v3.10
> fix an irritating cmake problem

- Code/PgSQL/rdkit/README
Just an update to the PgSQL README.
> Updated the PgSQL README

- Code/RDGeneral/LocaleSwitcher.cpp
A super simple one.
I've tested this with clang-3.9 on linux and the standard xcode suite on High Sierra
> Fixes #1728

- README.md
None
Add DeepChem to list of projects using rdkit.
> Add DeepChem to projects that use rdkit

- Code/GraphMol/Atom.h
- Code/GraphMol/details.h
- Code/GraphMol/test1.cpp
This is the move of #1643 from @mwojcikowski to the modern_cxx branch.
I'll merge it once the build passes.
> Use uint32 atom and bond indices

- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/MMPA/Wrap/rdMMPA.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolHash/Wrap/rdMolHash.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
- Code/RDBoost/Wrap.h
That is what was being used for modern c++ anyway
> replace the usage of rdk_auto_ptr with std::unique_ptr

- External/FreeSASA/CMakeLists.txt
Change the `CMakeLists.txt` file to avoid downloading the FreeSASA source if we already have a copy.
> Fixes #1630

- Code/GraphMol/Renumber.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/molopstest.cpp
- Code/GraphMol/new_canon.cpp
- Code/GraphMol/testChirality.cpp
Fixes #1735
I’m unsure if this is the correct solution, it appears empty molecules can't initialize their rings so we need to check for that when using ring information.
> Fixes #1735

- Code/GraphMol/ChemTransforms/ChemTransforms.cpp
- Code/GraphMol/ChemTransforms/MolFragmenter.cpp
- Code/GraphMol/ChemTransforms/testChemTransforms.cpp
- rdkit/Chem/BRICS.py
The problem was with the handling of multiple attachments at a chiral center. Once I tracked down the cause, the fix wasn't complicated.
> Fix github1734

- rdkit/Chem/Fingerprints/FingerprintMols.py
- rdkit/Chem/Fingerprints/MolSimilarity.py
- rdkit/Chem/Fingerprints/UnitTestFingerprints.py
- rdkit/sping/TK/pidTK.py
- rdkit/sping/pid.py
Not all of the changes are really testable, but I added at least one.
> Fixes #1747

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/smatest.cpp
- Code/GraphMol/Subgraphs/test2.cpp
The SMARTS that come out of this can look odd, but they seem correct.
> Fixes #1756

- Code/JavaWrappers/MorganFingerprints.h
- Code/JavaWrappers/MorganFingerprints.i
Added a *getFeatureFingerprint* method to the java API to allow the calculation of Morgan feature fingerprints
> Added Morgan feature fingerprints to Java API

- Code/GraphMol/ChemReactions/CMakeLists.txt
- Code/GraphMol/ChemReactions/Enumerate/testEnumerate.cpp
- Code/GraphMol/ChemReactions/Wrap/CMakeLists.txt
- Code/GraphMol/FilterCatalog/CMakeLists.txt
- Code/GraphMol/FilterCatalog/Wrap/CMakeLists.txt
the builds weren't working if boost::serialization wasn't installed or disabled
> make the build work even if boost::serialization is disabled

- Code/GraphMol/Wrap/Mol.cpp
Fixing documentation to reflect method.
> Fix typo in GetBoolProp documentation

- Code/GraphMol/ChemReactions/ReactionFingerprints.cpp
- Code/GraphMol/ChemReactions/ReactionFingerprints.h
- Code/JavaWrappers/ReactionFingerprints.i
- Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FingerprintsTests.java
Add a new wrapper file along with some tests for java.
> Fixes #1776

- External/INCHI-API/Wrap/pyInchi.cpp
- External/INCHI-API/inchi.h
- External/INCHI-API/python/inchi.py
- External/INCHI-API/test.cpp
- rdkit/Chem/UnitTestInchi.py
Adds a convenience function to generate an InChI key directly from a structure.
> Add MolToInchiKey function()

- Code/GraphMol/Fingerprints/Fingerprints.cpp
- Code/GraphMol/Fingerprints/test1.cpp
A bit of auto-reformatting too.
> Fixes #1793

- Code/GraphMol/CMakeLists.txt
> disable sln with gcc48

- Docs/Book/GettingStartedInPython.rst
- Docs/Book/Install.md
- Docs/Book/Overview.md
- Docs/Book/RDKit_Book.rst
- ReleaseNotes.md
> update docs for release for release

- Code/GraphMol/FileParsers/MolFileStereochem.cpp
- Code/GraphMol/FileParsers/MolFileStereochem.h
- Code/GraphMol/FileParsers/test1.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
Adds a new function `wedgeBond()` that allows a single selected bond to be wedged.
Unfortunately a bit of code formatting snuck in there too, so it looks like more than it is.
> Fixes #1615

- CMakeLists.txt
- Code/RDBoost/CMakeLists.txt
- Code/cmake/Modules/RDKitUtils.cmake
Supersedes #1807 and #1800 
This will need to be applied to the 2017_09 production branch as well.
> Fix python linkage

- Code/GraphMol/AddHs.cpp
one-liner that @d-b-w pointed out.
> minor oversight in fix for #1810

- ReleaseNotes.md
> - fixed typo

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
- Code/GraphMol/MolDraw2D/test1.cpp
Not a complicated one to fix.
Adds a couple of tests, including one to make sure the C++ code also behaves (though it was always fine)
> Fixes #1829

- Code/JavaWrappers/RWMol.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BasicMoleculeTests.java
This was just a matter of no longer ignoring a few methods in the SWIG wrappers and adding a couple of tests.
> Fixes #1837

- External/CoordGen/CoordGen.h
- External/CoordGen/Wrap/rdCoordGen.cpp
exposes a parameter for balancing coordinate quality and speed
> add control over the coordinate precision to coordgen

- Code/GraphMol/ChemReactions/Reaction.h
- Code/GraphMol/ChemReactions/ReactionPickler.cpp
- Code/GraphMol/ChemReactions/ReactionPickler.h
- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
- Code/GraphMol/ChemReactions/testReaction.cpp
- Code/GraphMol/Wrap/Mol.cpp
- Code/GraphMol/Wrap/props.hpp
This adds the full properties interface to the ChemicalReactions class.
> Add Properties interface to ChemicalReactions

- Code/GraphMol/RWMol.h
- Code/GraphMol/test1.cpp
Fixes #1843
<!-- Example: Fixes #1234 --
> RWMol::clear now calls ROMol::initMol

- Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.yy
- Code/GraphMol/SmilesParse/smatest.cpp
It was an oversight that this didn't make it into the last release.
> Fixes #1719

- rdkit/Dbase/UnitTestDbConnect.py
- rdkit/Dbase/UnitTestDbUtils.py
- rdkit/Dbase/UnitTestStorageUtils.py
- fixes failing tests on Windows due to attempted deletion on O_EXCL files left open
> Fixes failing Python tests on Windows

- Code/GraphMol/SLNParse/lex.yysln.cpp.cmake
- Code/GraphMol/SLNParse/sln.ll
- Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
- Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.ll
- Code/GraphMol/SmilesParse/smiles.ll
- Code/GraphMol/StructChecker/AtomSymbolMatch.cpp
- Code/GraphMol/StructChecker/Pattern.cpp
- Code/RDGeneral/LocaleSwitcher.cpp
Thanks to Roger Sayle for the patch.
> Allow building on cygwin using -std=c++11

- Code/cmake/Modules/RDKitUtils.cmake
The fact that `export.h` and `test.h` are re-generated at each CMake run impacts on build times, as unnecessary rebuilds of large portion of the source tree are triggered.
`export.h` and `test.h` are now generated in the `CMAKE_BINARY_DIR` directory tree, and are only copied to the `CMAKE_BINARY_DIR` directory tree if they differ from the previous version (or if the latter does not exist).
> Do not re-generate export.h and test.h if they have not changed

- Code/GraphMol/FileParsers/MolSupplier.h
- Code/GraphMol/FileParsers/testMolSupplier.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
going to wait for the travis build to finish, then merge this
> fix some problems caused by #1874

- Contrib/ChiralPairs/ChiralDescriptors.py
- Contrib/ChiralPairs/README.txt
This set of new descriptors were described in a recent publication, please see:
Schneider, N.; Lewis, R. A.; Fechner N.; Ertl, P. 
Chiral Cliffs: Investigating the Influence of Chirality on Binding Affinity. 
ChemMedChem, 2018, DOI: 10.1002/cmdc.201700798
> Add a script for calculating chiral descriptors to Contrib

- Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smarts.yy
- Code/GraphMol/SmilesParse/smatest.cpp
Not a complex fix and I don't think it has broad consequences.
> Fixes #1920

- Code/GraphMol/Descriptors/MolSurf.cpp
- Code/GraphMol/Descriptors/MolSurf.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
Addition of a version of the VSA descriptor that takes a custom property and custom bins.
> Custom property VSA

- Contrib/Fastcluster/fastcluster.py
@iwatobipen : the original fastcluster contribution didn't include anything explicit about the license. Are you ok with the changes I've made here?
> Make fastcluster license clearer

- Code/GraphMol/Aromaticity.cpp
- Code/GraphMol/Rings.h
- Code/GraphMol/molopstest.cpp
- rdkit/Chem/UnitTestInchi.py
This disables perception of fused-ring aromaticity between rings that share more than one bond.
I think this is physically reasonable since there's basically no way that such a system could be planar.
> Fix github1928

- rdkit/Chem/Descriptors.py
super simple one-line fix (and two lines of reformatting)
> Fixes #1948

- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
another easy one
Apologies that there's a bit of code reformatting mixed in as well
> Fixes #1924

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/smatest.cpp
includes a minor bit of refactoring/reduction of duplicated code
> Fixes #1906

- Docs/Book/Overview.md
> update knime urls in overview.md

- Code/GraphMol/SmilesParse/SmilesParse.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
This one just required moving a bit of code. Easy!
I also fixed a bit of ugly using a C++ feature.
> Fix for #1968

- rdkit/Chem/EnumerateHeterocycles.py
> Clarify that this file is covered under the parent RDKit BSD license.

- Code/PgSQL/rdkit/expected/rdkit-91.out
- Code/PgSQL/rdkit/expected/reaction.out
update expected results from the cartridge
> these should have been updated as part of #1940

- Code/GraphMol/Descriptors/MolSurf.cpp
- Code/GraphMol/Descriptors/MolSurf.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
- Code/GraphMol/Descriptors/test.cpp
- Docs/Book/GettingStartedInPython.rst
- Docs/Book/RDKit_Book.rst
parameters added from the paper.
More details are in the documentation
> Fix github1973: support optional inclusion of S and P contributions to TPSA

- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/testPickler.cpp
Mostly backwards compatible change to the pickle format as discussed in the #1999 comments.
> fixes #1999

- Docs/Book/GettingStartedInPython.rst
- Docs/Book/images/mfp2_bit872.svg
- Docs/Book/images/rdk_bit1553.svg
- Docs/Book/images/rdk_bit1553_2.svg
- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/Draw/__init__.py
@NadineSchneider did a really nice job of rendering Morgan fingerprint bits in CheTo. This ports that code to the core RDKit.
> port fingerprint bit rendering code from CheTo

- Code/GraphMol/Depictor/EmbeddedFrag.cpp
- Code/GraphMol/Depictor/testDepictor.cpp
Also includes a bit of modernization.
> Fixes #2027

- rdkit/Chem/Draw/IPythonConsole.py
> Fixes #2025

- Code/GraphMol/FileParsers/CMakeLists.txt
- Code/GraphMol/FileParsers/FileParsers.h
- Code/GraphMol/FileParsers/SVGParser.cpp
- Code/GraphMol/FileParsers/catch_tests.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
- Code/GraphMol/ROMol.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
The idea is that we'll be able to construct an RDKit molecule from the information present in the SVG.
This is what the format looks like:
```
<rdkit:mol>
<rdkit:atom idx="1" atom-smiles="[CH3]" drawing-x="9.09091" drawing-y="89.4974" x="-2.78651" y="0.295614" z="0" />
<rdkit:atom idx="2" atom-smiles="[NH]" drawing-x="52.6897" drawing-y="75.8699" x="-1.35482" y="0.743114" z="0" />
<rdkit:atom idx="3" atom-smiles="[C@H]" drawing-x="86.2908" drawing-y="106.814" x="-0.251428" y="-0.273019" z="0" />
<rdkit:atom idx="4" atom-smiles="[Cl]" drawing-x="76.2932" drawing-y="151.385" x="-0.579728" y="-1.73665" z="0" />
<rdkit:atom idx="5" atom-smiles="[C]" drawing-x="129.89" drawing-y="93.1862" x="1.18027" y="0.174481" z="0" />
<rdkit:atom idx="6" atom-smiles="[O]" drawing-x="139.887" …
```
> Allow dumping interchange information into SVG files

- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/__init__.py
Primarily there to make it more usable from the notebook
> a couple of small tweaks to the new fingerprint rendering code

- Code/GraphMol/Descriptors/PMI.cpp
- Code/GraphMol/Descriptors/PMI.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/Descriptors/Wrap/test3D.py
adds a `force` argument to the relevant functions
> Fixes #2037

- External/CoordGen/CMakeLists.txt
A simple patch until this is resolved upstream
> patch a memory allocation problem in the maeparser v1.0.0

- Code/GraphMol/FileParsers/FileParsers.h
- Code/GraphMol/FileParsers/SVGParser.cpp
- Code/GraphMol/FileParsers/catch_tests.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
- Code/GraphMol/Wrap/rough_test.py
- External/CoordGen/CMakeLists.txt
A few other changes in here too.
> enable SVG parsing from Python

- Code/GraphMol/MolInterchange/Parser.cpp
- Code/GraphMol/MolInterchange/test1.cpp
also fixes a problem with retrieving version info
> fixes #2046

- rdkit/ML/Scoring/Scoring.py
Misleading variable naming in ROC calculation could lead to future bugs
> roc calculation naming problem

- rdkit/ML/test_list.py
ensure that the tests in rdkit/ML/Scoring actually get run
> add scoring test (relevant to #1975)

- Code/GraphMol/FileParsers/testMolWriter.cpp
A copy/paste error when this test was added resulted in it never being run. Fix that.
> actually run the SmilesWriterNoNames() test

- rdkit/Chem/Draw/__init__.py
> Fixes #1851

- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/__init__.py
Nice suggestion from @PatWalters
> add Draw{RDKit,Morgan}Bits

- Code/GraphMol/FileParsers/SVGParser.cpp
- Code/GraphMol/FileParsers/catch_tests.cpp
- Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogEntry.h
- Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogParams.h
- Code/GraphMol/MolStandardize/AcidBaseCatalog/AcidBaseCatalogUtils.h
- Code/GraphMol/MolStandardize/CMakeLists.txt
- Code/GraphMol/MolStandardize/Charge.h
- Code/GraphMol/MolStandardize/Fragment.h
- Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogEntry.h
- Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogParams.h
- Code/GraphMol/MolStandardize/FragmentCatalog/FragmentCatalogUtils.h
- Code/GraphMol/MolStandardize/Metal.h
- Code/GraphMol/MolStandardize/MolStandardize.h
- Code/GraphMol/MolStandardize/Normalize.h
- Code/GraphMol/MolStandardize/Tautomer.h
- Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogEntry.h
- Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogParams.h
- Code/GraphMol/MolStandardize/TautomerCatalog/TautomerCatalogUtils.h
- Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogEntry.h
- Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogParams.h
- Code/GraphMol/MolStandardize/TransformCatalog/TransformCatalogUtils.h
- Code/GraphMol/MolStandardize/Validate.h
- Code/GraphMol/MolStandardize/Wrap/CMakeLists.txt
- Code/GraphMol/MolStandardize/testFragment.cpp
- Code/GraphMol/StereoGroup.h
@ptosco : I think I got these right, would you mind quickly looking at it to confirm that I didn't screw up?
> add export flags for the MolStandardize library

- Code/GraphMol/MolChemicalFeatures/MolChemicalFeatureFactory.cpp
- Code/GraphMol/MolChemicalFeatures/MolChemicalFeatureFactory.h
- Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeature.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeatureFactory.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py
- Code/GraphMol/MolChemicalFeatures/testFeatures.cpp
- rdkit/Chem/ChemicalFeatures.py
> A couple of chemical feature related enhancements

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
Cross the double bond if stereo is set to STEREOANY or the direction is set to crossed
> Fixes #2063

- Code/GraphMol/ChemReactions/CMakeLists.txt
- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
Copy residue info from reactants into products.
> Fixes #1632

- Code/RDGeneral/RDLog.cpp
one liner in response to the discussion on #2002
> move rdInfoLog to stderr

- External/FreeSASA/RDFreeSASA.cpp
simple fix
There's a bit of (automatic) reformatting in there that makes it look more complex than it is
> Fixes #1786

- Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
- Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
- Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py
- Docs/Book/GettingStartedInPython.rst
Makes ETKDG the default from Python
> Fixes #2057

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/CMakeLists.txt
- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/catch_tests.cpp
- Code/GraphMol/molopstest.cpp
Update the docs at the same time.
Fixes #2086
> Modify removeHs so that it does not remove degree 0 atoms

- Code/PgSQL/rdkit/adapter.cpp
- Code/PgSQL/rdkit/expected/reaction.out
- Code/PgSQL/rdkit/rdkit.control
- Code/PgSQL/rdkit/rdkit.h
- Code/PgSQL/rdkit/rdkit.sql.in
- Code/PgSQL/rdkit/rxn_op.c
- Code/PgSQL/rdkit/sql/reaction.sql
This is just adding the reaction_to_svg() function to the interface
Also bumps the version of the adapter
> Fixes 1916

- rdkit/ML/Scoring/Scoring.py
Update documentation on Scoring#CalcBEDROC
I'm not sure if I formatted it properly.  Is there a CONTRIBUTING.md which goes through code format, docstring format or linting?
> Update Docs For CalcBEDROC

- Code/GraphMol/Fingerprints/Fingerprints.cpp
- Code/GraphMol/Fingerprints/test1.cpp
- ReleaseNotes.md
> Fixes #2115

- Docs/Book/Overview.md
> overview.md updates

- CMakeLists.txt
- External/catch/CMakeLists.txt
the externalproject thing was not actually working on windows
this is a bit of a rats nest... let's see if the CI builds work
> switch the catch2 handling to a normal download

- Docs/Notebooks/FingerprintGenerators.ipynb
update to python3 and fix some older problems
> update fingerprint tutorial notebook

- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
Adds missing functions to wrapper
> Fixes #2149

- Code/GraphMol/ShapeHelpers/ShapeUtils.h
- Code/GraphMol/ShapeHelpers/Wrap/rdShapeHelpers.cpp
- Code/GraphMol/ShapeHelpers/Wrap/testShapeHelpers.py
The python function was not included. 
Not at the moment...
> ShapeTverskyIndex python function

- Docs/Book/Makefile
- Docs/Book/source/rdkit.DataManip.Metric.rdMetricMatrixCalc.rst
- Docs/Book/source/rdkit.DataManip.Metric.rst
- Docs/Book/source/rdkit.DataStructs.cDataStructs.rst
- Docs/Book/source/rdkit.DataStructs.rst
- Docs/Book/source/rdkit.DistanceGeometry.DistGeom.rst
- Docs/Book/source/rdkit.DistanceGeometry.rst
- Docs/Book/source/rdkit.ForceField.rdForceField.rst
- Docs/Book/source/rdkit.ForceField.rst
- Docs/Book/source/rdkit.Geometry.rdGeometry.rst
- Docs/Book/source/rdkit.Geometry.rst
- Docs/Book/source/rdkit.ML.Cluster.Clustering.rst
- Docs/Book/source/rdkit.ML.Cluster.murtagh_test.rst
- Docs/Book/source/rdkit.ML.Cluster.rst
- Docs/Book/source/rdkit.ML.InfoTheory.rdInfoTheory.rst
- Docs/Book/source/rdkit.ML.InfoTheory.rst
- Docs/Book/source/rdkit.Numerics.rdAlignment.rst
- Docs/Book/source/rdkit.Numerics.rst
- Docs/Book/source/rdkit.SimDivFilters.rdSimDivPickers.rst
- Docs/Book/source/rdkit.SimDivFilters.rst
- Docs/Book/source/rdkit.rdBase.rst
- Docs/Book/source/rdkit.rst
These are things that I missed when making the move from epydoc->sphinx/autodoc
> Fixes #2158

- Docs/Book/Overview.md
- README.md
Hi, 
I was hoping that my project, stk, which makes heavy use of rdkit, could be included the "Projects using RDKit" section of the README. I'm not sure what the usual process for getting a project included is, so I hope this is not out of place. Thank you!
> Added stk into the "Projects using RDKit" section of the README.

- Code/GraphMol/MolStandardize/testCharge.cpp
- Code/GraphMol/RWMol.h
- Code/GraphMol/cptest.cpp
There was no `RWMol(const RWMol &)` ctor. This adds one and a couple of tests
> Fixes #2144

- Code/DistGeom/DistGeomUtils.cpp
- Code/DistGeom/DistGeomUtils.h
- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.h
- Code/GraphMol/DistGeomHelpers/Embedder.cpp
- Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp
- Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.h
- Code/GraphMol/ForceFieldHelpers/CrystalFF/testCrystalFF.cpp
The idea to do this came out of a discussion with @coleb and @sriniker at this year's UGM.
There is, no doubt, more to be done, but I think this cleans things up quite a bit.
Curious to hear feedback.
> Some refactoring of the distance geometry code

- Code/GraphMol/Fingerprints/AtomPairGenerator.cpp
- Code/GraphMol/Fingerprints/MorganGenerator.cpp
- Code/GraphMol/Fingerprints/RDKitFPGenerator.cpp
- Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
- Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/RDKitFPWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
Some trivial to correct compilation warnings.
Cherry pick what you like in them.
> Less warnings

- Code/GraphMol/FileParsers/test1.cpp
Fix a mistaken bit of an old merge.
> re-enable (and update) the file parser tests

- Code/PgSQL/rdkit/adapter.cpp
- Code/PgSQL/rdkit/expected/props.out
- Code/PgSQL/rdkit/sql/props.sql
Fixes #2174
Change MolGetSVG to work on a copy of the input molecule.
> Fix for Issue #2174.

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.ll
The two are related to each other
> Fix #2197 and #2237

- Code/GraphMol/FileParsers/FileParsers.h
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/DiversityPickerTests.java
- Code/SimDivPickers/MaxMinPicker.h
- Code/SimDivPickers/Wrap/testPickers.py
- Code/SimDivPickers/testPickers.cpp
- ReleaseNotes.md
Fixes the problem.
More info in the discussion of #2245
> Fixes #2245

- Code/GraphMol/Substruct/CMakeLists.txt
- Code/GraphMol/Substruct/SubstructMatch.cpp
- Code/GraphMol/Substruct/SubstructMatch.h
- Code/GraphMol/Substruct/SubstructUtils.cpp
- Code/GraphMol/Substruct/SubstructUtils.h
- Code/GraphMol/Substruct/catch_tests.cpp
- Code/GraphMol/Wrap/Mol.cpp
- Code/GraphMol/Wrap/MolBundle.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/Wrap/substructmethods.h
- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BasicMoleculeTests.java
Not ready to be merged, but I'd love feedback on the API
> Add options for substructure searching

- Code/RDGeneral/StreamOps.h
- Code/RDGeneral/testRDValue.cpp
Allows Dictionaries to properly serialize binary strings (via get/setProp<std::string>
> Fix to serialize binary strings

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/catch_tests.cpp
We should now recognize all the cases where InChI considers things potentially chiral
> Fixes #2268

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
This implements parsing of enhanced stereo information in CXSMILES strings.
> Parse enhanced stereo information from CXSMILES

- Code/GraphMol/Atom.cpp
- Code/GraphMol/catch_tests.cpp
Make the check for allowed valences at aromatic atoms a bit stricter.
> Fixes #2258

- Code/GraphMol/QueryAtom.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
> Fixes #2299

- Code/GraphMol/SmilesParse/SmilesParseOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Just needed a special case in `CloseMolRings()`
> Fixes #2303

- Code/RDGeneral/Dict.cpp
- Code/RDGeneral/Dict.h
- Code/RDGeneral/testDict.cpp
adds the missing specialization along with some tests
> Fixes #2308

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
- Code/GraphMol/Wrap/rough_test.py
Also adds the CXSmiles writers to the python wrapper.
Both of these should have been part of #2276
> Add definition of MolFragmentToCXSmiles

- Code/GraphMol/FileParsers/FileParserUtils.h
- Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
@bp-kelley pointed out that this might be slow, but it was much worse than I anticipated.
Things are much better now.
> some much-needed optimization work on the new property lists

- CMakeLists.txt
instead of manually specifying compile args, let cmake do it for us.
> switch to using cmake to handle the C++ spec

- Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
- Code/JavaWrappers/CMakeLists.txt
- Code/JavaWrappers/SubstructLibrary.i
- Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
- Code/JavaWrappers/gmwrapper/CMakeLists.txt
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SubstructLibraryTests.java
Exposes substructlibrary and holders to swig.
> Exposes substructlibrary to swig

- Code/JavaWrappers/CMakeLists.txt
- Code/JavaWrappers/RGroupDecomposition.i
- Code/JavaWrappers/gmwrapper/CMakeLists.txt
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/RGroupDecompositionTests.java
- External/CoordGen/CMakeLists.txt
At the moment this is Java only, but it probably would work with C# too.
There's also another small change to allow static linking of the dependencies for the Java wrapper lib
> Expose RGroupDecomposition to SWIG

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/testCharge.cpp
> Fixes #2346

- CMakeLists.txt
Part of the deprecating Python2 support process
> show an error if attempting to compile with python2

- rdkit/Chem/EnumerateStereoisomers.py
- rdkit/Chem/PropertyMol.py
- rdkit/Chem/UnitTestDocTestsChem.py
Not a complex function since we just use the same logic as EnumerateStereoisomers() itself.
There's a big of cleanup of older tests in here as well.
> add GetStereoIsomerCount() function to EnumerateStereoisomers

- Code/GraphMol/MolStandardize/testCharge.cpp
- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SubstructLibrary/SubstructLibrary.h
- Code/RDGeneral/Dict.h
> Small fixes to get DLLs to build on Windows

- Code/GraphMol/Chirality.cpp
This will show up in every 2D SD file read... Whoops!
> Removes an extra debugging cerr statment

- Scripts/test.sh
N/A
Store, in a run-able format, the way to run all unit tests
Thanks to Paolo Tosco in the rdkit-discuss mailing list.
> added Scripts/test.sh

- Code/GraphMol/MolStandardize/MolStandardize.h
Simple fix. I will also pull this across to master and do a real PR there.
> Fixes #2368

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/Charge.h
- Code/GraphMol/MolStandardize/MolStandardize.cpp
- Code/GraphMol/MolStandardize/MolStandardize.h
- Code/GraphMol/MolStandardize/Wrap/Charge.cpp
- Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp
- Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
- Code/GraphMol/MolStandardize/catch_tests.cpp
- ReleaseNotes.md
Changes here:
- Allow the uncharging to be carried out in a canonical order 
- Fix a bug causing the charge to not be removed from negatively charged centers that aren't acidic.
> improvements to the Uncharge functionality

- Code/GraphMol/MolStandardize/MolStandardize.h
- Code/GraphMol/MolStandardize/Validate.cpp
cleans up a couple of possible seg faults when `RDBASE` is not set.
> Fixes: #2368

- Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
- Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Hs are now added with coords in the R-group decomposition
> Fixes #2332

- ReleaseNotes.md
- rdkit/Chem/PandasTools.py
- rdkit/Chem/UnitTestPandasTools.py
Simple fix along with a cleanup of some deprecation warnings
> Fixes #2380

- rdkit/Chem/Fingerprints/ClusterMols.py
> Fixes #2387 getDistanceMatrix in ClusterMols.py

- Code/GraphMol/MolPickler.cpp
- Code/ML/CMakeLists.txt
- Code/RDGeneral/StreamOps.h
- ReleaseNotes.md
- rdkit/ML/Cluster/Murtagh.py
- rdkit/ML/Cluster/UnitTestCluster.py
Should have done this PR a while ago
> Fix github #2311

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
- ReleaseNotes.md
Here we just reverse the logic and protonate non-acid groups first.
> Fixes #2392

- Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp
- Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
- Code/GraphMol/MolAlign/testMolAlign.cpp
This removes some redundancy from some of the test code in order to bring
the runtime down. This does not affect test coverage and shouldn't do
anything bad to the overall test quality.
> Speed up some of the tests

- Code/GraphMol/Trajectory/CMakeLists.txt
- Code/GraphMol/Wrap/CMakeLists.txt
> - avoid a build failure on Windows

- External/FreeSASA/CMakeLists.txt
- External/FreeSASA/RDFreeSASA.cpp
- External/FreeSASA/RDFreeSASA.h
- External/FreeSASA/Wrap/rdFreeSASA.cpp
- External/FreeSASA/Wrap/testFreeSASA.py
- External/FreeSASA/testFreeSASA.cpp
- enable building FreeSASA under Windows
- enable setting probeRadius as SASAOpts
- added C++ and Python tests for probeRadius
> FreeSASA improvements

- .azure-pipelines/linux_build.yml
- .azure-pipelines/mac_build.yml
- .azure-pipelines/vs_build.yml
- azure-pipelines.yml
I have (finally) been able to come up with the required files to use Azure Pipelines as CI backend. These will probably still require some tuning, so I'm putting up this PR so that we can start commenting.
> Enable Azure Pipelines builds for CI

- Docs/Book/Install.md
close #698
- fix GFM
- fix indentation of nested lists
- code block
- Add how to specify install location
> Improve installation guide [ci skip]

- Code/GraphMol/atomic_data.cpp
- Code/GraphMol/catch_tests.cpp
> Add an allowed valence of 3 for Al

- Code/GraphMol/Conformer.h
- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/MolPickler.h
- Code/GraphMol/Wrap/Conformer.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/testPickler.cpp
Should have done this a long time ago. :-)
> Fixes #2441

- Code/GraphMol/FMCS/FMCS.cpp
- Code/GraphMol/FMCS/FMCS.h
- Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
- Code/GraphMol/FMCS/Wrap/testFMCS.py
- Code/GraphMol/FMCS/testFMCS_Unit.cpp
Touching the MCS code is never particularly enjoyable, but it's good to get this one fixed.
> Fixes #945 and #2420

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
> Fixes #2427

- Docs/Book/RDKit_Book.rst
I had a bit of time on my hands while waiting for something else to run, so I wrote some docs.
> add docs for SMARTS primitives

- Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
- Code/GraphMol/Wrap/ForwardSDMolSupplier.cpp
- Code/GraphMol/Wrap/MaeMolSupplier.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/ResonanceMolSupplier.cpp
- Code/GraphMol/Wrap/SDMolSupplier.cpp
- Code/GraphMol/Wrap/SDWriter.cpp
- Code/GraphMol/Wrap/SmilesMolSupplier.cpp
- Code/GraphMol/Wrap/TDTMolSupplier.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
- Docs/Book/conf.py
A bunch of other doc formatting tweaks are in here too
> Fixes #2436

- Code/JavaWrappers/ExplicitBitVect.i
- Code/JavaWrappers/MorganFingerprints.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FingerprintsTests.java
Small changes to improve Java API
* Expose Tversky operator for sparse fingerprints
* Allow ExplicitBitVect to be converted to/from Java byte arrays (Java cannot process binary strings)
Thanks,
Gareth
> Cart fixes

- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/testPickler.cpp
- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/PicklingTests.java
Two small fixes for substantial problems.
I fixed them together since they both came out of the same bug report
> Fixes #2466 and #2465

- Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
This just changes a default on the Python side.
> Fixes #2475

- Code/GraphMol/ChemTransforms/CMakeLists.txt
- Code/GraphMol/ChemTransforms/MolFragmenter.cpp
- Code/GraphMol/ChemTransforms/catch_tests.cpp
This adds a test and a minor correction to the changes suggested in #1039 by @adalke
> Preserve bond direction in fragmentOnBonds

- Code/GraphMol/ChemReactions/SanitizeRxn.cpp
- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
Code cleanups in SanitizeRxn.cpp
> SanitizeRxn code and docstring cleanup

- Docs/Book/Install.md
N/A
I fixed an outdated Conda link in the installation docs
Thanks, this is my first pull request, so hopefully I did this correctly. - Vin
> fixed the dead Conda installation document link

- Code/GraphMol/Fingerprints/CMakeLists.txt
- Code/GraphMol/Fingerprints/PatternFingerprints.cpp
- Code/GraphMol/Fingerprints/catch_tests.cpp
The problem was an inadvertent consequence of one of the changes made in #2449
> Fixes #2501

- Code/GraphMol/Atom.cpp
- Code/GraphMol/Atom.h
- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
Adds a special case for neutralizing atoms that are early in the PT
> Fixes #2452

- Code/PgSQL/rdkit/expected/reaction.out
The change came about because of the fixes in #2487
Thanks to @rvianello for pointing it out
> update expected SVG output in cartridge tests

- .azure-pipelines/vs_build.yml
Trying to get the azure pipelines builds to work again
> Fix the azure pipelines builds

- Regress/Scripts/fingerprint_screenout.py
Not regularly run, but a useful benchmarking/validation tool
> add a script for benchmarking fingerprint screenout and substructure performance

- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BasicMoleculeTests.java
Relatively simple fix to expose these two methods.
> Fixes #2532

- ReleaseNotes.md
- rdkit/Chem/PandasTools.py
Expose ForwardSDMolSupplier options to LoadSDF.
(also defaults to isomericsmiles, we might want to revert this change).
> Expose SDF loading options to LoadSDF

- Code/GraphMol/SmilesParse/SmilesParseOps.cpp
- Code/GraphMol/SmilesParse/test.cpp
> Check for duplicate bond creation during closure

- Docs/Book/Cookbook.md
Simplification of code
Greg already had a look at this and mailed me this:
"The approach you suggest is certainly simpler. Unfortunately, it's also a lot slower. Here's timing information for converting a single fingerprint on my linux box:
In [6]: %timeit numpy.asarray(fp)                                                                                         
1.59 ms ± 5.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [8]: %timeit arr=numpy.zeros((1,));DataStructs.ConvertToNumpyArray(fp,arr)                                             
48.5 µs ± 2.39 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
The simple approach takes about 30 times as long.
This likely isn't a performance critical piece of code, so I would be willing to willing to make the change …
> Code simplification for fingerprints to np array

- Docs/Book/RDKit_Book.rst
N/A
I added an aromatic Tellerium SMILES example and a section to describe RDKit's support of the SMILES extension for ring closures (%NNN) as referenced in #1624.
Thanks!
> Added te aromatic SMILES and ring closure extension example to RDKit_Book

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Also exposes a number of additional drawing functions to the Python API
Fixes #2571
> Allows dative bonds to be drawn

- rdkit/Chem/QED.py
N/A
Adds a missing reference from the docs that was mentioned but not included.
Also updates the first reference to use the shorter DOI URL and corrects a typo.
> Add missing Wildman and Crippen logP reference

- Code/GraphMol/Canon.cpp
- Code/GraphMol/SmilesParse/test.cpp
This fixes #2023. Doesn't seem a high profile bug, but it was fun looking into it.
Basically, the issue is that the double bond canonicalizer, which decides where the directed bonds should go, sets two directed bonds on the same atom, and assumes the second one will be inside a branch of the SMILES, and therefore, needs to be reversed (such that it has the same direction as the other directed bond on the same atom).
But that is not always the case: an exception are cycles from with the first directed bond branches off from a double bond in the cycle, which the second directed bond close, as in the molecule in the issue.
Fix consists in checking if the double bond for which directions are defined is in the same SMILES branch as the second bond, and do not reverse the direction if it is. …
> Fix to Issue #2023 (Canonizalizer assumed directed bond must be reversed)

- Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeatureFactory.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py
Not a complicated one to fix given that you can compose `with_custodian_and_ward_postcall`
> Fixes #2603

- rdkit/__init__.py
> Automatically load the ipython extensions running in Jupyter

- Docs/Book/Cartridge.md
> emolecules link updated

- External/CoordGen/CMakeLists.txt
Mostly small improvements, but also a bugfix in coordgen (schrodinger/coordgenlibs/pull/32)
> Update maeparser to 1.2.1 and coorgen to 1.3.1

- Docs/Book/Cartridge.md
Made examples compatible with latest chembl (25) and most recent conda versions of rdkit (2019.03.4.0, python 3.6.9) + rdkit-postgresql (2019.03.4.0)
> Updated cartridge documentation

- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Don't call `getCXExtensions()` if there's no SMILES
> Fixes #2667

- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
add a function to the SWIG wrappers along with a test for it
> Fixes #2239

- Code/PgSQL/rdkit/adapter.cpp
- Code/PgSQL/rdkit/expected/props.out
- Code/PgSQL/rdkit/expected/reaction.out
- Code/PgSQL/rdkit/mol_op.c
- Code/PgSQL/rdkit/rdkit.control
- Code/PgSQL/rdkit/rdkit.h
- Code/PgSQL/rdkit/rdkit.sql.in
- Code/PgSQL/rdkit/sql/props.sql
Also updates the expected values for the generated SVG
> support the new hashing code in the cartridge

- Code/GraphMol/PartialCharges/Wrap/rdPartialCharges.cpp
- Code/GraphMol/PartialCharges/Wrap/testPartialCharges.py
> fixes #2480

- Code/GraphMol/Wrap/ResonanceMolSupplier.cpp
- Code/GraphMol/Wrap/SDMolSupplier.cpp
- Code/GraphMol/Wrap/SmilesMolSupplier.cpp
- Code/GraphMol/Wrap/TDTMolSupplier.cpp
> update supplier documentation to reflect python 3 iterator syntax

- Code/RDStreams/CMakeLists.txt
- External/CoordGen/CMakeLists.txt
Let's see if this actually passes CI. It works fine on my windows box.
> Get zlib-free linking working on windows

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
Switch to using total H count instead of explicit h count and be sure to update the computed properties
> Fixes #2749

- Code/GraphMol/SmilesParse/SmilesWrite.h
Simple header fix for documentation.
> Add doRandom to the header docs

- Code/MinimalLib/demo/demo.html
- Code/MinimalLib/docker/Dockerfile
- Code/MinimalLib/tests/tests.js
A few things here:
1. Make the HTML demo page not look like crap
2. Changes to the Dockerfile for doing builds so that it works with newer versions of emscripten
3. Get the JS tests working again.
> Improvements to JS wrappers

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/catch_tests.cpp
Small change to allow AddHs() to be called on molecules with "unhappy" atoms.
> Fixes #2782

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
Not a particularly difficult fix.
> Fixes #2792

- Code/GraphMol/FMCS/FMCS.cpp
- Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
- Code/GraphMol/FMCS/Wrap/testFMCS.py
- Code/GraphMol/FMCS/testFMCS_Unit.cpp
@greglandrum I thought about
https://github.com/rdkit/rdkit/pull/2731#issuecomment-546175466
and I believe you are indeed right: there may be use cases for this.
So I thought it would have been better to submit this one straightaway before I forget everything about how this thing works.
> MatchFusedRings does not imply CompleteRingsOnly anymore

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
Molecules whose Y size is very small will reult in a blank canvas. See #2762 for details.
> Fixes #2762

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/smatest.cpp
This fixes #2814 and #2815 
Both are simple fixes
> Fix a couple of smarts bugs

- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.h
- Code/GraphMol/DistGeomHelpers/Embedder.cpp
There was some data-structure initialization work not happening with user-provided bounds matrices.
> Fix for github #2800

- Code/SimDivPickers/testPickers.cpp
This PR addresses #2839. Now the test fails only if the same pick is found 3 times in a row.
> Fixes #2839

- Code/GraphMol/FileParsers/ProximityBonds.cpp
- Code/GraphMol/FileParsers/test1.cpp
- added code to to recognize RNA and DNA bases.
- added relevant tests
> Fixes #2822

- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
Allows the size of the SVG to be specified by adding optional arguments.
> Fixes #2858

- Code/PgSQL/rdkit/Makefile
- Code/PgSQL/rdkit/README
* PGRdkit Cartrige not building due to Makefile issues
* RD and INCHI lib switches in the Makefile missing RDKit prefixes
* Added 3 lines referenced in a comment to issue #2192
> Improve PostgreSQL cartridge install documentation

- Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
- Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp
- Code/GraphMol/ForceFieldHelpers/UFF/testUFFHelpers.cpp
- rdkit/Chem/Pharm3D/UnitTestEmbed.py
Adds the fix and updates the tests
This makes the original PR #2463  redundant, so I'll convert that to an issue.
> Fixes #2463

- rdkit/Chem/PandasTools.py
- rdkit/Chem/UnitTestPandasTools.py
I end up using this function more or less whenever I work with the RGD code, so I figure it's worth adding it to `PandasTools`
> add a convenience function for RGD--Pandas integration

- Code/PgSQL/rdkit/expected/molgist.out
- Code/PgSQL/rdkit/sql/molgist.sql
should have been fixed as part of #2869
> Update one of the cartridge tests that got missed

- Code/GraphMol/ChemReactions/Enumerate/EnumerationStrategyBase.h
- Code/GraphMol/ChemReactions/Enumerate/RandomSampleAllBBs.h
Simple fix for a pvs studio found issue (came up while doing the work for #2877)
Also updates the documentation
> Fix redundancy in RandomSampleAllBBs

- Code/JavaWrappers/CMakeLists.txt
- Code/JavaWrappers/gmwrapper/CMakeLists.txt
These help building on Windows
> java wrapper build cleanups

- Code/JavaWrappers/MolDraw2D.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
Exposes useable versions of `contourAndDrawGaussians()` and `contourAndDrawGrid()` with SWIG
> Fixes #2896

- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/MolPickler.h
- Code/GraphMol/Wrap/Mol.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/testPickler.cpp
Optionally pickle confs as double precision.
> Fixes #2510

- Code/GraphMol/Resonance.cpp
- Code/GraphMol/Substruct/SubstructMatch.cpp
These only show up if you build with the thread safety stuff disabled.
> Fix a couple of residual problems created by #2899

- Code/GraphMol/FileParsers/testMolSupplier.cpp
> Fixes #2929

- Code/GraphMol/MolStandardize/Tautomer.cpp
- Code/GraphMol/MolStandardize/Tautomer.h
- Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
- Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
- Code/GraphMol/MolStandardize/testTautomer.cpp
Comes out of the discussion on #2908 
Also in here:
- documentation improvements
- exposing the tautomer scoring to Python
> Tune the tautomer scoring

- Code/RDGeneral/RDValue.h
> Don't switch locales unless really necessary (float/double)

- Docs/Book/data/README.md
Description of two sdf files are added based on Greg's reply to Zhenting on Feb. 2020.
> Description for the data files.

- Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
- Code/GraphMol/ScaffoldNetwork/Wrap/testScaffoldNetwork.py
there was a copy-paste bug in the wrappers for the scaffold network
This fixes that and adds a few additional testss
> fix a typo in the scaffold network wrappers and add some tests

- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
Adds a couple more utility functions so that the JS wrappers are more useful as a backend for a sketcher.
> add add_hs() and remove_hs() to JS wrappers

- rdkit/Chem/Draw/IPythonConsole.py
Fixes #2786 
add two helper functions
I am not pretty sure if it's good enough. Let me know if I can improve in any aspect.
> add EnableSubstructMatchRendering and DisableSubstructMatchRending

- Code/GraphMol/MolStandardize/MolStandardize.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
Fixes issue #2965 
Changes made to the the cleanup function in MolStandardize.cpp and catch_tests.cpp.
None.
> Possible fix for issue #2965

- Code/GraphMol/MolStandardize/Tautomer.cpp
- Code/GraphMol/MolStandardize/Tautomer.h
- Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
- Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
- Code/GraphMol/MolStandardize/testTautomer.cpp
This is information that it can be useful to have elsewhere
> allow retrieval of the atoms/bonds modified by the tautomerization

- Code/GraphMol/MolDraw2D/MolDraw2D.h
Added a couple missing exports.
> Fixes DLL build failure

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
This also has a bunch of clang-format changes mixed in.
The actual change is at line 2078 of `MolDraw2D.cpp`
> Unset the dash pattern after drawing aromatic bonds.

- rdkit/Chem/Draw/__init__.py
It looks like there was a typo in `rdkit/Chem/Draw/__init__.py`.
> - fixes GitHub #3046

- Code/GraphMol/Resonance.cpp
- Code/GraphMol/Resonance.h
- Code/GraphMol/resMolSupplierTest.cpp
Also added a test for maxStructs and a couple of missing const.
> Fixes #3041

- CMakeLists.txt
- Code/cmake/Modules/RDKitUtils.cmake
This should get python to build on OSX.
> Only link to python if it was built shared

- Code/DataStructs/DiscreteValueVect.cpp
- Code/DataStructs/DiscreteValueVect.h
- Code/DataStructs/SparseIntVect.h
- Code/GraphMol/AddHs.cpp
- Code/GraphMol/Depictor/EmbeddedFrag.h
- Code/GraphMol/Descriptors/AtomFeat.cpp
- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
- Code/GraphMol/FileParsers/testMolSupplier.cpp
- Code/GraphMol/FindRings.cpp
- Code/GraphMol/Fingerprints/MHFP.cpp
- Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp
- Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp
- Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
- Code/GraphMol/MolAlign/O3AAlignMolecules.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/ChemicalFeatureUtils.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/MolStandardize/Validate.h
- Code/GraphMol/SmilesParse/SmilesParse.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
- Code/GraphMol/Substruct/SubstructMatch.cpp
- Code/GraphMol/Substruct/catch_tests.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/SubstanceGroup.cpp
- Code/GraphMol/Wrap/props.hpp
- Code/RDBoost/python_streambuf.h
The return of a classic: I did a sweep over the different build warnings I was seeing for different compiler versions and platforms.
Each commit addresses one warning, so that each commit is kind of a self contained fix.
> Address build warnings

- README.md
Fixes broken link to ``stk`` docs, due to domain change.
> Updated stk link.

- Docs/Book/Install.md
These were vestigial and were causing problems for some people.
> Update old windows install instructions

- External/catch/CMakeLists.txt
> Bump Catch2 to v2.12.1

- Code/DataStructs/BitOps.cpp
- Code/Demos/RDKit/Basement/TemplEnum/TemplEnumTools.cpp
- Code/Geometry/UniformGrid3D.cpp
- Code/GraphMol/FileParsers/PDBParser.cpp
- Code/GraphMol/FileParsers/ProximityBonds.cpp
- Code/GraphMol/MolAlign/O3AAlignMolecules.cpp
- Code/GraphMol/MolTransforms/MolTransforms.cpp
- Code/Numerics/Alignment/AlignPoints.cpp
- Code/Numerics/Conrec.h
- Code/Numerics/EigenSolvers/PowerEigenSolver.cpp
- Code/RDBoost/iterator_next.h
> Avoid C preprocessor macros

- Code/GraphMol/Depictor/RDDepictor.cpp
- External/CoordGen/CoordGen.h
- External/CoordGen/test.cpp
center coordinates coming from coordgen unless there's  reason not to do so
> Fixes #3131

- Code/GraphMol/ChemReactions/Reaction.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
> fixes #3119

- Code/GraphMol/catch_sgroups.cpp
- Code/GraphMol/testSGroup.cpp
Fixes #3135
Tested using this Dockerfile:
````
FROM fedora:32
ENV DEBIAN_FRONTEND=noninteractive
RUN dnf upgrade -y && dnf install -y \
curl \
wget \
make \
boost-devel \
cmake \
git \
g++ \
eigen3-devel
WORKDIR /src
RUN git clone https://github.com/rdkit/rdkit rdkit
ADD build.sh /src/rdkit
RUN chmod +x /src/rdkit/build.sh
````
and this build.sh:
````
mkdir -p build && cd build
cmake -DRDK_BUILD_PYTHON_WRAPPERS=OFF -DRDK_BUILD_CPP_TESTS=ON ..
make -j$(nproc)
make install
RDBASE=/src/rdkit/ -j$(nproc) --output-on-failure -T Test
````
> Remove unnecessary braces. Fix #3135

- Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smiles.yy
- Code/GraphMol/SmilesParse/test.cpp
This was detected by OSS-Fuzz.
The problematic SMILES was `C(`.
Simple fix
> fix a memory problem detected in malformed SMILES

- Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
- Code/GraphMol/FMCS/testFMCS_Unit.cpp
- Code/GraphMol/MMPA/MMPA.cpp
- Code/GraphMol/MMPA/MMPA_UnitTest.cpp
This was still hanging around in a few files.
> remove usage of auto_ptr

- Code/GraphMol/Wrap/Queries.cpp
- Code/GraphMol/Wrap/rough_test.py
add the missing wrapper functions
> Fixes #3198

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
> fixes stereo mapped to non bonded stereo in reaction

- Code/GraphMol/ChemTransforms/ChemTransforms.cpp
- Code/GraphMol/ChemTransforms/testChemTransforms.cpp
- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Turns out that these two are related only in theme, but this fixes both of them. :-)
> Fixes #3197 and #3206

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
1. Reduces the number of lines in the dash
2. Does the empirical check as to whether or not we have too many dashes in the correct coordinate system (drawing instead of molecular)
> Fixes #3226

- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
Adds support for parsing APO lines from v2000 mol blocks
> fixes #3207

- Code/GraphMol/MolDraw2D/test1.cpp
The BetterLegends PR was merged without a call to the test code in test1.cpp.
Sorry!
> Added call to test legends.

- Scripts/create_deb_packages.sh
> cairo support is needed to generate PNGs

- CMakeLists.txt
- Code/GraphMol/Descriptors/PMI.cpp
- Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py
- Code/GraphMol/Descriptors/test3D.cpp
some small changes to get this working.
@jaimergp did the legwork to find a system to test on and confirm that everything functions.
Apologies that reformatting ended up getting mixed into the python test file; I noticed that too late.
The only substantive changes are on lines 350 and 365 of that file.
> Get PPC builds working

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/testChirality.cpp
Cleans up and simplifies (a bit) the code for perceiving chirality
based on a conformer and wedged bonds.
> Fixes #3314

- Code/GraphMol/catch_adjustquery.cpp
> add test for #3325

- Docs/Book/conf.py
This allows the docs to build with recent versions of sphinx.
> Remove deprecated Sphinx options

- Code/GraphMol/FileParsers/FileParserUtils.h
- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/MolPickler.h
- Code/GraphMol/SmilesParse/SmilesParse.cpp
- Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smarts.yy
- Code/GraphMol/SmilesParse/smatest.cpp
- Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake
- Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake
- Code/GraphMol/SmilesParse/smiles.yy
- Code/GraphMol/SmilesParse/test.cpp
none of these are super urgent, but it certainly doesn't hurt to fix them.
> more bug fixes and cleanups from fuzz testing

- Code/GraphMol/SmilesParse/SmilesParseOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
This is a one-liner to set the appropriate property on the bond in `AddFragToMol()`
> Fixes #3342

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
let's hear it for easy bug fixes. :-)
> Fixes #3393

- Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
This corrects the logic in `isAtomCandForChiralH()`
There's a bit of code modernization in here too.
> Fixes #3392

- Code/GraphMol/Substruct/SubstructMatch.cpp
- Code/GraphMol/Wrap/rough_test.py
> Fixes #3403

- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
This is another one of those SUPER simple fixes. 
yeah!
> Fixes #3413

- Code/GraphMol/FileParsers/MolSGroupParsing.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
Small fix to handle quoted `"` characters in v3000 properties
> Fixes: #3415

- Code/GraphMol/RGroupDecomposition/RGroupCore.h
- Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
- Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
- code modernization
- removed unnecessary `O(n)` generation of `const` set
> Code modernization and an optimization

- Contrib/M_Kossner/Frames.py
- rdkit/utils/cactvs.py
basestring is outdated, and throws an error when used with Python3
> Replace basestring

- Code/MinimalLib/docker/Dockerfile
looks like the emscripten requirements have changed
> update minimallib python requirements to python3

- Code/MinimalLib/demo/demo.html
- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
> expose templated coordinate generation to the JS Wrapper

- Code/MinimalLib/demo/demo.html
allows coordgen to be used to generate coordinates in the demo when doing template alignment.
> add coordgen support to demo.html

- External/CoordGen/CoordGen.h
- External/CoordGen/Wrap/rdCoordGen.cpp
- ReleaseNotes.md
also makes preset precision settings accessible
> change default precision for coordgen

- Code/GraphMol/MolStandardize/testNormalize.cpp
- Data/MolStandardize/normalizations.txt
simple update to the normalization rules here
> Fixes #3460

- Code/GraphMol/MolDraw2D/DrawText.h
- Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
- Code/GraphMol/MolDraw2D/DrawTextCairo.h
- Code/GraphMol/MolDraw2D/DrawTextFT.h
- Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
- Code/GraphMol/MolDraw2D/DrawTextFTCairo.h
- Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp
- Code/GraphMol/MolDraw2D/DrawTextFTSVG.h
- Code/GraphMol/MolDraw2D/DrawTextSVG.cpp
- Code/GraphMol/MolDraw2D/DrawTextSVG.h
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.h
- Code/GraphMol/MolDraw2D/MolDraw2DUtils.h
- Code/GraphMol/MolDraw2D/MultiMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/rxn_test1.cpp
- Code/GraphMol/MolDraw2D/test1.cpp
no actual content changes here, this is purely formatting
> run clang-format over MolDraw2D

- Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp
- Code/GraphMol/FMCS/testFMCS_Unit.cpp
This PR fixes GitHub issue #3458.
Really simple fix - once I found out the source of the problem :-/
> Fixes #3458

- Code/GraphMol/Atom.cpp
- Code/GraphMol/catch_graphmol.cpp
Simple fix to make it clear that H doesn't act like an "early" atom (i.e. adding a negative charge makes it happy, it doesn't cause it to need additional implicit Hs.
> Fixes #3470

- Docs/Book/BackwardsIncompatibleChanges.md
- Docs/Book/GettingStartedInPython.rst
- Docs/Book/RDKit_Book.rst
- Docs/Book/source/rdkit.Chem.MolDraw.rdMolDraw2D.rst
- Docs/Book/source/rdkit.Chem.rdAbbreviations.rst
- Docs/Book/source/rdkit.Chem.rdDeprotect.rst
- Docs/Book/source/rdkit.Chem.rst
- adds the new modules to the python documentation
- does a bit of cleanup
- does a bit of updating
> Documentation update

- Code/GraphMol/Abbreviations/AbbreviationsUtils.cpp
- Code/GraphMol/AddHs.cpp
- Code/GraphMol/ChemReactions/PNGParser.cpp
- Code/GraphMol/FileParsers/GeneralFileReader.h
- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h
- Code/GraphMol/FileParsers/PNGParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/FileParsers/test1.cpp
- Code/GraphMol/FindStereo.cpp
- Code/GraphMol/MolDraw2D/DrawText.cpp
- Code/GraphMol/MolEnumerator/enumerator_catch.cpp
- Code/GraphMol/MolStandardize/Tautomer.cpp
- Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
- Code/GraphMol/MolStandardize/testTautomer.cpp
- Code/GraphMol/ScaffoldNetwork/catch_tests.cpp
- Code/GraphMol/Wrap/SubstanceGroup.cpp
- Code/GraphMol/catch_adjustquery.cpp
- Code/GraphMol/hanoitest.cpp
- External/FreeSASA/Wrap/rdFreeSASA.cpp
This PR include fixes for a number of issues flagged by `clang` in the macOS CI log.
> Fixes a number of issues flagged by clang

- Code/GraphMol/Fingerprints/Fingerprints.h
- Code/GraphMol/Wrap/MolOps.cpp
this should have been in there long ago
> add a version for the pattern fingerprint

- External/CoordGen/CMakeLists.txt
> maeparser 1.2.4

- Code/GraphMol/FileParsers/SDMolSupplier.cpp
- Code/GraphMol/FileParsers/testMolSupplier.cpp
- Code/GraphMol/Wrap/rough_test.py
This turned out to be a really simple one.
> Fixes #3517

- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/Wrap/test_data/github3553.sdf
- Code/RDBoost/python_streambuf.h
adds logic to python_streambuf.h to detect UTF-8 characters at the end of a block and shift them to the next block
> Fixes #3553

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Simple fix.
Thanks to @DavidACosgrove for pointing me in the right direction.
> Fixes #3577

- Code/GraphMol/SmilesParse/SmilesParse.h
- Code/GraphMol/Wrap/rdmolfiles.cpp
This PR fixes the incorrect result of the example in `MolToSmiles` documentation.
> Fix example of SmilesToMol

- Code/MinimalLib/docs/GettingStartedInJS.html
Adds a simple HTML file documenting a lot of the functions of the JS wrappers.
> add documentation for the JS wrappers

- Code/GraphMol/FileParsers/FileParsers.h
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
also adds a small test for PDB flavors
> Fixes #3089

- Code/GraphMol/PeriodicTable.cpp
- External/INCHI-API/inchi.cpp
some pretty bad mistakes in the way multithreading was being built.
> Fixes #3646

- .azure-pipelines/linux_build_limitexternal.yml
- Code/GraphMol/Depictor/RDDepictor.cpp
- Code/GraphMol/Depictor/RDDepictor.h
- Code/GraphMol/FileParsers/GeneralFileReader.h
- Code/GraphMol/FileParsers/testGeneralFileReader.cpp
- azure-pipelines.yml
Builds without support for Coordgen and MAEParser now work.
I also added a CI target for a minimal-external-dependency build.
> Fixes #3648

- External/INCHI-API/inchi.cpp
- External/INCHI-API/test.cpp
> A couple of InChI bug fixes

- Code/GraphMol/MolChemicalFeatures/Wrap/MolChemicalFeature.cpp
- Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py
- Docs/Book/GettingStartedInPython.rst
- rdkit/Chem/Pharm3D/Pharmacophore.py
Fixes #2530
- Added a second method to the python wrapper (in the Wrap/MolChemicalFeature.cpp file) that takes no arguments and that points to the overload MolChemicalFeature::getPos().
- Remove the default value from the method.
- Added tests for new functionality
> Fix for Github issue 2530

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/catch_tests.cpp
- Code/GraphMol/MolEnumerator/CMakeLists.txt
- Code/GraphMol/MolEnumerator/LinkNode.cpp
- Code/GraphMol/MolEnumerator/LinkNode.h
These are just another type of bracket, which we already know how to do.
Examples:
> Support rendering LinkNodes

- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
Exposes the function we already have to Python
> support setting MolDraw2DOptions using JSON from Python

- Code/GraphMol/MolEnumerator/MolEnumerator.cpp
- Code/GraphMol/MolEnumerator/MolEnumerator.h
- Code/GraphMol/MolEnumerator/Wrap/rdMolEnumerator.cpp
- Code/GraphMol/MolEnumerator/Wrap/rough_test.py
- Code/GraphMol/MolEnumerator/enumerator_catch.cpp
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolEnumeratorTests.java
- support enumerating from lists of operations
- support enumerating all supported operations for a molecule
> Expanded MolEnumerator functionality

- Code/GraphMol/Fingerprints/Fingerprints.h
- Code/GraphMol/Fingerprints/PatternFingerprints.cpp
- Code/GraphMol/Fingerprints/catch_tests.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/FingerprintsTests.java
The pattern fingerprint for the bundle is generated by anding the pattern fingerprints of the molecules it contains
> add support for generating pattern fps for MolBundles

- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/Wrap/CMakeLists.txt
- Code/GraphMol/Wrap/MolOps.cpp
> Move MolToSVG() to rdkit.Chem.Draw (Addresses #3694)

- Code/JavaWrappers/ROMol.i
Add MolBundle substructure search to Java API
> Add Molbundle search to SWIG

- rdkit/Chem/PandasTools.py
On moving from v1.1 -> v1.2 the pandas team made the previously "private" function `_get_adjustment()` public by renaming it to `get_adjustment()`.
This works around that change while still maintaining backwards compatibility
> Fixes #3701

- Code/PgSQL/rdkit/CMakeLists.txt
- Code/PgSQL/rdkit/adapter.cpp
- Code/PgSQL/rdkit/expected/fmcs.out
- Code/PgSQL/rdkit/expected/rdkit-91.out
- Code/PgSQL/rdkit/sql/fmcs.sql
- Code/PgSQL/rdkit/sql/rdkit-91.sql
This fixes a number of places where bad input would crash the cartridge.
The specific issues covered are: #3687, #3688, #3689
> Fix a number of cartridge stability problems

- Code/GraphMol/Fingerprints/FingerprintUtil.cpp
- Code/GraphMol/Fingerprints/test1.cpp
Fixes #3723 by just considering physical bonds to calculate the degree.
This sounds reasonable to me, but I'm wondering if using `getValenceContrib(atom) != 0.0` would be more appropriate.
> Address Issue 3723

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
> Fixes #3744

- Code/GraphMol/Wrap/MolOps.cpp
simple doc change, will merge after CI builds pass
> Fixes #3670

- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/Draw/__init__.py
need to be sure that the correct `DrawMolecule()` method is called
> fixes #3762

- Code/GraphMol/FileParsers/MolSGroupWriting.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
simple change to make sure we double double quotes in the output of V3K mol blocks
> Fixes #3768

- Code/GraphMol/CIPLabeler/CIPLabeler.h
- Code/GraphMol/CIPLabeler/Wrap/rdCIPLabeler.cpp
- Docs/Book/RDKit_Book.rst
- Docs/Code/CIPLabeling.md
> Replace − (U+2212, MINUS SIGN) with – (U+2013, EN DASH)

- Code/GraphMol/Wrap/Atom.cpp
- Code/GraphMol/Wrap/rough_test.py
Fixes #1631
- New method `SetPDBResidueInfo` in python wrapper
- New test for new functionality
> Fixes Github issue 1631

- Code/GraphMol/SubstructLibrary/PatternFactory.cpp
- Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
- Code/GraphMol/SubstructLibrary/SubstructLibrary.h
- Code/GraphMol/SubstructLibrary/substructLibraryTest.cpp
> Fixes crashes when using bad smiles in the cached smiles holders

- .azure-pipelines/linux_build_java.yml
- Code/Geometry/point.h
- Code/GraphMol/ChemTransforms/MolFragmenter.cpp
- Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
- Code/GraphMol/FileParsers/MolSGroupWriting.h
- Code/GraphMol/FileParsers/testMolSupplier.cpp
- Code/GraphMol/Fingerprints/MorganFingerprints.cpp
- Code/GraphMol/Fingerprints/MorganGenerator.cpp
- Code/GraphMol/Fingerprints/PatternFingerprints.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolInterchange/Parser.cpp
- Code/GraphMol/QueryOps.cpp
- Code/GraphMol/RGroupDecomposition/RGroupGa.h
- Code/GraphMol/RGroupDecomposition/RGroupUtils.cpp
- Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
- Code/GraphMol/Subgraphs/SubgraphUtils.h
- Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h
- Code/RDBoost/python_streambuf.h
- Code/RDGeneral/BoostStartInclude.h
- External/GA/ga/BinaryStringChromosomePolicy.cpp
- External/GA/ga/LinkedPopLinearSel.h
- External/INCHI-API/inchi.cpp
Been a while since we did a pass to clear up compiler warnings...
> cleanup a bunch of compiler warnings

- rdkit/Chem/PandasTools.py
There was a forgotten import here
> PandasTools.RGroupDecomposition throws an error when redraw_sidechains is set to True.

- rdkit/Chem/Draw/cairoCanvas.py
- rdkit/ML/MLUtils/VoteImg.py
- rdkit/sping/PDF/pdfgen.py
- rdkit/sping/PDF/pdfutils.py
- rdkit/sping/PS/pidPS.py
- rdkit/sping/WX/pidWxDc.py
A bit of cleanup in parts of the code which need to be deprecated anyway
See #3730 for description of the change
> Fixes #3730

- Code/Geometry/point.h
> remove an MSVC++ warning caused by #3849

- Code/GraphMol/Wrap/MultithreadedSDMolSupplier.cpp
- Code/GraphMol/Wrap/MultithreadedSmilesMolSupplier.cpp
- Code/GraphMol/Wrap/testMultithreadedMolSupplier.py
This should have been part of the changes in #3704
> include context managers for the multithreaded suppliers too

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/catch_graphmol.cpp
- Code/GraphMol/molopstest.cpp
Small changes to fix #3932 
1. make sure the H vector to the H points away from the opposite bond
2. fix the calculation of the perpendicular direction in the handling of #3854
> Fixes #3932

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
This is a small one that enables changing the color of annotations in MolDraw2D
> MolDraw2D: support changing annotation colours

- Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
- Code/GraphMol/ForceFieldHelpers/Wrap/testHelpers.py
Fixed #3824, added tests and removed deprecation warnings.
> Fixes #3824

- Docs/Book/Overview.md
- README.md
Hello rdkit developers
Our group have developed the [Scopy](https://github.com/kotori-y/Scopy) (Screnning COmpounds in PYthon), an integrated negative design python library designed for screening out undesiable compounds in the early drug discovery, which depend on RDKit. [Here](https://doi.org/10.1093/bib/bbaa194) is a paper about our project.
We would be very honored if our project can appear on the [list](https://github.com/rdkit/rdkit#projects-using-rdkit).
Thanks!
Kotori Yang
> appended a new project depend on RDKit

- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
Sometimes atom lines "in the wild" don't have enough characters after the atomic symbol.
We can parse these unambiguously, so allow them to be parsed when `strictParsing` is off.
> allow short atom lines in mol blocks when strictParsing is disabled

- .azure-pipelines/linux_build_fuzzer.yml
the version changed on azure pipelines
> update clang version for linux CI fuzzer builds

- .gitignore
- Code/GraphMol/MolPickler.h
- Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
This PR fixes the C# wrapper. Current master repo fails to build.
> Get SWIG wrappers working with C# again

- Docs/Book/Overview.md
- README.md
Adding the [datamol](https://github.com/datamol-org/datamol/) project to the list of open-source projects.
> Add datamol project

- Code/DataStructs/SparseIntVect.h
- Code/DataStructs/testDatastructs.cpp
> Fixes #3944

- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
> get the JS wrappers working again

- rdkit/Chem/Draw/__init__.py
Simple fix for a bit of code which never worked.
> Fixes #3616: highlightColor argument not working with MolToImage

- Code/GraphMol/MolStandardize/MolStandardize.cpp
- Code/GraphMol/MolStandardize/MolStandardize.h
- Code/GraphMol/MolStandardize/catch_tests.cpp
- Code/MinimalLib/CMakeLists.txt
- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/cffiwrapper.cpp
- Code/MinimalLib/cffiwrapper.h
- Code/MinimalLib/common.h
This seems like useful functionality to have available via CFFI
It will be easy to also add support to the JS wrappers, but that needs to wait until all of the MolStandardize code works without needing default parameters from disk. That will be a separate PR.
> Add some MolStandardize functionality to the CFFI library

- External/AvalonTools/AvalonTools.cpp
- External/AvalonTools/test1.cpp
Just needed to add some book-keeping
> Fixes #4075

- Code/GraphMol/ChemTransforms/ChemTransforms.cpp
- Code/GraphMol/ChemTransforms/testChemTransforms.cpp
`replaceSidechains` should clear the aromatic flag from dummy atoms.
> replaceSidechains creates aromatic dummy atoms

- README.md
- deleted deprecated MyChEMBL
- added ChEMBL_Structure_Pipeline and FPSim2
> update ChEMBL projects in Projects using RDKit

- Code/GraphMol/RWMol.cpp
- Code/GraphMol/catch_graphmol.cpp
just need to loop over the right indices
> Fixes #4122

- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/cffiwrapper.cpp
Ensure that the molecule we're using as a template actually has a conformer
> fixes #4121

- Code/GraphMol/Wrap/EditableMol.cpp
Fixes #3421
Simple change in documentation to make it match the actual behavior.
Changing the implementation would probably break quite a few things.
> fixed AddBond documentation

- Code/GraphMol/FileParsers/CMLWriter.cpp
- Code/GraphMol/Fingerprints/FingerprintUtil.cpp
- Code/GraphMol/ROMol.cpp
- Code/GraphMol/RWMol.cpp
- Code/GraphMol/catch_graphmol.cpp
This goes a bit beyond the original problem report and fixes some closely related problems I noticed while fixing this one.
> Fixes #4127

- Code/GraphMol/RGroupDecomposition/RGroupCore.cpp
- Code/GraphMol/RGroupDecomposition/RGroupCore.h
- Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
Addresses #4168 
Added comments to explain matching strategy for when cores contain user defined R groups.
Also moved function body code from RGroupCore.h to RGroupCore.cpp
> Comments added to RGD core matching

- Code/GraphMol/FindStereo.cpp
- Code/GraphMol/catch_chirality.cpp
removes the shared-bond restriction for potential chiral centers
add support for chiral bridgehead nitrogens
The discussion in the issue has more, but the key change here is being more "permissive" about which centers are potential stereocenters. 
An illustrative example:
atoms 2 and 5 are now both considered as possible stereocenters; previously there was a special case which excluded these. The code for this special case wasn't super complex but did have gaps - #4155 shows one of the them - and isn't completely consistent - for example adamantanes were still recognized as having "extra" chiral centers according to the old rules.
With the simplification here the code is now more focused on symmetry and less on what is physically realizable, as suggested by @jepdavison in the original …
> Potentially chiral bridgehead atoms not being identified.

- Code/GraphMol/Canon.cpp
N/A
added a flip bond dir function to remove repeated code inside the canonicalizeDoubleBond function
> Canon.cpp canonicalizeDoubleBond function refactor

- Code/GraphMol/Descriptors/Property.cpp
this accidentally got removed in #4200
> restore exactmw

- Code/GraphMol/Fingerprints/Wrap/AtomPairWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/RDKitFPWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/testGenerators.py
- Code/GraphMol/Fingerprints/catch_tests.cpp
- ReleaseNotes.md
1. the countBounds arguments were not working
2. the GetXXXGenerator() functions used inconsistent naming for the countSimulation argument
3. there were no tests to make sure that the changing countBounds actually did something
> Fix a couple of problems with fingerprint count simulation

- Code/GraphMol/Kekulize.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/catch_graphmol.cpp
In order to fix this problem I needed to add a function which kekulizes a fragment of a molecule instead of the whole thing.
That new function is currently in the `MolOps::details` namespace since I really don't think it should be used from other code until we've tested it more thoroughly and are sure we're happy with the behavior.
> Fixes #3998

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
The fix is one letter, the test is 10 lines. :-)
> Fixes #4260

- Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in
- Code/GraphMol/MolStandardize/testNormalize.cpp
Made the pyridine _N_-oxide pattern more specific and added a test.
> Fixes #4281

- Code/GraphMol/FindRings.cpp
- Code/GraphMol/catch_graphmol.cpp
Just need to be sure to return from the ring finding code after using FastFindRings.
> Fixes #4266

- Code/GraphMol/MolDraw2D/DrawTextCairo.cpp
- Code/GraphMol/MolDraw2D/DrawTextFTCairo.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Adding support for using the alpha channel actually ends up being pretty straightforward.
> Fixes #4323

- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
it's already in the minimallib, just need to get it into the JS wrapper
> support get_json in the rdkitjs wrapper

- Code/GraphMol/ShapeHelpers/ShapeUtils.cpp
- Code/GraphMol/ShapeHelpers/testShapeHelpers.cpp
> Fixes #4364: use the gridSpacing argument correctly when calculating shape tanimotoDistance

- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
we will also eventually need a version of this which works with the newer stereo perception code.
> fixes #4345

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Some queries were actually being parsed incorrectly when CXSMARTS info was there.
> fix a bug with query handling in CXSMARTS

- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/Draw/UnitTestIPython.py
Fixes #3101 and adds a couple of tests.
> Fixes #3101

- Code/GraphMol/FMCS/Test/testFMCS.cpp
- Code/GraphMol/FMCS/testFMCS_Unit.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/FindRings.cpp
- Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
- Code/GraphMol/MMPA/MMPA_UnitTest.cpp
- Code/GraphMol/MolTransforms/MolTransforms.cpp
- Code/GraphMol/Substruct/catch_tests.cpp
- Code/GraphMol/Substruct/test1.cpp
- Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
- Code/GraphMol/SubstructLibrary/catch_tests.cpp
- Code/GraphMol/TautomerQuery/catch_tests.cpp
- Code/GraphMol/catch_chirality.cpp
- Code/GraphMol/catch_graphmol.cpp
There aren't that many anyway, but this should get rid of most of the ones which are left
> cleanup some compiler warnings

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
An attempt to improve readability and lessen the number of questions which end up submitted as issues.
> update github templates

- Code/PgSQL/rdkit/expected/props.out
- Code/PgSQL/rdkit/expected/rdkit-91.out
- Code/PgSQL/rdkit/rdkit.sql.in
- Code/PgSQL/rdkit/sql/props.sql
- Code/PgSQL/rdkit/sql/rdkit-91.sql
- Code/PgSQL/rdkit/update_sql/rdkit--3.8--4.0.sql.in
Changes here:
- add mol_adjust_query_properties(qmol)
- add mol_to_svg(qmol)
> another round of cartridge improvements

- rdkit/Chem/SaltRemover.py
- rdkit/Chem/UnitTestSaltRemover.py
Closes #4550
This adds an argument to make sanitization after salt removal optional.
> Fixes #4550

- Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/testGenerators.py
This supports getting fingerprints or count fingerprints as Numpy arrays directly from the fingerprint generator interface.
> Fixes #4273

- Code/GraphMol/MolStandardize/Tautomer.h
- Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp
- Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py
- Code/GraphMol/MolStandardize/testTautomer.cpp
* changed `unique_ptr` into `shared_ptr`
* added Python copy constructor
* added C++ and Python tests for the copy constructor
> Fixes #4736

- azure-pipelines.yml
Move off the deprecated platform
Update boost an python versions
> Update mac CI builds

- rdkit/Chem/PandasTools.py
This PR is motivated by the need to fix my `PandasTools` integration, which broke this morning due to a `pandas` update in the Python environment occurred during the weekend.
I noticed that the `PandasTools` module already complied with the fact that the `get_adjustment` attribute in the `pandas.io.formats.format` module can have different spellings across `pandas` versions, but in another part of `PandasTools` module the attribute was still referenced with a hardcoded `_get_adjustment` name, which caused it to fail on my `pandas` version (1.3.2).
While going through the code I also did some minor cleanup.
* Use the relevant `get_adjustment/_get_adjustment` attribute consistently across the `PandasTools` module
* Remove some unused code
* Clean up imports a bit
> Minor PandasTools cleanup

- Code/GraphMol/ChemReactions/DaylightParser.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
Minor change to strip out extra stuff at the end of a reaction SMARTS/SMILES since we can't parse it anyway
> Fixes #4759

- Code/GraphMol/Substruct/SubstructMatch.h
Roger requested these warnings squashed in MSVC compiles.
> silence warnings in MSVC compilations

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
- Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
- Code/GraphMol/MolDraw2D/catch_tests.cpp
This includes fixes for #4838, #4837, and #4836
These are, luckily, all small changes
> Fixes a few MolDraw2D problems

- rdkit/CMakeLists.txt
- rdkit/Chem/CMakeLists.txt
- rdkit/Chem/PandasTools.py
- rdkit/Chem/nbtests/github4823.ipynb
#4821 is super simple.
For #4823 we just need to keep track of whether or not the patching was done in the pandas package.
This also adds a notebook test to `rdkit.Chem`. This explicitly tests #4823 and implicitly tests #4821.
Note that the commit message on b172946 should be:
Fixes #4823
> Fixes #4821 and #4823

- Code/GraphMol/CMakeLists.txt
Fixes #4875 
- Add missing dependency for target: `RDKit::GraphMol_static`.
- This is probably not the most general solution, so suggestions for improvement are very welcome.
> Implemented a quick fix for issue 4875

- Code/GraphMol/Depictor/DepictUtils.cpp
- Code/GraphMol/Depictor/DepictUtils.h
- Code/GraphMol/Depictor/EmbeddedFrag.cpp
- Code/GraphMol/Depictor/EmbeddedFrag.h
- Code/GraphMol/Depictor/RDDepictor.cpp
- Code/GraphMol/Depictor/RDDepictor.h
I have some changes I want to make in the depictor code, but it was just making my eyes burn so I did a bit of cleanup and refactoring.
Nothing really substantive here, it's mainly just switching to a more modern idiom.
> Some refactoring of the depictor code

- rdkit/Chem/AtomPairs/Pairs.py
- rdkit/Chem/AtomPairs/Sheridan.py
- rdkit/Chem/AtomPairs/Torsions.py
- rdkit/Chem/AtomPairs/Utils.py
- rdkit/Chem/AtomPairs/test_list.py
This is the first trial in breaking down the large PR 4815 #4815
> Clean-up Python 4815 - P1.1: Chem\AtomPairs

- rdkit/Chem/ChemUtils/AlignDepict.py
- rdkit/Chem/ChemUtils/BulkTester.py
- rdkit/Chem/ChemUtils/DescriptorUtilities.py
- rdkit/Chem/ChemUtils/SDFToCSV.py
- rdkit/Chem/ChemUtils/TemplateExpand.py
This is the sub-PR breaking from the large PR #4815
> Clean-up Python #4815 - P1.2: Chem/ChemUtils

- Docs/Book/RDKit_Book.rst
The previous link led to a ChemAxon page not found site.
> Updated Footnote to ChemAxon Extended Smiles

- rdkit/Chem/Draw/IPythonConsole.py
- rdkit/Chem/Draw/MolDrawing.py
- rdkit/Chem/Draw/SimilarityMaps.py
- rdkit/Chem/Draw/UnitTestDraw.py
- rdkit/Chem/Draw/UnitTestSimilarityMaps.py
- rdkit/Chem/Draw/aggCanvas.py
- rdkit/Chem/Draw/cairoCanvas.py
- rdkit/Chem/Draw/spingCanvas.py
---
- [New]: Clean-up unused import in IPythonConsole.py
- [New]: Clean-up unused import in UnitTestSimilarityMaps.py
- [Q&A]: In line 434, `symbolLength += 1 + len(str(nHs))` confused me as the number of hydrogen for every atoms is limited at most to one digit only, usually from 0 to 4 (probably at most 7). The number of hydrogen which is larger than 10 simply needs a further checking, I guess. So, the 'symbolLength' variable should be incremented by 2 rather than 1 + len(str(nHs)).
> Clean-up Python #4815 - P1.3: Chem\Draw

- rdkit/Chem/EState/AtomTypes.py
- rdkit/Chem/EState/EState.py
- rdkit/Chem/EState/EState_VSA.py
- rdkit/Chem/EState/Fingerprinter.py
- rdkit/Chem/EState/UnitTestEState.py
- rdkit/Chem/EState/UnitTestFingerprints.py
-----------------------------------
- [New]: Update function `EStateIndicies` in Estate.py
> Clean-up Python #4815 - P1.4: Chem\EState

- rdkit/Chem/Features/FeatDirUtilsRD.py
- rdkit/Chem/Features/ShowFeats.py
------------------------------
- [Q&A]: Documentation in FeatDirUtilsRD: Two docs are similar between `GetDonor3FeatVects()` and `GetAcceptor3FeatVect()`
- [Remark]: In `ShowFeats.py` we groups similar operation into one by its condition. And remove one unused variable named `nm` in line 178
> Clean-up Python #4815 - P1.6: Chem\Features

- rdkit/Chem/Fraggle/FraggleSim.py
> Clean-up Python #4815 - P1.9: Chem\Fraggle

- rdkit/Chem/fmcs/fmcs.py
- [Line 689]: I expect a better compatibility from Python between `dict` and `Counter`  or a better solution
> Clean-up Python #4815 - P1.8: Chem\fmcs

- rdkit/Chem/Fingerprints/ClusterMols.py
- rdkit/Chem/Fingerprints/DbFpSupplier.py
- rdkit/Chem/Fingerprints/FingerprintMols.py
- rdkit/Chem/Fingerprints/MolSimilarity.py
-------------------
- [New]: In `ClusterMols.py`, optimize data access in function `GetDistanceMatrix()`
- [New] Optimize method `NextItem()` in class `ForwardDbFpSupplier`
- Sorting all metric in method `GetMetricName()` and `SetMetricFromName()`. It may cost an extra memory ahead but trivial
> Clean-up Python #4815 - P1.7: Chem\Fingerprints

- rdkit/Chem/MolDb/FingerprintUtils.py
- rdkit/Chem/MolDb/Loader_orig.py
- rdkit/Chem/MolDb/Loader_sa.py
--------------------------------
- [New]: Clean tons of unused import in `Loader_sa.py`
> Clean-up Python #4815 - P1.10: Chem\MolDb

- Code/GraphMol/ChemReactions/ReactionParser.h
- Code/GraphMol/ChemReactions/ReactionWriter.cpp
- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
- Code/GraphMol/ChemReactions/catch_tests.cpp
- Code/GraphMol/FileParsers/FileParserUtils.h
- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/JavaWrappers/gmwrapper/CMakeLists.txt
We've had a parser for a while, but never got around to writing the writer.
> Support writing V3000 reactions

- rdkit/Chem/MolKey/InchiInfo.py
- rdkit/Chem/MolKey/MolKey.py
- rdkit/Chem/MolKey/UnitTestMolKey.py
> Clean-up Python #4815 - P1.11: Chem\MolKey

- rdkit/Chem/Scaffolds/MurckoScaffold.py
- rdkit/Chem/SimpleEnum/Enumerator.py
-----------------------
[Remark]: These two modules are completely independence. We only merged it due to the simplicity and easy clean-up. No intention here
> Clean-up Python #4815 - P1.14: Chem\Scaffolds & Chem\SimpleEnum

- Code/GraphMol/Conformer.h
No issue to reference
operator=(&&) Conformer.h wasn't returning anything in most cases.
Minimal testing, macOS only.
> operator= returns *this.

- rdkit/Chem/__init__.py
The Chem module needs to be explicit here.
> Code in the docstring for `FindMolChiralCenters()` doesn't work

- .azure-pipelines/linux_build.yml
- rdkit/Chem/Draw/SimilarityMaps.py
- rdkit/Chem/Draw/UnitTestSimilarityMaps.py
Simple fix.
This also re-enables the similarity map tests on windows
> Fixes #4763

- Code/GraphMol/SmilesParse/SmartsWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Simple fix to ensure that brackets end up around negated queries
> Fixes #4981

- Code/GraphMol/MolDraw2D/DrawTextFTJS.cpp
- Code/GraphMol/MolDraw2D/DrawTextFTJS.h
- Code/GraphMol/MolDraw2D/DrawTextJS.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
This PR fixes the JS build which had been broken by #4948.
> Fixes JS build broken by #4948

- Code/GraphMol/Substruct/SubstructMatch.h
> silence warnings in MSVC compliatons

- .azure-pipelines/linux_build.yml
adapting to a mysterious CI config change
> first pass at trying an update

- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/common.h
- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
I forgot to add support in the MinimalLib when I added the flexicanvas support in #4772
> support flexicanvas in the MinimalLib

- Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
- Code/GraphMol/MolDraw2D/Qt/catch_qt.cpp
Just needed to change the line capping.
> Fixes #5122

- Code/GraphMol/FilterCatalog/Wrap/rough_test.py
- Code/RDGeneral/RDLog.cpp
- Code/RDGeneral/RDLog.h
- ReleaseNotes.md
- rdkit/Chem/__init__.py
This gets the release notes ready for the next release cycle and does the deprecations announced in the last release cycle.
> update release notes, do deprecations

- Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
- Code/GraphMol/Wrap/rough_test.py
- Code/RDBoost/Wrap/RDBase.cpp
- Code/RDGeneral/RDLog.cpp
- Code/RDGeneral/RDLog.h
- Code/RDGeneral/catch_logs.cpp
- Contrib/FreeWilson/test/test_freewilson.py
- rdkit/Chem/Draw/__init__.py
Fixes #5172 using Brian's suggestion.
I also made `LogStateSetter` non-copyable (weird and unexpected things may happen, depending on what the compiler decides to do with copies/assignments!), and fixed the `BlockLogs()` in the Draw module that revealed the issue.
> Fixes #5172

- rdkit/Chem/Draw/IPythonConsole.py
This one snuck in as part of #5132 
At some point it would be a good idea to add some nbval tests for the parts of IPythonConsole.py that we can actually test, but that's a longer-term project.
> Fixes #5192

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/catch_chirality.cpp
This solves the immediate problem, but as discussed with @ricrogz offline, there are still some areas of concern around ZOBs and stereo that we should look into.
> Fixes #5239

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Simple fix for #5259 and a test.
> Fixes #5259

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
This was an oversight in the fix for #5291
> stop outputting empty block in CXSMILES

- Code/GraphMol/MolStandardize/Charge.cpp
- Code/GraphMol/MolStandardize/MolStandardize.cpp
- Code/GraphMol/MolStandardize/Tautomer.cpp
- Code/GraphMol/MolStandardize/catch_tests.cpp
This fixes #5317, #5318, and #5320
> Fix a couple of problems with MolStandardize

- rdkit/UnitTestLogging.py
The CI tests were occasionally failing due to mismatches in the logged timestamps in `UnitTestLogging.py`
This removes those timestamps
> make the logging tests more robust

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/catch_chirality.cpp
The bit of code which was causing the problem here was an inappropriate optimization
> Fixes #5307

- rdkit/Chem/PandasTools.py
This PR restores the #5103 fix that was accidentally reverted in #5132 (see discussion in #5103).
> Restore #5103 that was accidentally reverted in #5132

- Code/GraphMol/MolDraw2D/MolDraw2D.h
- Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
- Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Check to see if we need to call `initDrawing()` from `clearDrawing()`
> Fixes #5383

- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
Fixes: #5369
MinimalLib doesn't have Get/SetProp. So I added it.
```js
var initRDKitModule = require("../demo/RDKit_minimal.js");
var util = require("util");
var RDKitModule;
initRDKitModule().then(function (instance) {
RDKitModule = instance;
console.log(RDKitModule.version());
var mol = RDKitModule.get_mol(`
MJ201100
8  8  0  0  0  0  0  0  0  0999 V2000
-1.0491    1.5839    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.7635    1.1714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.7635    0.3463    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-1.0491   -0.0661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-0.3346    0.3463    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
-0.3346    1.1714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
0.3798    1.5839    0.0000 R#  0  0  0 …
```
> Add prop related method into JSMol

- Code/GraphMol/MolOps.cpp
- Code/GraphMol/catch_graphmol.cpp
Not a complex fix: make sure that we don't end up with a negative number of valence electrons for weird inputs.
> Fixes #5462

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
> Properly escape dots when writing atomProps

- Code/GraphMol/ChemTransforms/ChemTransforms.cpp
- Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Fixes https://github.com/rdkit/rdkit/issues/5569
See summary in next comment
> Fixed R-group attachment positions in RGD

- Contrib/FreeWilson/freewilson.py
This adds a rgroupdecomp aware molzip to the FreeWilson contrib to better handle broken cycles and chains in the FreeWilson reconstruction.
It also adds better logging to indicate how many of the original molecules were successfully reconstructed to better detect edge cases,
> Add an RGroupDecomp aware  molzip to the FreeWilson Contribution

- External/AvalonTools/CMakeLists.txt
Small PR just to update the AvalonTools version (and make future updates easier).
> Update AvalonTools to 2.0.2

- Code/GraphMol/MolPickler.h
Fix a faulty bitmask that causes issue https://github.com/rdkit/rdkit/issues/4621.
> Fixes #4621

- CMakeLists.txt
- ReleaseNotes.md
> Updates for the beta release.

- rdkit/Chem/Draw/InteractiveRenderer.py
- `setEnabled()` now takes two optional parameters:
1. `shouldEnable` (defaults to `True`)
2. `quiet` (defaults to `False`)
- `setEnabled()` now works also if it has downstream commands in the Jupyter Notebook cell
> InteractiveRenderer.setEnabled() improvements

- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/common.h
- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/tests/tests.js
This PR addresses https://github.com/rdkit/rdkit-js/issues/212.
> Expose highlighAtomColors, highlighBondColors and highlightAtomRadii to CFFI and JS

- Code/GraphMol/FindStereo.cpp
- Code/GraphMol/catch_chirality.cpp
This fixes #5659. It is a trivial fix, and we should include it in the 2022_09 fix.
> Fixes #5659

- CMakeLists.txt
- Docs/Book/BackwardsIncompatibleChanges.md
- Docs/Book/source/rdkit.Chem.RegistrationHash.rst
- Docs/Book/source/rdkit.Chem.rst
- ReleaseNotes.md
> Tag release and do final doc updates

- Code/GraphMol/Resonance.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/resMolSupplierTest.cpp
Fixes #5406 
Simple fix to prevent entering an infinite loop.
> Fix a hang in ResonanceMolSupplier when the computed ceMap is empty

- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/cffiwrapper.cpp
- Code/MinimalLib/cffiwrapper.h
- Code/MinimalLib/common.h
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
Brings MACCS fps to the MinimalLib
It is my first attempt to add functionality to the minilib. It is hopefully not a huge mess
> add MACCS fp to the MinimalLib

- Code/DataStructs/Wrap/testBV.py
- Code/DataStructs/Wrap/wrap_ExplicitBV.cpp
Check that we actually have a bit to set when converting an ExplicitBitVect to a List
> Fixes #5677

- Code/GraphMol/SmilesParse/SmilesParseOps.cpp
- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/nontetrahedral_tests.cpp
Information about non-tetrahedral stereo was being read and written from SMILES even when the global flag was disabled, this fixes that
Here's a demo of the new behavior on reading, where there's a warning printed:
```
In [3]: Chem.SetAllowNontetrahedralChirality(False)
In [4]: m = Chem.MolFromSmiles('O[Pt@SP2](F)(C)Br')
[06:07:47] ignoring non-tetrahedral stereo specification since setAllowNontetrahedralChirality() is false.
In [5]: m.Debug()
Atoms:
0 8 O chg: 0  deg: 1 exp: 1 imp: 1 hyb: 4 arom?: 0 chi: 0
1 78 Pt chg: 0  deg: 4 exp: 4 imp: 0 hyb: 5 arom?: 0 chi: 0
2 9 F chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
3 6 C chg: 0  deg: 1 exp: 1 imp: 3 hyb: 4 arom?: 0 chi: 0
4 35 Br chg: 0  deg: 1 exp: 1 imp: 0 hyb: 4 arom?: 0 chi: 0
Bonds:
0 0->1 order: 1 conj?: 0 aromatic?: 0
1 …
```
> allowNontetrahedralChiralty should be honored when reading/writing SMILES

- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
Small fix to make sure that information about R labels is always saved.
> Fixes #5763

- Code/GraphMol/FileParsers/MolFileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
This is a simple fix: just remove the exception to the previous logic
> Fixes #5810

- .azure-pipelines/linux_build.yml
- .azure-pipelines/linux_build_py37.yml
- .azure-pipelines/mac_build.yml
- .azure-pipelines/vs_build.yml
- Docs/Book/GettingStartedInC++.md
- Docs/Book/Install.md
- Docs/Book/Overview.md
- Docs/Book/RDKit_Book.rst
- Docs/Book/conf.py
- Docs/Book/source/modules.rst
- Docs/Book/source/rdkit.Chem.rdDetermineBonds.rst
- Docs/Book/source/rdkit.Chem.rst
switch to using myst and do a bunch of cleanup
Now that myst is available and supported we could consider looking into how bad it would be to translate the rst docs into myst-compatible markdown.
> Fixes #5812

- rdkit/Chem/PandasTools.py
A couple of improvements to `PandasTools.SaveXlsxFromFrame` to make it support a list of column names and not just a single column name, such that one can export, for example, a SAR table with R group decomposition.
I also added support for optional cell formatting, for example to enable multi-line cells containing newlines.
> Improvements to PandasTools.SaveXlsxFromFrame

- Code/GraphMol/FileParsers/CMakeLists.txt
- Code/GraphMol/FileParsers/MolFileStereochem.cpp
- Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
- rdkit/Chem/Draw/UnitTestDraw.py
Not much to this one, we just make the code more robust in cases where we can not wedge bonds
> Fixes #5863

- Code/GraphMol/ChemReactions/ReactionWriter.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
- Code/GraphMol/FileParsers/MolFileWriter.cpp
Since we already support parsing this info, this just required a small change to the V3000 reaction writer.
This also makes a minor change to the mol file writing to make it more robust when working with non-sanitized molecules.
> Fixes #5785

- rdkit/Chem/Graphs.py
- rdkit/ML/AnalyzeComposite.py
- rdkit/ML/Cluster/Resemblance.py
- rdkit/ML/Cluster/murtagh_test.py
- rdkit/ML/Composite/AdjustComposite.py
- rdkit/ML/Composite/BayesComposite.py
- rdkit/ML/EnrichPlot.py
- rdkit/ML/InfoTheory/BitRank.py
- rdkit/ML/ScreenComposite.py
- rdkit/ML/files.py
Fixes #5895 
Changed numpy.float to float
> Fix for #5895 - Changed deprecated numpy.float to float

- External/CoordGen/CMakeLists.txt
- External/CoordGen/test.cpp
Updating the version of CoordGen to pick up a fix for seg-faulting when bad coordinates are generated
fixes #4845
> Update CoordGen version

- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/QueryOps.cpp
This requires a few small logic changes to allow single-atom list queries to be written.
> Fixes #5930

- Code/MinimalLib/demo/demo.html
> Tiny change to get demo.html to load in legacy browsers

- Code/GraphMol/Descriptors/MolSurf.cpp
- Code/GraphMol/Descriptors/catch_tests.cpp
simple change: modify the name of the cached property
> Fixes #5941

- Code/GraphMol/FileParsers/Mol2FileParser.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
This is an overdue (and simple) fix for a problem with the mol2 parsing.
There's a good discussion and example output from coriina in the discussion of #3246 
This also fixes the older issue #1806
> Fixes #3246

- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
- Code/MinimalLib/demo/demo.html
Fixes 5963
The wrong points were being picked up in the wedged bond.
We count from 0!!
> Github5963

- Code/GraphMol/MolDraw2D/MolDraw2D.cpp
- Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
I should have suggested/done this a long time ago... sorry it took me so long to suggest it.
Fixes #5974
Fixes #2164
Fixes #5971
> Swap MolDraw2D from KekulizeMol() to KekulizeIfPossible()

- Code/GraphMol/MolStandardize/Metal.cpp
- Code/GraphMol/MolStandardize/test1.cpp
Fixes #5997
Skips valence of -1 in metal valence list when patching charges after disconnection.
> Fix disconnection of magnesium acetate in covalent form.

- Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp
- Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
- Code/GraphMol/Fingerprints/Wrap/AtomPairWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/RDKitFPWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/testGenerators.py
- Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
This also includes a bit of cleanup/refactoring work in it.
> Expose fingerprint generator options to python

- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Small PR to fix #6054 and add a test.
> Fixes #6054

- Code/GraphMol/Wrap/rdmolfiles.cpp
> Fixes #5986

- Code/MinimalLib/common.h
This is a minor code cleanup to make the logic clearer, avoid code repetitions and make sure that dummy atoms are considered as heavy atoms, which currently, incorrectly, does not happen.
> Minor code cleanup

- Code/GraphMol/CMakeLists.txt
- Code/GraphMol/MolDraw2D/catch_tests.cpp
- Code/GraphMol/QueryOps.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/catch_queries.cpp
dummies should not be considered to be metals. :-)
> Fixes #6106

- README.md
This PR adds two projects that use rdkit in the README.md
Both of the projects are authored by me
> Added two projects that use rdkit which I have authored

- Code/GraphMol/MolOps.cpp
- Code/GraphMol/catch_organometallics.cpp
Fixes #6252 and #6253.
Gets the format for the _MolFileBondEndPts correct when setting it.
> Fix _MolFileBondEndPts after dativeBondsToHaptic.

- Code/GraphMol/ChemTransforms/ChemTransforms.cpp
- Code/GraphMol/ChemTransforms/ChemTransforms.h
- Code/GraphMol/RGroupDecomposition/RGroupCore.cpp
- Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Fixes #6146 
Modified R group decomposition to copy stereo groups from the input structure to the core and R groups as described in the issue.  In addition to RGD changes I had to modify `ChemTransforms::replaceCore`
The decomposition from Issue #6146 now looks good:
> RGD and Stereo Groups

- Code/GraphMol/StructChecker/Utilites.cpp
Fixes #6274
Replaces calls to a tuple's get member function with std::get
> fixes #6274

- CMakeLists.txt
- Docs/Book/conf.py
- ReleaseNotes.md
update release notes, bump version, etc.
> release prep

- .azure-pipelines/vs_build.yml
- azure-pipelines.yml
simplifying things this time (hopefully)
> another attempt to get the windows ci builds working

- Code/GraphMol/Depictor/CMakeLists.txt
Was causing build problems under some circumstances
> add SmilesParse as dependency to Depictor

- Code/GraphMol/Wrap/Atom.cpp
- Code/GraphMol/Wrap/Bond.cpp
- Code/GraphMol/Wrap/Conformer.cpp
- Code/GraphMol/Wrap/Mol.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/SubstanceGroup.cpp
- Code/GraphMol/Wrap/props.hpp
- Code/GraphMol/Wrap/testPropertyLists.py
This is a test for optimizing GetPropsAsDict, it should be >10x faster in practice if it doesn't segfault the tests.
> Optimize GetPropsFromDict: use tags for conversion

- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
The bug was silly, the fix is simple.
> Fixes #6315

- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
straightforward fix to check ring size before deciding not to include stereo info on ring bonds
> Fixes #6316

- Code/GraphMol/MolEnumerator/MolEnumerator.cpp
- Code/GraphMol/MolEnumerator/enumerator_catch.cpp
We just need to remove the offending properties in the `enumerate()` function.
> Fixes #6432

- .azure-pipelines/linux_build_py311.yml
See if pinning numpy on 3.11 builds fixes the azure issue.
> pin numpy to 1.24.3

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
This is a simple fix brought over from #6491
> Fixes #6492

- Code/GraphMol/Wrap/StereoGroup.cpp
- Code/GraphMol/Wrap/rough_test.py
Ooops! This one slipped through!
> Fix bug in StereoGroup wrapper

- Code/GraphMol/Descriptors/MORSE.cpp
- Code/GraphMol/Descriptors/RDF.cpp
- Code/GraphMol/GenericGroups/GenericGroups.cpp
- Code/GraphMol/MolPickler.cpp
Inspired by @ricrogz's recent cleanup commit, here's one from me. 
:-)
> clear up some compiler warnings

- Code/GraphMol/Descriptors/BCUT.cpp
- Code/GraphMol/Descriptors/testBCUT.cpp
BCUT segfaults on empty molecules
> Fixes #6592

- Code/GraphMol/ROMol.h
- Code/GraphMol/catch_graphmol.cpp
> Fixes #6681

- Code/GraphMol/Depictor/testDepictor.cpp
- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolStandardize/test1.cpp
These ones escaped the scrutiny in #6675 :-/
> fix some more leaks

- rdkit/Chem/Draw/UnitTestIPython.py
- rdkit/Chem/Draw/__init__.py
this was an oversight when we did the original review
> make MolsMatrixToGridImage() work in notebook

- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
This was overlooked in the original PR
> expose the CDXML reaction parsers to python

- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
> add missing Python parameter and reformat

- Code/GraphMol/FileParsers/MolFileParser.cpp
this PR simply removes an incorrect comment.
> remove incorrect comment

- Code/GraphMol/ROMol.cpp
- Code/GraphMol/ROMol.h
- Code/GraphMol/Wrap/Mol.cpp
- Code/GraphMol/Wrap/rough_test.py
- Code/GraphMol/catch_graphmol.cpp
Fixes #6411
Adds ROMol::hasQuery & Mol.HasQuery()
This isn't cached as in the issue report
> Issue 6411 ROMol hasquery

- Docs/Book/source/rdkit.Chem.SpacialScore.rst
- rdkit/Chem/Descriptors.py
- rdkit/Chem/SpacialScore.py
- rdkit/Chem/UnitTestSpacialScore.py
- rdkit/Chem/test_list.py
Implementation of the SpacialScore for the RDKit, based on the original implementation by @frog2000.  
As part of the Hackathon of the 2023 UGM the code was adapted to fit into the RDKit Descriptor module by: @jose-manuel, Arsenio Cruz, @vincenzo-palmacci and myself.
Many thanks to @rvianello for his help in setting everything up!
> Add SpacialScore

- README.md
Add 3 popular projects that depend on RDKit to the list in the README
> add to projects using RDKit section

- Code/GraphMol/FindStereo.cpp
- Code/GraphMol/new_canon.cpp
- Code/GraphMol/new_canon.h
Switch to using unique_ptrs instead of naked pointers and re-arrange the allocation a bit.
I benchmarked this and there's no significant performance impact.
> some modernization of the memory handing in the canonicalization code

- CMakeLists.txt
- ReleaseNotes.md
Getting everything ready for a beta release
> update release notes and cmakelists for beta

- Code/GraphMol/Chirality.h
- Code/GraphMol/Depictor/CMakeLists.txt
- Code/GraphMol/Depictor/DepictUtils.cpp
- Code/GraphMol/Depictor/DepictUtils.h
- Code/GraphMol/Depictor/RDDepictor.cpp
- Code/GraphMol/Depictor/RDDepictor.h
- Code/GraphMol/Depictor/Wrap/rdDepictor.cpp
- Code/GraphMol/Depictor/Wrap/testDepictor.py
- Code/GraphMol/Depictor/catch_tests.cpp
- Code/GraphMol/Depictor/testDepictor.cpp
- Code/GraphMol/FileParsers/MolFileStereochem.cpp
- Code/GraphMol/FileParsers/MolFileStereochem.h
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/MarvinParse/testMrvToMol.cpp
- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
- Code/GraphMol/WedgeBonds.cpp
- Code/GraphMol/Wrap/MolOps.cpp
- Code/MinimalLib/common.h
- Code/MinimalLib/tests/tests.js
This is reapplying #6368
Apologies for the original premature merge of this which lead to the back-and-forth
> Removed some code duplication between Depictor.cpp and common.h

- Code/GraphMol/SmilesParse/CXSmilesOps.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
> Fixes #6309

- .azure-pipelines/linux_build_java.yml
- .azure-pipelines/mac_build_java.yml
- Code/GraphMol/GeneralizedSubstruct/XQMol.cpp
- Code/GraphMol/GeneralizedSubstruct/XQMol.h
- Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp
- Code/GraphMol/SubstructLibrary/CMakeLists.txt
- Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp
- Code/GraphMol/SubstructLibrary/SubstructLibrary.h
- Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
- Code/GraphMol/SubstructLibrary/Wrap/rough_test.py
- Code/GraphMol/SubstructLibrary/catch_tests.cpp
- Code/JavaWrappers/CMakeLists.txt
- Code/JavaWrappers/GeneralizedSubstruct.i
- Code/JavaWrappers/SubstructLibrary.i
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/SubstructLibraryTests.java
This allows ExtendedQueryMols to be used with the SubstructLibrary
This ended up being less code than I feared it might be
> support generalized substructure search in the SubstructLibrary

- Code/GraphMol/FileParsers/CDXMLParser.cpp
- Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
> Fixes #6887 - issue where stereogroups could overwrite each other

- Code/GraphMol/Fingerprints/FingerprintGenerator.cpp
- Code/GraphMol/Fingerprints/FingerprintGenerator.h
- Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/testGenerators.py
- Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
It's not clear that these would be immediately useful in C++, so I just put them in the Python wrapper code. We can pretty easily move them into the actual C++ library elsewhere if that seems right.
> Add (multithreaded) functions to the fingerprint generators for calculating multiple fingeprints in one call

- Code/GraphMol/FileParsers/MaeMolSupplier.cpp
- Code/GraphMol/FileParsers/MaeWriter.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #6973.
The fix is trivial: just check for atomic number `-2`, and translate it to `0`, and do the opposite for `MaeWriter`.
> Fixes #6973

- README.md
> 2 new projects using RDKit

- Code/GraphMol/ChemReactions/catch_tests.cpp
the issue was already fixed at some point.
> add a test for Github #6492

- Code/GraphMol/FilterCatalog/CMakeLists.txt
- Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp
- Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
Fixes issue #7054 
Exposes maxBondMatchPairs to the Python wrapper.
> Extra rascal option

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/catch_chirality.cpp
Fixing an oversight in `setBondStereoFromDirections()` resolves the backend problem here.
> Fixes #7076

- Code/GraphMol/MolDraw2D/CMakeLists.txt
the md5 sum for the font file changed
I've checked the new file and it seems fine
> update font md5 sum

- Code/GraphMol/FilterCatalog/FilterMatcherBase.h
- Code/JavaWrappers/Atom.i
- Code/JavaWrappers/Bond.i
- Code/JavaWrappers/FMCS.i
- Code/JavaWrappers/FilterCatalog.i
- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/SubstanceGroup.i
- Code/JavaWrappers/SubstructLibrary.i
- Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i
- Code/JavaWrappers/gmwrapper/GraphMolJava.i
This PR should fix a subset of the warnings produced during the build of the SWIG-based wrappers.
> fix several warnings originating from the swig wrappers

- Docs/Book/GettingStartedInPython.rst
There was an error in how Lipinski's Rule of 5 was described. I have fixed the changes and updated the documentation in docs to follow the original paper and also fixes consistency with the code example below.
Great project and love the work!
> Lipinski Rule of 5 was incorrectly described.

- Code/GraphMol/SmilesParse/SmilesWrite.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
This is a straightforward extension of the changes from #6482
> Fixes #5499

- Code/GraphMol/FileParsers/CDXMLParser.cpp
- Code/GraphMol/FileParsers/CDXMLParser.h
- Code/GraphMol/FileParsers/cdxml_parser_catch.cpp
Since these functions were already returning unique_ptrs, this is primarily just renaming and adding the parameters struct
> Add v2 API for the molecule CDXML parser

- Code/GraphMol/ChemReactions/SanitizeRxn.cpp
- Code/GraphMol/ChemReactions/SanitizeRxn.h
- Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp
- Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py
- Code/GraphMol/ChemReactions/catch_tests.cpp
Trying to cram this into the existing `sanitizeRxn()` function just didn't make sense, so I created a new one
Fixes #7108
> Adds a new function to sanitize the components of a reaction like molecules

- rdkit/Chem/TorsionFingerprints.py
No need to keep using the deprecated old FP code
> switch the TFD code to use a fingerprint generator

- .azure-pipelines/vs_build_swig.yml
- azure-pipelines.yml
make sure the swig wrappers for csharp build
This is not currently running any tests
> [CI] add csharp build on windows

- Code/MinimalLib/cffiwrapper.cpp
- Code/MinimalLib/common.h
- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
Fixes: #449
expose options parameter in get_inchi like in the python api.
> feat(minilib): expose the options parameter in get_inchi

- Data/FragmentDescriptors.csv
Remove duplicate entry in FragmentDescriptors.csv
> Remove duplicate entry

- CMakeLists.txt
- ReleaseNotes.md
Update ReleaseNotes and CMakeLists.txt
> beta release prep

- Code/GraphMol/Descriptors/DCLV.cpp
- Code/GraphMol/Descriptors/DCLV.h
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
There was a pretty serious leak here.
The tests now pass when run with address sanitization
> fix a leak in the new DCLV code

- Code/GraphMol/DetermineBonds/DetermineBonds.cpp
- Code/GraphMol/DetermineBonds/catch_tests.cpp
> Fixes #7299

- Code/ChemicalFeatures/Wrap/FreeChemicalFeature.cpp
- Code/ChemicalFeatures/Wrap/rdChemicalFeatures.cpp
- Code/ChemicalFeatures/Wrap/testFeatures.py
- Code/DataManip/MetricMatrixCalc/Wrap/testMatricCalc.py
- Code/DataStructs/Wrap/DataStructs.cpp
- Code/DataStructs/Wrap/DataStructs.h
- Code/DataStructs/Wrap/testBV.py
- Code/DataStructs/Wrap/testDiscreteValueVect.py
- Code/DataStructs/Wrap/testSparseIntVect.py
- Code/GraphMol/Wrap/rough_test.py
- rdkit/CMakeLists.txt
C++:
Deletion of empty header file. Fixing typos.
Python:
Writing more pythonic for-loops. Unused variables in the loops were assigned to `_`. `enumerate()` and `zip()` were used where possible.
> Cleaner forloops, deleting of empty header file

- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
Example: Fixes #7317
This was a discussion, not a bug report but was indeed a bug.
The drawing code assumed a bond wouldn't have a length of more than 2A.
> Fixes problem from discussion 7317

- Code/GraphMol/DetermineBonds/DetermineBonds.cpp
- Code/GraphMol/DetermineBonds/catch_tests.cpp
Simple fix for this which exploits the fact that N+ basically acts like C, N- acts like O, etc.
> Fixes github 7331

- Code/DataStructs/BitOps.cpp
- Code/DataStructs/BitVect.cpp
- Code/DataStructs/DiscreteValueVect.cpp
- Code/DataStructs/Utils.cpp
- Code/DataStructs/Wrap/testBV.py
- Code/DataStructs/base64.cpp
Various changes in the Code/DataStructs directory (both in the c++ and python codes) in order to modernize it.
For some of the changes I am not sure whether they are an improvement or not (especially for the switch statements and the use of std::max and std::min).
> Cleanup of Code/DataStructs

- Code/ForceField/MMFF/Params.h
- Code/ForceField/Wrap/ForceField.cpp
These are following up on @ricrogz's comments on #7406
> additional tweaks for #7406

- Code/GraphMol/MolOps.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/Wrap/rough_test.py
This provides python wrappers for a couple of functions from MolOps 
There's also a minor improvement of the docs in MolOps.h
> Expose a couple of additional functions to Python

- Code/JavaWrappers/ROMol.i
- Code/JavaWrappers/csharp_wrapper/RdkitTests/MolToFromByteArray.cs
- Code/JavaWrappers/gmwrapper/src-test/org/RDKit/PicklingTests.java
Implemented and tested for both C# and Java.
> Expose the property pickle options to SWIG

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/Chirality.h
- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolDraw2D/DrawMol.h
- Code/GraphMol/Wrap/MolOps.cpp
- Code/GraphMol/catch_chirality.cpp
This moves the required function into the Chirality namespace and exposes it to Python
> Fixes #7438

- Code/GraphMol/FileParsers/FileWriters.h
- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FileParsers/file_parsers_catch.cpp
- Code/GraphMol/Wrap/rdmolfiles.cpp
- Code/GraphMol/Wrap/rough_test.py
Adds the ability to force V2K output, even if that results in information loss
also a small amount of refactoring in the mol block writing
> add MolToV2KMolBlock()

- CMakeLists.txt
- Code/GraphMol/Wrap/Conformer.cpp
- Code/GraphMol/Wrap/rdchem.cpp
- Code/GraphMol/Wrap/rough_test.py
- rdkit/Chem/Pharm3D/EmbedLib.py
This took a bit longer than it should have.
Usage
```
array = mol.GetConformer(0).GetPositions()
mol.GetConformer(0).SetPositions(array)
```
> Add python Conformer.SetPositions wrapper

- Code/GraphMol/FindStereo.cpp
- Code/GraphMol/catch_chirality.cpp
This is a pretty simple fix: basically I just moved some logic out from the `if(cleanIt)` check.
> Fixes #7598

- rdkit/Chem/AtomPairs/Sheridan.py
A simple fix.
As an aside: it's worth considering doing a C++ implementation of the Sheridan fingerprints at some point
> Fixes #7602

- rdkit/Chem/Descriptors.py
A simple one:
- Switch fp density descriptors to use fp generators
- add fp caching to the fp density descriptors
> Fixes #7625

- Code/PgSQL/rdkit/rdkit_gist.c
This fixes #7493, where way too much LEAF-nodes had to be re-checked for structure isomorphism.
Fixes #7493
This fixes #7493, where way too much LEAF-nodes had to be re-checked for structure isomorphism.
> Update rdkit_gist.c fixes #7493

- Code/PgSQL/rdkit/rdkit_gist.c
Reverts rdkit/rdkit#7547
I misunderstood a comment form @rvianello and merged this too early
> Revert "GIST index improvements for @="

- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
@ptosco  I think I got this right
> fixes #7583

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/Descriptors/Lipinski.cpp
- Code/GraphMol/Descriptors/catch_tests.cpp
- Code/GraphMol/Descriptors/test.cpp
Simple change to make sure we have called `assignStereochemistry()` before doing the work in `numAtomStereoCenters()` and `numUnspecifiedAtomStereoCenters()`
> Fixes #6757

- Code/DistGeom/CMakeLists.txt
- Code/GraphMol/CIPLabeler/CMakeLists.txt
- Code/GraphMol/MarvinParse/CMakeLists.txt
- Code/GraphMol/MarvinParse/MarvinDefs.h
- Code/RDBoost/CMakeLists.txt
includes a couple of other small header-related cleanups too
> Fix some missing headers when doing "make install"

- Code/GraphMol/Fingerprints/MHFP.h
- Code/Numerics/Alignment/AlignPoints.cpp
- Code/RDGeneral/Dict.h
#7525
Fix HTML error in docstrings.
> doc: fix -Wdocumentation-html

- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/common.h
- Code/MinimalLib/tests/tests.js
@greglandrum As discussed, I extracted into this PR the two additional mol creation flags for MinimalLib which were originally part of #7322.
> Expose two additional boolean flags for mol creation to MinimalLib

- Code/GraphMol/SmilesParse/SmilesParse.cpp
- Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Switch from using detectBondStereochemistry() to setDoubleBondNeighborDirections()
> Fixes #7725

- README.md
Fixes #7052
Remove the stale documentation badge
> Remove Documentation Status link

- Contrib/SA_Score/sascorer.py
Fixes https://github.com/rdkit/rdkit/issues/7794
The SA score is impacted by the new fingerprint interface.
I tested on 1000 lead-like molecules that the new scores are the same as the old scores.
> Update SA score to use FingerprintGenerators

- CMakeLists.txt
> Current master identifies as 2023.03.1pre

- Code/RDGeneral/StreamOps.h
No issue.
Since we're fixing possible memory leaks, I just stumbled upon this one.  If the 2nd exception is thrown, buff will leak, I think.
> Use smart pointer for buffer.

- External/pubchem_shape/CMakeLists.txt
I updated `PUBCHEMSHAPE_URL` and removed `#include <cstdint>` injection code in External/pubchem_shape/CMakeLists.txt because it is not neeeded any more new commit led by PUBCHEMSHAPE_URL.
> Update `PUBCHEMSHAPE_URL` and remove patch code

- Code/DistGeom/Wrap/DistGeom.cpp
- Code/ForceField/Wrap/ForceField.cpp
- Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp
- Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp
- Code/GraphMol/Fingerprints/MorganGenerator.cpp
- Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp
- Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h
- Code/GraphMol/ForceFieldHelpers/UFF/Builder.cpp
- Code/GraphMol/ForceFieldHelpers/UFF/UFF.h
- Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp
- Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
- Code/GraphMol/MolCatalog/Wrap/rdMolCatalog.cpp
- Code/GraphMol/MolProcessing/Wrap/rdMolProcessing.cpp
- Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp
- Code/GraphMol/Wrap/CompressedSDMolSupplier.cpp
- Code/Numerics/Alignment/Wrap/rdAlignment.cpp
These come from running asan on the Python tests.
These all look like 2 different types of errors: unmanaged pointers that are returned to Python without also transferring ownership, and leftovers that aren't cleaned up when some call fails.
> Fix some more mem errors in 2024.09.1

- rdkit/ML/Cluster/Butina.py
- rdkit/ML/Cluster/UnitTestButina.py
- Optimized Butina clustering algorithm using NumPy arrays for improved performance
- Enhanced modularity and overall code readability
- Expanded API to support direct use of NumPy arrays as input
- Added support for nxn input distance matrices
> Optimize Butina Clustering for Performance and Expand API

- Code/GraphMol/MolPickler.cpp
- Code/GraphMol/MolPickler.h
- Code/GraphMol/QueryOps.h
- Code/GraphMol/Substruct/catch_tests.cpp
- Code/JavaWrappers/Dict.i
- Code/JavaWrappers/QueryOps.i
- Code/RDGeneral/Dict.h
- ReleaseNotes.md
> GitHub 7865 haspropwithvaluequery leaks

- Code/GraphMol/Fingerprints/MorganGenerator.cpp
- Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
One line fix: there was a simple logic error in the code
> Fixed #7986

- Code/GraphMol/MolPickler.h
- Code/JavaWrappers/ROMol.i
- Code/MinimalLib/CMakeLists.txt
- Code/MinimalLib/JSONParsers.cpp
- Code/MinimalLib/JSONParsers.h
- Code/MinimalLib/cffi_test.c
- Code/MinimalLib/cffiwrapper.cpp
- Code/MinimalLib/cffiwrapper.h
- Code/MinimalLib/common.h
- Code/MinimalLib/jswrapper.cpp
- Code/MinimalLib/minilib.cpp
- Code/MinimalLib/minilib.h
- Code/MinimalLib/tests/tests.js
- added property support to CFFI library
- added `propertyFlags` JSON parser
- added support for setting `propertyFlags` to MinimalLib
> Expose propertyFlags to CFFI and MinimalLib

- Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.cpp
- Code/GraphMol/SmilesParse/catch_tests.cpp
Trimethylcyclohexane gave incorrect results from canonicalizeStereoGroups.
Example of problem:
1,3,5-Trimethylcyclohexane with 3 OR groups ( ```C[C@H]1C[C@@H](C)C[C@@H](C)C1 |o1:1,o2:6,o3:3|```) 
(![TrimethylcyclohexaneMol1](https://github.com/user-attachments/assets/4bdf8ea2-44bb-4950-b3d1-34053e6ed55c)) after a call to canonicalizeStereoGroups gives a result that is incorrect - it gives:
```C[C@H]1C[C@@H](C)C[C@@H](C)C1 |o1:1,o2:3,6| ```
(![TrimethylcyclohexaneMol1Out](https://github.com/user-attachments/assets/b10f9d73-e80c-4a34-a741-7382aadb5209))
There should be only one OR group in the answer - as there are only two different mols in the sample - either all methyls are on the same side, or two are the same and the other is opposite.
Also, two other smiles that are equivalent to the …
> Fix for trimethylcyclohexane error

- rdkit/Chem/AllChem.py
- rdkit/Chem/__init__.py
> expanded documentation in Chem and AllChem

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/molopstest.cpp
> MergeQueryHs better detects hydrogens in OR queries

- Code/GraphMol/SynthonSpaceSearch/Synthon.cpp
- Code/GraphMol/SynthonSpaceSearch/SynthonSpace.cpp
- Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.cpp
- Code/GraphMol/SynthonSpaceSearch/data/gregs_space_fail.txt
- Code/GraphMol/SynthonSpaceSearch/synthon_space_search_catch.cpp
No issue
This pulls in a few changes to the synth space substructure search that were in the new FP search branch.
> Synthon space2

- Contrib/NP_Score/npscorer.py
This pull request fixes #8052.
> updated Morgan fingerprint generation to remove warnings

- Docs/Book/RDKit_Book.rst
This is a confusing one.
The explanation borrows from the discussion in PR #1339
> document H atoms in SMARTS

- Code/GraphMol/AddHs.cpp
- Code/GraphMol/catch_molops.cpp
This is caused by #8008. I missed that edge case in my PR.
> Fixes #8065

- Code/GraphMol/MolDraw2D/DrawMol.cpp
- Code/GraphMol/MolDraw2D/catch_tests.cpp
This addresses an issue noticed by @sroughley as a unit test was failing in KNIME.
Currently the code uses `map::at(-1)` to get the default color for atom symbols under a highlight, and will therefore throw an exception if the `-1` key is not present.
This PR adds a fallback to black as in `getColourByAtomicNum`.
It also avoids to call `map::find` twice in the above function.
> Avoid that map::at() throws an exception in case atomColourPalette includes neither 6 nor -1

- Code/GraphMol/RascalMCES/RascalMCES.cpp
- Code/GraphMol/RascalMCES/mces_catch.cpp
Fixes #8098
If the search passes tier1Sim and tier2Sim tests but still returns no hits, returns a basic results object.
> Fix empty results bug.

- External/INCHI-API/inchi.cpp
- External/INCHI-API/test.cpp
Inspired by #8123, which is where the tests came from.
Fixes #8129
> Fixes two out-of-bounds bugs in the InChI wrapper

- Code/GraphMol/FilterCatalog/Filters.cpp
- Code/GraphMol/NontetrahedralStereo.cpp
- Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake
- Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake
- Code/JavaWrappers/MorganFingerprints.h
- Code/RDGeneral/LocaleSwitcher.cpp
- Code/SimDivPickers/LeaderPicker.h
https://github.com/rdkit/rdkit/blob/454fe1c6f9c6b9db5e475ab6125b9e0f4dd1ec01/.clang-tidy#L2
> fix: apply modernize-use-nullptr

- Code/GraphMol/Fingerprints/FingerprintUtil.h
- Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
it's a simple one since the bug report from @QJ-Chen was so detailed.
> Fixes #6679

- Code/JavaWrappers/gmwrapper/CMakeLists.txt
- Code/PgSQL/rdkit/CMakeLists.txt
- External/INCHI-API/CMakeLists.txt
This makes small tweaks to a few cmake file in order to fix #8138 and #8139
> some cmake cleanups

- External/INCHI-API/Wrap/pyInchi.cpp
For the user manual https://www.inchi-trust.org/download/104/InChI_UserGuide.pdf can be also used, but is an older one.
> Update  InChi links

- Code/DistGeom/BoundsMatrix.h
- Code/DistGeom/TriangleSmooth.cpp
- Code/Numerics/Matrix.h
three pieces to get a bit of extra speed by not doing un-necessary work:
1. The bounds matrix code doesn't need to check that it's being passed valid indices since it calls the underlying `Matrix` code, which also checks.
2. Added some unchecked functions for setting and getting values on the `Matrix`
3. Switched the bounds-smoothing code to used the unchecked functions
> some optimizations of triangle smoothing and the bounds matrix code

- rdkit/Chem/RegistrationHash.py
Fixes #7650
Updates the return typehint of GetMolLayers to be syntactically correct
> issue 7650 - update GetMolLayers return typehint

- Code/GraphMol/ChemReactions/ReactionRunner.cpp
- Code/GraphMol/ChemReactions/catch_tests.cpp
- Code/GraphMol/MolEnumerator/MolEnumerator.cpp
- Code/RDGeneral/types.cpp
- Code/RDGeneral/types.h
Implements #8222 
Now "react_idx" is added to reaction product atoms so we can get back to the original atom and reactant.
> Implements #8222 adds react_idx (index of reactant) to product atoms

- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
- Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Simple fix to make sure that the bond actually has stereo atoms
> Fixes #8250

- Code/GraphMol/FileParsers/FileWriters.h
- Code/GraphMol/FileParsers/MolFileWriter.cpp
- Code/GraphMol/FileParsers/testMolWriter.cpp
Fixes #8265 
Simple fix to check for out of range coordinates.
> Throw error when V2000 coords are out of range

- Code/GraphMol/ChemTransforms/MolFragmenter.cpp
- Code/GraphMol/ChemTransforms/catch_tests.cpp
> Adds linker style zipping

- Code/GraphMol/QueryAtom.cpp
- Code/GraphMol/querytest.cpp
Fixes #8353
Checks qp_query on entry. 
I'm not sure if this is the correct way to do the test.
> Github8353

- Code/GraphMol/MolHash/catch_tests.cpp
- Code/GraphMol/MolHash/hashfunctions.cpp
There's another special case that we need to cover. This adds it, along with some documentation.
> Fixes #8405

- Code/GraphMol/Fingerprints/Wrap/MHFPWrapper.cpp
- Code/GraphMol/Fingerprints/Wrap/testMHFP.py
simple fix to return tuples instead of std::vector from the functions in the python wrappers
> Fixes #3102

- Code/GraphMol/Chirality.cpp
- Code/GraphMol/catch_chirality.cpp
The fix here applies to both legacy and non-legacy stereo and tests both.
> Fixes #8420

- Code/GraphMol/FilterCatalog/update_pains.py
Fixes #8430 
Updates update_pains.py script to check for all pains .in files existence
> Check for PAINS_C file existence in update_pains.py script

- azure-pipelines.yml
another attempt to robustify our build against CI vagaries
> switch to target_platform=14

- Code/GraphMol/Substruct/SubstructMatch.h
- Code/GraphMol/Substruct/SubstructUtils.cpp
- Code/GraphMol/Substruct/catch_tests.cpp
- Code/GraphMol/Wrap/Mol.cpp
Just adds another option to the SubstructMatchParameters
> Fixes #8485

- External/Eigen/CMakeLists.txt
That is C++20 compatible
Fixes #8476
> Set default Eigen3 version to 3.4.0

- Code/GraphMol/Wrap/ChiralityOps.cpp
- Code/GraphMol/Wrap/rough_test.py
Fixes #8467
just adds a function to the python wrappers
> expose cleanupStereoGroups to python

- External/INCHI-API/Wrap/pyInchi.cpp
- External/INCHI-API/inchi.cpp
- External/INCHI-API/inchi.h
- External/INCHI-API/python/inchi.py
- rdkit/Chem/UnitTestInchi.py
The InChI code has a `#define` with the version. We expose that here
> Fixes #8508

- Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp
- Code/GraphMol/DistGeomHelpers/Embedder.cpp
- Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py
- Code/GraphMol/DistGeomHelpers/catch_tests.cpp
The missing terms here were something @nmaeder and I noticed.
> add support for allene- and cumulene-like structures to KDG

- Code/GraphMol/DistGeomHelpers/Embedder.h
- Code/GraphMol/MolHash/catch_tests.cpp
- Code/GraphMol/MolHash/hashfunctions.cpp
No issue.
The default constructor for EmbedParameters sets ETversion to 1, but everywhere else in the file it defaults to 2.  It feels to me that there should be consistency.
> Change default ETversion.

- .azure-pipelines/vs_build.yml
- .azure-pipelines/vs_build_dll.yml
- .azure-pipelines/vs_build_swig.yml
- azure-pipelines.yml
> update to win-2022 for CI

- Code/GraphMol/DetermineBonds/DetermineBonds.cpp
Thanks to @rogersayle for pointing out these "opportunities for improvement." :-)
> Some cleanup of the xyz2mol code

- Code/GraphMol/Wrap/rdmolfiles.cpp
Documentation, Fixes #3087 
Documentation changes to reflect actual behavior.
> docs update to fix stale issue

- .azure-pipelines/vs_build.yml
> fix a typo in a CI file

- External/pubchem_shape/Wrap/cshapealign.cpp
No reference issue
Fixes some documentation related to rdShapeAlign.
> Fix documentation errors for rdShapeAlign

- rdkit/Chem/BRICS.py
> Fixes #7215

- External/pubchem_shape/CMakeLists.txt
This is one that @DavidACosgrove found.
We will patch it here until the change is merged in the upstream repo.
> patch a memory allocation problem in the pubchem shape code

- Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp
> fix a mistake caused by a dumb suggestion I made to #8757
