Code/GraphMol/SmilesParse/SmilesWrite.h
`std::numeric_limits<std::int32_t>::max()` is not handled properly by SWIG for C#.  This PR fixes to use an literal integer.
Because this enum is `uint32`, general formula is not needed. Another expression like `INT_MAX` also does not work.
=> Fix SWIG wrappers for C#

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
I have recently realized that the "Do not add unnecessary R labels" part of a previous PR (#3969) had an oversight.
Before #3969, the first matching core in the order cores are provided to RGD was chosen to decompose each molecule.
As discussed in #3969, this may cause suboptimal cores to be chosen when `onlyMatchAtRGroups` is set to `false`, so the rule was changed as follows: the first matching core is chosen that requires the least number of non-user defined R labels to be added.
However, this should only happen when later, more specific cores are structurally related to earlier cores, i.e. when they are superstructures of earlier cores.
To better explain this point, let's take a look at these examples, taken from the newly added `testDoNotChooseUnrelatedCores()` test.
We have these …
=> Fixes a bug with the choice of RGD cores

rdkit/Chem/Descriptors3D.py
Fixes #4952 .  
The definition of eccentricity should have only `pm3` in the denominator, not `pm3**2`.   The C++ implementation is correct.
=> Fixes definition of eccentricity (#4952)

CMakeLists.txt
A build using Anaconda's python 3.9 on CentOS7 was consistently failing on linking a shared object, with an error message reporting that `x86_64-conda-linux-gnu-gcc` couldn't be found.
It eventually turned out that the problem originated from a leading whitespace character in the string returned (in the conda build environment) by `sysconfig.get_config_var('LDSHARED')`. Because of this leading whitespace character, the compiler program name wasn't [removed](https://github.com/rdkit/rdkit/blob/master/CMakeLists.txt#L351) from the string by `.split(' ', 1)[1]` and it was therefore included in the `PYTHON_LDSHARED` cmake variable.
This resulted in the misplaced occurrence of `x86_64-conda-linux-gnu-gcc` in the link command generated by cmake for some shared objects.
For reference this is the …
=> fix CMakeLists.txt extracting link line from python LDSHARED config var

Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
two lines to fix the bug + a few additional calls to `reserve()` when we know the size of vectors
=> Fixes #4934

Code/GraphMol/FileParsers/GeneralFileReader.h, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
This PR fixes tests for `RDK_USE_BOOST_IOSTREAMS=OFF`.
`RDK_USE_BOOST_IOSTREAMS=OFF` issue was fixed on https://github.com/rdkit/rdkit/pull/4933, but only for non-test files.
=> fix to work tests when RDK_USE_BOOST_IOSTREAMS=OFF

Code/JavaWrappers/gmwrapper/CMakeLists.txt
- This PR adds `JavaGzStreamTests` test to `CMakeLists.txt`. `GzStreamTests` is introduced at https://github.com/rdkit/rdkit/pull/4933.
- `RunJavaWrapperTests` also deleted because `runUnitTests.sh` is missing.
=> add JavaGzStreamTests

Code/GraphMol/Atom.cpp
This is roger's patch from a discussion via email.
=> Move isEarlyAtom to a table to reduce lock contention in getPeriodicTable

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/catch_chirality.cpp, Code/RDGeneral/StreamOps.h
This PR attempts to fix most of the open security-relevant issues found by OSS-Fuzz:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36998: `RWMol::replaceAtom` needs to update references in stereo groups to avoid use-after-frees. Fixed in ae37e6eb3dabcb793b21ed679a4e4f4b4514a019
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28660: `iterateCIPRanks` wrote out-of-bounds in some cases when the rank did not change in the current iteration. Fixed in a88de3ed64a5278ac25e8541cbdc347a108e1bbd with an extra bounds check.
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25220 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25225: A couple of functions used uninitialized variables. 14b852bcee980db6a655bdb357f2905939bddc44 initializes them.
- …
=> Fix memory safety issues found by OSS-Fuzz

Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/ROMol.h, Code/GraphMol/RWMol.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp, Code/GraphMol/catch_chirality.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/rdkit-91.sql
The current code doesn't do anything about `StereoGroup`s when chiral info is removed from atoms.
Example 1, here there should be no `StereoGroup`:
```
In [39]: m = Chem.MolFromSmiles('C[C@](C)(Cl)F |o1:1|')
In [40]: Chem.MolToCXSmiles(m)
Out[40]: 'CC(C)(F)Cl |o1:1|'
```
And here the nonchiral atom should be removed from the `StereoGroup`
```
In [41]: m = Chem.MolFromSmiles('C[C@](C)(Cl)[C@H](F)Cl |o1:1,4|')
In [42]: Chem.MolToCXSmiles(m)
Out[42]: 'CC(C)(Cl)[C@H](F)Cl |o1:1,4|'
```
This PR fixes the problem by adding a new function `cleanupStereoGroups()` which is called from `AssignStereochemistry()` (it's also part of the `RDKit::Chirality` public API, so it can be called elsewhere).
The other change in this PR is to move the method `ROMol::setStereoGroups()` from private to public …
=> AssignStereochemistry should remove nonchiral atoms from StereoGroups

rdkit/Chem/MolStandardize/UnitTestMolStandardize.py, rdkit/Chem/MolStandardize/UnitTestMolVS.py, rdkit/Chem/MolStandardize/charge.py, rdkit/Chem/MolStandardize/fragment.py, rdkit/Chem/MolStandardize/metal.py, rdkit/Chem/MolStandardize/normalize.py, rdkit/Chem/MolStandardize/tautomer.py, rdkit/Chem/MolStandardize/utils.py, rdkit/Chem/MolStandardize/validations.py
----------------
Changes:
- [Remark]: In charge.py, the method in line 245 and 255 seems redundant. I has dropped it and no issue raised
- [Remark]: Method `normalize()` in `normalize.py`  is relatively weird due to the excessive use of list. This patch is to correct the method and free some unused memory. No speed-boost here.
=> Clean-up Python #4815 - P1.12: Chem\MolStandardize

rdkit/Chem/Pharm2D/Generate.py, rdkit/Chem/Pharm2D/Matcher.py, rdkit/Chem/Pharm2D/SigFactory.py, rdkit/Chem/Pharm2D/UnitTestGobbi.py, rdkit/Chem/Pharm2D/UnitTestLazyGenerator.py, rdkit/Chem/Pharm2D/UnitTestMatcher.py, rdkit/Chem/Pharm2D/UnitTestSignature.py, rdkit/Chem/Pharm2D/UnitTestUtils.py, rdkit/Chem/Pharm2D/Utils.py, rdkit/Chem/Pharm3D/EmbedLib.py, rdkit/Chem/Pharm3D/ExcludedVolume.py, rdkit/Chem/Pharm3D/Pharmacophore.py, rdkit/Chem/Pharm3D/UnitTestEmbed.py
------
- [Remark]: Optimize `DownsampleBoundsMatrix()` in `EmbedLib.py`. The execution is varied depended on the input rather than consuming the worst-case scenario
- [Bug]: `DownsampleBoundsMatrix()` in `EmbedLib.py` now returns the same datatype as input rather than always casting to `np.float64`
- [New]: Drop/Remove one doctest in `OrderTriangle()` as the result of duplication
- [New]: Function `CountUpTo()` use `NumCombinations()` one time if `verbose`  instead of two in the previous examples
- [New]: Remove function `_fact()` of user in `Pharm2D\Utils.py`. Now we used `math.comb()` and `math.factorial()` for computation if python version is 3.8+. Otherwise, use user-defined …
=> Clean-up Python #4815 - P1.13: Chem\Pharm2D & Chem\Pharm3D

Code/GraphMol/catch_graphmol.cpp
One of the tests for the move constructors included stereo group specifications on an atom without valid stereo.
This stereo group ends up being removed due to the fixes in #4986, but the tests were still expecting it to be there.
This updates the test so that the offending atom actually does have stereo.
=> resolves bad input in one of the tests

Code/GraphMol/CIPLabeler/CIPMol.cpp, Code/GraphMol/CIPLabeler/CMakeLists.txt, Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/CIPLabeler/rules/Rule1a.cpp, Code/GraphMol/CIPLabeler/rules/SequenceRule.cpp
Opening this to start a discussion about the fix for #4998 in particular.
What this is currently doing will clearly give the right answer if the non-kekulized bonds are not involved in distinguishing between ligands. If the bonds do need to be involved in setting chirality, it's not at all clear what the right answer should be.
We could pick bond order 1 (here) or bond order 0 (used for dative bonds).
It's worth discussing this.
=> Fixes #4996 and #4998

Code/GraphMol/MolDraw2D/test1.cpp, Code/GraphMol/QueryOps.cpp
Fixes #5006
With this PR a query atom containing an `atomAnd` query is depicted as a `?` rather than causing an exception to be raised.
=> Fixes #5006

External/CoordGen/CoordGen.h
When generating coordinates for molecules with zero order bonds,
the coordgen adapter layer emitted a warning. This addresses that
warning.
=> Fix warning when generating coordinates for ZOBs

Code/GraphMol/Kekulize.cpp, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java
The log message for a Kekulization failure had an extra newline.  This removes it.
Example of the old behavior:
```
[01:01:51] Can't kekulize mol.  Unkekulized atoms: 6 7 8 9 10
[01:01:51] Explicit valence for atom # 2 H, 2, is greater than permitted
[01:01:51] Explicit valence for atom # 2 H, 2, is greater than permitted
[01:01:51] Explicit valence for atom # 2 H, 2, is greater than permitted
[01:01:51] Can't kekulize mol.  Unkekulized atoms: 17 18 19 21 22
[01:01:51] Explicit valence for atom # 2 H, 2, is greater than permitted
[01:01:51] Can't kekulize mol.  Unkekulized atoms: 8 10 12 15 18
```
=> Remove extra newline from Kekulize error message.

Code/GraphMol/FMCS/FMCS.cpp, Code/GraphMol/FMCS/testFMCS_Unit.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
Fixes issue discussed in https://github.com/rdkit/rdkit/discussions/5000
the RMCS checkBondStereo function only compared if the bond stereo was defined for one bond, and not for the other.  It didn't check to see that if they were both set, that they matched.  Thus CC\C=C\CC and CC\C=C/CC were deemed a match.
Tested on macOS and C++ only.
=> Make FMCS check bond stereo.

Code/GraphMol/Fingerprints/FingerprintUtil.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp
The fix here is simple: add the toggle to have `getTotalNumHs()` consider the neighbors.
=> Fixes #5036

Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h
Improving dark mode palette for N, Br and I atoms.
=> Improving atom colors for dark mode.

Code/SimDivPickers/LeaderPicker.h
This code has been there for two years, but isn't built by default since we don't have a cross-platform solution yet.
Rather than continue to wait until the cross-platform solution is found (which we'll get for "free" with C++20), this enables the multithreaded picker on linux when the RDKit is already being built with threading support.
=> enable the multithreaded LeaderPicker on linux

Code/GraphMol/MolDraw2D/AtomSymbol.h, Code/GraphMol/MolDraw2D/DrawShape.h, Code/GraphMol/MolDraw2D/DrawTextFT.h, Code/GraphMol/MolDraw2D/DrawTextFTCairo.h, Code/GraphMol/MolDraw2D/DrawTextFTJS.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.h, Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
Simple fix for AtomSymbol, it needs a virtual destructor since it has virtual functions.
=> AtomSymbol needs to have a virtual destructor

Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
Use a simpler method of exposing MolzipParams::atomSymbols to python
=> Expose MolzipParams::atomSymbols to python

Code/GraphMol/Substruct/catch_tests.cpp, External/AvalonTools/CMakeLists.txt, External/CoordGen/CMakeLists.txt, External/INCHI-API/CMakeLists.txt
1. suppress a bunch of warnings from third-party code with clang and g++
2. get rid of one warning in RDKit code
I will probably add some additional suppression for MSVC++ too, but let's start with clang and g++
=> [WIP] Clean up the warning landscape

Code/GraphMol/MolHash/CMakeLists.txt, Code/GraphMol/MolHash/MolHash.h, Code/GraphMol/MolHash/Wrap/rdMolHash.cpp, Code/GraphMol/MolHash/Wrap/testMolHash.py, Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/MolHash/mf.h, Code/GraphMol/MolHash/nmmolhash.h, Code/GraphMol/MolHash/normalize.cpp, Code/GraphMol/catch_chirality.cpp, ReleaseNotes.md
This PR adds the option to include CXSMILES extensions to the hash strings generated by MolHash. One example of when this would be useful is when the molecules being hashed include enhanced stereochemistry.
Other changes in here:
- a bug fix to make sure hashes don't include stereo information on atoms/bonds which have newly duplicate neighbors
- a bit of general cleanup of the hashing code
=> Add a CXSMILES option to the MolHash

External/INCHI-API/inchi.cpp, External/INCHI-API/test.cpp
I noticed this while writing tests for an external project that uses RDKit.
A kekulization exception would cause `MolToInchi()` to return without cleaning up `m`. The smart pointer should now take care of cleaning it up whenever we leave the function.
=> To INCHI conversion leaks on kekulization failure

rdkit/UnitTestLogging.py, rdkit/__init__.py
The logging level was set to DEBUG since #4846. This causes an excess of text to be printed when certain operations are performed. We should raise the level to WARN to reduce the amount of logs being printed to a reasonable level.
E.g., just importing `from rdkit.Chem import MolStandardize` results in this output being printed on the console:
```
Initializing Normalization: Nitro to N+(O-)=O
Initializing Normalization: Sulfone to S(=O)(=O)
Initializing Normalization: Pyridine oxide to n+O-
Initializing Normalization: Azide to N=N+=N-
Initializing Normalization: Diazo/azo to =N+=N-
Initializing Normalization: Sulfoxide to -S+(O-)-
Initializing Normalization: Phosphate to P(O-)=O
Initializing Normalization: C/S+N to C/S=N+
Initializing Normalization: P+N to P=N+
Initializing Normalization: …
```
=> Python loggers set to DEBUG level by default

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes https://github.com/rdkit/rdkit/issues/5061
When no reagents are present in the reaction, there's nothing to use to scale the line width when drawing the arrow.  Duck the problem by drawing the arrow last.
On my macBook, I am getting what look spurious different hash codes messaged for the moldraw2DRxnTest1 SVGs.
=> Fix github 5061.

Code/GraphMol/Deprotect/Deprotect.cpp, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolEnumerator/LinkNode.cpp, Code/GraphMol/MolStandardize/testNormalize.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/RDBoost/Wrap/RDBase.cpp, Code/RDGeneral/CMakeLists.txt, Code/RDGeneral/RDLog.cpp, Code/RDGeneral/RDLog.h, Code/RDGeneral/catch_logs.cpp, ReleaseNotes.md, rdkit/UnitTestLogging.py
This reduces the default verbosity of the core.
This also adds the class `RDLog::LogStateSetter` class to make it easier to control which logs are active.
Including everyone on the review since this simple change is wide reaching
=> disable Info and Debug logs by default

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMol.h, Code/GraphMol/MolDraw2D/catch_tests.cpp
This changes the drawing code to directly honor the `legendFontSize` option when flexicanvas mode (this is when the canvas size is provided as -1,-1) is being used. This is now consistent with the way atom labels and other notes are handled.
Here's a comparison of what you get with master (left) and after this PR (right)
For the first three of those the default `legendFontSize`, 16, is used. For the last I specified `legendFontSize = 32`
=> modify the way legends are handled with the flexicanvas mode

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
Also fixes an off-by-one problem with the assigned isotope labels
Turns out we didn't have any tests for this so it never got caught.
=> Make the RGD code work when `rgroupLabelling` is `Isotope`

Code/GraphMol/MolStandardize/TautomerCatalog/tautomerTransforms.in, Code/GraphMol/MolStandardize/catch_tests.cpp, Code/GraphMol/MolStandardize/test_data/tautomerTransforms.in
The change is simple: make sure that the P involved in the tautomer shifts only has three neighbors and doesn't have an H (this is to avoid hypervalent P)
=> Fixes #5008: Add H and X specification to P tautomerization rules

External/catch/CMakeLists.txt
Apparently newer `libc` does not play well with older Catch2 versions, see for example
https://github.com/OffchainLabs/arbitrum/pull/1812
Updating to 2.13.8 should fix the problem.
=> Update Catch2 (fixes #5089)

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.h, Code/GraphMol/ChemTransforms/catch_tests.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
This code allows non sanitizable fragments to be combined.  This is useful when combining multiple fragments that may eventually become a sensible molecule.
=> Add sanitize option to molzip

Code/GraphMol/AddHs.cpp, Code/GraphMol/molopstest.cpp
This fixes #5099.
Not much explanation needed: `removeWithWedgedBond` is tested inside the conditional, but in the current state of the code, we were never entering if these were the only H we are keeping.
=> Fixes #5099

Code/GraphMol/Bond.h, Code/GraphMol/QueryAtom.h, Code/GraphMol/SubstanceGroup.h
We had some missing `#includes`
Pointed out by @rogersayle here: https://github.com/rdkit/rdkit/pull/4909#issuecomment-1059195106
=> add #include <utility>

rdkit/Chem/PandasTools.py
This PR fixes #5017
`patchPandasrepr()` patches `pd.io.formats.html.HTMLFormatter._write_cell()`, then it restores the original function before returning. However, while doing so, it also sets an `_rdkitpatched` attribute on `pandas.io.formats.html.HTMLFormatter`.
The next time patchPandasrepr() is called, the patch is not applied anymore due to the present of the `_rdkitpatched` attribute, even though the patch has actually been reverted.
This explains why the DataFrame displays molecules as PNG images only the first time.
The fix is removing the usage of `_rdkitpatched` attribute entirely as it is not necessary, since the patch is applied and then reverted. Instead, a `try..finally` block is used to make sure that the patch is reverted before returning even if an exception is raised. …
=> Fixes #5017

Docs/Book/source/rdkit.Chem.DSViewer.rst, Docs/Book/source/rdkit.Chem.Draw.rdMolDraw2DQt.rst, Docs/Book/source/rdkit.Chem.Draw.rst, Docs/Book/source/rdkit.Chem.Pharm2D.LazyGenerator.rst, Docs/Book/source/rdkit.Chem.Pharm2D.rst, Docs/Book/source/rdkit.Chem.Subshape.rst, Docs/Book/source/rdkit.Chem.Subshape.testCombined.rst, Docs/Book/source/rdkit.Chem.rdEHTTools.rst, Docs/Book/source/rdkit.Chem.rdStructChecker.rst, Docs/Book/source/rdkit.Chem.rst, Docs/Book/source/rdkit.DataStructs.HierarchyVis.rst, Docs/Book/source/rdkit.DataStructs.rst, Docs/Book/source/rdkit.ML.Data.cQuantize.rst, Docs/Book/source/rdkit.ML.Data.rst, Docs/Book/source/rdkit.ML.DecTree.randomtest.rst, Docs/Book/source/rdkit.ML.DecTree.rst, Docs/Book/source/rdkit.VLib.NodeLib.demo.rst, Docs/Book/source/rdkit.VLib.NodeLib.rst, Docs/Book/source/rdkit.utils.chemdraw.rst, Docs/Book/source/rdkit.utils.chemdraw_qax.rst, Docs/Book/source/rdkit.utils.comhack.rst, Docs/Book/source/rdkit.utils.rst
This removes files referencing modules which either no longer exist or for which the doc-generation just doesn't work and adds a couple stubs for modules which were missing.
=> Cleanup of python API documentation stubs

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Straightforward changes to `assignChiralTypesFromBondDirs()` to allow the wiggly bond spec to over-ride whatever else may be present.
=> Fixes #5108

Code/GraphMol/Descriptors/Lipinski.cpp, Code/GraphMol/Descriptors/catch_tests.cpp
This changes the SMARTS patterns to recognize single or aromatic bonds which are not in rings as potentially rotatable.
Clearly the "or aromatic" case only comes into play for molecules which haven't been kekulized - otherwise non-ring bonds can't be aromatic.
=> Fixes #5104

Code/MinimalLib/tests/tests.js
`String.prototype.matchAll()` is only available in `nodejs` >= 12.
This PR switches to using `String.prototype.match()` to avoid the problem.
=> Modified the JS tests to comply with older nodejs versions

Code/GraphMol/Aromaticity.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/QueryOps.cpp
We needed to add a special case to the aromaticity code for bond-order queries. There's not really a perfectly correct answer for this, but the change here is to have them contribute to valence for aromaticity like a normal bond. Previously they weren't contributing to the valence for aromaticity at all.
Also adds a typeLabel to the bond order queries so that they are easier to recognize
=> Fixes #5152

rdkit/Chem/Draw/qtCanvas.py
Fixes #5166
Explicitly cast float to int where appropriate/expected for Qt5.
=> Fix qtCanvas errors on Python 3.10 due to implicit float->int casting

Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/CIPLabeler/rules/Rule2.cpp, Code/GraphMol/CIPLabeler/rules/SequenceRule.cpp
This fixes #5142 
It seems that when we did #5001 we missed a couple of checks for `getAtomicNum() == 0`.
=> Fixes #5142

rdkit/Chem/Draw/InteractiveRenderer.py
This PR avoids that `delattr` fails with an `AttributeError` if `_opts` is not yet set.
Thanks to Jacob Gora for reporting this.
=> Very small fix to avoid an AttributeError

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #5185 
Puts an extra test to make sure the annotation doesn't lie on the vector between two bonded atoms.  With a double bond, there isn't a line exactly along that vector. 
Tested on macOs only.
=> Add test for string rectangle clashing with vector bwtween bonded atoms.

Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
`assignStereochemistry()` and `findPotentialStereo()` no longer take zero-order, unspecified, or dative bonds starting at an atom into account when figuring out the number of neighbors an atom has.
This doesn't do anything to the CIP assignment code. That assumes that atoms which have stereo markers should be considered for stereo, so there's no straightforward mechanism to add a "this can't be a stereo atom" check. As long as we're using either `assignStereochemistry()` or `findPotentialStereo()` to cleanup bogus stereo specifications before perceiving CIP I think everything should be fine though.
This also fixes #5200, which I discovered while working on this.
=> Fixes #5196

Code/GraphMol/ROMol.h, Code/GraphMol/catch_graphmol.cpp
This is something that had been bugging me for some time: I had tried a couple of times to use atom and/or bond iterators with the STL algorithms, but never got it to work. Now I finally looked it up, and it turned out to be a quite easy fix, it turns out we just had to define some tags on the iterators!
=> Make atom, bond iterators usable in STL algorithms

Code/DataStructs/MultiFPBReader.cpp, Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FindStereo.cpp, Code/RDGeneral/Ranking.h
My build (GCC 11.1.0) is currently failing due to multiple definitions of `Rankers::pairGreater` and `Rankers::pairLess`:
```
/scratch/toscopa1/.conda/envs/pyds_v0.9L/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/DataStructs.dir/MultiFPBReader.cpp.o:(.bss+0x0): multiple definition of `Rankers::pairLess';
CMakeFiles/DataStructs.dir/FPBReader.cpp.o:(.bss+0x0): first defined here
/scratch/toscopa1/.conda/envs/pyds_v0.9L/bin/../lib/gcc/x86_64-conda-linux-gnu/11.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/DataStructs.dir/MultiFPBReader.cpp.o:(.bss+0x1): multiple definition of `Rankers::pairGreater'; CMakeFiles/DataStructs.dir/FPBReader.cpp.o:(.bss+0x1): first defined here
```
Looking at the code, it seems that different lambdas …
=> Fixes multiple definitions of symbols

Code/GraphMol/CMakeLists.txt, Code/MinimalLib/CMakeLists.txt
With this change I was able to cross compile for Windows by using MinGW.
I'm not changing them, but as far as I can tell the `if`s at https://github.com/rdkit/rdkit/blob/4fafb72212163bbdaeafbb364d7f922b95a823bf/Code/MinimalLib/CMakeLists.txt#L32-L34 and https://github.com/rdkit/rdkit/blob/4fafb72212163bbdaeafbb364d7f922b95a823bf/Code/MinimalLib/CMakeLists.txt#L43-L45 are completely useless: `RDK_URF_LIBS` is always true, so these `if`s are _always_ hit, and `RingDecomposerLib` is already unconditionally added to `LIBS_TO_USE` at https://github.com/rdkit/rdkit/blob/4fafb72212163bbdaeafbb364d7f922b95a823bf/Code/MinimalLib/CMakeLists.txt#L31 and https://github.com/rdkit/rdkit/blob/4fafb72212163bbdaeafbb364d7f922b95a823bf/Code/MinimalLib/CMakeLists.txt#L42
=> More consistently check for `WIN32` instead of `MSVC` in CMake files

Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp, Code/GraphMol/FMCS/SubstructMatchCustom.h
I've been playing with address sanitization on Python tests (fortunately, asan is way faster than valgrind when working around Python).
Some Python test revealed an array overflow in line 204 of Code/GraphMol/FMCS/MaximumCommonSubgraph.cpp. I'm not familiar with the FMCS code, but this looks like a bug to me.
Sadly, I don't know how to write a test that would expose this.
=> Fixes array overflow in FMCS code

Code/GraphMol/PeriodicTable.cpp
Fixes #5207 by using the "correct" macro name mentioned in the CMake file (see the attached issue).
I'm adding the quotes because `RDK_THREADSAFE_SSS`, despite being the actual name of the macro we use, and being used in several other places, is apparently not the right name, or so we said in 2018:
https://github.com/rdkit/rdkit/blob/66476f01c014b4f0b81b2ff9851120227a5d548b/ReleaseNotes.md?plain=1#L2469-L2482
It's not the only macro we've messed up, though: `USE_BUILTIN_POPCOUNT` still seems to be used in some places, although it was first renamed to  and then, more recently, to `RDK_OPTIMIZE_POPCNT`, `BUILD_COORDGEN_SUPPORT` seems to be used once in one ROMol.i
I think we should fix the names at some point, but for now, I'm just renaming these to fix the periodic table.
Oh, and the …
=> Fixes #5207

Code/GraphMol/MolDraw2D/CMakeLists.txt, Code/GraphMol/MolDraw2D/Qt/CMakeLists.txt, Code/GraphMol/MolDraw2D/Qt/Demo/CMakeLists.txt, Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h, Code/GraphMol/MolDraw2D/Qt/Wrap/CMakeLists.txt, Code/GraphMol/MolDraw2D/Qt/Wrap/rdMolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/Qt/Wrap/testMolDraw2DQt.py, rdkit/Chem/Draw/UnitTestDraw.py, rdkit/Chem/Draw/__init__.py, rdkit/Chem/Draw/qtCanvas.py
This adds support for Qt6.
By setting `RDK_USE_QT6=ON`, we will use Qt6 instead of Qt5 to build.
I added a `rdkitQtVersion` attribute to the `rdMolDraw2DQt` Python module to indicate which Qt version was used in the build. The version will be populated with the Qt version found by CMake via a macro definition.
`PySide6` may sound weird, since for Qt5 we use `PySide`/`PySide2`, but that's the right one according to https://www.qt.io/blog/qt-for-python-6-released.
We don't currently have any CI with Qt6, but I've tested this with Qt6 on Linux and Mac, and I'm currently working on Windows. So  far, everything built fine and passed tests, except a couple of Inchi ones which failed on both platforms, but I think that's not related.
I'll keep this as WIP while I run more testing and fix any …
=> Add support for Qt6

Code/RDGeneral/RDLog.cpp
`localtime()` is not thread safe (https://linux.die.net/man/3/localtime): 
> 
> The four functions asctime(), ctime(), gmtime() and localtime() return a pointer to static data and hence are not thread-safe. 
> Thread-safe versions asctime_r(), ctime_r(), gmtime_r() and localtime_r() are specified by SUSv2, and available since libc 5.2.5. 
> 
RDkit uses `localtime()` in logging, and the thread sanitizer flags its usage as a data race. Fortunately, it's easy to fix.
=> Fix use of not thread safe function localtime() 

Code/GraphMol/MolStandardize/Charge.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
The fix is pretty easy: change the SMARTS patterns used to determine whether not a positively charged atom has hydrogens (and can thus be neutralized by removing an H) to only recognize implicit Hs.
We might think about adding an option to allow explicit (in graph) Hs to be removed at some later point.
=> Fixes #5169

Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.cpp, Code/GraphMol/MolDraw2D/Qt/DrawTextFTQt.h
I finally managed to test the Qt6 build under Windows, which requires VS2019.
The first try failed because the compiler complained about `QPainterPath` when it tried to generate a deleter function, I assume while trying to create a default destructor on header file import:
```
MSVC\14.29.30133\include\memory(3119): error C2027: use of undefined type 'QPainterPath'
C:\build\rdkit\Code\GraphMol\MolDraw2D\Qt\DrawTextFTQt.h(20): note: see declaration of 'QPainterPath'
MSVC\14.29.30133\include\memory(3118): note: while compiling class template member function 'void std::default_delete<QPainterPath>::operator ()(_Ty *) noexcept const'
```
Declaring the destructor, and specifying it to be a default in the implementation file solved the issue.
Also, given the unique pointer member, I decided to …
=> Fix qt build under VS2019

Code/RDGeneral/LocaleSwitcher.cpp
This fixes #5214 by refactoring the non-windows branch of `RDKit::Utils::LocaleSwitcher` to make it work in the same way as the windows branch, avoiding the use of `setlocale()` and updating the locale only for the local thread.
=> Fixes #5214

Code/GraphMol/FileParsers/MultithreadedMolSupplier.h
Another thread sanitizer detection: `d_lastRecordId` is, apparently, written and read by different threads, so we need to make sure it's accessed one at a time.
=> Fix data race in MultithreadedMolSupplier 

Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp
Another detection flagged by the thread sanitizer.
In this case, there's a data race condition in `rgroupData->fingerprint`, which is updated inside `addFingerprintToRGroupData()`. Maybe not a big issue due to the duplicated check, but it's still good to get it fixed by removing the duplicate check outside the mutex.
=> Fix duplicate non thread safe check in VarianceDataForLabel

Code/GraphMol/TautomerQuery/CMakeLists.txt, Code/GraphMol/TautomerQuery/TautomerQuery.cpp, Code/GraphMol/TautomerQuery/TautomerQuery.h, Code/GraphMol/TautomerQuery/Wrap/rdTautomerQuery.cpp, Code/GraphMol/TautomerQuery/Wrap/rough_test.py, Code/GraphMol/TautomerQuery/catch_tests.cpp
This adds boost::serialization support to the `TautomerQuery` class.
This is potentially useful by itself, but it's also a pre-req for using these in the PostgreSQL cartridge, which is what I really want to do. :-)
While implementing this I noticed that things would be a lot easier if `ROMol` supported boost::serialization; I'll do a separate PR for that.
=> Make TautomerQuery serializable

Code/GraphMol/CMakeLists.txt, Code/GraphMol/FilterCatalog/FilterMatchers.h, Code/GraphMol/ROMol.cpp, Code/GraphMol/ROMol.h, Code/GraphMol/SubstructLibrary/SubstructLibrarySerialization.h, Code/GraphMol/testPickler.cpp
This isn't really intended for use on its own (though that's possible of course); it's mainly there to allow other classes which include ROMols to be serialized more easily
=> add boost::serialization support to ROMol

Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/testReaction.cpp
I've noticed that the `ChemicalReaction` copy assignment operator has been purposefully hidden by making its declaration `private`.
https://github.com/rdkit/rdkit/blob/8a4c208a19c41a0c5a9fb2d5d2ed49349f61b59b/Code/GraphMol/ChemReactions/Reaction.h#L356-L360
As far as I can tell `ChemicalReaction` could be copied and assigned trivially. The base class `RDProps` is copy assignable, and so are all member variables of `ChemicalReaction`. In fact, removing the above declaration allows the compiler to generate a copy assignment operator which seems to work as expected.
Why was this operator disabled? If it should remain disabled I think it would be clearer to use the C++11 `delete` keyword as opposed to making the function declaration `private`.
```cpp
ChemicalReaction &operator=(const …
```
=> Allow the compiler to generate default ChemicalReaction copy assignment operator

Code/GraphMol/FileParsers/ProximityBonds.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Acetyl caps are fairly common, but currently their bond order isn't properly inferred.
Adding support for this would be pretty ACE.
=> add ACE caps double bonds

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes 5296, discussed in https://github.com/rdkit/rdkit/discussions/5195
When placing the atom annotations, it ignores the highlights.
Tested on macOS only.
=> Fix bad layout of atom notes with highlights.

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
An unintended consequence of the changes in #5264 was empty atom label sections being output to CXSMILES.
This clears that up.
=> remove extra output from CXSMILES

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
Avoids a segfault in case a `None` molecule is passed to `rdMolDraw2D.PrepareMolForDrawing()`.
=> Fixes #5298

Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/testReaction.cpp
Addresses the issues of PR #5265.
The default `ChemicalReaction` copy assignment operator introduced with PR #5265 copied pointers to reactant/agent/product templates as opposed to the underlying molecules. As noted by @bp-kelley, this can have unintended consequences when modifying the template molecules. This PR provides an implementation for the copy assignment operator that copies the underlying resources.
=> Add ChemicalReaction copy assignment implementation

Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_chirality.cpp, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js, Docs/Book/RDKit_Book.rst
This currently defaults to true, but when it is set then the new stereo code is used when calling `AssignStereochemistry()`
=> Add a global feature flag to enable the "new" stereo perception code

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Docs/Book/RDKit_Book.rst
The changes in #5251 didn't actually fix the thread-safety problem and the test was leading to intermittent test failures
This reverts the changes to #5251.
=> revert #5251, document the problem

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/catch_chirality.cpp
The primary change here is to cause stereochemistry to be perceived from 3D conformers in mol blocks even if there are no wedged bonds present (this is #5327). This removes the need to add a call to `AssignStereochemistryFrom3D()` after reading a molecule from a mol block or SDF in order to be sure that stereo is properly set.
Along the way I discovered that `assignChiralTypesFrom3D()` was ignoring wiggly bonds, so that also needed to be fixed.
=> [WIP] Fixes #5327 and #5328

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp
Fixes #5334 
FragmentOnBonds allows multiple links with the same label, everything else does not.  This caused issues when looking at the ordering for chirality.
This fixes both issues.
=> Fix segfault in mol zip

Code/MinimalLib/docker/Dockerfile, package.json
ref https://github.com/rdkit/rdkit/issues/5346#issuecomment-1144941460
- replace prepublish script with prepublishOnly script ref: https://docs.npmjs.com/cli/v8/using-npm/scripts\#prepare-and-prepublish
- fix bin command for node in minimallib Dockerfile
check context in issue ref https://github.com/rdkit/rdkit/issues/5346#issuecomment-1144941460
cc @greglandrum @ptosco 
-----------------------------
TLDR;
1. the npm `prepublish` script which runs automatically when you run `npm publish` [has been renamed to `prepublishOnly` in recent npm versions
](https://docs.npmjs.com/cli/v8/using-npm/scripts\#prepare-and-prepublish
)
2. the node bin command that gets installed is now named `node` and not `nodejs`
=> Minimallib NPM release fixes - wrong node bin command in Dockerfile and prepublish npm script command replacement

Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/catch_chirality.cpp
The code to select bond wedges currently chooses to wedge ring bonds rather than bonds to ring atoms with double bonds.
This leads to this kind of ugliness:
The non-ring bond to the phenyl ring should be wedged instead, like what happens with cyclohexane:
This PR fixes the problem.
=> Prevent wedging ring bonds

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes class annotation in SVGs for wavy bonds.
Unlike the other bond types, wavy bonds weren't being annotated with the atom and bond classes in SVGs.
Tested on macOS Apple silicon only.
=> Class info info missing for for wavy bonds in SVGs.

Code/GraphMol/Wrap/MolOps.cpp
- Use O[CH3] instead of OC for the existing examples, to ensure that the
the examples produce the output shown (assuming the query is parsed as
a SMARTS).
- Add a note and an example showing how bonds are formed only to the
atoms that were connected to the first atom in the substructure query,
and suggest using ChemicalReaction for finer control.
Documents behavior explained in #5329
=> Update docs for ReplaceSubstructs

Docs/Book/Install.md, README.md
RDKit platform wheels are now available at PyPI and can be installed using 
```sh
pip install rdkit
``` 
This PR updates the documentation. Fixes #1812
=> Fixes #1812

Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp
I believe this fixes the sgroup writing issue.
It appears that the headCrossing and tailCrossing were being filled with proper bond indices from getBondBetweenAtoms, but then looking these up in the bondIndexMap as if they were the index of the bond order when being parsed.   This was causing bad lookups when trying to get the bondType.
=> Fixes #5324

Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp
Fixes typos in docString in MolAlign.
Adds two 'e's.
This is my entry in the "Most pedantic PR ever" competition.
=> Fix typos in docString.

Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, Code/GraphMol/MolAlign/CMakeLists.txt, Code/GraphMol/MolAlign/Wrap/rdMolAlign.cpp, Code/GraphMol/MolAlign/Wrap/testMolAlign.py, Code/GraphMol/MolAlign/catch_tests.cpp, ReleaseNotes.md
Here's a demonstration of the problem this fixes; take two conformers of deprotonated propionic acid which just differ by swapping the two carboxylate O atoms:
```
In [4]: mol = Chem.MolFromSmiles("CCC(=O)[O-] |(-1.11,0.08,-0.29;0.08,-0.18,0.58;1.34,0.03,-0.16;1.74,1.22,-0.32;2.06,-1.04,-0.66)|")
In [5]: qry = Chem.MolFromSmiles("CCC([O-])=O |(-1.11,0.08,-0.29;0.08,-0.18,0.58;1.34,0.03,-0.16;1.74,1.22,-0.32;2.06,-1.04,-0.66)|")
```
The current version of `GetBestRMS()` produces this alignment since it assumes that the two O atoms are not equivalent to each other:
This PR adds allows those O atoms to be considered to be equivalent to each other, which gives a perfect alignment here:
```
In [7]: rdMolAlign.GetBestRMS(qry, mol, symmetrizeConjugatedTerminalGroups=True)
Out[7]: 0.0
```
They …
=> Support conjugated terminal groups in GetBestRMS()

Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/MolDraw2DJS.cpp, Code/GraphMol/MolDraw2D/MolDraw2DJS.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp, Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.h, Code/GraphMol/MolDraw2D/Qt/catch_qt.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Adds the missing wavy bonds to the Qt and JS drawing code and fixes the drawing of brackets in Qt.
=> Fixes #5386 and #5389

Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp
After merging #5387, builds using GCC 12 and Qt fail with:
```
/tmp/rdkit_builder/rdkit/Code/GraphMol/MolDraw2D/Qt/MolDraw2DQt.cpp:136:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
136 |     QPainterPath path;
```
Adding this include fixes the build.
=> Fix GCC 12/Qt build after #5387

rdkit/Chem/PandasTools.py
The PandasTools code always tries to import the IPythonConsole code. This ends up doing a bunch of monkey patching of code in `rdkit.Chem.Draw` even if things aren't being run in a notebook.
This patch checks to see if we're running in a notebook before bringing in the IPythonConsole code.
=> PandasTools should not always bring in IPythonConsole

Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
N/A - simple doc fix
The indentation of the parameters for EmbedMultipleConfs @ https://www.rdkit.org/docs/source/rdkit.Chem.rdDistGeom.html had an extra level of indentation. I believe I have corrected this.
I'm not 100% confident on the translation from C++ -> Python docstring here and don't know how to confirm my docstring. I also could not find instructions for building docs. I suspect there should not be any problems from such a minor change.
=> fix: rdkit.Chem.rdDistGeom.EmbedMultipleConfs docstring indentation

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
Ok, I think I found the issue. This fixes #5403
It seems the problem is in the way we try to find pairs of potential chiral atoms in fused rings (for the examples, we never hit the even-sided block, since we only look at the smaller rings, the two fused 5 bond rings):
https://github.com/rdkit/rdkit/blob/73d0d82664be5322861f5afe756c70ff4868b7a7/Code/GraphMol/FindStereo.cpp#L455-L467
First of all, we never check whether `aidx` is potentially chiral, but we still mark it as such. Second, we only check 1 bond away of `aidx` for a second potentially chiral atom.
Together, these 2 issues allow to correctly identify 2 chiral centers in `m = N[C@@]12CC[C@@](CC1)(C2)C(F)F`, but only one in `nm = C1C[C@]2(C(F)F)CC[C@@]1(N)C2`.
More specifically, in `m` we add the atom pairs (7,4) for ring …
=> Fixes #5403

Code/GraphMol/Aromaticity.cpp
We noticed a performance hit for sanitizing very ringy structures (specifically for chained bucky balls and a smaller performance hit for nanotubes) after the 2022_03_02 release and traced it back to https://github.com/rdkit/rdkit/pull/4722/. I did some profiling and found that copying all of the ring neighbors in RingUtils::checkFused seemed to be causing the performance degradation. 
Before this change:
Time to sanitize...
Chained bucky balls (128 atoms): 0.184651 s
Nanotube (2412 atoms): 0.361771 s
After this change: 
Time to sanitize...
Chained bucky balls (128 atoms): 0.025208 s
Nanotube (2412 atoms): 0.277536 s
=> Fix performance issue in RingUtils::checkFused

Code/ForceField/MMFF/Params.h, Code/Geometry/UniformGrid3D.h, Code/GraphMol/Abbreviations/Abbreviations.h, Code/GraphMol/Atom.h, Code/GraphMol/Canon.h, Code/GraphMol/ChemReactions/ReactionParser.h, Code/GraphMol/ChemReactions/ReactionPickler.h, Code/GraphMol/Chirality.h, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/FileParsers/FileParsers.h, Code/GraphMol/FileParsers/MultithreadedMolSupplier.h, Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h, Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h, Code/GraphMol/FileParsers/PNGParser.h, Code/GraphMol/FilterCatalog/FilterCatalogEntry.h, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolEnumerator/MolEnumerator.h, Code/GraphMol/MolInterchange/MolInterchange.h, Code/GraphMol/MolOps.h, Code/GraphMol/MolPickler.h, Code/GraphMol/MolStandardize/MolStandardize.h, Code/GraphMol/ROMol.h, Code/GraphMol/RWMol.h, Code/GraphMol/RingInfo.h, Code/GraphMol/SubstanceGroup.h, Code/Numerics/Vector.h
For example,
```cpp
int x;  //! comment for x
int y;
```
is equivalent to
```cpp
int x;
//! comment for x
int y;
```
i.e. that is a Doxygen comment for *y*; it should be
```cpp
int x;  //!< comment for x
int y;
```
https://www.doxygen.nl/manual/docblocks.html#memberdoc
=> fix doxygen comments

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
This addresses #5423 by clearing the `molTotValence` after it has been used to adjust H on the atom with the property.
=> Fixes #5423

.clang-format, Code/GraphMol/CMakeLists.txt, Code/GraphMol/ChemReactions/testReaction.cpp, Code/GraphMol/MolHash/Wrap/testMolHash.py, Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/catch_canon.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/new_canon.cpp, Code/GraphMol/new_canon.h, Code/GraphMol/testChirality.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
The canonicalization code has always used CIP codes on the atoms as part of the canonicalization process. This is sub-optimal since it means we need those assignments in order to generate canonical atom ranks and it won't work at all when we try to canonicalize non-tetrahedral centers.
This PR removes the CIP usage and just takes the canonical ranks of the chiral atom's neighbors into account instead.
Unfortunately this will change the canonical SMILES which is generated in many circumstances. There's no way around that.
I had some concerns about the performance impact of these changes, but I ran some benchmarking on ~75K ChEMBL molecules which include chirality and see no appreciable change in the time to generate canonical SMILES. Here's the timing info, the molecules are parsed once …
=> Drop usage of CIP information from the canonicalization code

Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
closes #5351
[`PrintThread::cout_mutex`](https://github.com/rdkit/rdkit/blob/9fa1df1cf6380a03bddb9b176dd4c9b1c0ac35af/Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp#L30-L38) misses its definition, which results in linkage error (#5351).
A conventional alternative is:
```diff
--- a/Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
+++ b/Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp
@@ -37,6 +37,8 @@ struct PrintThread : public std::stringstream {
}
};
+std::mutex PrintThread::cout_mutex;
+
void testSmiConcurrent(std::istream *strm, bool takeOwnership,
std::string delimiter, int smilesColumn, int nameColumn,
bool titleLine, bool sanitize,
```
Off-topic: `std::stringstream::~stringstream` is not `virtual`.
=> fix: specify static member variable `PrintThread::cout_mutex` inline (C++17)

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMolMCH.cpp, Code/GraphMol/MolDraw2D/DrawMolMCH.h, Code/GraphMol/MolDraw2D/DrawShape.cpp, Code/GraphMol/MolDraw2D/DrawShape.h, Code/GraphMol/MolDraw2D/test1.cpp, rdkit/Chem/Draw/UnitTestDraw.py
Fixes #5420
The bond highlights were sometimes missing the atom highlights and the fallback position was incorrect.
Fallback now correct.
The miss was occurring in the test case because the atom highlight wasn't centred on the atom, it was centred on the centre of the atom label which for a multiple character label was off to one side.  It now uses the label centre.  Only really an issue with small fonts.
Using the label centre now means that the bond highlights aren't always parallel with the bond, but I think that's ok.  The alternative would be to make them narrower, so they still went parallel to the bond but hit the atom highlight very much off-centre.  That could be done, but would look differently messy, I think.  It's an edge case.
=> Github5420

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.h, Code/GraphMol/ChemTransforms/catch_tests.cpp
Implements #5451 
This adds an option to allow unsigned integer (and integer) properties atom labels to indicate which atoms should be zipped together.
This will be primarily used in the cdxml parser.
=> MolZip: add atom property labels for mol-zipping

Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #5448 
Clears the wedging information before applying from mol block.
=> Clear bond dirs before re-wedging.

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
No issue to reference
The new drawing code from #5425 did a very poor job joining a wedged bond to a double bond, as seen in acs1996_9.svg.  This fixes that.
=> Fix poor join between wedge and double bond.

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out
One-liner fix.
The compiler can't be sure that the string being passed isn't a format string, so it complains. This PR makes the call to `elog()` in question similar to the other calls.
=> Fixes #5234

Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
This should have been handled as part of #2696, but I missed it then.
Also includes a minor bit of refactoring so this kind of oversight doesn't happen again
=> Fixes #5433

Code/GraphMol/RGroupDecomposition/RGroupGa.cpp
This fix an issue where the number of permutations would overflow in the GA and be set to 0.
This caused the code to fallback to the Exhaustive search which basically hangs at this point.
=> Fix integer overflow in RGroupDecomposition strategy GA

External/CoordGen/CoordGen.h
Not a big issue, but the Visual Studio compiler raises a C4305 warning when using this header. If anyone includes this header while building with the `/WX` flag (treat all compiler warnings as errors), the build will fail.
The cause of the issue is that we are using a literal double value to initialize a float value, which counts as downcasting. Making the value a literal float fixes the issue.
=> Fix double to float downcasting warning

rdkit/Chem/EnumerateStereoisomers.py
Currently, importing EnumerateStereoisomers triggers this warning:
```
In [4]: from rdkit.Chem import EnumerateStereoisomers
/Users/rodrigue/Documents/code/rdkit-install/lib/python3.8/site-packages/rdkit/Chem/EnumerateStereoisomers.py:165: DeprecationWarning: invalid escape sequence \C
""" returns a generator that yields possible stereoisomers for a molecule
```
The warning doesn't seem too bad, as anything still works as expected, but when I use `EnumerateStereoisomers` in my pytest unit tests, it causes them to fail due to the unexpected warning while tests are collected.
This patch fixes the issue but making the docstring literal, and removing the duplicate slashes so that the doctests still pass.
=> Fixes "DeprecationWarning: invalid escape sequence \C" when importing EnumerateStereoisomers

Code/GraphMol/Wrap/MolOps.cpp
I noticed a warning during compilation caused by a spurious `\c` tag in a Python docstring.
This PR removes it.
=> Remove spurious doxygen tag

rdkit/Chem/MCS.py
None
Adds the deprecation warning to the MCS.py docstring.
It's the first hit when you google "RDKit mcs" and it's a bit irritating when you start using it and have your IDE tell you it's deprecated.
=> Add deprecation warning to docstring.

.azure-pipelines/linux_build.yml, .azure-pipelines/mac_build.yml
This pins cmake on the Mac builds and qt on the linux builds.  There were apparently regressions in both in recent condo deployments.
=> Pin cmake in mac and qt in linux for azure builds

Code/GraphMol/ROMol.cpp, Code/GraphMol/StereoGroup.cpp, Code/GraphMol/StereoGroup.h, Code/GraphMol/SubstanceGroup.cpp, Code/GraphMol/SubstanceGroup.h
I love `ROMol::debugMol()` and `Chem.Mol.Debug()`. They are very helpful in debugging, but sometimes they fall a bit short when debugging problems related to Substance Groups or Stereo Groups.
This PR adds printing some information about any Substance Groups or Stereo Groups present on the mol we are debugging.
A couple of examples, extracted from tests, of what we get with this patch (without it we just get Atoms and Bonds):
```python
smi = ("*-CNC(CC(-*)C-*)O-* "
"|$star_e;;;;;;star_e;;star_e;;star_e$,"
"SgD:4:internal data:val::::,SgD:7:atom value:value2::::,"
"Sg:n:7::ht,Sg:n:2::ht,Sg:any:5,7,8,4,3,2,1,0,9::ht,"
"SgH:4:2.3.0,2:1|")
m = Chem.MolFromSmiles(smi)
m.Debug()
-----------------------------------------------------------
Atoms:
0 0 * chg: 0  deg: 1 exp: 1 imp: 0 hyb: 0 arom?: 0 …
```
=> Add Substance Groups and Stereo Groups to debugMol()

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
This bug was originally reported by Richard Lewis.
`MolDraw2D::drawMolecules()` under certain conditions will attempt to access non-existent vector items and hence segfault.
This simple PR fixes the problem and adds a test.
=> MolDraw2D::drawMolecules() should not crash on null molecules

.azure-pipelines/mac_build.yml, .azure-pipelines/mac_build_java.yml, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, azure-pipelines.yml
I merged #5493 too quickly: it has a problem which breaks the windows DLL builds.
This fixes that by adding `RDKIT_MOLDRAW2D_EXPORT` to everything in `MolDraw2DDetails.h`
=> fix windows dll ci builds

Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/testSGroups.py
At the moment creating a DAT SGroup from python is really hard because there's no straightforward way to create the `DATAFIELDS` string vector that's required.
This adds a new function to the python API: `CreateMolDataSubstanceGroup()` (analogous to `CreateMolSubstanceGroup()`) which solves this problem.
=> make it easy to create DAT SGroups from Python

Code/GraphMol/AddHs.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/FileParsers/ProximityBonds.cpp, Code/GraphMol/FindStereo.cpp, Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/TautomerQuery/TautomerQuery.h, Code/RDGeneral/RDLog.cpp, Contrib/ConformerParser/ConformerParser.cpp
This is the traditional build warnings cleanup PR.
In this PR:
- Fix some signed vs unsigned comparison warnings.
- `Bond::BondDir bond_dir` might be used uninitialized in mol fragmenter.
- `struct tm *tm` and `bool needsInit` defined but never used.
- Some for loops using copies instead of references.
- Reformatting of AddHs.cpp and MolFragmenter.cpp.
=> fix warnings ahead of 2022.09 release

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
This fixes #2984.
This issue has been sitting there for a long time, and now, with the new version of `AssignStereochemistry()`, we finally have the required infrastructure to fix it!
Also, I added a couple of fixture functions to manage the Legacy Stereo Perception and Allow Non Tetrahedral Chirality settings, since there was one test ("useLegacyStereoPerception feature flag") that was leaving the new stereo algorithm enabled.
I haven't been able to find a way to automatically apply a fixture to all tests in the file, though, so we still need to manually invoke the fixture in all tests that might require it. I either haven't been able to find a way of rerunning the same test sections with a different value for one variable, so I had to add the `for (auto use_legacy : {false, true})` …
=> Fixes #2984

Code/GraphMol/AddHs.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
Implements the suggestion in https://github.com/rdkit/rdkit/issues/5568
Changes `MolOps::mergeQueryHs` to have a `mergeIsotopes` argument (false by default) so that hydrogen isotopes will not normally be merged.
=> mergeQueryHs will not remove isotopes

Code/Catalogs/Catalog.h, Code/RDGeneral/ConcurrentQueue.h
We don't actually use C++20, but the RDKit should still build when using it. These two changes make that possible.
Here's a stackoverflow post with more detail on the issue:
https://stackoverflow.com/questions/63513984/can-class-template-constructors-have-a-redundant-template-parameter-list-in-c2
=> small changes to get the RDKit to build with C++20

Code/JavaWrappers/MolDraw2D.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolDrawHighlightTest.cs
Change SWIG binding for `MolDraw2D` to add `ColourPalette` to C# and `ColorPalette_Vect` to both C# and Java.
This permits creation of molecule images with multiple highlight colors for atoms and bonds.
=> Add ColorPalette_Vect to SWIG bindings

rdkit/Chem/TorsionFingerprints.py, rdkit/Chem/UnitTestMol3D.py
This makes it easier (and much, much faster) to compare a single conformer on one molecule with multiple conformers on another and to get the best result.
There's a bit of minor general cleanup in here as well
=> Add GetBestTFDBetweenMolecules()

Code/GraphMol/Chirality.cpp, Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, Code/JavaWrappers/ROMol.i, Code/JavaWrappers/RWMol.i, Code/JavaWrappers/csharp_wrapper/CMakeLists.txt, Code/JavaWrappers/gmwrapper/GraphMolJava.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java, Code/JavaWrappers/transforms.i
This PR exposes a few methods and classes to SWIG that were not yet exposed, plus a useful `MolFromSmiles` overload.
It also fixes an oversight in the `getBestRMS()` C++ signature, and a couple of glitches in the C# MinGW builds.
- `setenv()` should be defined also for MinGW builds, not just MSVC
- fixed `getBestRMS()` signature (`ROMol&` should be `const`)
- expose `normalizeDepiction()`, `straightenDepiction()`, `getBestRMS()`, `CalcRMS()` and `getBestAlignmentTransform()` to SWIG wrappers
- expose `MolFromSmiles()` overload taking `SmilesParserParams` parameter to SWIG wrappers
- expose `DoubleVector` class to SWIG wrappers as it is needed by alignment functions
- replace `std::string` with `const std::string&` in several SWIG wrapper signatures
- build `RDKit2DotNet.dll` as a 64-bit …
=> Expose additional functionality to SWIG wrappers

Code/GraphMol/Depictor/RDDepictor.cpp, Code/GraphMol/Depictor/testDepictor.cpp
Small fix to avoid incurring into division by zero, e.g., when coordinates of the molecule are all zero.
=> Avoid incurring into division by zero in normalizeDepiction

rdkit/Chem/Draw/IPythonConsole.py
There's a bad interaction in the notebook integration between the property display and the 3D molecule rendering: if 3d molecule rendering is enabled then no properties are displayed, even if a given molecule doesn't have a 3D conformer.
There's also one reformatting chunk here
=> Allow properties to be displayed in jupyter when 3D rendering is enabled

Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/FindStereo.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Docs/Book/RDKit_Book.rst, Docs/Book/conf.py
Reverts rdkit/rdkit#5595
Reverting because the combination with #5576 broke the build. I'll fix the problems and do a PR to re-integrate the changes.
=> Revert "Support ring-bond stereo flags in CXSMILES"

ReleaseNotes.md, rdkit/Chem/Draw/IPythonConsole.py, rdkit/Chem/Draw/InteractiveRenderer.py, rdkit/Chem/Draw/__init__.py, rdkit/Chem/PandasPatcher.py, rdkit/Chem/PandasTools.py
1. Avoid that Jupyter Notebooks become painfully slow when using PandasTools with hundreds of molecules by using `pandas` formatters rather than patching `Chem.Mol.__str__`
2. Make sure that static PNG images in `pandas` `DataDrames` honor `PandasTools.molSize`
3. Make sure that `PandasTools` works on the whole range of `pandas` versions
4. Improved and more robust loading of `rdkit-structure-renderer` in Jupyter Notebooks
5. `MolsToGridImage` is now also interactive
6. Interactive rendering now displays highlights and query molecules correctly
Take a look at the gists linked below to see how the new `PandasTools` works correctly on a wide range of `pandas` versions and avoids incurring in the sluggishness that currently affects notebooks using `PandasTools` on hundreds of molecules.
This …
=> PandasTools and InteractiveRenderer improvements

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/test1.cpp
Currently it is a bit cumbersome to set `IPythonConsole.drawOptions` to options read from a JSON file.
In fact, I have to instantiate a dummy `MolDraw2D` object that I do not actually need:
```
from rdkit.Chem.Draw import rdMolDraw2D, IPythonConsole
with open("JupyterDrawOptions.json") as hnd:
jupyter_draw_options = hnd.read()
drawer = rdMolDraw2D.MolDraw2DSVG(300, 200)
rdMolDraw2D.UpdateDrawerParamsFromJSON(drawer, jupyter_draw_options)
IPythonConsole.drawOptions = jupyter_draw_options
```
This PR simplifies the above to
```
from rdkit.Chem.Draw import rdMolDraw2D, IPythonConsole
with open("JupyterDrawOptions.json") as hnd:
rdMolDraw2D.UpdateMolDrawOptionsFromJSON(IPythonConsole.drawOptions, hnd.read())
```
Also, it seems more logical to have a function that takes directly …
=> Add updateMolDrawOptionsFromJSON()

Code/GraphMol/Aromaticity.cpp
Possible ring combinations expand combinatorially, so for large ring systems, just checking for ring fusions may be slow. For a reported example of 900 rings, the calculation never completes. 300 is about 2 million iterations, which takes approximately 1 minute.
###
From Hackathon RDkit UGM 2022.
Co-authors: @rachelnwalker @d-b-w
=> add stop condition for arom calc of large ringysystems

Code/GraphMol/FindRings.cpp
For an example large system, getSymmSSSR() took 3minutes. After this trivial change, it went down to 2min 30s. I recognize that's not much, but the change is _so_ minor I think that it's still worth pushing.
(speed-up is because a memory allocation was pulled out of a loop)
Unfortunately, I can't share the structure :( It has about 1K rings. For what it's worth, our ring-finding code finishes this molecule in 19s, so I don't think the current perf is a floor.
=> Speed up ring detection by reducing allocations

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/RWMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
This PR updates some SWIG definitions which are obsolete/incomplete with respect to the current C++ codebase.
- updated outdated SWIG definitions of `ROMol.generateDepictionMatching2DStructure`
- updated outdated SWIG definitions of `RWMol.MolFromMolBlock` and `RWMol.MolFromMolFile`
- added unit test
=> Update obsolete SWIG definitions

Code/GraphMol/FindRings.cpp
Counting the "on" bits in a bitset is a calculation - finding the size of a std::vector requires only a lookup! For my example system from https://github.com/rdkit/rdkit/pull/5654 , this reduces the duration by another minute or so.
Here's an example profile from before this change. The "big" `count()` calls are the two removed here. I think they're usually close to 30s each, or 25 with SSE4.2 enabled (on my computer):
(I think that there's more clever stuff that could be done, but this seems like another trivial change with an inarguably positive effect.)
=> Speed up ring detection by reducing count() calls

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
- expose two useful functions from SubtructUtils to SWIG wrappers (`getMostSubstitutedCoreMatch`, `sortMatchesByDegreeOfCoreSubstitution`)
- add unit test to exercise the above
=> Expose two SubstructUtils functions to SWIG wrappers

.azure-pipelines/linux_build.yml, .azure-pipelines/vs_build.yml, Code/cmake/Modules/RDKitUtils.cmake, rdkit/Chem/PandasTools.py
We've been using a deprecated approach to invoke pytest in `add_jupytertest()`. That approach no longer works in pytest and the CI builds are breaking because of it. This resolves that.
This also fixes #5702
=> Fix invocation of pytest

Code/GraphMol/Aromaticity.cpp
An internal user encountered the existing error message and became alarmed by the implication that no aromaticity detection was even attempted.
I think that the new error message more accurately reflects the logic - we halt the search eventually if the ring system is too large.
=> Update warning message about aromaticity detection

Code/PgSQL/rdkit/Makefile
Fixes: #5685
The clang Postgres bytecode needs to be compiled with `-std=c++17` or else fails with the build error mentioned in the issue.
=> Compile clang bytecode with -std=c++17 (#5685)

Code/GraphMol/Depictor/Wrap/rdDepictor.cpp, Code/GraphMol/Depictor/Wrap/testDepictor.py, Docs/Book/data/test_multi_colours.py
We have recently seen some mysterious test failure that ended up happening because of a `rdDepictor.SetPreferCoordGen(True)` that was never reset back to `False`. This PR adds a `UsingCoordGen` context manager to automatically reset the CoordGen preference and make it harder to hit bugs as the one we had.
This also adds a `IsCoordGenSupportAvailable()` function to allow checks for CoordGen Support from Python, and `getPreferCoordGen()` to check the current state of the setting.
=> Add a Python Context Manager for SetPreferCoordGen

Code/GraphMol/catch_chirality.cpp
Currently this only works for MSVC builds, but MinGW builds have the same requirement.
=> Environment not set properly in chirality tests for MinGW builds

Code/RDGeneral/RDExportMacros.h
The correct macro to identify Windows target is `_WIN32`, not `WIN32`: https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170#microsoft-specific-predefined-macros.  Besides, according to C standard, compilers can't predefine macros without one leading underscore (or two if the the first letter is lowercase).
=> Use correct `_WIN32` macro for checking Windows target

Code/GraphMol/MMPA/MMPA_UnitTest.cpp
`windows.h` header should be lowercase to avoid issues when cross-compiling on Linux. In fact, `windows.h` is lowercase on Linux and since the filesystem is case sensitive it will fail if it is uppercase. On Windows it will make no difference since the filesystem is not case sensitive.
=> windows.h header should be lowercase

Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/SmilesMolSupplier.cpp
We're still limited by using an int as the molecule index in the API; fixing that is a minor API break.
I think that's reasonable to do, but if we decide to go that way it should be in a separate PR so that we can get this fix out as a bug fix.
=> Fixes #5692

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
In functions `parse_coordinate_bonds()`, `parse_doublebond_stereo()` and `parse_wedged_bonds()` we attempt to apply the corresponding features on bonds which have the specified indexes in the RDKit mol, instead of those that in the SMILES string. These do match for simple SMILES, but in cases where rings are involved, these might not match.
The issue was discovered and described for wiggly bonds, since these are specified using both an atom and a bond, and an error was raised when bond wasn't connected to the atom.
This is an example of the issue:
```python
mb = """
RDKit          2D
0  0  0  0  0  0  0  0  0  0999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 10 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 2.366025 0.000000 0.000000 0
M  V30 2 C 0.866025 0.000000 0.000000 0
M  V30 3 C -0.433013 0.750000 …
```
=> Fixes bond index parsing for w/c/t/ctu labels in CXSMILES/CXSMARTS

Code/GraphMol/Fingerprints/CMakeLists.txt, Code/GraphMol/Fingerprints/MorganGenerator.cpp, Code/GraphMol/Fingerprints/MorganGenerator.h, Code/GraphMol/Fingerprints/Wrap/MorganWrapper.cpp, Code/GraphMol/Fingerprints/Wrap/testGenerators.py, Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
This is connected with the discussion #5665
As an aside: we're reaching a number of arguments to some of these functions that may make it worth making the data members of `FingerprintArguments` and derived classes non-const and adding a form of the generator factory functions which takes a FingerprintArguments structure directly.
=> add includeRedundantEnvironments support to GetMorganGenerator

External/AvalonTools/AvalonTools.cpp, External/AvalonTools/test1.cpp
Avoid passing a NULL pointer to CanSmiles (which will happen if there are not atoms in the molblock and hence a NULL SMILES) as undefined behavior will arise.
While I have already reported the problem to Bernd and submitted a patch for Avalon, this has not yet been incorporated upstream, so meanwhile it is better to make sure that RDKit is robust against this condition.
=> Avoid passing a NULL pointer to CanSmiles()

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMol.h, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
This is easy for cases where the begin and end atoms of the bond have the same color, but we need to make an arbitrary decision about which to pick if they differ or if one is color is specified and not the other.
Here we use the following logic to pick the bond highlight color:
1. Use the highlight color of the begin atom if it is set (this also covers the case when both atoms are set)
2. Use the highlight color of the end atom if it is set
3. Otherwise use the default highlight color
=> Fixes #5704

Code/RDGeneral/LocaleSwitcher.cpp
When `_WIN32` is defined but `RDK_BUILD_THREADSAFE_SSS` is not, the `old_locale` variable is not initialized in the LocaleSwitcherImpl constructor . This means that when the variable is consulted in the destructor, it returns an empty (default constructed) string.
When `std::setlocale()` is called with an empty string, this causes the locale to be set to "the user-preferred locale". This value is determined from environment variables/system settings and is not necessarily the previous locale that was used by the program.
Best I can tell from PR #1892, the non-RDK_BUILD_THREADSAFE_SSS path was simply missed when `old_locale` was added. (There's no indication that the omission was deliberate, though @ptosco may need to confirm.) Adding an analogous initialization as in the …
=> Adjust LocaleSwitcher on Windows when RDK_BUILD_THREADSAFE_SSS not set

Code/MinimalLib/docker/Dockerfile
There are two problems here:
1) The Debian `buster` distribution does not seem to include `freetype` headers. Adding `libfreetype6-dev` to the installed packages and configuring the `FREETYPE_*` cmake variables solves the problem. I think this is somehow connected to #5730; however, given that the `freetype` headers are not available in the distribution, I am not sure how the Docker container could find `freetype` before #5730.
2) The current `emsdk` throws a number of errors with `boost`. Updating `boost` does not fix the problem, downgrading `emsdk` does. Currently I do not have time to investigate further; there might be ways to get the latest `emsdk` to work.
=> Addresses #5792

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #5767
This draws the contents of the STY type label for the bracket on an Group.
It certainly fixes the issue filed (missing 'mon' label) but it may be too enthusiastic about what other STY types it puts on the drawing.  I don't know enough about CTFiles to know what should and what shouldn't be drawn.  It doesn't draw GEN/gen types because ChemDraw doesn't.
=> Draw type of SGroups (STY) in picture.

azure-pipelines.yml
As discussed previously with @greglandrum, this PR updates the macOS target platform to 10.13 (2017) from the previous 10.9 (2013). 10.13 is also the minimum required OS version for KNIME.
=> Update macOS target platform to 10.13

Code/RDGeneral/CMakeLists.txt
This PR removes the dependency on the MSVC runtime DLL from MinGW builds as I verified recently while doing the KNIME builds that it is not needed anymore.
=> Remove dependency on MSVC runtime DLL in MinGW builds

Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
As suggested by @d-b-w : we just catch kekulization errors during the tautomer enumeration
I have tested this on ~100K ChEMBL molecules and encountered no further problems.
=> Fixes #5784

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
For the bug-fix version of this we focus on making sure that information which is read in from a SMARTSQ is written back out to a SMARTSQ.
The implementation is simple: we set the `MRV_SMA` property on the atom when processing the SMARTSQ and just look for that property when generating the output CTAB.
We should add the (optional) ability to automatically include other SMARTS queries in SMARTSQ blocks, but that's clearly an enhancement. And it's more work.
=> Fixes #5718

Code/PgSQL/rdkit/CMakeLists.txt
This issue was reported by @tdudgeon. The problem here is that CPack creates the RPM or DEB install tree in a local staging directory, and installs all relevant files there.
However, the `pgsql_install.sh` is configured to install the PostgreSQL cartridge and the other extension files in the target PostgreSQL directories rather than in the CPack local staging directory.
Therefore, at CPack packing time the packing either fails due to insufficient permissions (usually installing PostgreSQL files requires superuser privileges), or anyway the PostgreSQL files are not installed where they should.
This PR fixes the problem by using `DESTDIR` if defined (as it is at CPack packing time) to install in the proper path.
Intermediate directories are also created as needed.
I have verified that the …
=> Allow building PgSQL RPM and DEB packages

Code/MinimalLib/docker/Dockerfile
Working on something completely different I realized what was wrong with `libfreetype`: `emscripten` compiles its own version of `libfreetype` and caches it within `emsdk`. Pointing `cmake` to the `emsdk` version of `libfreetype` solves all problems and it is possible to build again with the latest `emsdk`.
Since the latest `emsdk` is based on `clang16` the `-Wno-enum-constexpr-conversion` flag is needed to build `boost`.
- restore latest `emsdk`
- set `emsdk` path for `freetype`
- add compilation flag to enable building with latest `clang` compilers
=> Set emsdk path for freetype in emscripten builds

Docs/Book/Makefile
1. Allows documentation to be built without the C++ API docs by doing: `make html BUILD_CPP_DOCS=OFF`
2. Additional minor cleanups to the makefile
#EndOfYearCleanup
=> Cleanup work on documentation Makefile

Code/GraphMol/FileParsers/SDWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Straightforward fix:
if a property name includes a newline or a property value includes a blank line then generate warning message and skip the property for that molecule.
=> fixes #5827

rdkit/__init__.py
`rdkit.Chem.rdchem.Mol`  objects are missing the functions `_repr_svg_` and `__repr_png_` on Colab notebooks. Chemical drawings are not automatically shown.
`IPythonConsole` is not imported in `rdkit/__init__.py` for colab notebooks because the `kernel_name` is `Shell` on Colab and not `ZMQInteractiveShell`. 
Additionally check if `get_ipython().__class__.__module__`  is set to `google.colab._shell`.
=> Chemical drawings should be automatically enabled on Colab

rdkit/Chem/GraphDescriptors.py, rdkit/Chem/UnitTestGraphDescriptors_2.py
The Ipc descriptor goes up very quickly with the size/complexity of the molecule.
It's always been possible to dial this back by using the `avg=True` keyword argument, but most people don't do that. We can't change the default value of `avg` (that results in a different descriptor value), so this adds a new descriptor with that set.
See more discussion in #1527
=> Introduces AvgIpc descriptor

Code/GraphMol/DetermineBonds/DetermineBonds.cpp, Code/GraphMol/DetermineBonds/catch_tests.cpp
Simple one-line fix here to remove the extra call to `MolOps::assignChiralTypesFrom3D`
=> Fixes #5894

rdkit/Chem/SimpleEnum/Enumerator.py, rdkit/Chem/SimpleEnum/UnitTestEnumerator.py
Enhanced stereo information was not being used when `SimpleEnum.Enumerate()` is run with `uniqueProducts=True`:
```
In [1]: from rdkit import Chem
In [2]: from rdkit.Chem import rdChemReactions
In [3]: rxn = rdChemReactions.ReactionFromSmarts('[C:1]-[O:2]>>[C:1]-[N:2]')
In [4]: reacts1 = ['C[C@@H](F)CO','C[C@@H](F)CO |a:1|','C[C@@H](F)CO |o1:1|','C[C@@H](F)CO |&1:1|']
In [5]: reacts1 = [Chem.MolFromSmiles(x) for x in reacts1]
In [7]: from rdkit.Chem.SimpleEnum import Enumerator
In [8]: prods = list(Enumerator.EnumerateReaction(rxn,(reacts1,),uniqueProductsOnly=True))
In [9]: len(prods)
Out[9]: 1
```
The fix in this PR is easy: just use the CXSmiles for the molecule when uniquifying.
=> use enhanced stereo when uniquifying in SimpleEnum

Docs/Book/GettingStartedInPython.rst, rdkit/Chem/Descriptors.py, rdkit/Chem/Graphs.py, rdkit/Chem/UnitTestDescriptors.py
Adds `Descriptors.CalcMolDescriptors()`
Also adds a section to the documentation for this use case.
I really should have added this function years ago.
=> Make it easy to calculate all 2D descriptors

Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
This is a simple fix to stop propagating RGroup labels from the input core to the output cores in cases when we haven't requested that this should happen.
Here's an example.
The core used for RGD:
And then the `"Core"` element from one of the result rows after doing an RGD with `rgdps.rgroupLabelling = rdRGroupDecomposition.RGroupLabelling.AtomMap`:
Notice that the two "extra" attachment points are correct: they just have the atom map, but the three original attachments are still carrying the R group labels from the input core. What we should get is this:
=> clear MDL Rgroup labels from core atoms when we aren't using them

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
We should just read them in as dummies instead of throwing an exception. 
There's a light bit of refactoring in here as well.
=> Allow unrecognized atom types when strictParsing=False

Docs/Book/Cookbook.rst
For each abbreviation in rdAbbreviations.GetDefaultAbbreviations(), show its SMILES along with its abbreviation. Here are the first five:
```
Abbrev     SMILES
--------   --------
CO2Et      *C(=O)OCC
COOEt      *C(=O)OCC
OiBu       *OCC(C)C
nDec       *CCCCCCCCCC
nNon       *CCCCCCCCC
```
This should make it more obvious to visitors what each abbreviation corresponds to.
I also have code locally to show the abbreviations in a mol grid; I'm happy to contribute it, but understand if folks think that adds too much length to the page:
=> Add SMILES to each group abbreviation in Cookbook

Data/Pains/README.md
No issue
Adds a note to the PAINS README about explicit Hs.
When I came to use the PAINS SMARTS recently, I got bad results because I hadn't realised that the SMARTS have explicit H atoms that need extra treatment.  This is so other people have less excuse for making the same error.
=> Add info about mergeHs to README.

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes #5899 
The test was failing due to the points defining a rectangular bond highlight being produced in a different order on the raspberry pi, presumably due to small numerical differences.  The new test checks the points in whatever order they are in.
Over time, similar techniques should probably be introduced to replace the current regex approach for checking SVGs as and when the test code is being amended.
=> Github5899

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes issue #5943
The ellipses weren't being drawn correctly.
When I changed the interface for DrawEllipse to take a centre and radii, I obviously failed to fix this instance which was still using the old foci method.  Sorry.
When looking at the output, I saw that DrawEllipse::findExtremes() is also living in the old world, so the ferrocene picture is still wrong - the upper circles are cutoff.  I will do this as a separate PR as it feels like a separate bug to me.
=> Fix drawing of circles in extractVariableBonds.

Code/GraphMol/MolDraw2D/DrawShape.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp
Fixes #5944
As mentioned in PR5946, the ellipse extremes calculation was wrong, meaning that ellipses at the edge of a drawing might be cut off.
This will break the tests for #5946
=> Fix ellipse extremes calculation.

Code/GraphMol/ChemReactions/ReactionWriter.cpp, Code/GraphMol/FindRings.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/MolStandardize/Normalize.cpp, Code/GraphMol/RingInfo.cpp, Code/GraphMol/catch_graphmol.cpp, ReleaseNotes.md
Currently the ring-finding code caches its results, which leads to delightful confusion like this:
```
In [5]: m = Chem.MolFromSmiles('C1C2CC1CCC2')
In [6]: m.GetRingInfo().NumRings()
Out[6]: 3
In [7]: Chem.GetSSSR(m)
Out[7]: <rdkit.rdBase._vectclass std::vector<int,class std::allocator<int> > at 0x20583b62fc0>
In [8]: m.GetRingInfo().NumRings()
Out[8]: 3
In [9]: m = Chem.MolFromSmiles('C1C2CC1CCC2',sanitize=False)
In [10]: m.UpdatePropertyCache()
In [11]: Chem.GetSSSR(m)
Out[11]: <rdkit.rdBase._vectclass std::vector<int,class std::allocator<int> > at 0x20583ca1840>
In [12]: m.GetRingInfo().NumRings()
Out[12]: 2
```
That mess is by design, but it seems like a bug.
This removes the caching so that things are a bit less surprising.
We could add something to be more specific about what we …
=> stop caching ring-finding results

Code/GraphMol/Fingerprints/FingerprintGenerator.cpp, Code/GraphMol/Fingerprints/FingerprintGenerator.h, Code/GraphMol/Fingerprints/Wrap/testGenerators.py, Code/GraphMol/Fingerprints/catch_tests.cpp, Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp
Adds logic to copy the additional info from the non-count-simulation bits over into the corresponding slots for the count-simulation bits.
=> Fixes #5838

Code/GraphMol/MolDraw2D/test1.cpp
I had a failing test after updating freetype to v2.11.1 on my linux box. 
This should clear that up
=> Adjust expected test results for newer freetype versions

Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
This PR implements `JSMol::add_hs_in_place()` and `JSMol::remove_hs_in_place()` to the JS MinmalLib, as it can be desirable to do that without requiring the instantiation of a new molecule, similarly to `JSMol::set_new_coords()` that I added some time ago.
Note that I had to change `commonchem` to `rdkitjson` in the JS tests to get them to run, as a previous change in RDKit unrelated to this PR caused the tests to break.
=> MinimalLib JS functions to add/remove Hs in place

rdkit/Chem/RegistrationHash.py
This change addresses a minor issue in the docstring of the GetMolHash in RegistrationHash.py. The first a argument of the function appears to be a mol, while it is actually a dictionary of layers.
=> Updated the GetMolHash docstring for accuracy

Code/GraphMol/ROMol.h, Code/GraphMol/catch_moliterators.cpp
Small PR that enables using STL algorithms on `ROMol` atoms and bonds which were previously failing to compile due to missing `==` operator on the `CXXAtomIter` and `CXXBondIter` classes.
=> Enable using STL algorithms on ROMol atoms and bonds

Code/GraphMol/RGroupDecomposition/CMakeLists.txt, Code/GraphMol/RGroupDecomposition/RGroupData.cpp, Code/GraphMol/RGroupDecomposition/RGroupData.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/RGroupDecompData.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/testRGroupInternals.cpp, Code/JavaWrappers/RGroupDecomposition.i
None
RDG has a lot of code in header files.  I've created implementations in cpp files for functions previously defined in `RGroupData.h` and `RGroupDecompData.h`.  I also created a `RGroupDecompParams.h` to match `RGroupDecompParams.cpp`
=> Refactor RGD moving function implementations from header to source files

rdkit/Chem/RegistrationHash.py, rdkit/Chem/UnitTestRegistrationHash.py
The specific exception is:
```    
..../site-packages/rdkit/Chem/EnumerateStereoisomers.py:329: in EnumerateStereoisomers
Chem.SetDoubleBondNeighborDirections(isomer)
E   RuntimeError: Pre-condition Violation
E           bad dir
E           Violation occurred on line 396 in file Code/GraphMol/Chirality.cpp
E           Failed Expression: dir == Bond::ENDUPRIGHT || dir == Bond::ENDDOWNRIGHT
E           RDKIT: 2022.09.3
E           BOOST: 1_76
----------------------------
```
This happens if we are enumerating stereoisomers and there is a
center with a bond direction between an enumerated center and a
double bond. This is a bad way to draw a bond wedge/dash, but
in Registration, we often see weird depictions straight from
some drug database.
Encountered at some customer site in Schrödinger …
=> Exception in RegistrationHash for molecules with bad bond directions

Code/GraphMol/Fingerprints/MHFP.h, Code/GraphMol/Fingerprints/Wrap/testMHFP.py, Code/GraphMol/Fingerprints/testMHFPFingerprint.cpp
Fixes #5919.
This PR makes the `MHFPEncoder::Distance` compute a proper distance between two fingerprints, instead of a similarity like it currently does. The docstring was changed to indicate that it computes a Hamming distance rather than a Jaccard distance.
I added a test to make sure the distance from a fingerprint to itself is zero.
=> Fix computation of distance betwen MHFP fingerprints

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/JavaWrappers/DistGeom.i
The conformer generation code has a number of internal tests that it does to make sure the output conformers are reasonable. This PR makes it possible for client code to determine how often each of those tests fail.
This is mainly useful for debugging purposes, so it's not necessarily super well documented at the moment.
=> Allow the sources of conformer generation failures to be retrieved

Code/Geometry/point.h, Code/MinimalLib/common.h
`and` is a C++ keyword, but it isn't supported by default on some compilers (msvc). I'd like to disable it on _all_ platforms in Schrödinger builds so that developers don't accidentally post code that fails on a single platform.
However, that means external headers need to use `&&` and `||` instead of `and` and `or`, even in platform-specific code.
=> Remove `and` from C++ headers

Code/GraphMol/MolDraw2D/test1.cpp
No issue
gcc on ubuntu gives a warning about unnecessary copying in a test I altered recently.
I was bored waiting for a docker image to build.
=> Fix auto reference.

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #6011 
This is a straightforward fix: do not flag atoms with degree zero as potential tetrahedral stereo atoms.
Fixes #6012 
Anothe simple one: make sure that atoms which are not eligible for tetrahedral stereo do not end up getting flagged as potential stereo atoms when allowNontetrahedralChirality is false
=> Fix #6011 and #6012

Code/GraphMol/ChemTransforms/CMakeLists.txt, Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.h, Code/GraphMol/ChemTransforms/catch_tests.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/JavaWrappers/ChemTransforms.i
When performing molecule zipping from fragments/decomposition it would be nice if the fragments could be depicted aligned to the zipped molecule.
I've added a `generateCoordinates` option  for `MolzipParams` and a new `molzipFragments` function that takes a vector of molecules (the fragments) and parameters.  On zipping depiction coordinates are set on the output molecule and input fragments.
```python
import os
from rdkit import IPythonConsole
IPythonConsole.ipython_useSVG = True
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import PandasTools
from rdkit.Chem import Draw
smiles = ["c1nc([1*:1])c([2*:2])c([3*:3])n1", "CC(C)(C#N)c1ccc([1*:1])cc1", "Nc1ccc(C#C[2*:2])cn1", "CC[3*:3]"]
mols = [Chem.MolFromSmiles(s) for s in smiles] …
```
=> Add depiction coordinates to molzip

Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp
When reactions were applied to molecules with query features (e.g. constructed from SMARTS), none of the query features were being propagated to the products. This remedies that.
This fixes #6015 and #6014
=> Propagate query features from reacting molecules to products

Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/catch_tests.cpp
This was more straightforward than I had originally thought it would be.
The fix moves the uniqueness check for the solutions to substructure matching into the final check functor instead of doing after solutions are identified.
I've benchmarked this change using the `new_timings.py` script and it's actually a few percent faster than the older approach. I'm not sure I believe that, but it should at least tell us that there's no significant negative performance impact. This is true with both newer versions of boost (where we using `dynamic_bitset` for the hashing) and older versions (where we use `std::string`).
Doing the fix did highlight that we should also have a seperate parameter for governing the maximum number of recursive substructMatches. This is captured in #6017.
=> Fixes #888

rdkit/Chem/PandasTools.py
This fixes a typo that I inadvertently introduced in #5835: `molCol` can either be an iterable of `str` or a single `str`, certainly not a `Chem.Mol`.
=> Fixes typo in PandasTools (Chem.Mol should have been str)

Code/GraphMol/Fingerprints/AtomPairGenerator.cpp, Code/GraphMol/Fingerprints/FingerprintGenerator.cpp, Code/GraphMol/MolStandardize/test1.cpp, Code/GraphMol/ROMol.cpp
This fixes some minor leaks I found running asan on the tests:
- `Code/GraphMol/MolStandardize/test1.cpp`: just one Mol that wasn't being deallocated.
- `Code/GraphMol/Fingerprints/FingerprintGenerator.cpp`: `atomInvariants` and `bondInvariants` were not being cleaned up when something fails in downstream code.
- `Code/GraphMol/ROMol.cpp`: `ROMol::load()` is not a constructor, so it can only be called on already initialized mols, so when we call `initMol()` (I assume that to reset properties and ring info, `dp_ringInfo` is already allocated, and leaks.
=> Fix some minor leaks

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6025
The calculation to step the inner line of a ring double bond back to the intersection with the line from the end atom to the centre of the ring failed on a very small canvas when the two lines didn't intersect.  The line end got the default (0,0) coords which would only ever be the correct answer by accident.
=> Fix bug drawing double bond on very small canvas.

Code/GraphMol/DistGeomHelpers/Embedder.cpp
this was introduced in one of the recent conformer generator commits
=> cleanup a compiler warning about a multiline comment

Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp
This fixes #6034.
The fix is simple: it just adds `getNoImplicit()` to the conditions we check to know if we need to update an atom's number of explicit Hs when breaking a bond.
=> Fixes #6034

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
Before this commit, if you run MolToSmarts on a molecule with a zero order bond (ZOB), the SMARTS won't match the ZOB! It's a bit weird for a molecule not to be its own substructure...
This came up because in Schödinger we see ZOBs somewhat frequently in organometallics.
=> Allow SMARTS of zero order bonds to match zero order bonds

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py
This allows the sdf files to be saved to v3000 files
=> Allow WriteSDF to create v3000 SDF files

Code/MinimalLib/tests/tests.js
Small PR to replace a test that does not actually work (same stereochemistry is perceived regardless of whether legacy is used or not, same happens from Python), and hence is commented out, with a test that actually yields different results depending on the legacy stereo setting, and hence actually tests the underlying code.
=> Replace the broken, commented out test for legacy stereo with a test that works

Code/GraphMol/Canon.cpp, Code/GraphMol/Canon.h, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/FileParsers/cdxml_parser_catch.cpp, Code/GraphMol/MolHash/Wrap/testMolHash.py, Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolInterchange/molinterchange_catch.cpp, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/catch_canon.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/new_canon.cpp, Code/GraphMol/new_canon.h, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java, Code/PgSQL/rdkit/expected/rdkit-91.out, Docs/Book/RDKit_Book.rst, ReleaseNotes.md, rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/RegistrationHash.py, rdkit/Chem/UnitTestMol3D.py, rdkit/Chem/UnitTestRegistrationHash.py, rdkit/Chem/test_list.py
In previous releases the SMILES generated for molecules with stereo groups was not canonical: the information from the stereo groups was not taken into account when determining the atom ordering and there was no handling of the fact that `C[C@H](F)O |o1:1|` and `C[C@@H](F)O |o1:1|` are the same thing. This resolves that.
SMILES (and SMILES-derived things like some of the mol hashes) for molecules with stereo groups will now be different if canonicalization and isomeric SMILES are enabled (the default).
- We could theoretically not do the canonicalization of stereogroups if we're just generating SMILES (instead of CXSMILES), but this would have the consequence that the SMILES part of a CXSMILES wouldn't match the SMILES for the molecule. That feels ugly and wrong to me.
=> Add canonicalization of stereo groups (enhanced stereo)

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
No issue.
Corrects the default value for minFontSize in the python doctoring.
And that took longer and much more typing than the fix itself!
=> Correct docstring for minFontSize.

Code/GraphMol/Descriptors/Lipinski.cpp, Code/GraphMol/QueryOps.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/catch_graphmol.cpp
Updates the query for bridgehead atoms to resolve the issue.
This also impacts the `NumBridgeheadAtoms` descriptors, so the version on that gets bumped as well.
=> Fixes #6049

Code/GraphMol/SmilesParse/CMakeLists.txt, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp
We need to keep track of the group IDs of the stereo groups as the molecule is being built.
=> Fixes #6050

Code/JavaWrappers/RWMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
This PR exposes some stereochemistry-related functions to SWIG wrappers and adds some tests. I don't think it is necessary to test all of them, given they take similar input.
=> Expose some stereochemistry-related functions to SWIG wrappers

Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/testPickler.cpp, Code/RDGeneral/RDValue-taggedunion.h
Fixes #6036 
This fixes an issue where the serializer for ExplicitBitVector thought any dynamic rdvalue (aka boost::any) was an explicit bit vector and just plain did the wrong thing.
The issue was the rdvalue_is<T> wasn't properly checking the subtype of the boost::any.  This was due to the fact that rdvalue_is<boost::any>(value) also had to work.  This specializes the check for boost::any and allows rdvalue_is to do the right thing.
=> Properly check for boost::any in rdvalue_is

Code/GraphMol/CMakeLists.txt, Code/GraphMol/FileParsers/CMakeLists.txt, Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MaeWriter.cpp, Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/FileParsers/PDBWriter.cpp, Code/GraphMol/FileParsers/SDWriter.cpp, Code/GraphMol/FileParsers/SmilesWriter.cpp, Code/GraphMol/FileParsers/TDTWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Wrap/CMakeLists.txt, Code/GraphMol/Wrap/MaeWriter.cpp, Code/GraphMol/Wrap/PDBWriter.cpp, Code/GraphMol/Wrap/SmilesWriter.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
This adds an initial implementation of the `MaeWriter` class, which allows exporting mols to Maestro files (.mae). It is based on the `MolWriter` class, and works in a way similar to the other existing "Writer" classes. The implementation is still very basic, but we hope to improve it soon.
Some things to take into account when using this class:
- The writer does not yet support stereochemistry: Maestro files use absolute stereochemical labels (R/S/E/Z), which require knowledge of the CIP ranks of the atoms around the stereo feature. The new stereo algorithm in RDKit does not provide this information, and while the CIP labeler can calculate the labels, it doesn't currently provide CIP ranks information.
- Kekulization is always required, as there is no concept of aromatic bonds in the …
=> Start a Maestro file (.mae) writer.

Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
As previously discussed with @greglandrum and @DavidACosgrove, this PR changes the `useComplexQueryAtomSymbols` default value from `false` to `true`.
=> Set the useComplexQueryAtomSymbols default value to true

Code/GraphMol/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp
A simple fix.
We should think about (though not as part of this PR) also modifying the definition of the M atom query in QueryOps.cpp to excludes dummies: https://github.com/rdkit/rdkit/blob/1e1ff0b08406c1a6164ceb21d4a23d1d98dc7fa3/Code/GraphMol/QueryOps.cpp#L477
=> Fixes #6100

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
This enables symbol/atomic number substitution in SMARTS generation via the "smilesSymbol" property in a similar way as we already had it for SMILES generation.
=> Enable "smilesSymbol" substitution in SMARTS

Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp, Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h, Code/GraphMol/Fingerprints/Wrap/TopologicalTorsionWrapper.cpp, Code/GraphMol/Fingerprints/Wrap/testGenerators.py, Code/GraphMol/Fingerprints/catch_tests.cpp, Code/GraphMol/Subgraphs/CMakeLists.txt, Code/GraphMol/Subgraphs/Subgraphs.cpp, Code/GraphMol/Subgraphs/Subgraphs.h, Code/GraphMol/Subgraphs/catch_tests.cpp, Code/GraphMol/Wrap/MolOps.cpp
@gedeck pointed out that the topological torsion fingerprints can set bits corresponding to paths which do not correspond to the shortest path between the start and end atom. This PR adds an option to the `TopologicalTorsionGenerator` to only set bits for shortest paths.
This also adds a similar option to `findAllPathsOfLengthN()` and `findAllPathsOfLengthsMtoN()`, both of which are used by the topological torsion code.
The new options are disabled by default, so there is no backwards incompatibility.
Usage from Python:
```
g = rdFingerprintGenerator.GetTopologicalTorsionGenerator()
g.GetOptions().onlyShortestPaths = True
```
=> Add option to only include shortest paths for topological torsion fingerprints

Code/JavaWrappers/Conformer.i, Code/JavaWrappers/MolDraw2D.i
- wrap types that are otherwise not accessible from SWIG wrappers
- remove redundant `Point2D_Vect` definition (already defined in `Code/JavaWrappers/*/GraphMol*.`i)
- blacklist `Conformer::getPositions()` whose return type is not accessible from SWIG (and is anyway not necessary since `Conformer::getAtomPos()` and `Conformer::setAtomPos()` serve the same purpose just fine)
=> A few SWIG tweaks

Code/MinimalLib/common.h
Given that `shouldNeverClearWedgingInfo` does not change through all those 3 `if` clauses`, we can test it once and for all.
=> Another minor code cleanup

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6111
When drawing into a flexi canvas in ACS1996 mode, if there is a character on the edge of the drawing, the canvas isn't big enough.
=> Fix small ACS1996 drawing being cropped.

Code/GraphMol/Chirality.cpp
No issue
When reading ChEMBL v31, you get error messages about conflicting stereochemistry that contain a spurious full stop.  This removes them.
Reading ChEMBL takes long enough that one can fix the grammar and file a PR whilst waiting!
=> Remove spurious full stops from warnings.

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/ChemReactionTests.java, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java, Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/cffiwrapper.h, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js, ReleaseNotes.md
- expose `[sg]etUseLegacyStereo()`
- In `MolToSmiles()` `doIsomericSmiles` should default to `true` as in C++ and Python
- added missing parameters to `MolToSmiles()` and `MolToMolBlock()`
- added `SmilesWriteParams` `MolToSmiles()` overload
- added and updated Java tests
=> Stereochemistry-related SWIG updates

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes issue 6112.
If the 2D molecule comes into drawMolACS1996 without coords, it threw an exception as it tried to compute the mean bond length, required in the ACS setup.  It now generates for this purpose.
=> Github6112

Code/JavaWrappers/ExplicitBitVect.i, Code/JavaWrappers/FilterCatalog.i, Code/JavaWrappers/ROMol.i, Code/JavaWrappers/SubstructLibrary.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolToFromByteArray.cs, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/PicklingTests.java
- avoid leaking memory after instantiating `UChar_Vect` in methods added with `javacode` and `cscode`
- make helper methods private
- fix some indentation
- make it easier to read/write pickled molecules as native byte arrays from Java and C# as it happens from C++ and Python
- add tests
=> SWIG pickling improvements (and other cleanup)

rdkit/Chem/RegistrationHash.py, rdkit/Chem/UnitTestRegistrationHash.py
Fixes #6091 
This change deletes unreachable code after the return statement in RegistrationHash.py#_CanonicalizeStereoGroups
After carrying out the above change, it became apparent that the existance of _CanonicalizeStereoGroups was unnecessary since we already call  Chem.CanonicalizeEnhancedStereo(mol) in get mol layers (which is the only remaining functionality of _CanonicalizeStereoGroups after my initial changes.) With _CanonicalizeStereoGroups deleted, _UpdateEnhancedStereoGroupWeights was also unused, which I also deleted. I finally made changes to the tests to reflect this change.
Local Testing Done:
All the tests in UnitTestRegistrationHash.py passed after my changes.
=> Issue 6091: Cleaning up unreachable code after return statement

Code/MinimalLib/cffi_test.c, Code/MinimalLib/common.h, Code/MinimalLib/tests/tests.js
This PR fixes a problem in `MinimalLib`, where the combination of `sanitize=false` and `removeHs=false` causes `assignStereochemistry()` to fail because implicit valence has not been computed.
=> MinimalLib: avoid that assignStereochemistry() fails when removeHs=true

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/Wrap/rough_test.py
This fixes #6153 by catching the exception that is raised when maeparser fails to find a bond block.
Also, I noticed that some of the errors we can hit when parsing Maestro files, including the one being fixed, cause a failure without reporting any information on the error, just returning `None` in Python. On the C++ side we were getting different types of exceptions, depending on what failed. This patch catches different types of exceptions at the C++ and rethrows them as `FileParseException`, which gets translated into a Python `RuntimeError` with a proper error message. Note this is a change in behavior.
=> Fixes #6153

Code/GraphMol/Wrap/Queries.cpp, Code/GraphMol/Wrap/rough_test.py
The "recently" added `NonHydrogenDegree` and `BridgheadAtom` queries were never exposed to Python.
This remedies that.
=> expose two missing QueryAtom types to python

rdkit/Chem/UnitTestRegistrationHash.py
Continuing Issue #6091: Fixing a test that was not passing for the right reason
I reviewed my pull request after it was merged to make sure we did not miss anything and saw an issue with one of the tests.
What I was intending to do was to first canonicalize the mol, and then turn this mol into smiles. However, I mistakenly only did smi=Chem.CanonicalizeEnhancedStereo(mol).
Chem.CanonicalizeEnhancedStereo(mol) returns none always. Therefore, csmi=Chem.CanonicalizeEnhancedStereo(mol) was setting the smiles of both of the molecules to be "None". Even if these molecules had different smiles, they would both have "None" due to this error, which means the size of the set would still be 1, making the test pass but not for the right reason. 
What I did to address this situation:
- I called …
=> Continuing Issue #6091: Fixing a test that was not passing for the right reason

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMol.h, Code/GraphMol/MolDraw2D/catch_tests.cpp
Reference Issue
Fixes https://github.com/rdkit/rdkit/issues/6160
What does this implement/fix? Explain your changes.
The drawing of aminosulfimines went badly because the drawing code assumed that there would only be 2 bonds off an atom had a double bond incident on it. In the examples supplied, this meant it was using as references 3 atoms in a straight line which made the geometry calculations blow up. It now looks through the neighbour list until it finds a non-linear triplet.
Any other comments?
Having made a complete mess of the last PR (6164) this replaces it.  Sorry for the incompetence.
Having fixed the bug itself, it was apparent that the bonds were being drawn in an ugly manner in this case where there are atomic symbols at both ends of the double bond, so I've tidied that up as …
=> Fix drawing of Aminosulfimine Take 2

.gitignore, Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/cdxml_parser_catch.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/molopstest.cpp, ReleaseNotes.md
The problem this addresses is that neither the old stereo code nor the new stereo code would remove the bond dir information which marks the double bond in this molecule as being "either":
This PR clears that up.
The main idea is to recognize `BondDir` information when doing `assignStereochemistry()` (either version) with `cleanIt=true`  and set the corresponding double bond stereo to `STEREOANY`. Some small changes to the rest of the `assignStereochemistry()` code then makes sure that this is interpreted correctly and also clears the `stereoAtoms` on non-stereo bonds.
The backwards incompatible change is that crossed double bonds will no longer have their BondDir set after standard parsing or calls to `assignStereochemistry()`.
=> BondDir not cleared from bonds that aren't stereoactive

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, ReleaseNotes.md
The fix here is to recognize that the expected chiral volume for three-coordinate atoms is smaller than that for four-coordinate atoms.
The corrected value here is empirical
=> Fixes #5883

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6170
If it detects that a double bond has been crossed at the initial calculation, it uncrosses it.
=> Uncross accidentally crossed bonds.

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMol.h
No Issue
Function areBondsLinear is renamed areBondsParallel which is a better description of what it does.
As the world's most overrated scribbler put it "If it were done when 'tis done, then 'twere well It were done quickly"
=> Better name for areBondsLinear.

Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp
Fixes #6195
There is a bug in ` MolFileParser::toInt` that this PR fixes.  Here
```C++
// remove leading spaces
txt = input.data();
unsigned int sz = input.size();
if (acceptSpaces) {
while (*txt == ' ') {
++txt;
--sz;
}
}
int res = 0;
std::from_chars(txt, txt + sz, res);
return res;
```
`sz` can end up being negative if the `input` string view is all spaces.
This is what happens when parsing the topology entry for the bond line
```
4  5  1  0        4
```
The topology entry is all spaces and `txt` ends up pointing to 4 (the bond reaction center) with `sz` negative. 4 is returned and an exception thrown.
=> ReactionFromRxnBlock fails on bond with reacting center status set 

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #6217.
A very straightforward fix: just add a check to see if non-tetrahedral stereo is allowed before checking and assigning it.
=> Fixes #6217

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp
Introduces:
- `getMolSize()` to return the dimensions a molecule will be drawn to
- `flexiMode`: to ensure that molecules are always drawn with the current settings and font sizes
=> add features to allow drawing molecules in arbitrary positions on a large canvas

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Fixes #6040 
Checks the doIsomericSmiles param in `MolToCXSmiles` and changing the flags variable that gets passed to `getCXExtensions`
I wasn't able to find anywhere that it's possible for users to define their own flags variable, but I just wanted to makke sure that there is no concern with overwriting flags.
=> Changing flags if doIsomericSmiles is false

rdkit/Chem/TorsionFingerprints.py, rdkit/Chem/UnitTestMol3D.py
The TFD paper, [_J. Chem. Inf. Model._ 2012, 52, 1499-1512](https://doi.org/10.1021/ci2002318), states that "The maximal derivation for rings of size 14 or greater is 180 degrees.", but the current implementation ignores it.
This PR fixes it.
=> Fix TorsionFingerprints for 15 membered rings

Code/PgSQL/rdkit/README.md
Fixes markdown typo that currently screws up the PostgreSQL `README.md` formatting.
=> Fix markdown typo

Code/PgSQL/rdkit/README.md
I added a paragraph for each platform dealing with the installation of the PostgreSQL cartridge into `conda` PostgreSQL.
=> Updated README for cartridge installation into conda PostgreSQL

Code/GraphMol/Depictor/RDDepictor.cpp, Code/GraphMol/Depictor/catch_tests.cpp, Code/GraphMol/Depictor/testDepictor.cpp, Code/GraphMol/FindRings.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/catch_organometallics.cpp, ReleaseNotes.md
Fixes #6058 
The fix here is to add a new `includeDativeBonds` option to the ring-finding code which is disabled by default (i.e. dative bonds are not included in ring finding by default).
This necessitates a small tweak to the 2D coordinate generation code, which should take dative bonds into account (at least for some systems, it might be worth coming back to this at some point and ignoring the three-rings formed by haptic systems in the depiction code).
=> Do not include dative bonds in ring finding by default

Code/GraphMol/Depictor/EmbeddedFrag.cpp, Code/GraphMol/Descriptors/catch_tests.cpp, Code/GraphMol/DetermineBonds/DetermineBonds.cpp, Code/GraphMol/FileParsers/CDXMLParser.cpp, Code/GraphMol/FilterCatalog/filtercatalogtest.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolInterchange/Writer.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/Subgraphs/SubgraphUtils.cpp, Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
Yet another commit fixing build warnings. Most of them are about signed/unsigned comparisons, but there's also an unused variable, an unused argument, and even an infinite recursion loop! (that one actually looks like a bug!).
The diff looks huge, but it is mostly because of clang-format, there aren't that many real changes.
=> Fix build warnings

rdkit/Chem/PandasTools.py
Pandas 2.0 removes the method `DataFrame.append()`, which we use in the `PandasTools` doctests.
This change allows those tests to pass again. It should also still work with older versions of Pandas (`concat` has been present since at least v1.0 of Pandas).
=> deal with deprecated DataFrame.append method

Code/GraphMol/ChemReactions/Reaction.cpp, Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/ReactionPickler.cpp, Code/GraphMol/ChemReactions/ReactionPickler.h, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemReactions/ReactionUtils.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/SubstructUtils.cpp
This adds a `SubstructMatchParams` object to `ChemicalReaction` and uses that to control substructure matching.
It also adds a `substructMatchParamsToJSON()` function so that we can easily and flexibly serialize those parameter objects.
Fixes #6211
=> Fixes #6211

Code/GraphMol/Descriptors/OxidationNumbers.cpp
After merging #6266, builds started showing this warning:
```
rdkit/Code/GraphMol/Descriptors/OxidationNumbers.cpp:65:32: warning: comparison between
‘enum RDKit::Bond::BondType’ and ‘enum RDKit::Bond::BondDir’ [-Wenum-compare]
65 |         || bond->getBondType() == Bond::NONE) {
|            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```
This is because we don't have a `Bond::NONE` bond type, that's in the `BondDir` enum, so the comparison won't ever hit. I think @DavidACosgrove might have been thinking of a `Bond::ZERO` bond ?
=> Fix incorrect bond check in #6266

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/FileParsers/MolFileStereochem.h, Code/GraphMol/FileParsers/molfile_stereo_catch.cpp, Code/GraphMol/FileParsers/testMolWriter.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, ReleaseNotes.md
Adds a new function to `MolFileStereochem.h` and the python wrapper to apply the "standard" semantics of the chiral flag
=> Fixes #6241

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/MinimalLib/cffi_test.c, Code/MinimalLib/tests/tests.js
Currently `queryColour` is hardcoded to `(0.5, 0.5, 0.5)`.
This simple PR exposes it as part of `MolDrawOptions` such that it can be modified by users.
In passing, I have also converted some `int` values to `float` for clarity.
I also added C++, Python, `cffi` and JS unit tests.
=> Exposed queryColour in MolDrawOptions

Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp, Docs/Book/RDKit_Book.rst
This reverts some of the changes in #6038: `cleanUpOrganometallics()` is no longer part of the default sanitization process. The function is still available for people who choose to use it, though I've flagged it as experimental for this release.
There are two reasons for the change, both arising from the fact that the current implementation makes an arbitrary bond from a hypervalent atom to a metal to make dative:
1. The choice of bond to change is not canonical, so providing the same molecule with different atom orderings will produce different results and, thus, different SMILES. Here's a simple example of that:
```
In [3]: Chem.MolToSmiles(Chem.MolFromSmiles('F[Pd](Cl)(Cl1)Cl[Pd]1(Cl)Cl'))
Out[3]: 'F[Pd]1(Cl)<-Cl[Pd](Cl)(Cl)Cl->1'
In [4]: …
```
=> remove cleanupOrganometallics() from the default sanitization

Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
With this PR `has_coords()` will return `2` or `3` depending whether coordinates are 2D or 3D, if present, rather than just returning `1` (CFFI) or `true` (JS).
Note that the perception of 2D/3D is only based on the return value of `Conformer::is3D()` - no attempt is made to perceive the actual 3D character. This is still very useful in many circumstances, and this change should not break existing code relying on `has_coords()`.
=> has_coords() now reports whether coords are 2D or 3D if present

Docs/Book/Install.md
The stated `make`, `make install` and `ctest` aren't sufficient to get ctest to run properly without errors, and there's only limited indication in the output about what's needed to fix the errors you get. Add more information about the needed settings to get ctest to run properly.
=> Improve the installation/testing instructions for linux/conda

.gitignore, rdkit/Chem/UnitTestPandasTools.py
There's some existing code for making the UnitTestPandasTools tests robust to running in an environment where pandas is not present. (e.g. like the new conda environment one would make according to Docs/Book/Install.md). However, those precautions don't quite work with the current codebase.
Update the skip-test logic to check for the current situation. Also, defer using functionality which is only loaded in the presence of pandas until test running time. (As `__init__()` is called even when the test is being skipped.)
As a bonus, I added more test-generated files to the .gitignore file. (The files are not related to UnitTestPandasTools, but I figured it was close enough to not require a separate PR. )
=> Fix UnitTestPandasTools for running without pandas installed.

Code/GraphMol/MolDraw2D/DrawShape.h
The current drawing code does a poor job with aromatic dashes.
Here are three example molecules:
default rendering of non-kekulized benzene:
ACS1996 version of that:
ferrocene:
There's an argument that the first case isn't too terrible, but I think in general both the dashes and the gaps are too long.
Here are the three test cases with the new dashes:
default rendering:
ACS 1996:
ferrocene:
=> Aromatic dashes look bad

External/YAeHMOP/CMakeLists.txt
the new source version works better on modern (stricter) compilers
=> bump yaehmop version

Code/RDGeneral/RDLog.h
Required for uint64_t, fixes compile error
=> Added cstdint include

rdkit/Chem/Draw/__init__.py
Adds a graphical equivalent of the Debug() function. Here's what the output looks like:
I think that having this easily available in Draw will really help when the code isn't behaving as people expect it to.
Feedback on what should be added is very welcome!
=> add DebugDraw() function

Code/GraphMol/FilterCatalog/CMakeLists.txt, Code/JavaWrappers/RWMol.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/ToMolMemoryTest.cs
All the different `*ToMol` methods defined in `RWMol.i` contain memory leaks.
Looking at the generated `GraphMolCSharpCSHARP_wrap.cxx` they all return `boost::shared_ptr` with an empty deleter:
```c++
struct SWIG_null_deleter {
void operator() (void const *) const {
}
};
#define SWIG_NO_NULL_DELETER_0 , SWIG_null_deleter()
.....
jresult = result ? new boost::shared_ptr<  RDKit::RWMol >(result SWIG_NO_NULL_DELETER_0) : 0;
}
```
This is fixed by including `%newobject` statements for the C++ parser functions.
I've included a `C#` test file.
I ran into an error with one of the CMakelists.txt files where `PythonInterp` found a Python executable with no version.  The docs at https://cmake.org/cmake/help/latest/module/FindPythonInterp.html indicate that this is a possibility.
=> Fix swig memory leak

CMakeLists.txt
This PR refactors a few steps in the cmake configuration of the python build, to remove the dependency from the deprecated distutils module.
distutils is planned to be removed in python 3.12
=> remove the dependency from python distutils in the top CMakeLists.txt file

rdkit/Chem/PandasTools.py
This is a really tiny one. Currently `IPythonConsole.drawOptions` are being ignored when exporting a `pandas` dataframe to `xlsx` format with `SaveXlsxFromFrame()`. This PR corrects that.
=> take drawOptions into account when exporting structure to xlsx format

Code/GraphMol/Depictor/RDDepictor.cpp, Code/GraphMol/Depictor/catch_tests.cpp, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/MinimalLib/cffi_test.c, Code/MinimalLib/common.h, Code/MinimalLib/tests/tests.js
`generateDepictionMatching2DStructure` has an `allowOptionalAttachments` parameter which allows using scaffold bearing R groups. However, in most cases the bonds connecting R groups to the scaffold are single bonds, which won't match aromatic bonds. This is undesirable as the goal is to make depictions as consistent as possible in a SAR table to facilitate reading.
This PR corrects this by allowing single bonds from aromatic rings to R groups to match single or aromatic bonds using the existing `AdjustQueryParameters`.
=> Bonds to R groups should be generic

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/Wrap/MolOps.cpp
A small cleanup PR.
* In `adjustQueryProperties`, it is not necessary to dynamically allocate `QueryAtom` and `QueryBond` instances to be used with `RWMol::replaceAtom()` and `RWMol::replaceBond()`, since both functions will make a copy of the query rather than taking ownership. Therefore, it is better to use static allocation to avoid potential memory leaks in case an exception is thrown between allocation and deletion. Note that elsewhere in the same file static allocation is already used for `QueryAtom` and `QueryBond`; this PR only makes usage of static allocation consistent across the whole file
* switched to `auto` and `constexpr` where possible
* `ADJUST_IGNOREMAPPED` was not exposed to Python - this PR exposes it
=> adjustQueryProperties cleanup

Code/GraphMol/ForceFieldHelpers/FFConvenience.h, Code/GraphMol/ForceFieldHelpers/MMFF/MMFF.h, Code/GraphMol/ForceFieldHelpers/UFF/UFF.h
Added some inlines to header functions at ForceFieldHelpers. Without these including 
`<GraphMol/ForceFieldHelpers/MMFF/MMFF.h>` to an external C++ project caused "already defined" linker issue at least in MSVC.
=> Add inlines to ForceFieldHelpers header functions

Code/GraphMol/Depictor/RDDepictor.cpp, Code/GraphMol/Depictor/testDepictor.cpp, Code/MinimalLib/tests/tests.js
When deciding whether to bias the straightening towards a multiple of 30-degrees, we should not be counting 0-degree rotations as multiples of 60 degrees, as otherwise layouts which have no angles which are multiple of 60 degrees such as
would still be rotated by 30 degrees, even though it is not necessary nor desirable:
This small PR avoids that the above happens, and adds a couple of tests.
=> straightenDepiction should not consider 0-degree rotations as multiples of 60

CMakeLists.txt
In PR #6339 we dropped `CMAKE_INSTALL_PATH` from the code that detects the `PYTHON_INSTDIR` variable in the CMake script. As a consequence of this, when running `make install`, the Python package would not be installed to the `CMAKE_INSTALL_PATH`, but to a location that is dependent on the environment being used in the build. E.g., under `/usr/local/lib` (which requires root privileges), on my personal Ubuntu system.
This patch restores `CMAKE_INSTALL_PATH` in the `PYTHON_INSTDIR` determination in a way that makes sure that the results always match a POSIX or a WIN32 style schema.
=> CMAKE_INSTALL_PREFIX not honored during installation of the Python Files

Code/GraphMol/MolOps.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp, Docs/Book/RDKit_Book.rst
Fixed the problem identified in PR #6292.
As mentioned in the PR, when an atom could have a dative bond to 2 metals, the one selected wasn't canonical, such that different atom input orders gave different results, and sometimes 2 dative bonds went to the same metal.  It now picks the metal with fewer dative bonds with the canonical rank order as a tie breaker.  The examples in #6292 are now dealt with correctly.
I have put it back in the default sanitisation pipeline.
=> Fix cleanupOrganometallics and reinstate to sanitisation

External/INCHI-API/inchi.cpp, External/INCHI-API/test.cpp
The InChI in this case is clearly broken, but we shouldn't toss an exception in these cases... just return a null molecule instead.
=> Fixes #6172

Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
The recently added double-bond-related tags were missing.
=> expose two missing EmbedFailureCauses tags to python

Code/RDGeneral/Dict.h
Minor cleanup, no effect to functionality: There's a same loop variable name used in nested for-loops in Dict.h. Not a bug but causes compiler warnings.
=> Fix identical for-loop variable names

Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
- `fastFindRings()` was not being called
- a `count_matches()` overload was missing
- `count_matches()` was ignoring the `numThreads` parameter
- adding a `PatternFingerprintMol` created with a certain number of bits to the `PatternHolder` will *not* work: one needs to create the `PatternHolder` with the desired number of bits, and then call `makeFingerprint`
- improved tests to make sure the library actually behaves as expected
- added a `get_matches_as_uint32array()` function
- added functionality to serialize/deserialize a `JSSubstructLibrary`
=> Fixes some issues in the SubstructLibrary JS implementation

Code/GraphMol/CMakeLists.txt, Code/GraphMol/MolPickler.cpp, Code/GraphMol/MolPickler.h, Code/GraphMol/catch_pickles.cpp, Code/RDGeneral/StreamOps.h
The code changes aren't all that complex: storing key-value pairs is expensive, so we recognize particular keys when present and store then differently.
Using this scheme storing the private properties for atoms and bonds on the 1000 ChEMBL molecules I looked at in the discussion of #6312 looks like this:
```
In [6]: len(b''.join([x.ToBinary() for x in ms]))
Out[6]: 1578735
In [7]: len(b''.join([x.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickleOptions.BondProps|Chem.PropertyPickleOption
...: s.PrivateProps) for x in ms]))
Out[7]: 2184606
```
Previously just storing either the atom or bond properties was larger than that.
Adding computed properties still takes a lot of space:
```
In [8]: len(b''.join([x.ToBinary(Chem.PropertyPickleOptions.AtomProps|Chem.PropertyPickleOptio …
```
=> Fixes #6312: reduces the size of molecule pickles which include atom and bond properties

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #6395 
This code gives a fix to molfile parsing, where properties lines might not be processed correctly when they use pairs of values. The old code would fail to increase the string index when certain values were provided, so the code would fail to move completely to the next pair of values.
I've adjusted the code to be similar to the Attachment Points code https://github.com/rdkit/rdkit/blob/d4547e21165cf9cdc04ea6e0bfd1f25bbf2ed14e/Code/GraphMol/FileParsers/MolFileParser.cpp#L903-L973
and the ZCH code https://github.com/rdkit/rdkit/blob/d4547e21165cf9cdc04ea6e0bfd1f25bbf2ed14e/Code/GraphMol/FileParsers/MolFileParser.cpp#L689-L738
This code adjusts the string index close to where the values are being parsed, so that there aren't issues later on with continues skipping the string …
=> Fixes #6395: Move string index appropriately with molfiles

Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
Two members of the enum had not been exposed.
@adalke pointed this out in #6315
=> expose some missing CXSmiles flags to python

Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rdchem.cpp, Code/GraphMol/Wrap/seqs.hpp, rdkit/Chem/__init__.py
This fixes #6208:
The 'slowness' in the iterators is due to seqs.hpp actually throwing a C++ exception to tell boost::python that a Python exception should be thrown, even for the `StopIteration` at the end of an iterator.
As suggested in the issue, we can get around that by implementing the iterator directly in Python.
With this patch, the benchmarks on my Mac go from
```python
In [1]: from rdkit import Chem
...: mol = Chem.MolFromSmiles('CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O')
...: 
...: %time for a in mol.GetAtoms(): pass
CPU times: user 1.57 ms, sys: 44 µs, total: 1.61 ms
Wall time: 1.64 ms
```
to (note the change in the units, from `ms` to `µs`)
```python
In [1]: from rdkit import Chem
...: mol = Chem.MolFromSmiles('CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O')
...: 
...: %time for a in …
```
=> Fixes #6208

Code/GraphMol/AddHs.cpp, Code/GraphMol/catch_graphmol.cpp
Fixes #6437
The issue with pyrrole and pseudo-pyrroles like the one described in the issue is that the problematic atom has to satisfy a valence of 3 during kekulization (note that to trigger the issue, the mol has to start in the aromatic form!), and this can happen in two ways:
- With a single and a double bond to neighboring atoms in the aromatic cycle.
- With three single bonds, 2 to neighbors in the aromatic cycle, and one to a H.
If the input mol has the H atom attached, and we remove it without turning it into explicit H, then the kekulization routine will not have any way to disambiguate between both possibilities, and will therefore fail.
As mentioned in the issue, we have code in place to add the explicit H to the pyrrole case, so I'm just adding an extra case to the check. This …
=> Fixes Issue 6437

Code/MinimalLib/minilib.cpp, Code/MinimalLib/tests/tests.js
Small PR to enable using JSSubstructLibrary without pattern fps.
- enable using `JSSubstructLibrary` with no fps by passing `num_bits 0`
- get rid of `dynamic_cast` which never looks great
- add unit tests for no-fingerprint `JSSubstructLibrary`
=> Enable using JSSubstructLibrary without pattern fps

Code/MinimalLib/jswrapper.cpp
Small cleanup PR:
- removed leftover, unused `parse_morgan_fp_param()` function
- remove leftover, unused `deprecationMsgShown` variable
- corrected error message which had a typo
- removed unused `molArray` variable
- removed `DEPRECATED` comment that had been forgotten
=> misc jswrapper.cpp cleanup

Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/SubstructUtils.h, Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/rough_test.py
These changes add parameters to `SubstructMatchParams` that allows callers to require specific properties on atoms and bonds to match when performing a substructure search. A simple example:
```
m = Chem.MolFromSmiles("CCCCCCCCC")
query = Chem.MolFromSmiles("CCC")
m.GetAtomWithIdx(0).SetProp("test_prop", "1")
query.GetAtomWithIdx(0).SetProp("test_prop", "1")
print(f"Without setting atomProperties: {m.GetSubstructMatches(query)}")
ps = Chem.SubstructMatchParameters()
ps.atomProperties = ["test_prop"]
print(f"With setting atomProperties: {m.GetSubstructMatches(query, ps)}")
```
gives
```
Without setting atomProperties: ((0, 1, 2), (1, 2, 3), (2, 3, 4), (3, 4, 5), (4, 5, 6), (5, 6, 7), (6, 7, 8))
With setting atomProperties: ((0, 1, 2),)
```
and the same can be done with bond properties.
I …
=> Add atom and bond property parameters to substruct matching

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
The old stereo perception code handled these cases, as does InChI, so we shouldn't reject them.
This was raised in discussion #6291 here:
https://github.com/rdkit/rdkit/discussions/6291#discussioncomment-6214078
=> Allow systems like C/C=N/[H] to be stereogenic with the new chirality code

Code/GraphMol/FileParsers/testPropertyLists.cpp, Code/RDGeneral/RDValue.h
Fixes #6465 
Adds int64 bit conversions to getProp<std::string>, this allows the atom property lists in mol files to be used in the substructure property match code.
=> Add int64 bit conversions to getProp<std::string>

Code/GraphMol/Fingerprints/Wrap/MHFPWrapper.cpp, Code/GraphMol/Wrap/Trajectory.cpp, rdkit/Chem/FilterCatalog.py
- Fix a couple of docstrings that were confusing `boost::python` ([FromArray](http://rdkit.org/docs/source/rdkit.Chem.rdMHFPFingerprint.html?highlight=fromstringarray#rdkit.Chem.rdMHFPFingerprint.MHFPEncoder.FromArray), [FromStringArray](http://rdkit.org/docs/source/rdkit.Chem.rdMHFPFingerprint.html?highlight=fromstringarray#rdkit.Chem.rdMHFPFingerprint.MHFPEncoder.FromStringArray)); namely, the comment was being parsed as the parameter name, i.e.:
**FromArray**(_(MHFPEncoder)vec, (list)Creates a MHFP vector from a list of unsigned integers._) → `_vectj`
**FromStringArray**(_(MHFPEncoder)vec, (list)Creates a MHFP vector from a list of arbitrary strings.) → `_vectj`
- Python keywords should not be used as parameter names (namely, `from`)
- Function documentation should not include the …
=> Fix a few broken docstrings

Code/GraphMol/ROMol.h
The docstring claimed that it returned the new number of atoms. It actually returns the index of the new atom.
I think it makes more sense to change the documentation than the behavior, because callers are definitely out there using the current behavior.
=> Fix RWMol::addAtom docstring

Code/GraphMol/Depictor/Wrap/testDepictor.py
These tests weren't being ran due to an indentation issue. I think that when I wrote these, my formatting was incorrect, and the re-formatting done before the last release accidentally moved all of these tests into another function and skipped them.
=> Fixed tests that weren't being run in testDepictor.py

Code/GraphMol/FMCS/FMCS.cpp
Small refactoring to replace a `try..catch` block with an `if` clause. Exceptions are expensive, and not supported by the legacy JS MinimalLib builds, so it is good to avoid them when they can be replaced without pain.
=> Replace a try..catch block with an if clause

CMakeLists.txt, Code/MinimalLib/docker/Dockerfile, Code/MinimalLib/docker/Dockerfile_legacy_browsers
This PR allows building MinimalLib using the latest `emsdk` (see https://github.com/rdkit/rdkit-js/issues/347).
The issue described in https://github.com/rdkit/rdkit-js/issues/347 is not actually caused by anything changed in RDKit, but rather by an `emsdk` update.
- Add appropriate compiler flags such that MinimalLib builds also when using `clang` version >=15
- Use the `nodejs` version bundled with `emscripten` to run tests since the one in Ubuntu is ancient and does not support recent `wasm` features
=> Fixes rdkit-js/issues/347

Code/MinimalLib/tests/tests.js
Small fix as I realized some JS tests were failing when run with MinimalLib built without exception support, as is the case for the legacy pure JS library.
=> Get tests to work when building without exception support (i.e., legacy pure JS library)

CMakeLists.txt
This is a second fix after #6339. Even after #6371, `CMAKE_INSTALL_PREFIX` is not honored when building under windows. I just built 2023.03.2, and noticed that the Python wrappers were not installed under the path I had specified.
The cause of the issue is that the "nt" scheme in `sysconfig.get_path()` uses the `base` key for the "platlib" path instead of  `platbase`, as does the "posix_prefix" schema:
```
In [9]: sysconfig._INSTALL_SCHEMES
Out[9]:
{'posix_prefix': {'stdlib': '{installed_base}/lib/python{py_version_short}',
'platstdlib': '{platbase}/lib/python{py_version_short}',
'purelib': '{base}/lib/python{py_version_short}/site-packages',
'platlib': '{platbase}/lib/python{py_version_short}/site-packages',
'include': '{installed_base}/include/python{py_version_short}{abiflags}', …
```
=> CMAKE_INSTALL_PREFIX not honored for Python files installation on Windows

Code/GraphMol/FileParsers/CDXMLParser.cpp
This PR should fix a warning about an unused `targetBondLength` argument in the CDXML parser implementation, that looked like an oversight. It then replaces the literal 1.5 value with a constant as suggested in a recent related PR.
=> unused targetBondLength argument in the CDXML parser's scaleBonds

Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/MolEnumeratorTest.cs
Exposes MolEnumerator and MolBundle to the C# wrapper
I added a simple test, though we don't have any automated testing for C# yet.
=> Add MolEnumerator to C#

Code/GraphMol/Canon.cpp, Code/GraphMol/FileParsers/cdxml_parser_catch.cpp, Code/GraphMol/MolHash/Wrap/testMolHash.py, Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp, Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/catch_canon.cpp, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/WrapperTests.java, Code/PgSQL/rdkit/expected/rdkit-91.out
This makes sure that information which is not going to be in the output SMILES doesn't end up getting used in the canonicalization.
=> Fixes #6479

Code/GraphMol/ChemReactions/ReactionWriter.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/molfile_stereo_catch.cpp
Fixes #6502
The issue was happening because in #6387 we check that the ends of the stereo bonds have at least one neighbor, but we should also check that there are no more than 2 neighbors (or degree 3, including the double bond).
This patch fixes the issue by replacing the check in the code with `Chirality::detail::isBondPotentialStereoBond()`, which includes the check for the maximum allowed neighbors. This means checking the order of the bond twice, but I think it is a good idea to centralize the check in a single function instead of reimplementing multiple times.
=> Fixes #6502

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, rdkit/Chem/UnitTestRegistrationHash.py
Fixes #6505.
The fix is trivial: the call to `TautomerHashv2()` in `MolHash::MolHash()` was not passing the `cxFlagsToSkip` argument, so that no CX extensions were being filtered from the output.
=> Fixes #6505

rdkit/Chem/PandasPatcher.py, rdkit/Chem/UnitTestPandasTools.py
This issue was originally reported by Rainer Wilcken.
In the current version of `PandasTools`, molecules will not show up as images in a Jupyter Notebook whenever the number of columns in the DataFrame exceeds `max_cols` and therefore some columns are truncated and replaced with `...`.
See a simple reproducible below:
```
from rdkit.Chem import PandasTools
from io import StringIO
import pandas as pd
pd.__version__
1.5.2
PandasTools.RenderImagesInAllDataFrames()
buf = '''"Molecule ChEMBL ID";"Molecule Name";"Molecule Max Phase";"Molecular Weight";"#RO5 Violations";"AlogP";"Compound Key";"Smiles";"Standard Type";"Standard Relation";"Standard Value";"Standard Units";"pChEMBL Value";"Data Validity Comment";"Comment";"Uo Units";"Ligand Efficiency BEI";"Ligand Efficiency …
```
=> Make sure that molecules are shown as images by PandasTools also when DataFrames are truncated horizontally

Code/Demos/boost/smartPtrsAndIters/test.py, Code/GraphMol/ChemReactions/Wrap/testEnumerations.py, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/Wrap/testSanitize.py, Code/GraphMol/FilterCatalog/Wrap/rough_test.py, Code/GraphMol/MolChemicalFeatures/Wrap/testChemicalFeatures.py, Code/GraphMol/SLNParse/Wrap/testSLN.py, Code/GraphMol/StructChecker/Wrap/rough_test.py, Code/GraphMol/Wrap/rough_test.py, Code/ML/InfoTheory/Wrap/testRanker.py, Contrib/ConformerParser/Wrap/testConformerParser.py, rdkit/Chem/MolStandardize/UnitTestMolStandardize.py, rdkit/DataStructs/UnitTestcBitVect.py, rdkit/Dbase/UnitTestDbUtils.py
https://docs.python.org/3/library/unittest.html#deprecated-aliases
=> refactor(python): replace deprecated unittest methods

Code/GraphMol/FileParsers/MaeWriter.cpp, Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/Wrap/MaeWriter.cpp, Code/GraphMol/Wrap/rough_test.py
The `s_m_color_rgb` property is not one of the required atom properties by the Maestro format, but it was added to MaeWriter in #6069. This PR removes this property. It also fixes a couple of bugs that I found during testing.
=> Drop the s_m_color_rgb property from MaeWriter

Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/common.h, Code/MinimalLib/minilib.cpp, Code/MinimalLib/tests/tests.js
This PR exposes partial sanitization options to MinimalLib (both JS and CFFI), namely:
- `setAromaticity` (defaults to true)
- `fastFindRings` (defaults to true; only used when sanitize=false)
- `assignStereo` (defaults to true)
These options avoid doing unnecessary work when the molecule is only used for specific purposes (e.g., computing FPs or doing substructure searches), as nicely described [in this blog post](https://rdkit.blogspot.com/2016/09/avoiding-unnecessary-work-and.html).
I also added `try..catch` blocks to the CFFI library FP functions to avoid that they throw exceptions that cannot be caught from C, but rather return `nullptr`, as other functions already do.
=> Exposed partial sanitization options to MinimalLib (both JS and CFFI)

.azure-pipelines/vs_build_dll.yml, azure-pipelines.yml
The windows DLL CI builds were failing due to an error deep in some python dependency. Rather than tracking that down and pinning things, this just disables the python wrappers for the windows DLL build. 
The primary purpose of the DLL builds is to make sure that it's actually possible to build the RDKit in DLL mode on winows (it's easy to forget to add some boilerplate and break this), and we test that python builds work on Windows in another CI configuration, so this change shouldn't affect test coverage.
=> update windows DLL CI build config

ReleaseNotes.md, rdkit/Chem/MolStandardize/charge.py, rdkit/Chem/MolStandardize/fragment.py, rdkit/Chem/MolStandardize/metal.py, rdkit/Chem/MolStandardize/normalize.py, rdkit/Chem/MolStandardize/resonance.py, rdkit/Chem/MolStandardize/standardize.py, rdkit/Chem/MolStandardize/tautomer.py, rdkit/Chem/MolStandardize/validate.py, rdkit/Chem/MolStandardize/validations.py
We aren't supporting this any more and it's causing some confusion, so it should be removed for the 2024.03 release.
=> Deprecate the pure python MolStandardize implementations.

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6504
Fixes the bug.  The code for stepping the inner bond of a double bond shouldn't be called when there's an atomic symbol at each end of the bond.
The action is on line 2807.  There's some re-formatting as well, for some reason.
=> Github 6504 - incorrect drawing of double bonds in sulfoximines

Code/GraphMol/Canon.cpp, Code/GraphMol/ChemReactions/ReactionRunner.cpp, Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/Chirality.cpp, Code/GraphMol/FileParsers/CDXMLParser.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/testExtendedStereoParsing.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolInterchange/Parser.cpp, Code/GraphMol/MolInterchange/Writer.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/MolPickler.cpp, Code/GraphMol/MolPickler.h, Code/GraphMol/ROMol.cpp, Code/GraphMol/Renumber.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp, Code/GraphMol/StereoGroup.cpp, Code/GraphMol/StereoGroup.h, Code/GraphMol/Wrap/StereoGroup.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/catch_canon.cpp
This implements parsing, storing and optionally forwarding the Enhanced Stereo Group ids on output for multiple formats: CXSMILES, mdl V3000, pickle, mol interchange and cdxml (parsing only).
By default, we reassign the Stereo Group IDs, but we can use the `forwardStereoGroupIds()` function to preserve the Stereo Group IDs on output. Still, it must be noted that some operations (stereo group canonicalization, reactions) can either reset the ids or potentially alter the Stereo Groups, so that the IDs won't be preserved even if `forwardStereoGroupIds()` is used.
Also note that Stereo Group id "0" means that the id is not set, so that one will be assigned on the fly on export.
=> Optionally forward Enhanced Stereo Group ids

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
This fixes the issue @ptosco noticede in PR #6473: the problem is that, since we use `getTotalDegree()` to evaluate the minimum number of neighbors to each bond end atom, we allow stereo bonds with just one implicit Hydrogen neighbor on one side, as in Paolo's example.
If that is the case, when we try to call `getStereoInfo(bond)` we get the exception due to this check https://github.com/rdkit/rdkit/blob/88c5d80b3309d2b2ae15d766434650029923fa05/Code/GraphMol/FindStereo.cpp#L131. And further down we'd have even more trouble when trying to figure out the bond's stereo.
This PR fixes this problem by detecting the `getTotalDegree() == 1` and marking the stereo as "unspecified". Note that this also causes both controlling atoms associated to that bond end  to be `StereoInfo::NOATOM`. I think …
=> Fix issue introduced in #6473

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6569
When 2 atoms had the same coordinates, some things like the placement of atom or bond notes or drawing wedges gave NaN due to division by the zero length.  This fix temporarily moves one of the atoms by 0.1, 0.1 in these circumstances so it doesn't occur.
It was lucky that Greg's example had the offending atoms on a chiral centre, or the extra problem with drawing the wedges would have been missed.  Sometimes the sun shines on the righteous :-).
=> Placement of bond or atom labels gets confused when atoms overlap

Docs/Book/Cookbook.rst, rdkit/Chem/AllChem.py
No issue
The docs for ConstrainedEmbed at http://rdkit.org/docs/source/rdkit.Chem.AllChem.html have a poorly formatted line such that the crucial exemplification of use of the function is buried in the text rather than highlighted with a green background:
Working from analogy with the rest of the docstring I think this newline is important.
I don't know how to test to see if this has fixed it.
=> Add newline to ConstrainedEmbed docstring.

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/RWMol.cpp
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49783
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44520
(1) During fuzzing, it's possible that one atom object is added to the same Stereo group multiple times. The replaceAtom function only replaces a single occurrence. The code later references the second copy of the atom in the stereo group (which wasn't replaced) which accesses deleted memory. This change replaces all copies of an atom during the replaceAtom process.
(2) Catches situations during fuzzing where index values for text substrings in ParseOldAtomList could go out of range.
=> Fix vulnerabilities found by fuzzer.

Code/PgSQL/rdkit/rdkit.h
Small PR to add the `varatt.h` header and define the `Abs` macro as it was defined on PostgreSQL <16.
=> allow building the cartridge against PostgreSQL 16

Code/ForceField/ForceField.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemTransforms/testChemTransforms.cpp, Code/GraphMol/Descriptors/PMI.h, Code/GraphMol/FileParsers/MolWriters.h, Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp, Code/GraphMol/MolBundle.h, Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/RDBoost/python_streambuf.h, Contrib/ConformerParser/test.cpp
This fixes some build warnings I have been noticing over the past weeks.
The most annoying one is the missing `override` in `Code/GraphMol/FileParsers/MolWriters.h`, since this is propagated to code that uses this header.
=> Fix some build warnings

Code/GraphMol/Fingerprints/MACCS.cpp, Code/GraphMol/Fingerprints/MorganGenerator.cpp, Code/GraphMol/Substruct/vf2.hpp
While running CFFI tests under `valgrind` I noticed that memory is leaked when an exception is thrown during generation of certain FPs; see the `valgrind` trace below:
```
$ valgrind --leak-check=full ./Code/MinimalLib/cffi_test
[...]
==255551==
==255551== HEAP SUMMARY:
==255551==     in use at exit: 192 bytes in 7 blocks
==255551==   total heap usage: 524,741 allocs, 524,734 frees, 39,361,697 bytes allocated
==255551==
==255551== 16 bytes in 1 blocks are definitely lost in loss record 1 of 7
==255551==    at 0x4C2C866: operator new[](unsigned long) (vg_replace_malloc.c:579)
==255551==    by 0x5162D5A: bool boost::vf2_all<boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS, RDKit::Atom*, RDKit::Bond*, boost::no_property, boost::listS>, RDKit::detail::AtomLabelFunctor, …
```
=> Avoid leaking memory in case exceptions are thrown while generating FPs

Code/GraphMol/Canon.cpp, Code/GraphMol/Canon.h, Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/SmartsWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
This adds a `rootedAtAtom` to `MolToSmarts()`. This argument may come in handy in the case of generating SMARTS expressions for inclusion in recursive SMARTS, where the atom for which the context is being specified must be the first atom in the SMARTS expression.
I'm not 100% sure about the handling of lead chiral atoms -- is it really that simple, just not reordering at all? Am I missing something here, @greglandrum ?
=> Add a "rootedAtAtom" to MolToSmarts

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
This option allows conformer generation to be restarted with reproducible results.
As an example, the 5th conformer generated using the seed `0xf00d` and the first conformer generated using the seed `0xf00d+5` will be the same:
```
DGeomHelpers::EmbedParameters ps = DGeomHelpers::ETKDGv3;
ps.enableSequentialRandomSeeds = true;
ps.randomSeed = 0xf00d;
auto cids = DGeomHelpers::EmbedMultipleConfs(*mol, 10, ps);
ps.randomSeed = 0xf00d + 5;
auto cids2 = DGeomHelpers::EmbedMultipleConfs(mol2, 5, ps);
compareConfs(mol.get(), &mol2, 5, 0);
```
=> add option to use sequential random seeds in the conformer generator

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
This Fixes #6640.
This is the structure that is causing the infinite loop:
The cause of the loop is the dependency between the potential stereochemistries of atom 8 and  the imide double bond at the opposite side of the ring. Given that the imide bond does not have any "real" neighbors (just an implicit H), it can never be resolved to cis or trans, and would stay undersolved after https://github.com/rdkit/rdkit/pull/6473 and https://github.com/rdkit/rdkit/pull/6527. The reason we didn't see this after any of these patches is that none of the structures we looked at there did have a dependency on the newly added (and fixed) imine bonds.
This fix solves the infinite loop problem by catching the neighborless imine bonds in `updateBonds()` and definitively marking them as "Unknown", since the …
=> Fixes #6640

Code/GraphMol/Canon.cpp, Code/GraphMol/catch_canon.cpp, External/INCHI-API/inchi.cpp
This fixes #6633.
The cause of the issue is that when running `canonicalizeDoubleBond()`, we allow any neighboring bonds to be used as a reference. These bonds will be given a direction (`ENDDOWNRIGHT` / `ENDUPRIGHT`), and will potentially be written to the smiles as `/` or `\`. The problem with this is that according to the documentation, https://www.daylight.com/dayhtml/doc/theory/theory.smiles.html#RTFToC23, the slashes represent single or aromatic bonds. `switchBondDir()` has a precondition that checks for these types of bonds, and it is being triggered in the case of the mol I attached to the issue, since, due to the mol's construction, it is the dative bond that is being chosen as a reference for the stereochemistry of the double bond.
This addresses the issue by restricting the …
=> Fixes #6633

Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp, Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py
No issue.
Exposes the singleLargestFrag option of RascalMCES::RascalOptions to the Python wrapper.
Writing documentation is always valuable!
=> Expose RascalMCES singleLargestFrag option to Python.

Code/GraphMol/FileParsers/CDXMLParser.cpp, Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/Mol2FileParser.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/MarvinParse/MarvinParser.cpp, Docs/Book/GettingStartedInPython.rst
The issue in #6664 is happening, basically, because we run H removal before stereo bond detection.
In H removal, the option to not remove stereogenic H is enabled by default, but since the removal is run before stereo bond detection, the imine H does not have anything that marks it as stereogenic, and is removed. So, when bond stereo is finally run, the H atom are no longer there, so that the imine double bond cannot be resolved.
The fix is to run stereo bond detection prior to H removal, but as this also causes some problems, we also need to call "cleanup" sanitization before the detection so that we charge separate some double bonds as the ones in nitro groups.
=> Fixes #6664

Code/GraphMol/MolOps.cpp, Code/GraphMol/catch_graphmol.cpp
We were calling `cleanupOrganometallics()` far too late in the sanitization process. This moves it up to where it belongs.
=> fix order of cleanupOrganometallics() in sanitizeMol()

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Sometimes, mol files may have an incorrect 2D/3D tag. RDKit's current behavior is to always honor a "3D" tag, but check the Z coordinate and eventually override the tag if it is "2D".
This PR changes this behavior to distrust the tag, and always assign the conformer dimensionality flag depending on the Z coordinates and the chirality marks on the input.
Basically, the new behavior would be to honor what we see in the Z coordinates, with the exception of all-zero coordinate mols, where we also check the existence of 2D stereo marks (i.e., bond directions) to decide whether the structure should be marked 2D (so that we honor the stereo marks) or 3D (so that `assignStereochemistryFrom3D()` can be used if changes are made to the mol).
=> Do not trust the 2D/3D tag in ctab mol files

Code/MinimalLib/tests/tests.js
This small PR fixes a failing `flexicanvas` JS test, as apparently the size of the `flexicanvas` generated for that specific molecule has changed.
=> Fixes failing flexicanvas JS test

README.md
Add links to UGM Materials from 2022 and 2023
There is no issue fixed.
I just linked the last two years' UGM materials.
None
=> Update README.md for newest RDKit UGMs

Code/GraphMol/Depictor/DepictUtils.cpp, Code/GraphMol/Depictor/DepictUtils.h, Code/GraphMol/Depictor/EmbeddedFrag.cpp, Code/GraphMol/Depictor/catch_tests.cpp
If there is a trans double bond in a ring, it's important to add a trans 2d depiction! This is important for visualization, but it is also important for chemical accuracy. SDF uses the 2D coordinates to discern bond stereochemistry, and some 3D embedding techniques may start from 2D.
Without this commit, trans double bonds in rings invert on roundtrip through SDF.
Here's a very simple assertion that fails before this commit and passes after:
smi = "C1=C/CCCCCCCCCCCC/1"
assert smi == Chem.MolToSmiles(Chem.MolFromMolBlock(Chem.MolToMolBlock(Chem.MolFromSmiles(smi))))
And here's what a couple odd molecules look like now:
=> Add trans layout for double bonds in rings

Code/GraphMol/DetermineBonds/CMakeLists.txt, Code/GraphMol/DetermineBonds/DetermineBonds.cpp, Code/GraphMol/DetermineBonds/DetermineBonds.h, Code/GraphMol/DetermineBonds/Wrap/rdDetermineBonds.cpp, Code/GraphMol/DetermineBonds/Wrap/testDetermineBonds.py, Code/GraphMol/DetermineBonds/catch_tests.cpp, ReleaseNotes.md
This was a suggestion by @rogersayle at the 2023 RDKit UGM: use the connect the dots algorithm instead of the xyz2mol VdW method by default in DetermineBonds
=> Use the connect-the-dots algorithm by default in DetermineBonds

Code/GraphMol/ForceFieldHelpers/MMFF/AtomTyper.cpp, Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp
This PR fixes a crash bug that had gone unnoticed so far as it is triggered by awkward chemistry (e.g., divalent H- anion).
=> Fixes #6728

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecomp.h, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RGroupDecomposition/Wrap/test_rgroups.py, Code/GraphMol/RGroupDecomposition/catch_rgd.cpp
This PR extracts the RGD core matching logic into a separate `getMatchingCoreIdx()` function, which can take an optional `std::vector<MatchVectType>` pointer to retrieve the atom idx matches if desired.
This is very useful to quickly attribute the matching core to a molecule using the same parameters that will be used for RGD without actually running the more compute-intensive RGD stage of sorting out the most appropriate mapping of R labels to substituents.
=> Extract the core matching logic into a separate function

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/Substruct/test1.cpp
The SMARTS should set the _SmilesStart property to handle inverted chirality on the first atom.
None but #760, #1489 are related
Chirality on the first atom should invert in SMARTS like it does in SMILES. It seems there was intention for this in the code (logic in ``Canon::chiralAtomNeedsTagInversion``) but the parser was not setting the property.
```python
smi = "[C@H](C)(O)N"
qry = Chem.MolFromSmarts(smi)
mol = Chem.MolFromSmiles(smi);
print(mol.HasSubstructMatch(qry, useChirality=True))
```
I conda installed bison/flex but still seemed to be an older version than was currently used. May be worth someone else regenerating ``smarts.?pp.cmake`` with the minor changes to the smarts.yy.
I have many failures when I run ``ctest`` (SegFault/Exceptions) so not sure if …
=> Fix chirality handling when the chiral atom is the first one in a SMARTS

Code/GraphMol/Atom.cpp, Code/GraphMol/ROMol.cpp, Code/GraphMol/SubstanceGroup.cpp, Code/GraphMol/SubstanceGroup.h
1. Removes some redundant PRECONDITION calls.  In cases where function A has a precondition and calls function B which has the same precondition, the precondition can be safely removed from function A
2. Modernizes some code in Atom.cpp and ROMol.cpp
3. Moves a const std::vector from the header into a .cpp file in SubstanceGroups (this is something @rogersayle pointed out at the UGM)
As a reference point for future cleanup passes, this loop:
```
for (auto ai = mol->beginAtoms(); ai != mol->endAtoms(); ++ai) {
if ((*ai)->getAtomicNum() > 1) {
++sum;
}
}
```
takes 25 times as long to execute as this one:
```
for (const auto atom : mol->atoms()) {
if (atom->getAtomicNum() > 1) {
++sum;
}
}
```
I've tested this on both linux (GCC) and windows (MSVC++) and see similar differences on both
=> Some small cleanups from the UGM Hackathon

Code/GraphMol/FileParsers/CMakeLists.txt, Code/GraphMol/FileParsers/ProximityBonds.cpp, Code/GraphMol/FileParsers/connectTheDots_catch.cpp
straightforward test to check whether or not residue info is present before using the pointers
adds a new testing file for the connect the dots functionality so that we can move the code elsewhere in a future release.
=> Fixes #6756

rdkit/Chem/Draw/__init__.py
`_moltoimg()` should honor `drawOptions.prepareMolsBeforeDrawing` and not run `PrepareMolForDrawing` if requested not to.
This is annoying when trying to visualize a molecule with original molblock wedging as, for example, chiral Hs were still being added even if one does not want to.
=> _moltoimg() should honor drawOptions.prepareMolsBeforeDrawing

Code/GraphMol/FMCS/FMCS.cpp, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
This PR implements into MinimalLib a version of `get_mcs()` that returns a JSON string rather than a SMARTS string or a `JSMol`.
This is useful to:
* tell whether an MCS calculation has run to completion or rather has timed out (by checking `canceled`)
* to retrieve the size of the MCS (by accessing `numAtoms` and `numBonds`)
* to retrieve all degenerate SMARTS as an array rather than as a string in case `StoreAll` was set to `true`
I also realized that I had forgotten to expose `StoreAll` to `parseMCSParametersJSON`, so I fixed that too.
=> Implement MinimalLib get_mcs() version that returns JSON

Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/FileParsers/GeneralFileReader.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/testGeneralFileReader.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py, Docs/Book/GettingStartedInPython.rst, Docs/Book/conf.py, rdkit/Chem/Draw/UnitTestDraw.py
make sure that a full build and test can work when we don't build with boost::iostreams support
Hopefully nobody ever actually needs this, but as long as we supply the option, the tests should actually work
=> Fixes #6818

Code/GraphMol/RGroupDecomposition/RGroupCore.cpp, Code/GraphMol/RGroupDecomposition/RGroupCore.h, Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp
Fixes #6779
When reading R-group decomposition codes, I find that the variable and function argument `hasCoreDummies` serves as a temporary variable and it only affects itself. Maybe it was useful during development and debugging, but I feel like at this stage it causes more confusion than benefits.
=> Remove redundant argument and variable `hasCoreDummies` (#6779)

Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/Wrap/Mol.cpp
There's a bit of cleanup in here too. The fix itself is in 74e68bd.
One question here is if we want to always honor the limit on recursive queries that's used to `maxRecursiveMatches` or to `std::max(maxRecursiveMatches,maxMatches)` (which is what's done here).
i..e is there a real use case where you would want `maxRecursiveMatches` to be smaller than `maxMatches` (the use case where it's larger is easy for me to imagine)
=> Fixes #6017

rdkit/Chem/FunctionalGroups.py
This fixes the unclosed resource warning that gets triggered when you run `BuildFuncGroupHierarchy`:
```
from rdkit.Chem import FunctionalGroups
group_hierarchy = FunctionalGroups.BuildFuncGroupHierarchy()
##########################################
<ipython-input-1-8e0f104e2c1c>:2: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/rodrigue/Documents/code/rdkit_builder/rdkit/Data/Functional_Group_Hierarchy.txt' mode='r' encoding='UTF-8'>
group_hierarchy = FunctionalGroups.BuildFuncGroupHierarchy()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
=> Fix unclosed resource in BuildFuncGroupHierarchy

Code/GraphMol/ChemReactions/Enumerate/EvenSamplePairs.h
Unlike other files that use the `RDK_USE_BOOST_SERIALIZATION` flag, EvenSamplePairs.h does not wrap the `BOOST_CLASS_VERSION` boilerplate in an #ifdef.
This happens to work anyway when built against older versions of boost, where the required header is being made visible by other boost includes, but this causes a build breakage when compiled against Boost 1.82 or later and with serialization off.
=> Fix build error when serialization is off.

Code/GraphMol/FileParsers/MaeWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
This updates the MaeWriter to include chirality and double bond stereo. Since there doesn't seem to be a great way to get CIP rankings, this sets atom numbering chirality and will allow schrodinger software and RDKit's MaeMolSupplier to interpret chiral centers.
I also added a property that sets bond parity for "any stereo" double bonds. For now, this is just so the output can be used with schrodinger software -- we will need to update the MaeMolSupplier to recognize this property.
=> Add support for writing chirality and stereo in MaeWriter

Code/GraphMol/RGroupDecomposition/RGroupDecompData.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp
If `doEnumeration` is set in RGD and a input core does not enumerate into a bundle that core is not added. This PR fixes this   by adding the original input core if it does not enumerate into a bundle.
=> RGD: Fix doEnumeration true for cores that are not bundles

.azure-pipelines/linux_build_limitexternal.yml, .azure-pipelines/mac_build.yml, Code/GraphMol/Descriptors/GETAWAY.cpp, Code/GraphMol/Descriptors/test3D.cpp, Code/GraphMol/Descriptors/testPBF.cpp, Code/GraphMol/Descriptors/testWHIM.cpp, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp, Code/GraphMol/FMCS/Test/testFMCS.cpp, Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.cpp, Code/GraphMol/FileParsers/SmilesMolSupplier.cpp, Code/GraphMol/MolDraw2D/DrawText.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompParams.cpp, Code/GraphMol/RGroupDecomposition/RGroupGa.cpp, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/SmilesParse/CMakeLists.txt, Code/GraphMol/WedgeBonds.cpp, Code/GraphMol/new_canon.cpp, Code/GraphMol/testPickler.cpp, External/GA/ga/LinkedPopLinearSel.h, azure-pipelines.yml, rdkit/ML/UnitTestBuildComposite.py
Some of this is a response to CI configuration changes.
Adjusting to that ended up resulting in a newer version of clang for the OSX builds and that then required some code cleanup to get rid of some warnings.
I don't think there's anything really substantive here.
=> Update CI, remove some warnings

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Code/GraphMol/ScaffoldNetwork/ScaffoldNetwork.cpp, Code/GraphMol/ScaffoldNetwork/catch_tests.cpp, rdkit/Chem/Scaffolds/MurckoScaffold.py, rdkit/Chem/Scaffolds/UnitTestMurckoScaffold.py
Fixes #6836 
reseting the isotope to 0 for every atom to fix unintended retention of isotope labels during generation of generic scaffolds
=> MakeScaffoldGeneric isotope removal

Code/GraphMol/MolEnumerator/PositionVariation.cpp
#6906 
updated procedure to prevent unnecessary  copying
=> Used const reference to prevent copying in PositionVariationOp::getVariationCounts() (#6906)

ReleaseNotes.md, rdkit/ML/AnalyzeComposite.py, rdkit/ML/BuildComposite.py, rdkit/ML/Composite/__init__.py, rdkit/ML/CompositeRun.py, rdkit/ML/DecTree/__init__.py, rdkit/ML/EnrichPlot.py, rdkit/ML/GrowComposite.py, rdkit/ML/KNN/__init__.py, rdkit/ML/ModelPackage/__init__.py, rdkit/ML/NaiveBayes/__init__.py, rdkit/ML/Neural/__init__.py, rdkit/ML/ScreenComposite.py
I don't think there's any reason for people to be using this code. scikit-learn has been better than anything here for a very long time.
Unless someone has an objection, the plan would be to add the deprecation now, for the 2023.09.3 release, and remove the code in the 2024.03 release
=> Deprecate some of the ancient python-based ML code

rdkit/Chem/Descriptors.py
Fixes #6928 
This fixes the duplicate `SPS` descriptor in `descList`. I thought this might require a conditional check for `SPS`, but I think it was as simple as not manually adding the `SPS`. So, a very minor change. :)
Vin
=> fix duplicate SPS descriptor in Descriptors.descList #6928

Code/GraphMol/MMPA/MMPA_UnitTest.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #6900 
When we remove stereo atoms from a cis/trans bond we should also remove the CIS/TRANS stereo flags since they require stereo atoms for canonicalization.
This might not be the correct fix for this particular problem since we should want:
"C/C=C/N" to fragment with the  into "*/C=C/N" not 
"*C=CN"
However, because we removethe first bond which affects the stereo atoms in the double bond, this causes the errors down stream.
The correct fix is probably to have a custom removeBond that detects this and handles it correctly by adding the new dummy atoms to the stereo bond.
However this fix preserves the current behavior:
```
mol = MolFromSmiles("N/C=C/C")
frag1 = rdMMPA.FragmentMol(mol)
for a,b in frag1:
if a: print(Chem.MolToSmiles(a),end=", ")
else: print(a,end=", " ) …
```
=> Removing stereoatoms requires removing CIS/Trans stereo flags

CMakeLists.txt, Code/GraphMol/GeneralizedSubstruct/CMakeLists.txt, Code/GraphMol/GeneralizedSubstruct/Wrap/testGeneralizedSubstruct.py, Code/GraphMol/MolBundle.h, Code/GraphMol/SubstructLibrary/SubstructLibrary.cpp, Code/GraphMol/SubstructLibrary/Wrap/rough_test.py, Code/GraphMol/SubstructLibrary/catch_tests.cpp, Code/GraphMol/TautomerQuery/Wrap/rough_test.py, Code/GraphMol/TautomerQuery/catch_tests.cpp, Code/GraphMol/Wrap/MolBundle.cpp, Code/GraphMol/catch_molbundle.cpp, Code/MinimalLib/docker/Dockerfile, Code/MinimalLib/scripts/build_rdkitjs.sh, Code/RDBoost/Wrap/RDBase.cpp, External/CoordGen/CMakeLists.txt
- Set the correct minimal cmake version
- some updates to the minimallib build process
- Some fixes to the build/test process for cases where not all options are being installed
- Get things working again with coordgen but without maeparser
- make it possible to check from python if iostreams, serialization, or multithreaded builds were done
=> Fix minimal build, allow building without boost::serialization

Code/GraphMol/MolInterchange/Parser.cpp, Code/GraphMol/MolInterchange/molinterchange_catch.cpp
this fixes #6890 
the DocToMols procedure assumes that the "commonchem" and "rdkitjson" fields are nested json docs, but that is not true. This change updates the procedure to stop relying on that wrong assumption and adds a test for validation.
=> Segfault in JSONToMols when "commonchem" is an int #6890

.azure-pipelines/mac_build.yml, Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #6876 
This allows squiggle bonds in mol blocks to be stereo enumerated.  If we round trip through CXSmiles, the bonds are stereo enumerable so this is intended behavior.
=> Set squiggle bonds to STEREOANY with stereo atoms

CMakeLists.txt, Code/cmake/Modules/CodeCoverage.cmake
Fixes #6941
Updated compiler id comparisons to do a regex comparison against "Clang" instead of doing a direct string comparison. This allows us to match compiler ids like "AppleClang"
=> Some Clang-specific build instructions skip some clang compilers on mac

External/CoordGen/CMakeLists.txt
This should fix #6946.
Also, I don't think we need `MolAlign` to build coordgen, and `maeparser` is no longer a required dependency of Coordgen. Maybe we should split it into a separate directory?
=> Fixes #6946

Code/GraphMol/AddHs.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/test_fixtures.h
This fixes #6944.
The fix is simple: when removing H atoms, just check if they are defining bond stereo, and if so, clear the stereo on the bond.
=> Fixes #6944

Code/GraphMol/Wrap/rough_test.py, rdkit/Chem/__init__.py
This might fix #6945.
It just makes `useLegacyImplementation` depend on the function we use in the C++ code to see if we should use the legacy or the new stereo algorithm. In this way, unless we manually override the argument, we should always use the same algorithm as specified via environment variable.
=> Fixes #6945

Code/GraphMol/FileParsers/PNGParser.cpp
This `zlib.h` include is not required. After the changes in https://github.com/rdkit/rdkit/pull/6814, zlib is only required on windows if building with static libraries, so if the header is not in one of the include directories we have already added (e.g. system or conda directories), and needs to be specified separately, it will break the build.
=> Drop unrequired zlib include which may break the windows build

Code/GraphMol/Canon.cpp, Code/GraphMol/FindStereo.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_canon.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/new_canon.cpp, Code/GraphMol/new_canon.h
adds the option to use atom map numbers in the canonical ranking and exposes that to python
Needs more testing of the new functionality pre-merge
Fixes #6975
=> Fixes #6975

Code/GraphMol/MolStandardize/Fragment.cpp, Code/GraphMol/MolStandardize/Fragment.h, Code/GraphMol/MolStandardize/MolStandardize.cpp, Code/GraphMol/MolStandardize/MolStandardize.h, Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/Tautomer.h, Code/GraphMol/MolStandardize/Wrap/Fragment.cpp, Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/catch_tests.cpp, Code/GraphMol/MolStandardize/testFragment.cpp, Code/GraphMol/MolStandardize/testTautomer.cpp, Code/RDGeneral/CMakeLists.txt
This PR is primarily aimed at getting the various parent operations working in place and to provide multi-threaded versions of them.
=> Add in place and multithread support for more of the MolStandardize code

CMakeLists.txt, Code/DataStructs/ExplicitBitVect.h, Code/DataStructs/SparseBitVect.h, Code/DataStructs/Wrap/DiscreteValueVect.cpp, Code/DataStructs/Wrap/wrap_ExplicitBV.cpp, Code/DataStructs/Wrap/wrap_SparseBV.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp, Code/GraphMol/Fingerprints/Wrap/MHFPWrapper.cpp, Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Conformer.cpp, Scripts/gen_rdkit_stubs/__main__.py, Scripts/patch_rdkit_docstrings/__init__.py, rdkit-stubs/CMakeLists.txt
This PR enables building stubs in both in-tree and out-of-tree builds with `cmake --build . --target stubs` (`make stubs` will also work on *NIX).
This PR also features improvements to the patching script to do a better assignment of overloaded constructor parameters, which results in a number of fixes to docstring parameters which were previously incorrectly assigned or in some cases even re-assigned.
=> Enable in-tree builds and improve overloaded constructor docstrings

Code/GraphMol/Chirality.cpp, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #6981
This fixes the issue by moving the cleanup of the property to the functions where bond stereo detection happens. There's 2 locations, one for legacy stereo and one for the new stereo perception.
=> Fixes #6981

Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/catch_tests.cpp
Fixes #6983
After all the discussion in #6825 about what max to use, we failed to notice that we never passed any max matches argument to `vf2_all` in RecursiveMatcher...
=> Fixes #6983

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #6968
The linear system about the triple bond was confusing the code that matched the ends of the highlight rectangles up.  This just rotates one of the atoms a bit to break the linearity during construction.  Obviously not permanently.
It now looks like this (bonds highlighted only).
I suspect that in the process of discussing and filing the bug, @thwelln's credit for the report has got lost.
=> Github6968

Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Docs/Book/GettingStartedInPython.rst, ReleaseNotes.md, rdkit/Chem/UnitTestDescriptors.py
Also changes the default behavior to only consider heavy atoms when calculating the RMS during pruning
These are both in the spirit of having good defaults.
Neither change affects code which uses the explicit parameter objects.
=> Change the defaults for the conformer generation to be ETKDGv3

Code/GraphMol/GeneralizedSubstruct/CMakeLists.txt, Code/GraphMol/GeneralizedSubstruct/Wrap/rdGeneralizedSubstruct.cpp, Code/GraphMol/GeneralizedSubstruct/XQMol.cpp, Code/GraphMol/GeneralizedSubstruct/XQMol.h, Code/GraphMol/GeneralizedSubstruct/catch_tests.cpp, Code/JavaWrappers/GeneralizedSubstruct.i, Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/GeneralizedSubstructTest.cs
Adds pattern fingerprint capability to `GeneralizedSubstruct` search.
Use `ExtendedQueryMol::patternFingerprintQuery` to get a pattern fingerprint for the query.
Target molecules can get a compatible fingerprint from `patternFingerprintTargetMol`
I have added these functions to the Python and SWIG wrappers.  The SWIG wrapper now exposes full matching by adding a `getSubstructMatch` method to `ExtendedQueryMol`.
Extended C++ tests for fingerprinting and there is a C# test (though no way yet to run it)
=> Added fingerprints to GeneralizedSubstruct search and extended SWIG wrappers

Code/SimDivPickers/HierarchicalClusterPicker.cpp
Fixes #7001
This fixes the cause of the Invariant Violation: accessing an array index out of bounds.
The explanation of the problem is simple: when the last proper removal happens, `j` is incremented one final time, so that `j == removed.size()`, which causes the following iterations to access`removed[j]`, which is out of bounds, and will likely contain some random value. If, by chance, this value happens to be equal to `i`, then an additional and unexpected "removal" will happen, returning a result that will not contain the number of clusters we expect, and will trigger the invariant violation in line 113, right after the call to `cluster()`: https://github.com/rdkit/rdkit/blob/31de6b09fba6cb62f51c6c1253b6744c8a42a2dd/Code/SimDivPickers/HierarchicalClusterPicker.cpp#L112-L113
I wonder if …
=> Fixes #7001

rdkit/Dbase/DbUtils.py
Fixes #7009
In Python 3.12 sqlite connection objects have an `autocommit` attribute with possible values `False`, `True` and `LEGACY_TRANSACTION_CONTROL`. This PR introduces a small change in `rdkit/Dbase/DbUtils.py` so that an explicit commit is executed when the sqlite connection's `autocommit` "flag" has value `LEGACY_TRANSACTION_CONTROL` (the default value in Python 3.12).
Maybe there are better ways to address this issue, I don't find this one particularly pretty, but it's simple and I think should preserve the original behavior.
=> change the handling of autocommit flag to support sqlite3 connections

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, Docs/Book/Cookbook.rst
This is discussed in #6470. 
I believe this fixes #6472, where aromatic bond flags were causing different MolHash ElementGraph and AnonymousGraph hashes for molecules where they are expected to match.
1. The hashed ElementGraphs and AnonymousGraphs are now the same for the test case as expected (and some others that I tried), but they do not necessarily match the MolHash binary CLI hash atom order. I am assuming this is unrelated and a result of RDKit's canonicalization.
2. Thank you for tagging this issue with "Good for Beginners". It was fun to test and (hopefully) offer the correct fix.
Vin
=> Fixes #6472 - remove aromatic bond flags in Molhash anonymous graph

Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp, Code/GraphMol/ForceFieldHelpers/Wrap/rdForceFields.cpp, Code/GraphMol/MolChemicalFeatures/Wrap/ChemicalFeatureUtils.cpp, External/FreeSASA/Wrap/rdFreeSASA.cpp
This PR just removes a few calls to `std::move` that the compiler reports to be redundant.
Warnings were observed with GCC 13.2 and boost 1.81.0
=> fix GCC 13.2 warnings about redundant move in return statement

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #7036
Normally, a wedged bond is altered so there's no gap between it and an incident single bond.  This is not appropriate for a wedge onto a triple bond where they are co-linear, and the reported effect was a consequence.  It's a simple check to skip the process in this case.
There's also some minor tidying suggested by clang.
=> Fixes 7036 - middle line of triple bond meeting wedge

Code/GraphMol/DistGeomHelpers/BoundsMatrixBuilder.cpp, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
In a system with conjugated double bonds, the single bond in the middle can be either "trans" (180 degrees) or "cis" (0 degrees). In a non-cyclic system, the trans configuration is preferred. In a small ring (like benzene), the single bond needs to be cis. However, in a macroycle both options should be possible. However, ETKDG previously only generated the "cis" conformer.
* Previously, `C=C([#1])C([#1])=C` groups in a macrocycle were always cis because of a bug in the bounds calculation. Although the bounds within the main chain (carbon-carbon) allowed cis or trans, the 1-4 bounds of the H atoms were always set to trans, which forces the carbons into the cis position. This change fixes this behavior to allow cis or trans conformations.
* Furthermore, the useMacrocycle14config flag could …
=> Update distance bounds calculation for conjugated double bonds in macrocycles

Code/GraphMol/Atom.cpp, Code/GraphMol/Atom.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/test1.cpp
**Reference Issue**
Fixes https://github.com/rdkit/rdkit/issues/6242
**What does this implement/fix? Explain your changes.**
Implementation of Atom::hasValenceViolation which calls out to the calculation of explicit and implicit valences with strict=True -- which require refactoring this code to create two static functions for those calculations.
The function always returns false for dummy atoms, query atoms, and query bonds.
=> Add Atom::hasValenceViolation (Take 2)

Code/GraphMol/FilterCatalog/CMakeLists.txt
I noticed that the update of FilterCatalog's `Filters.cpp` at cmake configuration time is no longer working. I think this is because line
if(DEFINED ${PYTHON_VERSION_STRING} AND ${PYTHON_VERSION_STRING} VERSION_GREATER "2.6" )
should have been
if(DEFINED PYTHON_VERSION_STRING AND ${PYTHON_VERSION_STRING} VERSION_GREATER "2.6" )
Would it be preferable to just remove the if clause?
=> fix check of python version when updating Filters.cpp

Code/GraphMol/MolInterchange/molinterchange_catch.cpp, Code/GraphMol/SubstanceGroup.cpp, Code/GraphMol/SubstanceGroup.h, Code/GraphMol/catch_sgroups.cpp
This adds error checking to `setAtoms()`, `setParentAtoms()`, and `setBonds()`
It also changes `addAtomWithIdx()`, `addParentAtomWithIdx()`,  and `addBondWithIdx()` to throw a ValueError instead of failing a precondition when a bad index is provided
=> Fixes #5923

.azure-pipelines/linux_build.yml, .azure-pipelines/linux_build_limitexternal.yml, .azure-pipelines/linux_build_py311.yml, .azure-pipelines/mac_build.yml, .azure-pipelines/vs_build.yml, .azure-pipelines/vs_build_dll.yml
The CI builds run on PRs are not the place to find that things have changed in new releases of our dependencies
=> lock the versions of a bunch of stuff used in the CI builds

Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/GeneralizedSubstructTest.cs
Fixes #7069 
Currently, after posting `SWIG_CSharpSetPendingException`, execution of wrapped methods continues.  This can result in memory access errors as seen in #7069.
In SWIG you can use `return $null` to return from the wrapped method immediately after posting `SWIG_CSharpSetPendingException`.  `$null` resolves to the appropriate null value or pointer (or nothing for a void method).  I've added it to all the catch clauses.
=> Update C# exception handling

Code/Numerics/testConrec.cpp
This was caused by a zero-tolerance problem in the setup for one of the tests.
The change is only to the affected test.
=> fixes #7083

Code/GraphMol/Aromaticity.cpp, Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/test1.cpp, Code/GraphMol/QueryOps.h, Code/GraphMol/RGroupDecomposition/testRGroupDecomp.cpp, Code/GraphMol/SmilesParse/test.cpp, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Wrap/rough_test.py
Fixes #6349 
For a query with OR atoms, such as `[C,N]`, we can construct a Mol object from either a SMARTS (via `MolFromSmarts`) or a Mol block (via `MolFromMolBlock`), but the exported SMILES (via `MolToSmiles`) from these two approaches are inconsistent:
```python
m = Chem.MolFromSmarts("[C,N]")
print(Chem.MolToSmiles(m)) # *
mb = Chem.MolToMolBlock(m)
m2 = Chem.MolFromMolBlock(mb)
print(Chem.MolToSmiles(m2)) # C
```
where `*` is the expected output. There is a bug in Mol block parser that always logs the atomic number of the first atom (i.e., `C` in `[C,N]`) as that of the query atom. 
The fix is very straightfoward. When we load the first atom (e.g., `C`), the atomic number of the query atom is set to 6. If there are OR atoms in the brackets (e.g., `[C,N]`), …
=> Fix Mol block parser by resetting atomic number to 0 for COMPOSITE_OR query atoms (#6349)

Code/GraphMol/MolStandardize/Validate.cpp, Code/GraphMol/MolStandardize/Validate.h, Code/GraphMol/MolStandardize/Wrap/Validate.cpp, Code/GraphMol/MolStandardize/test2.cpp, Code/GraphMol/MolStandardize/testValidate.cpp, ReleaseNotes.md
This PR implements a refactoring of the `MolStandardize` validation classes. The changes are mainly related to the reimplementation of `MolVSValidation` as a composite of `ValidationMethod` and the consequent harmonization of the API originally provided by `MolVSValidations` and `ValidationMethod`.
The new implementation should support a better usability of the validation criteria migrated from MolVS (which are this way easier to use directly) without a very significant impact on the existing client code.
The implementation of the python wrappers related to these classes was also streamlined in the process.
=> refactoring of MolStandardize validation module

Code/GraphMol/ChemReactions/Reaction.h, Code/GraphMol/ChemReactions/ReactionDepict.cpp, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp
The calculation of the offset between reactants/products was just wrong.
With the offset corrected, the old default spacing of 2.0 seems quite high, so this also lowers that to 1.0
=> Fixes #7028

README.md
The blog link on the README points to the old blog. Instead, point to the new blog (same link the old blog refers to).
=> chore: fix blog link to new blog location

Code/GraphMol/ChemReactions/CDXMLParser.cpp, Code/GraphMol/ChemReactions/SanitizeRxn.cpp, Code/GraphMol/ChemReactions/SanitizeRxn.h, Code/GraphMol/ChemReactions/Wrap/testReactionWrapper.py, Code/GraphMol/ChemReactions/catch_tests.cpp
previously only reactant templates could be sanitized
the change is enabled by default 
also removes a deprecated usage from the CDXML reaction parser
=> support sanitization of reaction product templates

Code/GraphMol/Chirality.cpp, Code/GraphMol/testChirality.cpp
Fixes #7115 
Small fix to allow 4-coordinated nitrogens to be considered for stereo  in > 3 membered rings
=> Fixes #7115

Code/GraphMol/AddHs.cpp, Code/GraphMol/molopstest.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
Fixes #7123
The fix is very simple: just remove the code that sets the flag. I'm also removing the property we were setting on the atoms, `origNoImplicit`, as it isn't used anywhere else.
After making the change, just one test needs to be updated (the H count flips from explicit Hs to implicit ones).
This is a fairly simple bug, so instead of adding a new test, I'm adding an additional check to one of the tests for `addHs`.
=> Fixes #7123

rdkit/Chem/PandasTools.py, rdkit/Chem/UnitTestPandasTools.py, rdkit/RDLogger.py
Fixes #7019
Allows users to set sanitize in PandasTools.LoadSDF. I describe in #7019 what I hope to change with this PR.
Also an unused import is removed in RDLogger.py. Unsure if it should be part of this PR.
=> Sanitize parameter for LoadSDF (#7019)

Code/GraphMol/RWMol.cpp, Code/GraphMol/catch_graphmol.cpp
Fixes #7128
This fixes the issue by updating the Explicit Hs according to the change in bond orders when we replace a bond. We only care about the case in which the bond order increases, as for a decrease, implicit Hs should be able to compensate the difference.
=> Fixes #7128

Code/GraphMol/CMakeLists.txt, Code/GraphMol/MolOps.cpp, Code/GraphMol/hanoitest.cpp
Fixes #7104
The new implementation of `getMolFrags()` was amazingly inefficient for molecules with a bunch of very small fragments, like a protein with crystallographic waters.
There was some discussion of performance in the comments on the PR, so here are some numbers.
Here's a mol file for a recent protein + ligands + waters I pulled down from the PDB this morning. [pdb_8jhl.mol.txt](https://github.com/rdkit/rdkit/files/14162327/pdb_8jhl.mol.txt) That structure has 128 fragments, most of which are water.
Here's the same structure with the single atom fragments (water and Mg) stripped: 
[pdb_8jhl.stripped.mol.txt](https://github.com/rdkit/rdkit/files/14162369/pdb_8jhl.stripped.mol.txt) That structure only has two fragments.
Here's timing info with v2023.09.3 of the RDKit …
=> Fix a pathological slow case with the new getMolFrags()

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_graphmol.cpp
Fixes #7131
This fixes the issue by not considering wedge/dash bonds when choosing which bonds to flag as `ENDDOWNRIGHT` or `ENDUPRIGHT` around double bonds in `controllingBondFromAtom()`. I also updated `setDoubleBondNeighborDirections()` to not consider these bonds when deciding the order in which double bonds should be assigned stereo directions.
=> Fixes #7131

Code/GraphMol/Canon.cpp, Code/GraphMol/catch_canon.cpp
Fixes #7023 by deleting the check that hits the invariant violation.
This is different from https://github.com/rdkit/rdkit/pull/7065, which just avoided  the issue using the same code as in https://github.com/rdkit/rdkit/pull/6903
=> Fixes #7023

Code/GraphMol/FileParsers/CMakeLists.txt
In #6903,  MolFileStereochem.h was dropped from the CMakeLists.txt file that installed it.
=> Install MolFileStereochem.h again

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h
I forgot to extend the size of the array used to track failure causes after adding a new failure cause.
This removes that problem and ensures that the problem won't arise again.
=> fix a memory overwrite caused by #7098

Code/GraphMol/CMakeLists.txt, Code/GraphMol/Chirality.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_chirality.cpp
deprecates the old version of `addStereoAnnotation()` and creates a new one, named `addStereoAnnotations()` (which is more accurate) in Chirality.h 
I also added this to the python wrappers
=> Fixes #7140

Code/JavaWrappers/ROMol.i, Code/JavaWrappers/RWMol.i
The csharp wrappers are currently not building.  The various `ROMol::MolFrom*DataStream` functions require the `std_unique_ptr.i` SWIG file. 
I also updated the namespace for the raw pointers in `RWMol.i` that end up in functions like `RDKFuncs.SmilesToMol`.
I think I'm going to take the time to write a pipeline for the C# build!
=> C sharp failing to build

Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
This cleans up the bonds that leak when you try to parse (incorrect) SMILES or SMARTS that contain unmatched ring closures. 
Background story:
For ring closures, the parsers create "half bonds" that are attached to a begin atom, but not an end one. These cannot be added to the mol because of the lack of an end atom. When we run `CloseMolRings` it tries to close the rings by adding the end atom with the matching bookmark to these half bonds. For unmatched closures, there's no such atom, so `CloseMolRings` it triggers a parsing failure.
The error:
When `CloseMolRings` triggers the failure, it raises an exception that we catch to print the error message and clean up. But the clean up is faulty: we reset `rest`, which deletes the problematic mol, without deleting the unmatched ring closure …
=> Fix leaking Bonds on unmatched ring closures

Code/GraphMol/RWMol.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/testSGroup.cpp
Fixes #7064
This adds the code required to copy stereo and substance groups when inserting one mol into another.
I'm not quite sure about the bonds in the stereogroups (expecially in the ABS stereo groups), but I thought I should write the code to copy them too, just in case.
=> Fixes #7064

Code/MinimalLib/docker/Dockerfile, Code/MinimalLib/docker/Dockerfile_legacy_browsers
This PR updates the MinimalLib `Dockerfile` Boost version 1.84.0.
The other changes are only cleanup, plus changing some parameters from being hardcoded to being configurable.
- added a few optional configurable parameters to the MinimalLib Dockerfiles (all have defaults)
- updated Boost to version 1.84.0
- removed obsolete `./emsdk update-tags` which was triggering a warning during the build
- `WORKDIR` should always be absolute, so changed `build` to `$RDBASE/build`
- updated the `Dockerfile_legacy_browsers` help text
=> Update MinimalLib Dockerfiles

Code/GraphMol/ChemReactions/ReactionParser.h
I am developping a C++ package using rdkit as a lib and I noticed there is a few missing headers causing a compilation error. This small PR fixes it.
=> Adding missing headers in ReactionParser.h

Code/RDGeneral/RDProps.h
We noticed in a performance test that hydrogen removal was taking a surprising amount of time, with over half in `setVal`:
It looks like the problematic `ROMol::clearComputedProps` call is done every time an atom is removed, which I think means the computed properties should only need to be cleared once. These changes brought the runtime for these particularly large structures from ~25s to ~9s. Here is a smaller/more reasonable example:
```
import time
smiles = "CC[C@@H](C)C[C@H](C)CCCCCCCCC(=O)N[C@H](C[C@@H](O)[C@H](NCCN)NC(=O)[C@H](N12)[C@H](O)CC1)C(=O)N[C@H]([C@H](O)C)C(=O)N3[C@H](C[C@@H](O)C3)C(=O)N[C@@H](C(=O)N[C@@H](C2=O)[C@H](O)CCN)[C@@H](O)[C@H](O)c4ccc(O)cc4"
m = Chem.MolFromSmiles(smiles)
mhs = Chem.AddHs(m)
st = time.time()
Chem.RemoveHs(mhs) …
```
=> Don't reset computed properties if already empty

CMakeLists.txt, Scripts/gen_rdkit_stubs/__init__.py, Scripts/gen_rdkit_stubs/worker.py
While testing the `conda` build of RDKit stubs on Windows using the `rdkit-feedstock` repo, I found a few issues that need to be fixed in the main RDKit repo.
1. A warning caused by backslash separators is issued during installation of Python packages into `PYTHON_INSTDIR`.<br>I have verified that the warning is actually harmless (the `conda` package generated by the build is identical to the one generated replacing backslashes with forward slashes), but I think it is still worth fixing it as it does not look good.
```
[ 97%] Built target SubstructLibrary
[ 98%] Built target rdRGroupDecomposition
[100%] Built target rdSubstructLibrary
Install the project...
-- Install configuration: "Release"
CMake Warning (dev) at cmake_install.cmake:41 (list):
Syntax error in cmake code at …
```
=> Fix a few issues found while attempting to build stubs as part of a Windows conda build

Code/JavaWrappers/ExplicitBitVect.i, Code/JavaWrappers/csharp_wrapper/RDKitCSharpTest/ExplicitBitVectTest.cs
Add some useful `ExplicitBectVect` bitwise operators to the SWIG wrappers.
=> Add some ExplicitBitVect operations to Swig

Code/GraphMol/Conformer.cpp, Code/GraphMol/Conformer.h, Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h
Optimize atom and bond removals
1. add two new private functions, batchRemoveBonds, batchRemoveAtoms
2. minimizes calls to expensive functions, clearComputedProps(true), renumbering atoms/bonds, conformers
3. calls to removeBond queues up atom removals (which didn't happen before, the makes book keeping easier)
=> optimize batch operations when editing molecules

Code/GraphMol/MolStandardize/Charge.cpp, Code/GraphMol/MolStandardize/testCharge.cpp
This PR fixes the neutralization of groups containing halogens in higher oxidation states. The neutralization of the negatively charged oxigen atoms sorrounding the halogen was supposed to happen at most once, but it was actually applied also to the already neutralized group.
The problem addressed by this PR is probably a regression introduced with #7088.
=> Fix Uncharger applying to already neutralized perhalic groups

.github/workflows/documentation-links.yml
Fixes #6849
When a pull request is opened, a preview of the documentation will be created on Read the Docs, and linked to in the PR.
=> Build documentation preview upon opening a pull request

Code/GraphMol/FileParsers/MolSupplier.h, Code/GraphMol/FileParsers/MolSupplier.v1API.h
#7168 seems to be missing the `moveTo()` methods, which might break builds. This adds them back. Also fixes a couple of typos.
----
📚 Documentation preview 📚: https://rdkit--7222.org.readthedocs.build/en/7222/
=> v1 Mol Suppliers missing the moveTo method

Code/DistGeom/DistGeomUtils.cpp, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.cpp, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionPreferences.h
The problem was that ET terms were being applied within the atoms that were in the coordmap. This disables that and adds tighter distance constraints between coordMap atoms when doing the ETK minimization.
=> Fixes #7181

Code/GraphMol/FindStereo.cpp
This simple patch speeds up reading large files when using the new stereo perception.
As an example, I have used protein [1AON](https://www.rcsb.org/structure/1AON) (~59k atoms, ~59k bonds), converted into SD format.
With current RDKit code:
```python3
In [2]: def read_sd():
...:     m = Chem.MolFromMolFile('1AON.sd')
...: 
In [3]: Chem.SetUseLegacyStereoPerception(False)
In [4]: %time read_sd()
CPU times: user 52.3 s, sys: 238 ms, total: 52.5 s
Wall time: 52.3 s
```
After this patch:
```python3
In [1]: def read_sd():
...:     m = Chem.MolFromMolFile('1AON.sd')
...: 
In [2]: Chem.SetUseLegacyStereoPerception(False)
In [3]: %time read_sd()
CPU times: user 5.12 s, sys: 106 ms, total: 5.23 s
Wall time: 5.27 s
```
If I'm understanding correctly what's going on, most of the slowdown is due to …
=> Speed up cleanMolStereo

rdkit/Chem/Randomize.py, rdkit/Chem/UnitTestRandomize.py
We're implementing shuffle / invariance tests for the InChI (https://github.com/IUPAC-InChI/InChI/issues/7).
I was planning on using `RandomizeMolBlock` when I came across #1376.
The current PR is an attempt to bring #1376 over the finish line.
I refactored `RandomizeMolBlock` according to @greglandrum's [suggestion](https://github.com/rdkit/rdkit/pull/1376#pullrequestreview-36938717).
Two things weren't clear two me.
1. The docstring / attribution at the top of `Randomize.py` seems outdated . Should it be updated, and if so, how?
2. Does `test_smiles_canonicalization` belong to the tests? I moved it over from the `if __name__ == '__main__'` block in `Randomize.py`. However, essentially, it doesn't test the randomization. Should I remove the test or move it somewhere else? If so, where?
=> Fix `Chem.Randomize.py`

Code/GraphMol/AddHs.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/RWMol.h
This is a follow up to https://github.com/rdkit/rdkit/pull/7188 -- it looks like there is still quite a bit of time spent on calling clearComputedProps:
These changes improve the runtime of my example from ~9s to ~5.6s. I added an overload to removeAtom because I was having linking issues when trying to make clearProps a default argument, and wanted to make sure this would be a reasonable change before looking further into it.
=> Postpone clearing computed properties until after all Hs removed

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Fixes #7256
A simple fix to prevent the parser from throwing when it find M RAD 0. We shouldn't need to `setNumRadicalElectrons(0)`, since there's nothing that would change it in the atom or bond block, but just in case.
=> Fixes #7256

Code/GraphMol/Chirality.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
`_NonExplicit3DChirality` was introduced in the atropoisomers patch (#6903), but it is not exposed through any header nor Python wrapped. This moves it to `common_properties` so that it is exported through the public header and wrapped.
=> Make _NonExplicit3DChirality a public property

Code/GraphMol/FileParsers/MolSGroupParsing.cpp, Code/GraphMol/catch_sgroups.cpp
Fixes #7246
Easy fix: when parsing the value, if the first thing we see is a space, then assume that the field is empty, since values containing spaces should be double quoted.
=> Fixes #7246

Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/MolSGroupWriting.cpp, Code/GraphMol/FileParsers/TplFileWriter.cpp, Code/GraphMol/MolDraw2D/DrawTextFTSVG.cpp, Code/GraphMol/MolDraw2D/DrawTextSVG.cpp, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp
Nothing fancy here, this just replaces a number of occurances of `std::endl` with `"\n"`
There are a number of places suggesting that `std::endl` should be avoided when the explicit flush that it does isn't actually needed; here's one of them: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rio-endl
I initially implemented this as a global change, but it caused problems with a number of tests and logging (see below), and we aren't logging in performance-critical code, so I went back to mainly changing the places we write files
On the problems with logging in the tests: the problems came up in tests where the logs are captured in other streams (like stringstreams). These are not automatically flushed (unlike `std::cerr` and `std::cout`), so I would have had to rewrite a bunch …
=> remove a bunch of std::endls

Code/GraphMol/DistGeomHelpers/CMakeLists.txt, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Embedder.h, Code/GraphMol/DistGeomHelpers/EmbedderUtils.cpp, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/MolAlign/AlignMolecules.cpp, Code/GraphMol/MolAlign/AlignMolecules.h, ReleaseNotes.md
This should have been done in #5322, but it slipped through the cracks. This fixes that. 
Because it's the right thing to do, this is enabled by default. It can be disabled if people want the old behavior.
=> add option to symmetrize conjugated terminal groups when RMS pruning conformers

ReleaseNotes.md
this hasn't been maintained for years and should remove this for the next release
=> Deprecate legacy molecule drawing code

Code/GraphMol/RingInfo.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/molopstest.cpp
Prompted by @sroughley reporting a failure in his KNIME testing pipeline involving `RingInfo::isFusedRings()`, I reviewed that code and, though I did not manage to reproduce a segfault (`RingInfo::isFusedRings()` uses `std::vector::at()` to access vector elements, so it should never segfault for going out of bounds), I assembled a couple of test cases where the current code would certain yield wrong results.
Here's a PR to fix that.
=> Update ring fusion cache when needed

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
Very small change to fix a canonical SMILES bug in molecules which have ring stereo and multiple fragments.
With this change in place, all of the differences in canonical SMILES generated with 2024.03.1 relative to 2023.09.6 are expected.
=> fixes #7295

CMakeLists.txt, Code/GraphMol/MolDraw2D/CMakeLists.txt, ReleaseNotes.md
=> tag 2024.03 release

Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in, Code/GraphMol/MolStandardize/testNormalize.cpp
This PR updates the reaction patterns defining the normalization of 1,3- and 1,5-conjugated cations, so that they won't apply to compounds where the positive charge is placed on a nitrogen bound to a negatively charged N, P, O, or S. The intention is to prevent the normalization from applying to some functional groups like e.g., diazo groups and azides.
=> restrict the application of 1,3- 1,5- conjugated cation normalization

CMakeLists.txt
This fixes an oversight in #6885: that PR inadvertently completely removed YAeHMOP support from DetermineBonds
=> re-enable yaehmop support in DetermineBonds

Code/GraphMol/Wrap/rough_test.py
#6903 added some instances of keyword arguments in Python function calls that are specified like `sanitize:=False`. I've never seen this done before and it looks like a mistake to me. It seems that these walrus expression assignments actually translate into positional arguments and (what looks like) keyword parameter names have no effect, e.g:
```
>>> def myfunc(arg1, arg2, arg3):
...     print(f"arg1: {arg1} arg2: {arg2} arg3: {arg3}")
...
>>> myfunc(arg3=3, arg1=1, arg2=2)
arg1: 1 arg2: 2 arg3: 3
>>> myfunc(arg3:=3, arg1:=1, arg2:=2)
arg1: 3 arg2: 1 arg3: 2
```
This was not obvious to me, and feels like a potential source of future bugs. Additionally, it breaks Python 3.7 compatibility (not sure if this is officially supported anymore, but it's the only instance of Python 3.8+ syntax …
=> Remove misleading walrus operators

rdkit/CMakeLists.txt
To run the tests for a non-dev install (i.e. with `RDK_INSTALL_INTREE=OFF`) I previously used to do something like this: 
```shell
cmake -D RDK_INSTALL_INTREE=OFF -D CMAKE_INSTALL_PREFIX=$INSTALL_PREFIX [etc...]
make install
export RDBASE=$SRC_DIR
export PYTHONPATH=$INSTALL_PREFIX/lib/python3.10/site-packages
ctest --output-on-failure
```
This runs the tests out of the source directory, but all the RDKit Python imports and libraries are loaded from the installation. However, since the switch to using pytest test discovery in #5916, I see the following error for `pythonSourceTests`:
```
230/230 Test #230: pythonSourceTests ......................***Failed    0.88 sec
ImportError while loading conftest '$SRC_DIR/rdkit/conftest.py'.
__init__.py:6: in <module>
from . import rdBase
E …
```
=> Make ctest run installed tests if RDK_INSTALL_PYTHON_TESTS

Code/GraphMol/Atom.cpp, Code/GraphMol/Atom.h, Code/GraphMol/ConjugHybrid.cpp, Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/Fingerprints/FingerprintUtil.cpp, Code/GraphMol/Fingerprints/FingerprintUtil.h, Code/GraphMol/Fingerprints/catch_tests.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/catch_graphmol.cpp, ReleaseNotes.md, rdkit/Chem/AtomPairs/UnitTestDescriptors.py, rdkit/Chem/AtomPairs/Utils.py
Fixes #7318
Fortunately, we have a good replacement for `Chem.AtomPairs.Utils.NumPiElectrons` we just need to expose and wrap `RDKit::AtomPair::numPiElectrons`.
The small change in `Code/GraphMol/ConjugHybrid.cpp` also fixes the wrong hybridization I mentioned in the issue too.
=> Fixes #7318

Code/GraphMol/Chirality.cpp
This PR deletes some code from `RDKit::MolOps::detectBondStereochemistry` that depends on a temporary "_isStereoAny" bond property that is never assigned.
=> cleanup RDKit::MolOps::detectBondStereochemistry

Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/ChemTransforms/catch_tests.cpp, rdkit/Chem/UnitTestSaltRemover.py
Fixes #7327
The fix is easy: the computed props are cleared in the call to `commitBatchEdit()`, so we just need to return before the batch edits if there's no atoms to delete.
=> Fixes #7327

Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in, Code/GraphMol/MolStandardize/testNormalize.cpp
This PR should hopefully fix an oversight introduced with #7287 (sorry)
=> fix 1,3- 1,5- conjugated cation normalizer transforms

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #7346
This fixes the issue by taking the 4th bond into account if it is available and the first three don't result in an absolute value of `chiralVol` that is above the threshold value.
Also, I think the code before the patch would have ignored wiggly bonds on the 4th neighboring bond, as it would have left the loop after storing the 3rd neighbor.
=> Fixes #7346

Code/JavaWrappers/csharp_wrapper/GraphMolCSharp.i, Code/JavaWrappers/csharp_wrapper/RdkitTests/TestMolStandardize.cs
Adds `MolStandardize.i` to the C# wrapper build.  Includes `Xunit` test.
=> Add MolStandardize to C# wrappers

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/RascalOptions.h, Code/GraphMol/RascalMCES/RascalResult.cpp, Code/GraphMol/RascalMCES/RascalResult.h, Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp, Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py, Code/GraphMol/RascalMCES/mces_catch.cpp
No issue
Consider the pair of molecules
The default RASCAL options give rise to 2 distinct MCESs, with the 2 different amide moieties matching, as in:
They don't both match at the same time, obviously.
Sometimes, for example when looking for pairs of molecules that differ only by a linking group, that's a bit too permissive.  This option only allows atoms to match if they have the same degree (i.e. same number of explicit connections).  In this case the SMARTS returned is
```
[#6&a&D2]1:[#6&a&D2]:[#6&a&D2]:[#6&a&D2]:[#6&a&D2]:[#6&a&D3]:1.[#6&A&D3](=[#8&A&D1])-[#6&A&D3](-[#7&A&D1])-[#7&A&D1]
```
which gives the single match:
=> Add option for RASCAL to restrict atom matching to atoms of same degree

Code/GraphMol/MolStandardize/Charge.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
This PR fixes the behavior for the `MolStandardize::Uncharger` when the `force` option is enabled and the input molecule includes some non-neutralizable negatively charged sites.
In these conditions, with the current implementation, the deprotonation of positively charged sites is not exhaustively performed and instead stops when the molecule reaches an overall neutral state. The proposed changes should fix this behavior and allow the deprotonation to proceed to completion.
=> Fix the Uncharger 'force' option w/ non-neutralizable negatively charged sites

Code/GraphMol/Chirality.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/WedgeBonds.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
This PR adds a default argument to `Chirality::reapplyMolBlockWedging()` so that it may be optionally possible to restore the original wedging also for bonds with type different from single or aromatic (e.g., double bonds with up/down orientation).
A change was introduced with #6903 limiting `Chirality::reapplyMolBlockWedging()` to only reapply wedged bonds to single and aromatic bonds. Without the changes proposed with this PR, validating the original mol file and identifying cases where wedging is assigned to other bond types would be quite impractical and it would basically require duplicating what `Chirality::reapplyMolBlockWedging()` already does.
=> Allow reapplyMolBlockWedging() to restore the original wedging regardless the bond type

Code/MinimalLib/minilib.cpp
This fixes a typo I accidentally introduced in #7194.
=> Fixes typo in minilib: MolToCXSmiles should have read MolToSmiles

Code/GraphMol/ChemTransforms/ChemTransforms.cpp, Code/GraphMol/RWMol.cpp
I came back to #7327, and noticed that there's a performance in the PR that slipped through the review: the `for` loop I added don't use references! This means making copies of vectors, which may become slow. I updated them, and a couple more I noticed in RWMol, to use references.
I also noticed Dan's comment in the PR, and added checks to `commitBatchEdit()`, `batchRemoveBonds()` and `batchRemoveAtoms()` to exit early if nothing is going to be removed.
=> Fix performance issue in PR 7327

Code/PgSQL/rdkit/bfp_gist.c, Code/PgSQL/rdkit/low_gist.c, Code/PgSQL/rdkit/rdkit_gist.c
PostgreSQL 16 got stricter wrt proper Pointer and Datum handling.
Fix developed against 202303.3 and tested with PostgreSQL 10 up to 16.
=> Code/PgSQL: Fix Pointer vs Datum (Compatibility with PG16)

Code/RDGeneral/RDValue-taggedunion.h
Build was failing with Boost 1.85.0:
```
/tmp/rdkit-20240425-44167-eojptu/rdkit-Release_2024_03_1/Code/RDGeneral/RDValue-taggedunion.h:420:19: error: no member named 'numeric_cast' in namespace 'boost'
return boost::numeric_cast<float>(v.value.d);
~~~~~~~^
```
Probably an indirect include in Boost library was removed.
Seen when updating Boost in Homebrew - https://github.com/Homebrew/homebrew-core/pull/169237
=> Include header for boost::numeric_cast

Scripts/gen_rdkit_stubs/__init__.py
This reverts commit `7a050b4b191fb147977cbc3b9490422311bc376a`, as the proper fix was contributed by @pechersky in #7379.
=> Revert "fix #7221 (#7230)"

rdkit/Chem/Draw/__init__.py
Fixes #7378, by setting the docstring to be `r`aw, which escapes the escapes.
The `\x00` characters in the un-raw docstring originally get interpreted as null bytes, while the docstring means for this to be an example. By making the docstring raw, this keeps the desired formatting and does not insert null (or other control) bytes into the file.
=> Fixes #7378, raw docstring to escape null chars

Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp
The logic which was automatically assigning square planar stereo to 4-coordinate atoms was incorrect.
=> Fixes #7300

Code/GraphMol/StructChecker/StripSmallFragments.cpp
fixStructureCheckerBuildError - building Structure Checker fails
the location is/was incorrectly specificed in .../Code/GraphMol/StructChecker/StripSmallFragments.cpp
=> fixStructureCheckerBuildError - fix location of MolFileSterechem.h

Code/GraphMol/QueryOps.h, Code/GraphMol/Wrap/Queries.cpp, Code/GraphMol/Wrap/rough_test.py
No issue
Exposes the QueryOps::replaceAtomWithQueryAtom to Python.  At present it's available in C++ and Java/C# but not Python.
As usual, the Boost::Python has been done by analogy and clueless experimentation.  One day, perhaps I'll understand what I'm doing.
At the same time, fixes a recurring typo on docstrings.
=> Expose replaceAtomWithQueryAtom to Python

Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp, Code/GraphMol/Fingerprints/Wrap/testGenerators.py
FingerprintGenerator.GetOptions() wasn't keeping the underlying generator alive.
The fix is simple.
reported by Andrew Dalke
=> fix a lifetime bug in the fingerprint generator

Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp
Two bugs with a one character change! ;-)
Fixes #7409
Fixes #7414
=> Make CXSMILES writer use the default conformer ID

Code/DataStructs/BitVect.cpp, Code/ForceField/MMFF/DistanceConstraint.cpp, Code/ForceField/MMFF/Params.h, Code/ForceField/MMFF/PositionConstraint.cpp, Code/ForceField/MMFF/StretchBend.cpp, Code/ForceField/MMFF/testMMFFForceField.cpp, Code/ForceField/UFF/AngleBend.cpp, Code/ForceField/UFF/DistanceConstraint.cpp, Code/ForceField/UFF/Inversion.cpp, Code/ForceField/UFF/Params.h, Code/ForceField/UFF/PositionConstraint.cpp, Code/ForceField/UFF/TorsionAngle.cpp, Code/ForceField/Wrap/ForceField.cpp
Some minor changes to modernize Code/ForceField.
=> Cleanup: Force field

Code/GraphMol/Atropisomers.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp, rdkit/Chem/RegistrationHash.py, rdkit/Chem/UnitTestRegistrationHash.py
Fixes #7367
The cause of the issue is simply that we don't consider the `Chem.CXSmilesFields.CX_BOND_ATROPISOMER` SMILES extension when computing the registration hash. Fixing the issue is as simple as adding it to the flags we use.
While working on this, I noticed that `wedgeBondsFromAtropisomers()` is missing a check for ring info, since both `WedgeBondFromAtropisomerOneBond2d()` and `WedgeBondFromAtropisomerOneBond3d` require ring info and call `minBondRingSize()`.
=> Fixes #7367

Code/GraphMol/Chirality.cpp, Code/GraphMol/FindStereo.cpp, Code/GraphMol/catch_chirality.cpp, Docs/Book/RDKit_Book.rst
Adds two conditions in order to allow three-coordinate N to be considered as stereogenic:
1. Must be sp3 hybridized
2. Cannot be involved in a conjugated bond
=> Fixes #7434

Code/GraphMol/Wrap/rough_test.py
This PR fixes a small regression in the compatibility with python 3.12
=> Fix a python 3.12 compatibility issue

Code/GraphMol/SubstructLibrary/Wrap/SubstructLibraryWrap.cpp
Fixes  #7457
Using the equivalent of an infinite number monkeys writing Shakespeare, this patch allows python to free a substructlibrary when the ref count goes to zero.
Why it works, or why it was broken in the first place, I have no idea.
=> Allow the substruct library to be deleted when refcount goes to 0

Code/GraphMol/FileParsers/MaeMolSupplier.cpp, Code/GraphMol/FileParsers/MaeWriter.cpp, Code/GraphMol/FileParsers/MaestroProperties.h, Code/GraphMol/FileParsers/file_parsers_catch.cpp
Maestro Structures adopted RDKit's property name for R group labels, but instead of prefixing it with the standard `i_rdkit_` prefix that is usually applied to integer properties coming from RDKit properties to adapt them to Maestro's property format, it is prefixed with `i_sd_`. This patch adds a few lines of code to handle this in `MaeWriter` and `MaeMolSupplier`.
Also, this patch updates the prefix that is applied to and expected from Maestro properties: oddly enough, Schrödinger's code applies a `[birs]_rdkit_` prefix to (most; see above) properties coming from RDKit, but `MaeWriter` was using `[birs]_rdk_`. This patch updates `MaeWriter` to also use `[birs]_rdkit_` as prefix. I allowed `MaeMolSupplier` to still accept `[birs]_rdk_` for backwards compatibility with potantially …
=> MaeWriter: handle the R group label property and update the Maestro property prefixing

Code/GraphMol/CMakeLists.txt
The atropisomer header is missing is not being installed in the 2024.03.3 release.
=> Install the atropisomer header

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
When working with atropisomers, it's more or less inevitable that we're going to have things like this happen and we need to be able to render them.
This uses the following drawing style for these cases (shown here for aromatic bonds):
(yes, the example molecule is a stupid one... the idea is just to show what the drawing style is)
=> Allow wedged double and aromatic bonds

Code/GraphMol/MolHash/catch_tests.cpp, Code/GraphMol/MolHash/hashfunctions.cpp, ReleaseNotes.md
The logic to define the tautomeric zone for systems like imines was adding an extra bond.
So for this molecule:
we'd get the v2 tautomer hash: `[CH3]-[C]:[C]:[N]:[C]_6_0`, corresponding to this:
After this fix, we get the hash: `[CH3]-[C]:[C]:[N]-[CH3]_3_0`, which corresponds to:
=> Shrink the tautomeric zone for the v2 hash of things like imines

Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/testMolWriter.cpp
This was originally reported by @MariaDolotova.
While the V2000 MDL writer has logic to prevent writing the isotopic label associated to an R-group as a separate `M  ISO` record, the V3000 MDL writer lacks such logic, and hence the R-group atom has a `MASS` record. This is undesired and inconsistent with the V2000 behavior.
This PR corrects that.
Additionally, the decision whether the isotopic label should be written to the MDL output for an atom with atomic number 0 is made based on the presence of the `common_properties::_MolFileRLabel` rather than on the presence of an atom query as previously happened for V2000, which seems a preferrable choice to me as it is less restrictive.
=> Avoid inconsistency between V2K and V3K MDL output wrt isotopic labelling of R groups

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_chirality.cpp, rdkit/Chem/UnitTestInchi.py
Fixes #7509
The issue is caused by the scale of the coordinates: when bond lengths become large enough, the pseudo 3d offset used in `atomChiralTypeFromBondDirPseudo3D()` becomes irrelevant in the volume calculation, leading to this issue.
The fix is to scale the offset based on the bond length. This patch assumes that, while the scale of the coordinates is weird, at least all bonds are not distorted (i.e. they are all scaled the same), so that we can use the length of the reference bond as representative of the bond lengths in the mol (which seems reasonable, since before we assumed all bond lengths were "normal").
=> Fixes #7509

Code/DataStructs/CMakeLists.txt, Code/DataStructs/SparseBitVect.cpp, Code/DataStructs/SparseBitVect.h, Code/DataStructs/SparseIntVect.h, Code/DataStructs/catch_tests.cpp, Code/DataStructs/testDatastructs.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp
If you want to create a max-capacity (for the index type) SparseIntVect or SparseBitVect, you previously got a result which was effectively one bit too small because we use std::numeric_limits<IndexType>::max() to determine the size.
This clears up that problem.
=> Fixes github #7533

rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
This allows us to better explore the space.
Fixes #7516
This still doesn't support atropisomers, but handling that would require code for recognizing potential atropisomeric bonds, which is a rabbit hole we may not want to fall into.
=> Switch to using FindPotentialStereo() in EnumerateStereoisomers

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/MinimalLib/cffi_test.c, Code/MinimalLib/common.h, Code/MinimalLib/common_defs.h, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/tests/tests.js
The current `master` depiction code has a few issues connected with usage of the `useMolBlockWedging` drawing option to depict the wedging as originally specified in the molblock (as opposed to calling `Chirality::reapplyMolBlockWedging` in advance).
The first issue affects all RDKit layers: since the code in `Code/GraphMol/MolDraw2D/DrawMol.cpp` calls `MolDraw2DUtils::prepareMolForDrawing` _before_ `Chirality::reapplyMolBlockWedging`, the kekulization code does not have a chance to try and place double bonds on non-wedged bonds, and hence results in unnecessary double bond wedging.
Here's a reproducible on current `master`:
```
from rdkit.Chem.Draw import rdMolDraw2D
from IPython.display import SVG
mb = """
Mrv2311 05242408162D          
0  0  0     0  0 …
```
=> Fix issues arising from useMolBlockWedging and the new atropisomer kekulization code

Code/JavaWrappers/MolWriters.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/BasicMoleculeTests.java, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/Chemv2Tests.java
As part of #7077 mol writers were moved to `Code/GraphMol/FileParsers/FileWriters.h`, but since `Code/JavaWrappers/MolWriters.i` was not updated accordingly, symbols which used to be available in the `RDKFuncs` module are now missing.
This went unnoticed as there were no unit tests in RDKit for those `RDKFuncs` free functions, since the same functions are available as `ROMol` methods.
However, as there may be Java or C# code using those free functions, I think it would be good to restore them; for example, this was noticed by @manuelschwarze while running KNIME tests on 2024.03.3.
This PR restores the missing symbols and adds a couple of tests to avoid similar regressions in the future.
=> Restore mol writing functions in the RDKFuncs module

Code/GraphMol/MolInterchange/CMakeLists.txt, Code/MinimalLib/docker/Dockerfile
- patch RapidJSON 1.1.0 release backporting a fix from the master branch to avoid a compilation error on newer compilers (fix #7485)
- update MinimalLib Dockerfile to Debian Bookworm and patch RapidJSON in case someone wants to build an older release (fix #7530)
=> Fix #7485 and #7530

Code/JavaWrappers/SubstanceGroup.i, Code/JavaWrappers/csharp_wrapper/RdkitTests/TestSubstanceGroup.cs
Exposes unsigned integer vector properties from substance groups in the C# and Java wrappers as a `getUIntVectProp` method (actually the method is available to all `RDProps` classes.
=> Add getUIntVectProp to SubstanceGroups in SWIG wrappers

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/mces_catch.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h
No issue.
Further testing of the new exactConnectionsMatch option for RASCAL revealed that the MCES sometimes gave incomplete results with different atom orders of the same molecule.
I have also updated the docstring for the C++ MolToSmiles function as it was incomplete.
=> Rascal exactConnectionsMatch bug

Code/GraphMol/MolStandardize/TransformCatalog/normalizations.in, Code/GraphMol/MolStandardize/testNormalize.cpp
This PR fixes one of the "1-3 charge recombination" normalization transformations to prevent the undesired application on two adjacent N-oxide groups.
A similar constraint I think is already in place for the aliphatic case, and this is basically the same, but applying to aromatic rings.
=> fix one case of undesired 1-3 charge recombination

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
The error here was leading to structures with a chiral volume that had the correct sign but which was too small.
@nmaeder pointed out the example that led to this fix
=> ConfGen: fix a logic error in one of the chiral volume tests

Code/DistGeom/ChiralSet.h, Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
This adds code to recognize tetrahedral centers which are involved in more than one ring with < members and be more tolerant when checking their geometries.
=> Fixes #7552

CMakeLists.txt, Code/GraphMol/Bond.h, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/lex.yysmiles.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smiles.ll
1. get the cmake config working with cygwin
2. rearrange the memory layout of the Bond class so that it uses less memory. Unfortunately in the end this doesn't have a concrete effect due to alignment, but it does get us 7 more bytes to use the next time we need to add something to Bond
3. Simplify the SMILES lexer so that stdio is no longer used (I added a similar change to the SMARTS lexer)
Tested on linux; I'm curious to see what happens with the windows CI builds
=> A collection of small improvements from Roger S

rdkit/Chem/nbtests/github4823.ipynb
Imp has been deprecated since Python 3.4 and Importlib is replacing it. In Python 3.12 the module has been removed.
This should build on any version of Python >= 3.4
=> Switch imp to importlib in nbtests

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #7570
The drawing code displays a complex query atom as a "?", but without the map number which means a reaction drawing isn't a true reflection of the reaction, for example.
In the 'Getting Started' guide, for instance, the reaction
`rxn = rdChemReactions.ReactionFromSmarts('[C:1](=[O:2])-[OD1].[N!H0:3]>>[C:1](=[O:2])[N:3]')`
is drawn as
This adds the map number, so that one gets
The 2nd image is the no-freetype version, hence the slightly flakey character positioning.  It was easier for the test case.
=> Add atom map number to complex query atom symbol.

Code/GraphMol/Wrap/props.hpp
Speed up GetPropsAsDict(), especially on mac
I noticed that we have some workflows for which
GetPropsAsDict() is a bottleneck. This function _should be_ pretty
fast, but exception stack unwinding is pretty slow, especially
on Mac. I'd expect conversion to int or double to _often_ fail
for properties with "string" type tag.
I ran this script on my M3 macbook pro:
```
import time
m = Chem.MolFromSmiles('c1ccccc1')
for i in range(100):
m.SetProp(f'foo{i}', f'{i % 5} sdf')
m.SetProp('foo', 'bar')
m.SetIntProp('foo1', 1)
m.SetIntProp('foo1', 123)
start = time.perf_counter()
try:
for i in range (3000):
m.GetPropsAsDict()
finally:
duration = time.perf_counter() - start
print(f'Ran {i} iterations in {duration:.2f} seconds')
```
**Before this change: 100s**
**After this …
=> Speed up GetPropsAsDict(), especially on Mac

Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
Fixes #7585 
Missed for years, this prevents the warning the FilterMatcherBase is already registered.
=> Don't register FilterMatcherBase twice

Code/GraphMol/FileParsers/ForwardSDMolSupplier.cpp
An update to the osx toolchain on conga hit this long standing bug,
=> Fix an out of bounds access in ForwardMolSupplier

Code/GraphMol/CMakeLists.txt, Code/GraphMol/ConjugHybrid.cpp, Code/GraphMol/catch_molops.cpp
This adds an additional condition for an atom to be a candidate for conjugation: it cannot be hypervalent (as determined by it having a non-default valence).
=> Fixes #7556

Code/GraphMol/Wrap/rdmolfiles.cpp
Some of parameters and docstrings in `rdkit.Chem.rdmolfiles` are incorrect e.g. <https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolFromTPLBlock>.
=> fix(rdmolfiles): fix parameters and docstrings

rdkit/Chem/EnumerateStereoisomers.py, rdkit/Chem/UnitTestMol3D.py
Simple fix to handle the case that one end of a "potential stereo bond" doesn't have any controlling atoms.
=> Fixes #7608

Code/GraphMol/MolStandardize/MolStandardize.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
adds a test that all the mol pointers are unique to each of the `InPlace` functions that take a vector of pointers
=> Fixes #7642

Code/GraphMol/FileParsers/MolFileParser.cpp, Code/GraphMol/FileParsers/MolFileWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/RDGeneral/types.cpp, Code/RDGeneral/types.h
This fixes parsing the RBCNT field in mol file atom lines, and adds exporting it.
The existing implementation didn't handle the special "-2" value, and also didn't cap the possible values at 4, as mentioned in the documentation.
=> Fix parsing RBCNT from mol files, and add exporting it

Code/DistGeom/DistGeomUtils.cpp, Code/DistGeom/DistGeomUtils.h, Code/GraphMol/DistGeomHelpers/Embedder.cpp
removing some code duplication by extracting duplicate code into functions.
Also exchanging some for loops containing `push_back` with `vector.insert(...)` and removing `push_back(ForceFields::ContribPtr(contrib))` in favor of  `emplace_back(contrib)`
Added an inline overload for construct3DImproperForceField, all calls in Embedder.cpp have been adapted accordingly.
=> Refactor distgeom minimizations

Code/GraphMol/ChemReactions/ReactionPickler.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp
The logic for pickling reactants and products was not honoring the user-provided property flags.
=> Fixes #7674

Code/GraphMol/DetermineBonds/DetermineBonds.cpp
Simple fix, removes a call to debugMol that we missed earlier.
=> determinBonds: remove call to debugMol that logs to std::cerr

Code/MinimalLib/CMakeLists.txt, Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/cffiwrapper.h, Code/MinimalLib/common.h, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h
Hi, thanks for RDKit! This PR allows the CFFI lib to build successfully with `-DRDK_BUILD_INCHI_SUPPORT=OFF`. It currently fails with:
```text
ld: library 'RDInchiLib_static' not found
```
This produces a smaller shared library (7.9 MB instead of 9 MB on Mac arm64) with simpler licensing for users who don't need InChI support.
=> Add support for building the CFFI lib without InChI

Code/MinimalLib/tests/tests.js
#7698 enables building MinimalLib without support for InChI, so we need to make sure that JS InChI tests run only if InChI support was built in.
=> Only test InChI functionality if it was built into JS MinimalLib

Code/GraphMol/MolStandardize/Pipeline.cpp, Code/GraphMol/MolStandardize/Validate.cpp, Code/GraphMol/MolStandardize/Validate.h, Code/GraphMol/MolStandardize/Wrap/Validate.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/testValidate.cpp
This PR implements an alternative cleanup of the `MolStandardize::Pipeline` workflow in relation to the handling of molecule with no atoms, keeping the `allowEmptyMolecules` option, but moving the conditional logic into `RDKitValidation`.
=> refactor MolStandardize::PipelineOptions::allowEmptyMolecules

Code/PgSQL/rdkit/rdkit_gist.c
Fixes #7493 
This PR includes @ergo70's fix for the RDKitEquals strategy of gmol_consistent and applies the same changes to greaction_consistent.
@ergo70: sorry I couldn't find your branch `ergo70-issue_7493` in github (was it deleted?) and I was for this reason unable to include your original commit objects.
=> fix RDKitEquals strategy of gmol_consistent and greaction_consistent

Code/MinimalLib/CMakeLists.txt
I have just realized that after #7700 the attempt to build `RDKit_minimal.js` fails due to missing symbols:
```
[100%] Linking CXX executable RDKit_minimal.js
wasm-ld: error: CMakeFiles/RDKit_minimal.dir/minilib.cpp.o: undefined symbol: RDKit::Descriptors::Properties::Properties()
wasm-ld: error: CMakeFiles/RDKit_minimal.dir/minilib.cpp.o: undefined symbol: RDKit::Descriptors::Properties::getPropertyNames() const
wasm-ld: error: CMakeFiles/RDKit_minimal.dir/minilib.cpp.o: undefined symbol: RDKit::Descriptors::Properties::computeProperties(RDKit::ROMol const&, bool) const
```
This small PR restores the ability to build `RDKit_minimal.js`.
=> Restore the ability to build RDKit_minimal.js after #7700

Code/DistGeom/DistGeomUtils.cpp, Code/ForceField/AngleConstraints.cpp, Code/ForceField/AngleConstraints.h, Code/ForceField/CMakeLists.txt, Code/ForceField/DistanceConstraints.cpp, Code/ForceField/DistanceConstraints.h, Code/ForceField/MMFF/testMMFFForceField.cpp, Code/ForceField/MMFF/testMMFFForceField.h, Code/ForceField/UFF/Contribs.h, Code/ForceField/UFF/Inversion.cpp, Code/ForceField/UFF/Inversion.h, Code/ForceField/UFF/Inversions.cpp, Code/ForceField/UFF/Inversions.h, Code/ForceField/UFF/Utils.cpp, Code/ForceField/UFF/Utils.h, Code/ForceField/UFF/testUFFForceField.cpp, Code/ForceField/catch_tests.cpp, Code/GraphMol/ForceFieldHelpers/CMakeLists.txt, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionAngleContribs.cpp, Code/GraphMol/ForceFieldHelpers/CrystalFF/TorsionAngleContribs.h, Code/GraphMol/ForceFieldHelpers/CrystalFF/testCrystalFF.cpp, Code/GraphMol/ForceFieldHelpers/UFF/AtomTyper.cpp
New type contribs added for Angle, Distance, Inversion and the `CrystalFF` torsion constraints. 
These are added both to the `DistGeomUtils` as well as to the `UFF/AtomTyper` (inversions)
The Corresponding tests in `ForceField` are adapted to use the new Contribs.
A `catch_tests.cpp` is added for the new contribs.
I did not change any of the wrappers, i think this is something we need to discuss on how to achieve optimal performant code.
=> New contribs for DG

Code/GraphMol/SmilesParse/SmilesWrite.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
Relevant to #4830.  Requested by [@laurenreid1](https://github.com/laurenreid1)
When generating canonical SMILES, the atom maps are temporarily removed so that the atom order is the same as if the atom maps weren't present.
=> Allow atom map numbers to be ignored when generating canonical SMILES

rdkit/Chem/SaltRemover.py, rdkit/Chem/UnitTestSaltRemover.py
Implements #7750
Adds 'useChirality flag to the SaltRemover class configuration options.
The standard behaviour of SaltRemover is to ignore chirality when stripping species from the parent mol, but to store the removed species as they are defined in the 'defnData'. Setting useChirality to True will allow species to be stripped 
Example:
defnData contains maleaic acid and fumaric acid:
OC(=O)\C=C/C(O)=O
OC(=O)/C=C/C(O)=O
With useChirality = False (default behaviour):
For either of OC(=O)C=CC(O)=O, OC(=O)\C=C/C(O)=O, OC(=O)/C=C/C(O)=O
- StripMolWithDeleted removes the species, but returns OC(=O)\C=C/C(O)=O in the deleted species list (stripper ignores stereo in defnData, but returns first occurence of the defnData SMILE in deleted list)
With useChirality = True:
- For OC(=O)C=CC(O)=O, no …
=> add useChirality flag to SaltRemover

Code/RDGeneral/RDValue.h, Code/RDGeneral/testDict.cpp
This small PR fixes `vectToString` such that it outputs valid JSON (i.e., without a trailing comma) such that it can be directly parsed as a JSON string.
@greglandrum As discussed, I have extracted this change out of #7322.
=> Fix vectToString such that it outputs valid JSON

CMakeLists.txt
It seems that the newest versions of CMake may have problems with the `Python3_LIBRARY` variable (we've seen some on Mac with CMake 3.27.1) that was introduced in #7720 (before we used `Python3_LIBRARIES`).
The CMake documentation for `FindPython3` mentions `Python3_LIBRARY` as an "Artifact" (I'm not sure what that is), but it seems that the correct "result" variable is `Python3_LIBRARIES`.
=> Fix issue in #7720

Code/GraphMol/MolDraw2D/DrawMolMCHCircleAndLine.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/MinimalLib/cffi_test.c, Code/MinimalLib/common.h, Code/MinimalLib/common_defs.h, Code/MinimalLib/tests/tests.js
This PR exposes the multi-color highlight functionality to MinimalLib and adds relevant tests.
This code was originally part of #7322 and I have now extracted it to make #7322 easier to review.
I have also added a `PRECONDITION` in `DrawMolMCHCircleAndLine::calcSymbolEllipse` as I incurred in a segfault while testing with out-of-bounds atom indices, and added relevant tests .
=> Expose multicolor highlights to MinimalLib

CMakeLists.txt
Fixes #7776
`Boost_INCLUDE_DIR` is not always set ([more info](https://discourse.cmake.org/t/findboost-difference-between-boost-include-dir-and-boost-include-dirs/855/2)).
=> Use Boost_INCLUDE_DIRS instead of Boost_INCLUDE_DIR

Code/GraphMol/QueryOps.h
Since #7692, including `GraphMol/QueryOps.h` in a .cpp file results in a build error:
```
In file included from /tmp/rdkit-install/include/rdkit/GraphMol/QueryAtom.h:17,
from /tmp/test/rdkit.cpp:15:
/tmp/rdkit-install/include/rdkit/GraphMol/QueryOps.h:866:7: error: ‘class RDKit::HasPropWithValueQueryBase’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
866 | class HasPropWithValueQueryBase {
|       ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
This PR gives `HasPropWithValueQueryBase()` a default constructor and a virtual destructor, which fixes the build issue.
=> HasPropWithValueQueryBase needs a virtual destructor

Code/ForceField/MMFF/TorsionAngle.cpp
Fixes #7671
`calcTorsionCosPhi` was returning `nan` when two adjacent bonds in a torsion are parallel. For example, atoms 37, 38, 39, 42 here:
This change makes the return 0.0 instead so that the minimization doesn't fail. I'm not sure if that is the right thing to do or not.
I also spent some RDKit UGM hackathon time looking into #7781 and #7726 because they had the same error message. I didn't have time to actually fix them, but I believe they are due to the entire gradient being set to 0 causing the linearSearch to return early.
=> Torsion energy calculations are sometimes nan

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/RascalOptions.h, Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp, Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py, Code/GraphMol/RascalMCES/mces_catch.cpp
No issue
The default behaviour in Rascal is to encode bond types as `<atomic number><bond type><atomic number>` where the atomic numbers are for the two atoms involved in the bond.  In the pair of molecules
The MCES returned is [#6]-NCC
where the ring carbon is included in both cases.  You might not want that, so there's a new option in RascalOptions that distinguishes aromatic and aliphatic carbons, such that the MCES becomes NCC.  It is off by default.
The extract from the unit test demonstrates use.
```
opts = rdRascalMCES.RascalOptions()
opts.similarityThreshold = 0.1
opts.exactAtomTypeMatch = True
mol1 = Chem.MolFromSmiles('c1ccccc1NCC')
mol2 = Chem.MolFromSmiles('C1CCCCC1NCC')
results = rdRascalMCES.FindMCES(mol1, mol2, opts)
self.assertEqual(results[0].numFragments, 1) …
```
=> Rascal match exact atom type

External/pubchem_shape/CMakeLists.txt
Currently `pubchem-align3d` fails to build on g++ >=13 because of a missing `#include`.
I have already submitted a PR to the `pubchem-align3d` repo to fix the root issue:
https://github.com/ncbi/pubchem-align3d/pull/1
but here's a patch to fix the issue on the RDKit side until the problem is fixed upstream.
=> Avoid pubchem-align3d build failure on g++ >=13

Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp
Given that those classes cannot be instantiated from Python and currently
```
grep -l FingeprintGenerator -r .
```
in the `rdkit` source tree only yields hits in `./Docs/Book` and `./rdkit-stubs` I would not bother deprecating the old name with the typo and just fix it.
=> Fix typo (Fingeprint -> Fingerprint)

Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp
Small PR to fix duplicate `self` argument in `rdkit-stubs/Chem/rdfiltercatalog/__init__.pyi`.
=> Fixes #7401

rdkit/Chem/__init__.py
Small PR which renames the `m` parameter to `self` in the `GetAtoms` and `GetBonds` lambdas to address #7526.
=> Fixes #7526

rdkit/Chem/Draw/InteractiveRenderer.py
This small PR fixes two issues that I noticed when trying to set a custom size on a specific image through the `data-width` and `data-height` `div` attributes, namely:
- Allow overriding the default image size through individual image options in the InteractiveRenderer
- `float` and `int` attributes should be converted to `str` before calling `setAttribute`
=> A couple of fixes to the InteractiveRenderer Jupyter integration

Code/RDBoost/Wrap/RDBase.cpp
Simple matter to switch to `Py_IsFinalizing()` for python v3.13+
=> Fixes #7731

Code/GraphMol/Atom.cpp, Code/GraphMol/MolStandardize/catch_tests.cpp
A typo in `calculateExplicitValence()` was causing things that should fail not to fail.
Fixing this turned up that we were still accepting two coordinate `[H-]` after the isoelectronic valence fix. We probably should not accept this, but removing it breaks a bunch of tests and I'm reluctant to do this just before a release.
We should revisit whether or not we think accepting `C[H-]C` is a good idea as part of the 2025.03 release cycle.
=> Fixes #7689

Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/vf2.hpp
The cause of the issue seems to be the bad performance of `std::list` in some C++ implementations (probably older ones). For large number of matches, like in the example issue description, this difference may become very large, making the call intractable.
This fixes the issue by replacing `std::list` with `std::vector`. I have benchmarked the change on 3 different platforms using the example script in the issue (maxMatches=1000000).
```
2019 Intel Mac on macOS 14.6.1 / xcode 16: 0.06 minutes
Intel i7-10870H / Ubuntu 22.04 / gcc 12.3.0: 0.35 minutes
Intel w5-2465X / Rocky8 container / gcc 11.3.0: ... never finishes running (I interrupted the run after several minutes).
```
After this patch:
```
2019 Intel Mac on macOS 14.6.1 / xcode 16: 0.03 minutes
Intel i7-10870H / Ubuntu 22.04 / gcc …
```
=> Fixes #7685

Code/GraphMol/CIPLabeler/Digraph.cpp
std::list is almost never the data structure that you want. vector uses fewer allocations, and the data has better locality. This speeds up the CIPLabeler on some protein examples by about 2x (75s to 38s)
=> Simple speed up for CIPLabeler

azure-pipelines.yml
The Mac CI images no longer include conda by default: 
https://github.com/actions/runner-images/issues/9262 
We need to update the mac build scripts to install miniforge ourselves at some point, but before starting that dance, I wanted to get the CI builds working quickly.
=> [CI]: temporarily be explicit about using the macos-12 image

Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/ChemTransforms/MolFragmenter.cpp, Code/GraphMol/DetermineBonds/catch_tests.cpp, Code/GraphMol/FileParsers/PDBParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/FileParsers/molfile_stereo_catch.cpp, Code/GraphMol/FileParsers/testMolWriter.cpp, Code/GraphMol/FileParsers/v2_suppliers_catch.cpp, Code/GraphMol/Fingerprints/catch_tests.cpp, Code/GraphMol/MolEnumerator/enumerator_catch.cpp, Code/GraphMol/MolInterchange/Parser.cpp, Code/GraphMol/catch_graphmol.cpp, Code/GraphMol/test1.cpp, External/INCHI-API/inchi.cpp
I hadn't done a mem tests run in a while.
Most of these are pointers leaking from tests, but there's also a couple of real things there, like the PDB parsing thing or the `combineMol()` one.
Besides these, there's also https://github.com/rdkit/rdkit/issues/7865, and some more leaks I hit in Inchi, but those can't be fixed here (I'm also not sure I build against the last release).
=> Fix some mem errors in 2024.09.1

Code/JavaWrappers/ROMol.i
@greglandrum As you may remember, this is something that we noticed while updating the KNIME depiction nodes. We worked around the missing methods in the current KNIME nodes by creating an `RWMol` copy of the `ROMol`, which is suboptimal for performance reasons.
This PR obviates the problem.
=> Expose three ROMol methods which were not previously exposed to SWIG wrappers

Code/GraphMol/Fingerprints/MorganGenerator.cpp
Fingerprinting is improved via the following changes:
* Neighborhoods are stored in a set rather than a vector, as lookup is the only operation performed
* Removed an extraneous neighborhood lookup that was already covered elsewhere in the code
* Pull vectors out of loops and preallocate where possible
* Use swap on  current and next level invariants.
The aggregate speedup on a random sample of Chembl molecules was about ~60% on radius = 2, and 100% on radius = 3
=> Improve Morgan Fingerprint Performance

Code/DataStructs/BitOps.cpp, Code/DataStructs/ExplicitBitVect.cpp, Code/DataStructs/ExplicitBitVect.h
No issue
Holds the bitset in a unique_ptr rather than a raw pointer.
Adds move c'tor and move operator=.
Some minor tidying.
Technically, this is a breaking change because someone could be uncouth enough to be using dp_bits directly, since it's public.  Maybe it should be made private?
=> Modernise ExplicitBitVect.

Code/GraphMol/CIPLabeler/CIPMol.cpp, Code/GraphMol/CIPLabeler/CIPMol.h
For example, PDB ID 2ZP8 goes from 133s (after #7826) to 53s (this plus #7826) on my M3 laptop.
Boost graph edges (our bonds) cannot be accessed by index, they must be searched for - linearly. This protein only has 27,000 bonds (after addition of explicit hydrogens), but that's still a enough to make `getBondWithIdx()` a rate-limiting step.
For comparison, the sdgr suite does CIP labelling on 2ZP8 in 0.7s, so we're nowhere near the floor (I also don't think that 0.7 is the floor). I'm just proposing some easy fixes while I try to understand this code and figure out a plan.
=> Another 2x performance improvement in CIP labelling

Code/GraphMol/RGroupDecomposition/RGroupDecomp.cpp, Code/GraphMol/RGroupDecomposition/RGroupDecompData.h
Restores a RGD code snippet that was intentionally removed in #7186 because 1. it is unclear 2. it is not tested 3. It introduced an undocumented change in the documented `GreedyChunks` behavior based on an arbitrary threshold. Discussed in #7896.
=> Restore "oops, exponential is a pain" code snippet in the RGD algorithm

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/MinimalLib/cffi_test.c, Code/MinimalLib/tests/tests.js
Small PR to expose preset color palettes to MinimalLib via JSON.
Custom palette could already be loaded via a JSON object as follows:
```
{
"atomColourPalette": {
"7", [1.0, 0.0, 0.0]
}
}
```
Now in addition to the JSON object mapping atomic numbers to RGB(A) tuples, it is also possible to associate the `atomColourPalette` key to a string value chosen among `default, avalon, cdk, darkmode, bw` (all case-insensitive), e.g.:
```
{
"atomColourPalette": "bw"
}
```
=> Expose preset color palettes to MinimalLib through JSON

Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
Fixes #5599 
The `SplitMolByPDB*` functions dereference an `Atom`'s `MonomerInfo*` that may be null if the molecule was not loaded from a PDB. This leads to a `SEGFAULT` in Python.
This change adds a check for non-null `MonomerInfo*` before dereferencing it to avoid this crash.
Added a basic unit test that calls these functions as in #5599
=> Prevent SIGSEGV in SplitMolByPDBResidues

Code/GraphMol/Chirality.cpp
Partial implementation of #7888
Pulled neighbor assignment and counts out of the iteration loop. The idx and count are paired for sorting. Each atom is strided up to 8 bond partners, but only the actual number of partners is 
The bulk of the diff is extracting the counting functionality from the core loop verbatim.
Perf implications are discussed in the issue - but the reported values are for this combined with two followup PRs
=> [IterateCIPRanks] Precompute neighbor indices and counts, sort them together for each atom

Code/GraphMol/Atom.cpp, Code/GraphMol/Atom.h, Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_graphmol.cpp
This fixes two issues, one when calling setMonomorInfo with a nullptr would leak an existing residue, second, the python API would try to dereference a nullptr causing a segmentation fault.
Both are resolved.
=> Fixes #7873

.github/workflows/close_stale_issues.yml
This adds a github action to mark issues/PRs as stale after 90/60 days of inactivity and then close them 14 days after being marked stale if they are still inactive.
I will do a discussions post after this is merged to explain what is going on.
=> auto-close stale issues and PRs

Code/GraphMol/Chirality.cpp
PR 2/3 targeting #7888
At each iteration, the full array of CIP entries is sorted, but in the algorithm, any pair of atoms that previously was not tied is guaranteed to be in the same relative order. So this is actually a problem of re-sorting subsections of the atoms that were tied, rather than re-sorting the full array. This is important since vector comparisons are a large chunk of the runtime.
This PR does the following:
* Sorts CIP entries in place, using a lightweight reference struct so the data itself doesn't need to be moved. 
* replaces the previous generic vector ranking with an implementation that yields pairs of start/end indices that actually need sorting. 
* Iterates over those regions to sort
=> Sort CIP entries in place using a lightweight wrapper, only sort tied entries

Code/GraphMol/Chirality.cpp, Code/GraphMol/catch_chirality.cpp
Fixes #7929
Just clean the `_CIPCode` property when we use `cleanIt=true`.
=> Fixes #7929

Code/GraphMol/Chirality.cpp
Final PR for #7888
Previous PRs have isolated rank sorting to sections of atoms that were previously tied. Since they were previously tied, the CIP entries of previous iterations are guaranteed to be identical, and no longer need to be stored. 
With this change, each iteration no longer increases the length of vectors that need to be compared.
=> Only save the most recent CIP rank for sorting

Code/GraphMol/MolOps.h, Docs/Book/source/rdkit.Chem.rdShapeAlign.rst, Docs/Book/source/rdkit.Chem.rst, External/pubchem_shape/PubChemShape.hpp, External/pubchem_shape/Wrap/cshapealign.cpp
First of a series of PRs with improvements to the docs.
There are no actual code changes here.
A note on docstring formatting: when adding new docstrings for the python wrappers, I've started using the numpy/scipy format (https://numpydoc.readthedocs.io/en/latest/format.html) instead of whatever random thing we were doing before.
I'd suggeste that we adopt this format going forward and switch old docstrings over as time allows.
=> Documentation updates

Code/GraphMol/Canon.cpp, Code/GraphMol/Chirality.h, Code/GraphMol/Depictor/catch_tests.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/NontetrahedralStereo.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/nontetrahedral_tests.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/catch_graphmol.cpp
n/a
- add a ``getMaxNbors(tag)`` utility function to avoid repeated logic in multiple places
- tweak ``getChiralPermutation()`` for handling implicit/missing ligands (uses -1), allow inverse lookup
- use the tweaked chiral ordering in the reading/writing from SMILES
Change how missing/implicit ligands on SP/TB/OH atoms are treated. This does not change the internal RDKit semantics only the to/from SMILES. The missing functionality was ``getChiralPermutation`` needed to support missing ligands and being able to do the inverse look up.
```
Cl[Co@OH1]Cl Cl-Co-Cl trans
Cl[Co@OH1H4]Cl Cl-Co-Cl trans
Cl[Co@OH1](*)(*)(*)(*)Cl Cl-Co-Cl trans
```
This is also useful for SMARTS matching, i.e. matching a partial substructure in a larger octahedral, but will add that another time.
```
SMILES: …
```
=> Improved handling of SP/TB/OH reording in SMILES/SMARTS.

Code/GraphMol/RascalMCES/Wrap/CMakeLists.txt
While working on https://github.com/rdkit/rdkit/pull/7943 I noticed that `pyMolDraw2D` was mentioned twice in the `ctest` tests list. I thought the test had been become duplicated somehow, but it's just that the Python Rascal MCE test is misnamed.
=> Fix misnamed test

Code/PgSQL/rdkit/update_sql/rdkit--4.3.0--4.4.0.sql.in
Duplicate of https://github.com/rdkit/rdkit/pull/7713, which I accidentally closed.
Below is a copy+paste of that PR
---
Updates the script to drop the operator family so the subsequent creation attempt can pass.
I noticed the provided PostgreSQL cartridge upgrade path from 4.3.0 to higher versions does not appear to work.
Example upgrade attempt on on PostgreSQL 15.8, rdkit version 3.8 (Release_2020_03_2) upgrading to rdkit 4.5.0 (Release_2024_03_5).
```
psql (15.8)
Type "help" for help.
postgres=# \dx
List of installed extensions
Name   | Version |   Schema   |                  Description                  
---------+---------+------------+-----------------------------------------------
plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
rdkit   | 3.8     | public     | …
```
=> Fix 4.3.0--4.4.0 sql upgrade script

Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/PDBWriter.cpp, Code/GraphMol/Wrap/SDWriter.cpp, Code/GraphMol/Wrap/SmilesWriter.cpp, Code/GraphMol/Wrap/TDTWriter.cpp, Code/ML/Cluster/Murtagh/Clustering.cpp, Code/RDBoost/python_streambuf.h
This is round 3.
- The change in `Code/RDBoost/python_streambuf.h` that takes ownership of the pointer allows fixing the leaking `streambuf`s in `getTDTWriter()`, `getSmilesWriter()`, `getSDWriter()` and `getPDBWriter()`.
- The changes in `Code/GraphMol/Fingerprints/Wrap/FingerprintGeneratorWrapper.cpp` are due to the `std::vector<std::uint32_t> *`s leaking in `getFingerprint()`.  `customAtomInvariants` and `customBondInvariants` are never cleaned up, but `fromAtoms` and `ignoreAtoms` would also leak if something goes wrong in `getFingerprint()` and an exception is thrown.
- In `Code/GraphMol/Wrap/MolOps.cpp`, there's two fixes: `sb` and `istr` leaking if `parseQueryDefFile()` throws, and `atomCountsV` in `wrapLayeredFingerprint()` also leaking if we either hit the `throw_value_error()` …
=> ... and more mem errors fixed

Code/GraphMol/Chirality.cpp
@greglandrum  a newer Xcode compiler revealed this issue, we need to reserve space before assignment.  It's unclear to my why this didn't show up in the tests.
=> Need to reserve space before assignment

Code/DataManip/MetricMatrixCalc/Wrap/rdMetricMatrixCalc.cpp, Code/ForceField/ForceField.cpp, Code/GraphMol/ChemReactions/Wrap/Enumerate.cpp, Code/GraphMol/Descriptors/Property.cpp, Code/GraphMol/Descriptors/Property.h, Code/GraphMol/Descriptors/RegisterDescriptor.h, Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/Descriptors/Wrap/testMolDescriptors.py, Code/GraphMol/FilterCatalog/Wrap/FilterCatalog.cpp, Code/Numerics/Optimizer/BFGSOpt.h, Code/SimDivPickers/MaxMinPicker.h, Code/SimDivPickers/Wrap/MaxMinPicker.cpp
The final round of leak fixes (and some more). These took longer than the rest because I made the mistake of looking into the Mol Descriptor issues first, which, unfortunately, were not just leaks, but also a couple other issues on top.
In any case, here we have:
- Fixes to leaking objects in  `Wrap/Enumerate.cpp`, `Wrap/FilterCatalog.cpp` and `Wrap/rdMolDescriptors.cpp`: we need to declare those wrappers as `shared_ptr`s, and not plain pointers, or else Python won't take care of cleaning up the new objects it creates.
- in `testMolDescriptors.py`, registering the Python declared `NumAtoms` `PropertyFunctor` was overwriting the C++ functor with the same name that is initialized [here](https://github.com/rdkit/rdkit/blob/cf29f0895fbe7397c38a2e6c0b52f70ab9dd5108/Code/GraphMol/Descriptors/Pro …
=> One final round of mem errors

Code/JavaWrappers/MolStandardize.i, Code/JavaWrappers/gmwrapper/src-test/org/RDKit/MolStandardizeTest.java
`MolStandardize.i` includes `enumtypeunsafe.swg`, which has the undesired side effect of making all `enums` downstream type-unsafe. For example, the `RGroupMatching.java` wrapper changes as follows:
```
/* ----------------------------------------------------------------------------
* This file was automatically generated by SWIG (https://www.swig.org).
* Version 4.2.1
*
* Do not make changes to this file unless you know what you are doing - modify
* the SWIG interface file instead.
* ----------------------------------------------------------------------------- */
package org.RDKit;
public enum RGroupMatching {
Greedy(RDKFuncsJNI.Greedy_get()),
GreedyChunks(RDKFuncsJNI.GreedyChunks_get()),
Exhaustive(RDKFuncsJNI.Exhaustive_get()),
NoSymmetrization(RDKFuncsJNI.NoSymmetrization_get()), …
```
=> Fixes a regression introduced in #7582 which made all SWIG enums become type-unsafe

Code/MinimalLib/CMakeLists.txt, Code/MinimalLib/common.h
This PR also contains small cleanup to MinimalLib `CMakeLists.txt`.
=> Remove deprecation warnings by switching MinimalLib to fingerprint generators

Code/GraphMol/ChemReactions/ReactionFingerprints.cpp, Code/GraphMol/ChemReactions/ReactionFingerprints.h, Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/ChemReactions/catch_tests.cpp, Code/GraphMol/ChemReactions/testReactionFingerprints.cpp, Code/GraphMol/Fingerprints/AtomPairGenerator.cpp, Code/GraphMol/Fingerprints/AtomPairGenerator.h, Code/GraphMol/Fingerprints/FingerprintGenerator.h, Code/GraphMol/Fingerprints/MorganGenerator.cpp, Code/GraphMol/Fingerprints/MorganGenerator.h, Code/GraphMol/Fingerprints/RDKitFPGenerator.cpp, Code/GraphMol/Fingerprints/RDKitFPGenerator.h, Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.cpp, Code/GraphMol/Fingerprints/TopologicalTorsionGenerator.h
This fixes #7521 
There are also a general improvement to the FingerprintGenertors themselves here: adding a ctor that allows them to be constructed from the corresponding `FingerprintArguments` subclasses.
=> Convert reaction fingerprinter to use FingerprintGenerators

.azure-pipelines/mac_build.yml, .azure-pipelines/mac_build_java.yml, azure-pipelines.yml
The macos-12 image we've been using is deprecated
This also bumps the SDK version
This is probably going to take 53 attempts to get it right
=> Move CI builds to macos-14

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp, Code/GraphMol/DistGeomHelpers/testDgeomHelpers.cpp
This was another one of those embarassing ones: the total number of atoms was being used as the denominator in the RMSD calculation, but only the heavy atoms are used to calculated the SSD
=> fixes #8001

Code/GraphMol/MolStandardize/Tautomer.cpp, Code/GraphMol/MolStandardize/Tautomer.h, Code/GraphMol/MolStandardize/Wrap/Tautomer.cpp, Code/GraphMol/MolStandardize/Wrap/testMolStandardize.py, Code/GraphMol/MolStandardize/catch_tests.cpp
This exposes the pieces of the tautomer scoring function to make it easier to adjust from python and other languages.
Example
```
terms = rdMolStandardize.SubstructTermVector()
terms.append(rdMolStandardize.SubstructTerm("C=0", "[#6]=,:[#8]", 1000))
rdMolStandardize.ScoreSubstructs(m, terms) # now == 1000
```
=> Expose tautomer scoring functions to python

Code/ForceField/UFF/TorsionAngle.cpp
This is, basically, the same thing we in for MMFF in #7814 (which fixed #7671), but in UFF this time.
=> Fix potential division by zero in UFF TorsionAngle

Code/GraphMol/MolOps.h, Code/MinimalLib/JSONParsers.cpp, Code/MinimalLib/JSONParsers.h, Code/MinimalLib/cffi_test.c, Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/cffiwrapper.h, Code/MinimalLib/common.h, Code/MinimalLib/jswrapper.cpp, Code/MinimalLib/minilib.cpp, Code/MinimalLib/minilib.h, Code/MinimalLib/tests/tests.js
The JSON parsers allow to expose finer-grained control on sanitization and H atom removal to CFFI and MinmalLib.
This also addresses [a long-standing request in the rdkit-js repo](https://github.com/rdkit/rdkit-js/issues/438).
=> Implemented two more JSON parsers for CFFI and MinimalLib

Code/GraphMol/MolDraw2D/DrawMol.cpp
Another easy fix: if X is too small, then just look at Y to decide the orientation.
=> Avoid division by zero in DrawMol

Code/Numerics/Alignment/AlignPoints.cpp
Only check if we are below the tolerance if `diagNorm` is big enough, else, continue the calculation.
=> Avoid division by zero in AlignPoints

Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp, Code/GraphMol/FileParsers/multithreaded_supplier_catch.cpp
This is a followup to #7763 as discussed with Greg during the UGM hackathon.
* In next(), simply ignore any exceptions from nextCallback.
* In reader(), if readCallback throws, log a warning and proceed using the unmodified record.
* (writer() was already handling exceptions from writeCallback.)
The multithreadedSupplierCatchTest sometimes hangs, and getting a stack trace, I see something involving com.apple.rosetta.exceptionserver ; I'm using an Intel build on an M1 Mac. Google suggest this may have something to do with System Integrity Protection (SIP) on the Mac. I suspect and hope that this is only be a problem for Intel builds on the Mac. I should note that I see the same random hangs with a build before applying my changes! (I was at commit 4c37b03071181007316c306d874f75aa9f5cb7cf …
=> Catch exceptions in MultithreadedMolSupplier callbacks

Code/DataStructs/Wrap/SparseIntVect.cpp, Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/CIPLabeler/rules/Pairlist.h, Code/GraphMol/ChemReactions/MDLParser.cpp, Code/GraphMol/MarvinParse/MarvinParser.cpp, Code/GraphMol/Substruct/test1.cpp, Code/RDGeneral/testDict.cpp
- `Code/DataStructs/Wrap/SparseIntVect.cpp` and `Code/GraphMol/Substruct/test1.cpp`: fix several build waringings about "possibly dangling reference to a temporary".
- `Code/GraphMol/CIPLabeler/rules/Pairlist.h` and `Code/GraphMol/CIPLabeler/catch_tests.cpp`: increase the size of `d_pairing`, as it overflowed when running `pyCIPLabelsValidation`.
- `Code/GraphMol/ChemReactions/MDLParser.cpp`: initialize chiralityPossible, which was passed as a reference to an uninitialized value to `ParseV3000CTAB()` and `finishMolProcessing()` (it would be assigned a value in `ParseV3000CTAB()`).
- `Code/GraphMol/MarvinParse/MarvinParser.cpp`: Fix downcasting `MarvinMolBase` `res` to `MarvinMol`.
- `Code/RDGeneral/testDict.cpp`:  fix some integer overflow issues.
=> Fix some minor issues reported by ubsan and the compiler

External/pubchem_shape/PubChemShape.hpp, External/pubchem_shape/Wrap/cshapealign.cpp, External/pubchem_shape/Wrap/test_rdshapealign.py, External/pubchem_shape/test.cpp
The updated defaults are based on some experiments that @brje01 and I did over the past week.
We may want to tweak these parameters again at some point in the future (and will do a quick writeup of how we got here), but these new defaults produce better alignments thatn the current defaults without completely exploding the calculation time, so I think it's worth getting them out there now.
=> improve defaults for the shape-based alignment

Code/GraphMol/MMPA/MMPA.cpp, Code/GraphMol/MMPA/MMPA.h, Code/GraphMol/MMPA/MMPA_UnitTest.cpp
Shifting negative numbers is undefined behavior.
This fixes the issue by shifting the absolute value of the charge, and setting bit 30 (which is unlikely to be touched by any of the previous shifts) if the value was negative.
=> Fix shifting of a potentially negative number

External/pubchem_shape/Wrap/cshapealign.cpp
--
The doc string for the rdShapeAlign.AlignMol function had a small spelling mistake: The variable name is opt_param not optParam.
--
=> fixing the doc string in the shape alignment code

Code/GraphMol/Depictor/RDDepictor.h
The explicit default constructor actually blocks the other defaults. It also means this is no longer a "plain struct", and so designated initializers aren't available.
I wanna be able to do:
Compute2DCoordParameters params{.useRingTemplates = true};
Or even:
RDDepict::compute2DCoords(*mol, {.useRingTemplates = true};
I know that we haven't moved the RDKit code to C++20 - but I'm using it from C++20.
=> Remove explicit default constructor from Compute2DCoordParameters

Code/GraphMol/Abbreviations/Wrap/rdAbbreviations.cpp
Discussion #8044
Adds some extra documentation explaining the format of the abbreviations table.
=> Improve doc string for ParseAbbreviations in python wrapper.

Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/props.hpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Code/GraphMol/Wrap/rough_test.py
Fixes #4570 
It turns out that any Boost python function that has a signature
```
T func(const char * value)
```
will segfault when called with
```
func(None)
```
Switching to:
```
T func(const std::string &value)
```
is the easy solution here as boost will not permit the type cast.  We should probably have a once over for char * in exposed functions.
=> Fix #4570 Segfault on Property Getters/Setters

Code/GraphMol/MolDraw2D/AtomSymbol.cpp, Code/GraphMol/MolDraw2D/AtomSymbol.h, Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/DrawMol.h, Code/GraphMol/MolDraw2D/catch_tests.cpp
This came up in discussion #8044.
If 2 atom labels are seen to clash, the orientation of one or the other is changed to try and fix it.
So
becomes
Probably it could be a bit better, such that the upper methyls went up rather than down but that seemed like a bit more effort than is warranted by the frequency that the issue occurs.
=> Resolve clashing atom labels in 2D drawing

Code/GraphMol/SynthonSpaceSearch/SynthonSet.cpp, Code/GraphMol/SynthonSpaceSearch/SynthonSet.h, Code/GraphMol/SynthonSpaceSearch/SynthonSpaceFingerprintSearcher.cpp, Code/GraphMol/SynthonSpaceSearch/fingerprint_search_catch_tests.cpp
No Issue
When doing a fingerprint search in synthon space, the connector patterns for the query fragments and synthons need to match, but the former weren't being compared with the right thing.
This should make the search slightly quicker as it does a better screen out of things that don't need a full check.
=> Synthon search fp bug

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/mces_catch.cpp
No issue
When comparing fragments (such as when search a synthon space by Rascal similarity) you might get partial aromatic rings in both fragments.  The default setting of completeAromaticRings means that they won't match.  This change allows for the case where bonds that are marked aromatic but not in rings to be matched.
=> Allow fragments of aromatic rings to match in RascalMCES

rdkit/Chem/Draw/IPythonConsole.py
This started with adding the convenience function `IPythonConsole.drawMols3D()` (a cleaned up version of something I use all the time), then led to adding some additional docs, and finally fixing a bug (#8082) that I discovered along the way.
=> Add drawMols3D() and improve documentation for IPythonConsole

External/YAeHMOP/EHTTools.cpp
Creates the temp files in the system temporary directory instead of locally and gives them random names.
We might think about moving the RAII tempfile class somewhere else so that it's usable from other code
=> Fixes #8092

Code/GraphMol/DistGeomHelpers/Embedder.cpp
> [!NOTE]
> The authors of this change are: Akvilė Žemgulytė with work done in Google Deepmind. I am porting this with their approval, and will be addressing any comments from reviews here.
Before the change, matching after conformer generation was done always despite the fact that it is's only used if pruning threshold for conformer similarity is provided. After the change, we check if the pruning threshold will require us to check for similarity and only do matching in that case. Matching can be very expensive for some molecules, so avoiding it when not needed will improve the performance of conformer embedding.
=> Avoid expensive matching in conformer generation if it's not needed.

Code/RDGeneral/StreamOps.h
No issue
The std::string specialisations of streamRead and streamWrite did a raw read/write of the string length, rather than use the endian-aware versions.
It's been this way since at least 2017 so probably not a big deal.  There's no test because of that and also because it is tested indirectly all over the place.
There's been a re-formatting as well, which wasn't intentional.  I run Clang-format on saving.  The changes are round about line 268.
=> Use endian-aware read/write for length of string.

Code/GraphMol/Substruct/SubstructMatch.cpp, Code/GraphMol/Substruct/SubstructMatch.h, Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/catch_tests.cpp, Code/GraphMol/Wrap/Mol.cpp
This adds an option to the substructure searching code to allow specified features in the query to match unspecified features in the molecule. The option is disabled by default so that current behavior is not changed.
Current behavior with `useChirality` is true:
| query | molecule | matches? |
|---------|--------------|---------------|
|`C[C@](F)(Cl)Br` | `C[C@](F)(Cl)Br` |  yes |
|`C[C@](F)(Cl)Br` | `C[C@@](F)(Cl)Br` |  no |
|`C[C@](F)(Cl)Br` | `C[C](F)(Cl)Br` |  no |
And when `useChirality` and the new `specifiedQueryChiralityMatchesUnspecifiedChirality` option are both set:
| query | molecule | matches? |
|---------|--------------|---------------|
|`C[C@](F)(Cl)Br` | `C[C@](F)(Cl)Br` |  yes |
|`C[C@](F)(Cl)Br` | `C[C@@](F)(Cl)Br` |  no |
|`C[C@](F)(Cl)Br` | `C[C](F)(Cl)Br` |  yes | …
=> allow specified chiral features to SSS match unspecified features

Code/MinimalLib/cffiwrapper.cpp, Code/MinimalLib/cffiwrapper.h, Code/MinimalLib/tests/tests.js
- `str_to_c()` should initialize len to 0 even if memory allocation fails
- `str_to_c()` should check the ptr returned by malloc for non-nullness before using it
- change `has_coords()` `mol_pkl` parameter to `const`
- use `assert.equal` in JS tests where possible
=> Minor MinimalLib cleanup

Docs/Book/GettingStartedWithContributing.md
Builds on #7813
Explains how to build RDKit documentation locally, on the page `Getting Started with Contributing to the RDKit`.
=> Add section `How to Build RDKit Documentation Locally`

Code/GraphMol/Wrap/Mol.cpp
Note that "Atom query options are given in the rdkit.Chem.rdqueries module"
=> GetAtomsMatchingQuery: Tell where to find query options for

Docs/Book/GettingStartedWithContributing.md
Explain how to run doctests locally.
CI runs take a long time (90+ minutes), so running doctests locally can shorten documentation development cycles.
=> Explain how to run doctests locally

Code/GraphMol/Wrap/Conformer.cpp, Code/GraphMol/Wrap/rough_test.py
Fixes a weird bug in Conformer.SetPositions when you've provided a strided numpy array - previously SetPositions assumed that the provided numpy array used contiguous-C stride patterns.
A realistic time you could hit this would be if you were playing with rotational matrices:
```python
pos = conformer.GetPositions()
pos = (rotmat @ pos.T).T
conformer.SetPositions(pos)
```
see also:
https://numpy.org/doc/2.1/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray
=> fix SetPositions when using strided numpy array

Code/GraphMol/DistGeomHelpers/catch_tests.cpp
when building on ARM64 systems, the DistGeomHelper test (catch_test.cpp) generates two errors where the returned value is just slightly outside the expected range.
The expected values were increased slightly.
=> relax two tolerances for ARM64 builds

Code/GraphMol/Substruct/SubstructUtils.cpp, Code/GraphMol/Substruct/catch_tests.cpp
Straightforward fix to make only conjugated double and single bonds match aromatic bonds
=> Fixes #8162

rdkit/Chem/Draw/IPythonConsole.py
Fixes #8165
Ensures that `__sssAtoms` is also used to highlight structure, when `_repr_html_ ` is used, similar to how it is works with  `_repr_svg_ ` and `_repr_png_ `
=> Unify Mol rendering in IPython

Code/GraphMol/FileParsers/MolFileStereochem.cpp, Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #8177
The new atropisomer code requires 2D coordinates, but that is done before missing 2D coords were being created  in the drawing pipeline.  I've moved that to earlier.
On my Mac, the tests complain about the hash codes for testWedgeNonSingleBonds-*.svg files.  I have done a diff on them against those produced by the current master and the files are identical.  I don't know what that means, but this PR has not affected those pictures.
=> Fix for 8177 - bad conformer if prepareMolsBeforeDrawing is false and unspecifiedStereoIsUnknown is true

Code/GraphMol/SmilesParse/SmartsWrite.cpp, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smatest.cpp, Code/GraphMol/Substruct/catch_tests.cpp
Fixes #7944
This converts smarts / and \ to match single or aromatic bonds with the appropriate bond direction.
=> Simple fix to allow aromatic CIS/TRANS SMARTS to match molecules

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Allows SIGINT to be handled in conformer generation.
This is most relevant from Python, where Ctrl-C didn't do anything at all.
If we're ok with this pattern, I will apply it to a few more examples where we have long-running calculations in C++ that are called from Python
=> support Ctrl-C in conformer generation

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/RascalResult.h, Code/GraphMol/RascalMCES/mces_catch.cpp
Fixes #8200
After singleLargestFrag has been applied, re-sorts the results by size and takes out any duplicates and any that are now smaller than the largest one.
=> Trim results after singleLargestFrag = true applied.

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #8213
Uses the panel width rather than the full canvas width when drawing reactions.
Now gives this for the test code given in the issue.
Will merge this in when the other drawing PRs go through.
=> Fix reaction panel bug.

Code/ForceField/UFF/AngleBend.h
Having a look at the paper and the code, there is a typo in the docstring.
n=4 for square-planar and octahedral coordination environments.
=> Fix typo in documentation

Code/DistGeom/DistGeomUtils.cpp, Code/ForceField/MMFF/AngleBend.cpp, Code/ForceField/MMFF/AngleBend.h, Code/ForceField/MMFF/BondStretch.cpp, Code/ForceField/MMFF/BondStretch.h, Code/ForceField/MMFF/Nonbonded.cpp, Code/ForceField/MMFF/Nonbonded.h, Code/ForceField/MMFF/OopBend.cpp, Code/ForceField/MMFF/OopBend.h, Code/ForceField/MMFF/StretchBend.cpp, Code/ForceField/MMFF/StretchBend.h, Code/ForceField/MMFF/TorsionAngle.cpp, Code/ForceField/MMFF/TorsionAngle.h, Code/GraphMol/ForceFieldHelpers/MMFF/Builder.cpp, Code/GraphMol/ForceFieldHelpers/MMFF/testMMFFHelpers.cpp, Code/GraphMol/ForceFieldHelpers/catch_tests.cpp
Previously, a separate contrib had been added for each common term. Each of these required a separate allocation, and a separate dynamic dispatch on call. This change moves to a struct-of-arrays style, making data access contiguous and drastically reducing the number of calls.
Performance gains vary based on system size, between 4% and 8% on systems we've benchmarked, with more gains for larger systems.
=> Condense MMFF Contribs into single contrib per type.

Code/DistGeom/DistViolationContribs.cpp, Code/DistGeom/DistViolationContribs.h
Optimizing DistViolationContribs to improve running time for conformer generation. Code changes inlcuding:
1. Replaced lambda functions with inline functions for DistGeom::distance2 and DistGeom::distance to improve performance.
2. Added two new parameters, ub2 (squared upper bound on the distance) and lb2 (squared lower bound on the distance), to DistViolationContribsParams with default values, initialized in the constructor function.
3. Updated DistViolationContribs::getEnergy and DistViolationContribs::getGrad to utilize the new ub2 and lb2 parameters, avoiding repetitive calculations of squared bounds and improving overall performance.
We benchmarked the performance of our optimized DistViolationContribs against the current RDKit implementation. Our benchmarking involved two datasets: …
=> DistViolationContribs optimization

ReleaseNotes.md, rdkit/Chem/Pharm2D/Generate.py, rdkit/Chem/Pharm2D/UnitTestUtils.py, rdkit/Chem/Pharm2D/Utils.py
Fixes #8207
Remove `GetUniqueCombinations`, use instead `GetUniqueCombinations_new` for improved speed; remove `GetUniqueCombinations_new`'s unused and uncalled parameter `which`. Update related tests.
This PR makes the following choices; alternatives are noted:
- Removes the old function `GetUniqueCombinations` to prevent its use in the future; that old function could instead be kept.
- Keeps the name `GetUniqueCombinations_new` to indicate that it's the new algorithm; the name of the new function could be changed to `GetUniqueCombinations` to prevent confusion over why there's a function with the prefix `_new` and no function without that prefix.
=> Use GetUniqueCombinations_new instead of GetUniqueCombinations

Code/GraphMol/Aromaticity.cpp, Code/GraphMol/catch_adjustquery.cpp
Fixes #8256.
The issue is in `countAtomElec()`, which now returns a different electron count for the ring C atom connected to the N atom, than before #8256 was merged. 
The cause of this is the "single or aromatic" query that is added since #8256. This query is not caught by `isBondOrderQuery()` (a "single or aromatic" query is definitely a bond order query, even if a complex one), and causes `QueryBond::getValenceContrib()` to return 0, as query bonds don't contribute to valence. This means that `countAtomElec()` discounts the bond from the degree, which prevents the aromatization of the ring.
This patch updates `isBondOrderQuery()` to first check the bond order: if the bond is "real" (i.e. it has a non-zero order), and if that's not the case, then check if it's a bond order query bond …
=> Fixes #8256

Code/MinimalLib/docker/Dockerfile
@greglandrum This PR restores functionality of the MinimalLib Dockerfile and switches exception handling to native WebAssembly exception handling [which has much better performance](https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-based-support) than the legacy JS handling. I have been building MinimalLib with `-fwasm-exceptions` for the past 2 years and I never incurred into problems.
- bump `boost` version to `1.87`
- fetch `boost` sources from `archives.boost.io`
- build in `/src` rather than in `/opt`
- build `freetype` from source with `-fwasm-exceptions` support as the emscripten port on GitHub is outdated and archived
- build RDKit with `-fwasm-exceptions` support as performance is significantly better than with `DISABLE_EXCEPTION_CATCHING=0`
=> Restore functionality of the MinimalLib Dockerfile and improve exception handling performance

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/RascalOptions.h, Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp, Code/GraphMol/RascalMCES/Wrap/testRascalMCES.py, Code/GraphMol/RascalMCES/mces_catch.cpp
No issue.  Requested by Lauren Reid of MedChemica.
Normally the lower bound on the clique size is calculated from the similarityThreshold.  Sometimes it's convenient to specify it directly.
=> Rascal: Add option to specify minimum clique size directly.

Code/MinimalLib/docker/Dockerfile
This addresses https://github.com/rdkit/rdkit/pull/8267#issuecomment-2656454454
=> Revert Dockerfile to JavaScript-based exceptions (with an option for switching to native WASM)

Code/GraphMol/RascalMCES/RascalResult.cpp, Code/GraphMol/RascalMCES/mces_catch.cpp
Fixes #8246
The code that corrects the output SMARTS to remove atomic numbers >= 110 wasn't dealing with the case where the ringMatchesRingOnly option causes a &R addition to the SMARTS for the atoms in question.  It now does.
=> Rascal left some high atomic numbers in the output SMARTS

Code/GraphMol/MolDraw2D/DrawMol.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DHelpers.h, Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, Code/GraphMol/MolDraw2D/test1.cpp, ReleaseNotes.md
It is very often difficult to distinguish between atom and bond indices when both are displayed at the same time.
This changes that by adding new parameters to control the color of the atom and bond indices separately and to make them, by default, different.
Here's what the default behavior looks like when this PR is applied:
=> MolDraw2D: add separate colors for atom and bond annotations

Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/mces_catch.cpp
Fixes #8255
In the singleLargestFrag = true option, the initial sort of the results should have been in descending order of number of bonds and number of atoms but was ascending so the removal of smaller hits failed.
Doh!
=> Initial Rascal results sort the wrong way round on number of atoms and bonds.

Code/GraphMol/ChemTransforms/MolFragmenter.cpp
No issue
MolFragmenter rejects dummyLabels that are longer than bondIndices with a PRECONDITION.  It is not an error if there are more dummyLabels than bondIndices, as the extra are just ignored.  When fragmenting a molecule multiple times with different numbers of bonds, as in the SynthonSpaceSearch, it's very convenient to have one set of dummyLabels that's as large as will ever be needed that can be used for all fragmentations.  This PR relaxes the PRECONDITION so this is allowed.
Whilst in the area, I have changed the use of boost::uint64_t to std::uint64_t and updated a couple of bond traversals to use the modern idiom.
=> Tweak mol fragmenter

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/Fingerprints/fpgen_catch_tests.cpp, External/INCHI-API/inchi.cpp
I ran the tests under asan again, and found some issues.
Besides the issues patched here, it's worth mentioning that the INCHI code has become way more leaky in v1.07.2: even after the attached fixes, running `testInchi' now leaks about 20 mb memory.
=> Some mem fixes.

Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Apparently, the basinThresh was not exposed to python.
This adds  `basinThresh` in the `PyEmbedParameters`
=> Expose basinThresh to the python layer

Code/SimDivPickers/pickersCLI.cpp
Reading up to 327666 bytes into a buffer of size 32768 is not good. 
`fgets` reads size-1 bytes and writes `\0` after it, so we should be fine with `sizeof(buffer)` here, which also more resilient to future errors than any duplicated value.
=> Fix buffer size in pickersCLI.cpp

.azure-pipelines/linux_minimal_build.yml, Code/MinimalLib/docker/Dockerfile_CI, azure-pipelines.yml
This adds a new CI job which does a build of the minimallib docker image.
The amount of duplicated code in the new Dockerfile and the old one is not great, but the docker mechanisms for combining files are considerably more complicated and would require some refactoring. Maybe someone will have time and motivation to work on that in the future, but it doesn't seem critical
=> try adding a CI job to build the minimallib docker image

External/INCHI-API/inchi.cpp
I missed this one in #8276. It leaks about 40 kb of data from the InChI structure when there's an illegal bond type.
=> Another mem leak fix to the InChI conversion

Code/GraphMol/FindStereo.cpp, Code/GraphMol/SmilesParse/catch_tests.cpp
when using the new (non-legacy) stereochemistry, the chirality in `C[C@H]1C[C@@H](C)C[C@@H](C)C1` (trimethyl cyclohexane) is lost.  These three chiral centers are evenly placed around the ring and should be retained.
There was already code to deal with two chiral centers on ring that are opposite to each other (even membered rings).  THis fix extends that to include 3 evenly spaced chiral groups (or potential chiral groups) around a ring whose size is divisible by 3.
This also applies to `C[C@H]1C[C@@H](C)C[C@@H](C)C1 |o1:1,o2:6,o3:3|`.  This is the same mol but with enhanced stereo chemistry.
=> trimethylcyclohexane chirality error

Code/GraphMol/RGroupDecomposition/RGroupFingerprintScore.cpp, Code/JavaWrappers/MolStandardize.i
The `MolStandardize` methods that return molecules return raw pointers.  This PR wraps those using `%newobject` to prevent memory leaks. 
Also includes a small change to RGD logging.
=> Fix memory leaks in MolStandardize SWIG Wrapper

Code/GraphMol/FileParsers/FileWriters.h, Code/GraphMol/FileParsers/MaeWriter.cpp, Code/GraphMol/FileParsers/PDBWriter.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, ReleaseNotes.md
`MaeWriter` didn't throw on errors, it was just returning an empty string when an error happened. We have now decided that it should throw, instead.
The change in `PdbWriter` avoids an unnecessary downcast from `ROMol` to `RWMol`.
=> Make MaeWriter to throw on errors.

Code/GraphMol/FileParsers/Mol2FileParser.cpp, Code/GraphMol/FileParsers/file_parsers_catch.cpp, Code/GraphMol/MolOps.cpp, Code/GraphMol/catch_molops.cpp
In the current master the logic in `cleanupOrganometallics()` for converting single bonds from hypervalent atoms to metals into dative bonds essentially doesn't work for carbon.
For example, eta-3 propene represented with the SMILES `[CH2-]1-[CH]2=[CH2]3.[Fe]123`:
Should be converted to:
Even worse is the handling of this: `[cH]12[cH]3[cH]4[cH]5[cH]6[cH]17.[Fe]234567`, which ends up losing the aromatic bonds:
It should be converted to:
This fixes that problem.
There's also a change to disable `cleanupOrganometallics()` when parsing mol2 files. Given the semantics encoded by the atoms types on those files, this kind of cleanup operation doesn't really make sense for them.
Fixes #8312
=> Fix the way carbon is handed in cleanupOrganometallics()

Code/GraphMol/AdjustQuery.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_adjustquery.cpp, ReleaseNotes.md
In current RDKit releases if you call AdjustQueryProperties() with `makeAtomsGeneric` set, the other query adjustments will not performed to the atoms:
```
In [2]: m = Chem.MolFromSmiles('C1CC1OC')
In [3]: ps = Chem.AdjustQueryParameters()
In [4]: Chem.MolToSmarts(Chem.AdjustQueryProperties(m,ps))
Out[4]: '[#6&D2]1-[#6&D2]-[#6&D3]-1-[#8]-[#6]'
In [5]: ps.makeAtomsGeneric = True
In [6]: Chem.MolToSmarts(Chem.AdjustQueryProperties(m,ps))
Out[6]: '*1-*-*-1-*-*'
```
This PR fixes that, so that we get the following:
```
In [2]: m = Chem.MolFromSmiles('C1CC1OC')
In [3]: ps = Chem.AdjustQueryParameters()
In [4]: Chem.MolToSmarts(Chem.AdjustQueryProperties(m,ps))
Out[4]: '[#6&D2]1-[#6&D2]-[#6&D3]-1-[#8]-[#6]'
In [5]: ps.makeAtomsGeneric = True
In [6]: …
```
=> apply query adjustments when makeAtomsGeneric is enabled

Code/GraphMol/Atom.h
This is an edge case that I've hit with MSVC VC v14.29.30133 compiler.
It seems there's an ambiguity of this `friend operator<<` declaration: if the compiler has seen a `::Atom` `class` or `struct` declaration (even a forward declaration) before including this header, it seems that the VC compiler will prefer that declaration to the `RDKit::Atom` one where this declaration is made. It will trigger a build error like this one:
```
my_code.cpp
..\rdkit-Release_2024_09_5\include\rdkit\GraphMol/Atom.h(79): error C2063: 'operator <<': not a function
```
This patch seems to resolve the ambiguity and fix the issue.
=> Fix potential build error under MSVC

Code/GraphMol/AddHs.cpp, Code/GraphMol/MolOps.h, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py, Code/GraphMol/catch_graphmol.cpp
This does not change the default behavior of the code, but instead introduces a new option to AddHs that allows adding Hs to query atoms to be toggled off.
Rather than adding YA parameter to the standard AddHs call, I introduced an `AddHsParameters` struct and put the new option there.
=> Fixes #8304

Code/GraphMol/MolDraw2D/DrawMolMCHCircleAndLine.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
`MolDraw2D::drawString()` now uses the current drawing color. Previously it would always use black
This also changes the exception type that the multicolor highlighting code throws when it gets bad user input for atom/bond indices to a ValueError (previously it was a PRECONDITION)
=> Feat/use draw color in drawString()

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/rdkit.control, Code/PgSQL/rdkit/rdkit.h, Code/PgSQL/rdkit/rdkit.sql.in, Code/PgSQL/rdkit/rdkit_io.c, Code/PgSQL/rdkit/sql/rdkit-91.sql, Code/PgSQL/rdkit/update_sql/rdkit--4.4.0--4.5.0.sql.in, Code/PgSQL/rdkit/update_sql/rdkit--4.6.1--4.7.0.sql.in
This adds the sanitize and removeHs options to `mol_from_ctab()`
It also documents the names of the arguments, something that should be done for all the functions in the cartridge (but that's a separate PR)
=> cartridge: expose sanitize options to mol_from_ctab

Code/GraphMol/MolDraw2D/MolDraw2DUtils.cpp, Code/GraphMol/MolDraw2D/MolDraw2DUtils.h, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp, rdkit/Chem/Draw/SimilarityMaps.py
Here's what we used to get (and what the defaults still generate) with a color-gradient heatmap:
Using the new option (which disables the filling of small-magnitude boxes) we get:
This also exposes a couple of more parameters in `GetSimilarityMapFromWeights()`
=> Fixes #8308

Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearcher.cpp, Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearcher.h
The build is currently failing under gcc 14 :
```
In file included from /opt/gcc-14/include/c++/14.2.0/bits/random.h:35,
from /opt/gcc-14/include/c++/14.2.0/random:48,
from /tmp/rdkit_builder/rdkit/Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearcher.cpp:11:
/opt/gcc-14/include/c++/14.2.0/bits/uniform_int_dist.h: In instantiation of ‘std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomBitGenerator&, const param_type&) [with _UniformRandomBitGenerator = boost::random::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>; _IntType = long unsigned int; result_type = long unsigned int]’:
/opt/gcc-14/include/c++/14.2.0/bits/stl_algo.h:3758:35: …
```
=> Fix build under gcc-14

Code/GraphMol/CIPLabeler/CIPLabeler.h, Code/GraphMol/CIPLabeler/Digraph.h, Code/GraphMol/CIPLabeler/Mancude.h, Code/GraphMol/FileParsers/MolSGroupWriting.cpp, Code/GraphMol/FileParsers/MolSGroupWriting.h, Code/GraphMol/FileParsers/SDWriter.cpp, Code/GraphMol/FileParsers/TDTWriter.cpp, Code/GraphMol/FileParsers/XYZFileParser.cpp, Code/GraphMol/MolDraw2D/AtomSymbol.cpp, Code/GraphMol/MolDraw2D/DrawTextJS.cpp, Code/GraphMol/MolDraw2D/DrawTextSVG.cpp, Code/GraphMol/PartialCharges/GasteigerParams.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/RascalMCES/PartitionSet.h, Code/GraphMol/RascalMCES/RascalMCES.cpp, Code/GraphMol/RascalMCES/RascalResult.cpp, Code/GraphMol/StereoGroup.cpp, Code/RDGeneral/RDExportMacros.h, External/GA/util/Util.cpp
In `CMakeLists.txt` we define `BOOST_NO_CXX98_FUNCTION_BASE` for `clang` versions >= 15:
```
if (CMAKE_COMPILER_IS_CLANG OR CMAKE_COMPILER_IS_EMCC)
if (CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 15)
target_compile_definitions(rdkit_base INTERFACE -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_NO_CXX98_FUNCTION_BASE -D_HAS_AUTO_PTR_ETC=0)
target_compile_options(rdkit_base INTERFACE -Wno-deprecated-builtins -Wno-deprecated-non-prototype -Wno-unused-parameter)
endif()
endif()
```
to avoid usage of the unary function which is deprecated in C++11 and later.
However, recent versions of Boost already do this check and define `BOOST_NO_CXX98_FUNCTION_BASE` accordingly, without checking if `BOOST_NO_CXX98_FUNCTION_BASE` had already been defined previously:
```
#if _LIBCPP_VERSION >= 15000
//
// Unary …
```
=> Suppress large amounts of 'macro redefined' warnings in clang/emcc builds

Code/GraphMol/SynthonSpaceSearch/SynthonSpace.h
I'm not sure how the win64 DLL CI builds worked, but this definitely broke the conda-forge builds
=> add correct export to SynthonSpace.h

External/CoordGen/CMakeLists.txt
Version 1.3.2 of `maeparser` can optionally be built without the `boost::iostreams` dependency.
=> Bump MaeParser version to 1.3.2

Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Bond.cpp, Code/GraphMol/Wrap/Conformer.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/SubstanceGroup.cpp, Code/GraphMol/Wrap/props.hpp
A common pattern _in Python_ for checking for the presence or absence of a key is:
```
try:
return mol.GetProp('mykey')
except KeyError:
return None
```
Shockingly, this is really slow with boost python objects! I was recently profiling a workflow and 90% of the time or more was spent in failed GetProp calls (mostly on bonds, some on atoms or mols).
I sped up the workflow by protecting the calls using HasProp. But I think this is a silly trap we've set for our users.
The problem comes because boost::python uses a C++ exception to indicate that there is already a Python exception set. In C++, exceptions are slow - they require unrolling a stack. In Python, exceptions are about the same speed as any other control flow!
This commit speeds up GetProp failures by circumventing the boost …
=> Speed up GetProp Python keyerrors

Code/GraphMol/Depictor/catch_tests.cpp, External/CoordGen/CoordGen.h
This was originally reported by @sroughley.
When a double bond has a stereo spec but no stereo atoms, CoordGen segfaults as it attempts to access elements at indices 0 and 1 in an empty vector.
```
$ cat ~/py/crashes_coordgen.py
from rdkit.Chem import rdDepictor
m = Chem.MolFromSmiles("C=C1C=CC(=O)CC1")
m.GetBondWithIdx(0).SetStereo(Chem.BondStereo.STEREOZ)
print(list(m.GetBondWithIdx(0).GetStereoAtoms()))
rdDepictor.SetPreferCoordGen(True)
rdDepictor.Compute2DCoords(m)
$ python ~/py/crashes_coordgen.py
[]
Segmentation fault
```
This PR prevents this and adds a unit test.
=> Avoid a segfault in CoordGen when a double bond has stereo spec but no stereo atoms

External/pubchem_shape/PubChemShape.cpp, External/pubchem_shape/PubChemShape.hpp, External/pubchem_shape/test.cpp
Fixes #8416 
The loop was going over all atoms, but only updating coords for non-H atoms so gaps could be left in the array and values written over the end of the vector.
I couldn't find a simple test that crashed it, so haven't added one.  However the test "Github #8096" now gives Tanimoto scores of 1.0 for shape and colour which I think is correct since the deuterium shouldn't be affecting things at all.  Previously, it caused an extra coordinate in the array which was left at its default value of 0.0, 0.0, 0.0 (atom index 4).
It is not impossible that whatever was done to fix #8096 didn't get to the root of the problem, or there were 2 problems.
=> Fix indexing of heavy atoms in PubChemShape

azure-pipelines.yml
gcc-10 doesn't seem to be on the ubuntu-latest image anymore.
Switch to gcc-11
=> bump gcc version in CI

Code/MinimalLib/tests/tests.js
I noticed that `tests.js` occasionally fails on the
`assert.equal(patternFpArray.length, sslib.size())`
assertion, and I believe this might be causing by `sslib.delete()` being called too early, i.e. when the `patternFpArray` is still needed. This may cause objects in the array to be invalidated ahead of time.
If that is indeed the root cause, this should fix the problem.
=> Do not free sslib until patternFpArray is still needed by the test

.azure-pipelines/mac_build.yml, .azure-pipelines/mac_build_java.yml, azure-pipelines.yml
There was some unannounced change on the Mac CI runners and jobs are intermittently failing.
At the time I wrote this, there are at least a couple of different versions of the Mac CI build images out there:
`Current image version: '20250331.1019'`
which works, and:
`Current image version: '20250414.1083'`
which doesn't work.
This PR adds some debugging info to the build script to try and figure out which SDK versions are actually installed, but since I added them the CI builds have not been sent to one of the bad images.
I'm going to merge this and hope ti at least have debugging info available the next time there is a problem.
=> bump versions of SDK in MacOS CI jobs

CMakeLists.txt
removes the call to `find_package(better-enums)` since it can never succeed
=> Fixes #8438

Code/GraphMol/Wrap/StereoGroup.cpp, Code/GraphMol/Wrap/rough_test.py
this was an oversight when we added bonds to stereo groups
=> add StereoGroup.getBonds() to Python wrapper

Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp, Code/GraphMol/DistGeomHelpers/Wrap/testDistGeom.py, Code/RDBoost/Wrap.cpp, Code/RDBoost/Wrap.h
Allows to overwrite __setattr__ for python classes from within c++.
This to raise errors in case a class attribute is misspelled.
=> add function to overwrite __setattr__ to only accept valid arguments

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolDraw2D/Wrap/testMolDraw2D.py
No issue.
Just adds @nmaeder's attribute protection to the DrawOptions object.
clang-format seems to have had a go, as well.
=> Protect Python DrawOptions from bad attributes.

Code/GraphMol/CIPLabeler/Wrap/pyCIPLabelWrapTest.py, Code/GraphMol/Wrap/rdmolfiles.cpp
No Issue
Adds the new `safeSetattr` to the param objects of rdMolFiles.
=> Add the safeSetattr to the rdMolFiles param objects

Code/GraphMol/SmilesParse/CXSmilesOps.cpp, Code/GraphMol/SmilesParse/SmilesWrite.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, Docs/Book/RDKit_Book.rst, ReleaseNotes.md
SMILES cannot encode Zero Order Bonds, so roundtripping mols that include them through SMILES causes data loss: ZOBs will be encoded into the SMILES with a tilde character, `~` (this is also a RDKit custom feature, since SMILES doesn't support this symbol).
This PR implements a custom CXSMILES feature to indicate that one or more bonds are ZOBs. The feature uses the `Z:` label, followed by a list of comma-separated bond indexes, similarly to the `c:`/`t:`/`ctu:` features. On the SMILES expression (also when not writing a CX extension), the ZOB will still be indicated by the tilde character.
The feature can be disabled by toggling the `CX_ZERO_BONDS` flag in the CXSMILES generation.
=> Add a custom CXSMILES feature to indicate Zero Order Bonds

Code/GraphMol/DetermineBonds/DetermineBonds.cpp, Code/GraphMol/DetermineBonds/catch_tests.cpp, Code/GraphMol/FileParsers/ProximityBonds.cpp, Code/GraphMol/FileParsers/ProximityBonds.h, Code/GraphMol/FileParsers/connectTheDots_catch.cpp
Adds a mode to connectTheDots which quickly recognizes and removes H-H bonds that should not be there as part of the cleanup stage.
=> add quick H-H bond removal to connectTheDots

Code/GraphMol/MolOps.cpp, Code/GraphMol/WedgeBonds.cpp
1. `cleanupAtropisomers()` was always calling the ring finding code, even if there are no possible atropisomeric bonds
2. move the ring-finding test out of `countChiralNbrs()`, which didn't need it, and into `pickBondToWedge()`, which does need it.
=> A couple optimizations to when the ring finding code is called

Code/PgSQL/rdkit/adapter.cpp, Code/PgSQL/rdkit/expected/rdkit-91.out, Code/PgSQL/rdkit/sql/rdkit-91.sql
Fixes Issue #8465 
Modifies behavior of @= operator in the cartridge to ignore coordinates when comparing CXSmiles. This is needed becuase the existing implementation will evaluate identical molecules as different if one or more atoms has a different position than the reference molecule.
=> Make Cartridge @= operator coordinate agnostic

Code/GraphMol/MolDraw2D/DrawShape.cpp, Code/GraphMol/MolDraw2D/DrawShape.h, Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/MolDraw2D.h, Code/GraphMol/MolDraw2D/MolDraw2DCairo.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.cpp, Code/GraphMol/MolDraw2D/MolDraw2DDetails.h, Code/GraphMol/MolDraw2D/MolDraw2DSVG.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Discussion #8500, 2nd bit, the solid arrow head positions.
Allows for the mitre on the arrowhead correctly rather than the ridiculous guess it was doing before.
@bertiewooster's test (slightly amended) now looks like this:
Both open and solid arrows are drawn on the same image to show that they are now the same.
At the same time I have fixed the Cairo/PNG polygon drawer so it uses mitred line joins, and also the SVG open polygon drawing.  So the reaction arrows look better, too.
The difference in the code for drawing the arrows is below.  Note that for some reason this uses the American spelling of colour, even though most of the code uses the British spelling.  I am still embarrassed about creating this confusion for post-colonial reasons.  Sorry.
```
p1 = Geometry.Point2D(0, 0)
for i in …
```
=> Fix arrowhead8500

Code/GraphMol/SynthonSpaceSearch/SynthonSpace.cpp, Code/GraphMol/SynthonSpaceSearch/SynthonSpace.h, Code/GraphMol/SynthonSpaceSearch/SynthonSpaceSearch_details.cpp, Code/GraphMol/SynthonSpaceSearch/substructure_search_catch_tests.cpp
Fixes #8502
The fragmentation code wasn't dealing with a query with only 1 bond.
I've added a function to read a SynthonSpace from a stream, to make setting up little tests like this easier.
clang-format seems to have found a few more things to fiddle with.
=> Synthon space github8502

Code/GraphMol/TautomerQuery/TautomerQuery.cpp, Code/GraphMol/TautomerQuery/catch_tests.cpp
This fixes #8492.
The problem was that for the `modifiedAtoms`, we create fresh `QueryAtoms` and replace the `templateMolecule's` atoms with them, but we never forward the queries to these new `QueryAtoms`. This is what this PR adds: forwarding the queries to the modified and replaced atoms.
=> Fixes #8492

Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp
None
Explains the remaining parameters in `DrawArrow`: `frac`, `angle`, and `color`. For `DrawArrow` and all `rdMolDraw2D` docstrings involving `rawCoords`, explain the effect of setting it to `True`.
=> Explain DrawArrow and rawCoords=True

Code/GraphMol/FileParsers/testMolSupplier.cpp, Code/GraphMol/FileParsers/testMolWriter.cpp, Code/GraphMol/FileParsers/v2_suppliers_catch.cpp, Code/GraphMol/catch_chirality.cpp, Code/GraphMol/querytest.cpp
I ran asan on tests again. Besides finding https://github.com/rdkit/rdkit/issues/8520, there's just some minor leaks in tests.
Special mention to the two issues in  `Code/GraphMol/FileParsers/v2_suppliers_catch.cpp`, which weren't using the "v2" API at all.
=> A few mem fixes in tests

Code/GraphMol/MolDraw2D/DrawShape.cpp
Fixes #8520 
Does the rectangle clash on the original points as supplied.  
Taken out a now unnecessary calculation.
There's no functional test, as nothing showed up before.  It now runs under valgrind and ASAN without complaints.  I've scanned through the output and all looks fine.
=> DrawShapeArrow::doesRectClash uses origPts_.

Code/GraphMol/DistGeomHelpers/Embedder.cpp, Code/GraphMol/DistGeomHelpers/catch_tests.cpp
Cleans up an oversight in #8518 
Make sure that will still check angles around centers like a Sulfone, where we have two adjacent double bonds but a higher degree than two.
Not really sure how to test this, since the function running the check is not declared in the header, is creating a details header the solution to this?
=> Fix ETKDG double bond check from #8518

Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.cpp, Code/GraphMol/SmilesParse/CanonicalizeStereoGroups.h, Code/GraphMol/SmilesParse/catch_tests.cpp, Code/GraphMol/Wrap/MolOps.cpp, Code/GraphMol/Wrap/rough_test.py
If the number of OR groups or the number of AND groups is too large, the rigorous canonicalization of stereo groups effectively never returns.   
This allows the number of stereo ORs or stereo ANDs to be limited.   If the number is above that cutoff, the original molecule is not changed.    The default number allowed is 12, which makes the processing take something on the order of 3 seconds.
=> allow limiting the  number of stereo groups to process

Code/MinimalLib/jswrapper.cpp
This change in `emscripten`
https://github.com/emscripten-core/emscripten/pull/24175
has broken our MinimalLib build, and this PR restores it by wrapping the raw pointer into an `emscripten::val` constructed with `allow_raw_pointers()` policy.
=> Explicitly wrap raw pointer into emscripten::val object with allow_raw_pointers() policy

Code/MinimalLib/docker/docker_compose_build_minimallib.yml
The current `Code/MinimalLib/docker/docker_compose_build_minimallib.yml` file is missing defaults for variables in case an `.env` file does not exist; this PR fixes that.
=> Add missing default values to docker-compose configuration

Code/GraphMol/StereoGroup.cpp, Code/GraphMol/molopstest.cpp
Fixes #8527
removeAtomFromGroup() in StereoGroups.cpp checks for empty groups and deletes them. Previously it would only check group atoms to see if the group was empty. I modified so it also checks bonds.
=> Fixes #8527

Code/GraphMol/MolDraw2D/DrawMolMCHLasso.cpp
No issue.
On my Ubuntu machine using gcc 14.2.0 (from the conda env) I was getting an irritating warning from the std::vector include file when compiling DrawMolMCHLasso.cpp.  This uses a different way of copying the vector that doesn't cause the warning.
I've checked that the lasso images don't change.
=> Fix irritating warning when DrawMolMCHLasso compiled.

Code/GraphMol/DetermineBonds/DetermineBonds.cpp, Code/GraphMol/DetermineBonds/Wrap/rdDetermineBonds.cpp, Code/GraphMol/DetermineBonds/catch_tests.cpp
As requested by @DavidACosgrove  in PR #8548
=> Support Ctrl+C in determineBondOrders

Code/GraphMol/MolOps.cpp, Code/GraphMol/RWMol.cpp, Code/GraphMol/StereoGroup.cpp, Code/GraphMol/StereoGroup.h, Code/GraphMol/molopstest.cpp
This is a continuation of #8542: empty stereogroups involving bonds were not being correctly removed from fragments.
=> fix a problem with stereogroups involving bonds and getMolFrags()

Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp, Code/GraphMol/FileParsers/MultithreadedMolSupplier.h, Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.cpp, Code/GraphMol/FileParsers/MultithreadedSDMolSupplier.h, Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.cpp, Code/GraphMol/FileParsers/MultithreadedSmilesMolSupplier.h, Code/GraphMol/FileParsers/testMultithreadedMolSupplier.cpp, Code/GraphMol/Wrap/testMultithreadedMolSupplier.py, Code/RDGeneral/ConcurrentQueue.h
Fixes #8284 
The MultiThreadedMolSupplier wasn't properly clearing the input queue before ending threads.  This caused a deadlock in the inputQueue where a thread was blocking because the queue was full and couldn't properly end.
The solution was to add a df_forceStop atomic boolean (although we could probably reuse df_started) and to stop the readers when this is set and also stop the writers.
So the procedure is:
1. df_forceStop = true
2. pop items of the inputQueue
4. endThreads
6. now we can clear the input queue and output queue
8. finally close any input stream.
One issue is that we can't close the SDMolSupplier streams until the threads are shut down and destructors are called last to first, so we add a closeStreams protected virtual function that the base destructor can call.
As a …
=> Fixes #8284

External/CoordGen/CMakeLists.txt
This updates the maeparser dependency to v1.3.3. The new version fixes issue #8525.
=> Bump maeparser to 1.3.3 (fixes #8525)

Code/GraphMol/Wrap/StereoGroup.cpp, Code/GraphMol/Wrap/rough_test.py
Fixes #8584 
Currently, there is no way to create a StereoGroup that is bond-only, or contains bonds. I added a bond list to the createStereoGroup function to enable this.
=> Update createStereoGroup to accept bond list

Code/GraphMol/Descriptors/GETAWAY.cpp
This fixes an out of bounds access in GraphMol/Descriptors/GETAWAY.cpp's `GetGeodesicMatrix` function.  Because the vector has memory reserved, this code didn't crash in release builds, but because the size is incorrect, a debug check failure occurs in Windows debug builds, when `std::transform` dereferences the invalid iterator into `Geodesic`.  The return copy should be elided and the calling code never checks the size, only the data pointer, so the release build behaviour should be unaffected by this change.
=> Fixed out of bounds vector access in GetGeodesicMatrix

Code/GraphMol/CIPLabeler/CIPLabeler.cpp, Code/GraphMol/CIPLabeler/Wrap/rdCIPLabeler.cpp, Code/GraphMol/CIPLabeler/catch_tests.cpp, Code/GraphMol/CIPLabeler/rules/SequenceRule.cpp, Code/RDGeneral/ControlCHandler.h
This allows interrupting `assignCIPLabels`, which is nice if you forgot passing a value for `maxRecursiveIterations`.
=> Make assignCIPLabels Ctrl+c interruptable

Code/GraphMol/SmilesParse/CMakeLists.txt, Code/GraphMol/SmilesParse/SmilesParse.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.cpp, Code/GraphMol/SmilesParse/SmilesParseOps.h, Code/GraphMol/SmilesParse/lex.yysmarts.cpp.cmake, Code/GraphMol/SmilesParse/smarts.ll, Code/GraphMol/SmilesParse/smarts.tab.cpp.cmake, Code/GraphMol/SmilesParse/smarts.tab.hpp.cmake, Code/GraphMol/SmilesParse/smarts.yy, Code/GraphMol/SmilesParse/smiles.tab.cpp.cmake, Code/GraphMol/SmilesParse/smiles.tab.hpp.cmake, Code/GraphMol/SmilesParse/smiles.yy
This attempts to improve the SMARTS parsing procedure to provide more information about bad inputs by pointing to general location of the offending token. The improved error messages currently only apply to syntax errors, inputs with extra close parentheses, and inputs with too large numbers, but this will provide a way to extend that in the future
Some examples of the improved error messages
| old version                            | new version            |
|----------------------------------------|------------------------|
|syntax error while parsing: [C:10H3]CC | syntax error while parsing input:<br /> `[C:10H3]CC` <br /> `~~~~~^` |
|syntax error while parsing: [C:10:3]ON | syntax error while parsing input:<br /> `[C:10:3]ON` <br /> `~~~~~^` |
|extra close parentheses while parsing: …
=> Update SMARTS parsing syntax error to include bad token position

azure-pipelines.yml
Apparently the default for `COMPOSE_BAKE` has changed to `true` and this change broke the `minimallib` build.
This change should restore the build functionality.
=> Explicitly set COMPOSE_BAKE to false

Code/GraphMol/MolDraw2D/MolDraw2D.cpp, Code/GraphMol/MolDraw2D/catch_tests.cpp
Fixes #8679 
Adds the offset before doing the drawing, in the same manner as DrawMolecule().
clang-format has changed the previous test in catch_tests.cpp.  I didn't change anything else in that test.
=> Fix offsets for DrawMoleculeWithHighlights.

azure-pipelines.yml
we keep getting failures due to this, so we might as well increase the allowed time
=> increase max time for win64 CI builds

Code/GraphMol/FileParsers/MultithreadedMolSupplier.cpp, Code/GraphMol/FileParsers/MultithreadedMolSupplier.h, Code/GraphMol/Wrap/testMultithreadedMolSupplier.py
Reverts rdkit/rdkit#8768
The merge causes a seemingly reproducible failure in one or more multi-threaded tests in the linux CI builds. This did not happen with the CI build of the PR itself, only post merge.
I, unfortunately, cannot reproduce this locally. Threading problems are terrible.
=> Revert "Fixes #8644"

Code/GraphMol/SmilesParse/SmilesJSONParsers.cpp, Code/GraphMol/SmilesParse/cxsmiles_test.cpp, Code/MinimalLib/JSONParsers.cpp, Code/RDGeneral/JSONHelpers.h
This PR introduces a templated function for parsing Boolean flags from a JSON file, which previously was duplicated in multiple places. Additionally, the previous parsing function only considered `true` values and ignored `false` ones. Now `false` values are `AND NOT`ed from the `true` values, which is a more useful behavior. I also added a test.
=> Avoid code duplication through a templated function and improve JSON parsing of Boolean flags

Docs/Book/Install.md
- closer to the azure builds
- uses conda-forge
- consolidated all dependencies into one command
- removed two cmake flags causing warnings that were not in the azure builds
=> Changed linux build from source docs to use miniconda

Code/GraphMol/DistGeomHelpers/Wrap/rdDistGeom.cpp
Fixes #8806 
The EXCEEDED_TIMEOUT failure was never added to the python enum.
=> expose exceeded timeout failure to python

Code/GraphMol/Wrap/Atom.cpp, Code/GraphMol/Wrap/Bond.cpp, Code/GraphMol/Wrap/Conformer.cpp, Code/GraphMol/Wrap/Mol.cpp, Code/GraphMol/Wrap/props.hpp, Code/GraphMol/Wrap/rough_test.py, Code/RDGeneral/RDValue.h, Code/RDGeneral/testRDValue.cpp
Fixes #8546 
By default, when converting to double/floats this trims the right hand white space.  This simulates round tripping through SDFiles which automatically do this.
When converting to a python dictionary, the rdkit will be more aggressive and trim all spaces.
```
mol.SetDoubleProp("foo", "123.0 ")
mol.GetDoubleProp("foo") == 123.
mol.SetDoubleProp("bar", " 123.0 ")
mol.GetDoubleProp("bar) # throws exception
mol.GetPropsAsDict()["bar"] == 123.
```
=> Trim spaces from RDProp strings to simulate reading from SDFiles

Scripts/gen_rdkit_stubs/__init__.py, Scripts/gen_rdkit_stubs/patch/rdkit/Chem/inchi.pyi.diff, Scripts/gen_rdkit_stubs/worker.py
This PR implements a mechanism to patch `.pyi` files after they are generated by `Scripts/gen_rdkit_stubs` during the build process. This, for example, enables adding type hints to Python-only modules (such as `Chem/inchi.py`) for which there is no C++ source code to infer types from. This is preferrable to adding type hints to `.py` files directly as we do not normally do that in RDKit.
=> Implement a mechanism to patch .pyi files as proposed in #8749

Code/GraphMol/MolOps.cpp, Code/GraphMol/RWMol.cpp, External/ChemDraw/chemdraw.cpp, External/ChemDraw/test.cpp, External/ChemDraw/utils.cpp
This fixes some leaks in ChemDraw code, which can be detected in `External/ChemDraw/test.cpp`. The problem is happening in this block of code:
https://github.com/rdkit/rdkit/blob/2e1d946f6de4f7834106b1a5bf9a92d93ab8cd85/External/ChemDraw/utils.cpp#L176-L180
The problem is that `FragmentReplacement::replace()` runs a loop that creates some bonds, and then deletes some atoms. When this happens inside the batch edit that is initiated in the code I linked above, we can create bonds involving atoms that have already been marked for deletion. And that will cause the bond to leak, since the detection for bonds that need to be deleted together with the atom happens when `removeAtom()` is called, not when the batch edit is committed.
In other words, when we start a batch edit, then run …
=> Fixes a leak in ChemDraw code

External/ChemDraw/ChemDrawStartInclude.h, External/ChemDraw/bond.cpp, External/ChemDraw/bond.h, External/ChemDraw/bracket.cpp, External/ChemDraw/bracket.h, External/ChemDraw/chemdraw.cpp, External/ChemDraw/chemdraw.h, External/ChemDraw/chemdraw_doc.h, External/ChemDraw/chemdrawreaction.cpp, External/ChemDraw/chemdrawreaction.h, External/ChemDraw/fragment.cpp, External/ChemDraw/fragment.h, External/ChemDraw/node.cpp, External/ChemDraw/node.h, External/ChemDraw/reaction.cpp, External/ChemDraw/reaction.h, External/ChemDraw/test-chiral.cpp, External/ChemDraw/test-reactions.cpp, External/ChemDraw/test.cpp, External/ChemDraw/test_3d.cpp, External/ChemDraw/test_6k.cpp, External/ChemDraw/utils.cpp, External/ChemDraw/utils.h, External/ChemDraw/writer.cpp
This is just a run of clang-tidy-18 and then clang-format-18 across the .cpp and .h files in External/ChemDraw 
For reviewing: I would suggest just looking at the changes from the first commit (the clang-tidy run)
The second one is just clang-format changes.
=> run clang-tidy and clang-format on the chemdraw files

Code/GraphMol/ChemReactions/Wrap/rdChemReactions.cpp, Code/GraphMol/Depictor/Wrap/rdDepictor.cpp, Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp, Code/GraphMol/FMCS/Wrap/rdFMCS.cpp, Code/GraphMol/MolDraw2D/Wrap/rdMolDraw2D.cpp, Code/GraphMol/MolEnumerator/Wrap/rdMolEnumerator.cpp, Code/GraphMol/MolInterchange/Wrap/rdMolInterchange.cpp, Code/GraphMol/MolProcessing/Wrap/rdMolProcessing.cpp, Code/GraphMol/MolStandardize/Wrap/rdMolStandardize.cpp, Code/GraphMol/RGroupDecomposition/Wrap/rdRGroupComposition.cpp, Code/GraphMol/RascalMCES/Wrap/rdRascalMCES.cpp, Code/GraphMol/ScaffoldNetwork/Wrap/rdScaffoldNetwork.cpp, Code/GraphMol/Wrap/rdmolfiles.cpp, External/CoordGen/Wrap/rdCoordGen.cpp, External/FreeSASA/Wrap/rdFreeSASA.cpp
Fixes no specific issue.
Scanned through the `rd*.cpp` files for parameter and options objects and added the `safeSetattr` to the ones not having it.
=> Add safeSetattr to more params / options objects
